### ISSUE TITLE
[Front - Signalement] Certains suivis créés par les usagers ne sont pas publics

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1001]
Remonté par Thibault ici : 
https://mattermost.incubateur.net/betagouv/pl/ss3aawfdsjdejxm9wz4qz1bqoc

Bien visible dans Metabase dans la table de suivi en sélectionnant isPublic falsee, et type 2 (une partie des 624 signalements sont mal typés car ce sont des suivis partenaires, mais sans id d'utilisateur donc ils ont été mal catégorisés par la commande)

**Comment by sfinx13** [comment]
@hmeneuvrier j'ai supprimé le copie d'écran, est ce qu'on peut partager un lien metabase plutôt

**Comment by hmeneuvrier** [comment]
https://histologe-metabase.osc-fr1.scalingo.io/question/6-suivis-usager-non-public
