### ISSUE TITLE
[BO - Fiche signalement] Réorganisation UX

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1021]
Réorganiser les infos dans la fiche signalement en prenant en compte les diverses demandes d'amélioration

A prendre en compte : 
- #627 
- #1040 
- #1041 
- #1244 

Evolutions fonctionnelles : 
- Le nom de l'occupant est affiché à côté de la référence du signalement
- On ajoute un label avec le statut du signalement (nouveau / en cours / fermé)
- Les différentes actions entraînent l'ouverture d'une modale (sauf l'édition des infos qui renvoie vers la page d'édition)
- Par défaut, la carte n'est pas affichée, elle est consultable au clic via le lien "voir sur la carte"
- La modification des infos renvoie vers le formulaire de modifications mais uniquement les étapes 1 (Identité) et 4 (logement) : la déclaration et description des désordres n'est plus modifiable par les agents
- Au clic sur les labels : il ne se passe rien, on ne modifie plus les infos en cliquant sur un label
- On supprime les infos qui ne sont pas demandées dans le formulaire FO, à savoir : 
    - date d'entrée
    - loyer
    - montant de l'allocation
    - bail en cours
- Le bloc "coordonnées du tiers déclarant" n'est affiché que dans le cas d'un dépôt par tiers déclarant
- La modale d'affectation des partenaires évolue : elle permet uniquement d'affecter de nouveaux partenaires. La suppression d'un partenaire se fait sur la page signalement directement.
- Par défaut, on a affiche les 3 derniers suivis et un lien "afficher tous les suivis"

**Comment by mathildepoulpux** [comment]
## Vue agent
![BO - fiche signalement - agent](https://user-images.githubusercontent.com/97226289/224399191-a5bfeb25-af1b-418e-852c-fad31e1c15e2.png)

## Vue responsable territoire
![BO - fiche signalement - resp territoire](https://user-images.githubusercontent.com/97226289/224399203-4beda99e-f809-4255-925d-7cc39db6a865.png)

**Comment by mathildepoulpux** [comment]
On laisse de côté pour le moment dans ce cas :)

**Comment by hmeneuvrier** [comment]
Ok j'ai créé un ticket https://github.com/MTES-MCT/histologe/issues/1255
