### ISSUE TITLE
[BO - Territoire Tarn et Rhône] Impossible d'accéder à la liste des signalements

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1039]
Sur les comptes des responsables de territoire du Tarn ou du Rhône, quand je clique sur la liste des signalements dans le menu ou sur les cartes suivantes du BO : 
![image](https://user-images.githubusercontent.com/97226289/225266216-7ffc029e-6178-4cd9-898a-c00d9d54d2bf.png)

J'ai une erreur 500 : 
![image](https://user-images.githubusercontent.com/97226289/225265978-d986b1f6-9889-4ec6-a9b3-b5b7f8bdf905.png)

J'ai testé sur d'autres territoires (Corrèze, Yonne, Finistère, Corse, 13, 04...), ça fonctionne

**Comment by hmeneuvrier** [comment]
On a aussi le souci sur la liste de signalement en super admin si on filtre sur le Tarn

**Comment by hmeneuvrier** [comment]
On n'a pas le souci sur la branche de perf

**Comment by hmeneuvrier** [comment]
J'ai essayé tous les territoires (en superadmin c'est facile), il n'y a le souci que pour le Rhône et le Tarn

**Comment by hmeneuvrier** [comment]
Si je filtre Tarn et Nouveau, pas de souci, Tarn et Fermés pas de souci, Tarn et En cours -> bug
Cela doit venir d'un signalement spécifique.


--> pour le Tarn, cela vient du signalement 62ea84f0328c7, mais je ne sais pas pourquoi

**Comment by hmeneuvrier** [comment]
Super @sfinx13  a trouvé !!! 
Il y a des vieux motifs de cloture INDECENCE pour les affectations, et ça ne peut plus marcher avec le passage des motifs de cloture en enum. C'est déjà en cours de correction dans la branche de perf de Saidi qui va être mergée sur develop bientôt.
Je ferme le ticket
