### ISSUE TITLE
mettre une fiche de visite éditable et téléchargeable par les partenaires (un simple pdf éditable), sur chaque signalement.

### ISSUE THREAD

**Issue by Tibo-aplus** [MTES-MCT/histologe#1043]
Se baser sur la fiche CAF13

**Comment by Tibo-aplus** [comment]
[Fiche-decence-RSD-PDLHI-modifiable-637e3375c3670 (1).pdf](https://github.com/MTES-MCT/histologe/files/10989431/Fiche-decence-RSD-PDLHI-modifiable-637e3375c3670.1.pdf)

**Comment by mathildepoulpux** [comment]
Besoin à affiner -> déplacé sur Notion
