### ISSUE TITLE
[NDE][BO - Signalements] 3 petits bugs relevés pendant la démo

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1049]
Pendant la démo, sur la reviewApp, nous avons constaté 2-3 petits pbs.
1. pour tous les signalements NDE, dans la fiche signalement, le label "Non-Décence énergétique" ne doit pas apparaitre si le partenaire n'a pas la compétence (condition à changer)
![image](https://user-images.githubusercontent.com/33071753/225880957-7625ffe8-be74-4021-bc18-af0046e197e0.png)

2. pour le signalement https://histologe-staging-pr1010.osc-fr1.scalingo.io/bo/signalements/6849a896-14a4-4cf2-a515-80f838ef7cd3
le statut n'est pas bon, on a "décence énergétique ok", alors qu'on devrait avoir "à vérifier" comme on n'a pas rentré le dpe ni la consommation, 
![image](https://user-images.githubusercontent.com/33071753/225881111-1263428a-4f10-4bc9-90b2-947ab97b6ff1.png)

3. sûrement lié au précédent, ce signalement n'a pas le label NDE dans la liste des signalements (mais il a bien Non décence énergétique" dans la fiche signalement, du coup à harmoniser dans un sens ou dans l'autre)
![image](https://user-images.githubusercontent.com/33071753/225881254-0ea6e2fc-cc0b-4d98-bfb8-a2235106d430.png)

4. bug sur le calcul d'Arnaud : il a mis 2023 avec un calcul, puis avant 2023, changé les données plusisuers fois, et il s'est retrouvé avec une conso de 25 et un statut non décence avérée

5. enlever les dates côté back pour mettre avant/après 2023 comme dans le front

**Comment by mathildepoulpux** [comment]
Le 1 et le 5 c'est bon
Les autres à tester
