### ISSUE TITLE
[BO - Profil utilisateur] Modifier ses info de connexion (email et mdp)

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#105]
CF. #108 

Modifier ses info de connexion (email et mdp)
- Les [spécficiations modif email](https://github.com/MTES-MCT/histologe/wiki/Gerer-le-profil#modifier-mon-adresse-email)
- Les [specs modif mdp](https://github.com/MTES-MCT/histologe/wiki/Gerer-le-profil#modifier-mon-mot-de-passe)
- Le [prototype](https://xd.adobe.com/view/16386013-8dac-45bf-ad9e-760d94c1612a-436b/)

### User flow

1. Accéder à la page profil
2. Cliquer sur `Modifier mon adresse email`
3. Accéder à la modale
4. Champ email obligatoire avec vérification sur le format
5. Cliquer sur `Valider`
6. Nouvelle modale : renseigner le code de confirmation reçu par mail
7. Un e-mail de confirmation avec un code à 6 caractères est envoyé sur la nouvelle adresse mail
8. Le user renseigne le code dans la modale
9. L'adresse est validée

**Erreurs possibles:**
- Champ vide : `Ce champ est obligatoire.`
- Mauvais format : `Veuillez saisir une adresse email au format adresse@email.fr.`

#### Conséquences
- Retour à la page profil avec le message succès `Votre adresse e-mail a bien été confirmée !`
- Les info sont MAJ sur :
    - La page profil
    - Sur la page du partenaire

### Email Confirmez votre email
Objet : `Histologe {{territoire}} - Confirmez votre adresse mail`

Corps : `Bonjour,`

`Voici le code de confirmation à renseigner pour confirmer votre adresse mail :`

{{code}}

`A bientôt sur Histologe !`

-----

### User flow
1. Accéder à la page profil
2. Cliquer sur `Modifier mon mot de passe`
3. Accéder à la modale
4. Modifier les infos dans le formulaire
	a. Nouveau mot de passe : obligatoire. Le mot de passe doit contenir :  12 caractères, 1 majuscule, 1 minuscule, 1 chiffre, 1 caractère spécial     
	Le mot de passe doit être différent du mdp actuel
	b. Confirmer le nouveau mot de passe : obligatoire     
	Le mdp doit correspondre strictement à celui renseigné dans le champ "Nouveau mot de passe"
5. Cliquer sur `Valider` 

**Erreurs possibles**
- Champ vide : `Ce champ est obligatoire.` 
- Mot de passe identique à l'actuel : `Vous utilisez déjà ce mot de passe. Veuillez saisir un nouveau mot de passe.`
- Pas de correspondance : `Les mots de passes renseignés doivent être identiques.`
- Mauvais format : `Le mot de passe doit contenir : 12 caractères, 1 majuscule, 1 minuscule, 1 chiffre, 1 caractère spécial.`

#### Conséquences
- Retour à la page profil avec le message succès `Votre mot de passe a bien été modifié.`
- Le nouveau mot de passe est enregistré
- Un email de confirmation est envoyé

#### Email
Objet : `Histologe {{territoire}} - Mot de passe mis à jour !`

Corps : `Bonjour,`

`Votre mot de passe a bien été mis à jour sur Histologe. Vous pouvez dès à présent vous connecter en utilisant votre nouveau mot de passe.`

Bouton : `Me connecter à Histologe`     
`Si le bouton ne fonctionne pas, cliquez ici`

`A bientôt sur Histologe !`

**Comment by hmeneuvrier** [comment]
Géré dans #108 je ferme
