### ISSUE TITLE
[BO - Carto] Les signalements sur la carto ne sont pas cliquables

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1059]
![image](https://user-images.githubusercontent.com/33071753/226347627-ca083e47-81a1-4567-994c-0bb49e158a3b.png)

**Comment by hmeneuvrier** [comment]
Pas reproductible en local.
Je reproduis sur la staging par contre...

**Comment by hmeneuvrier** [comment]
Cela vient d'un signalement apparemment dans le Cher, qui n'a pas des coordonnées (latitude et longitude) correctes, et ça fait tout buguer. On n'a pas le pb en filtrant sur d'autres territoires

**Comment by sfinx13** [comment]
Si tu joue la commande `app:get-geoloc` sur staging ça donne quoi ?
