### ISSUE TITLE
[BO - Profil utilisateur] Modifier les infos de son profil

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#107]
CF. #108 

Modifier les informations de son compte (nom, prénom, avatar)
- Les [spécficiations](https://github.com/MTES-MCT/histologe/wiki/Gerer-le-profil#modifier-mes-infos)
- Le [prototype](https://xd.adobe.com/view/16386013-8dac-45bf-ad9e-760d94c1612a-436b/screen/2f37cf5e-30fa-4577-b0bb-72dd462a3680/)

![image](https://github.com/user-attachments/assets/f1e98404-4e89-4bfc-9bf9-0e463630bd56)

### User flow
1. Accéder à la page profil
2. Cliquer sur Modifier mes infos
3.  Accéder à la modale
4. Modifier les infos dans le formulaire a. Avatar : facultatif. Photo au format PNG ou JPG, taille max 5Mo. Recoupée pour être carrée. b. prénom : champ obligatoire c. nom : champ obligatoire
5. Cliquer sur Valider

**Erreurs possibles :**
- Champ vide : Ce champ est obligatoire.
- Mauvais format photo : Ce format n'est pas pris en charge. Veuillez choisir une photo au format PNG ou JPG, de 5Mo maximum.

### Conséquences
- Retour à la page profil avec le message succès Les informations de votre profil ont bien été modifiées.
- Les info sont MAJ sur :
- La page profil
- Le menu du BO
- Le tableau de bord
- Dans les suivis des signalements
- Dans les affectations
- Sur la page du partenaire

---
**Avatar par défaut**
Par défaut (quand l'utilisateur n'a pas uploadé d'avatar ou qu'il supprime son avatar), on lui affiche le numéro de département sur un fond de couleur.
Fond : #ececfe
Numéro : #e4794a 

En utilisant la police Marianne en extrabold.
Ca donne ça 👇 
![image](https://github.com/user-attachments/assets/fe46d499-1a20-4b74-bae1-42078c476739)

**Comment by hmeneuvrier** [comment]
Géré dans #108 je ferme
