### ISSUE TITLE
[FO - Signalement] Impossible de déposer des signalements

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1075]
✅ J'ai testé plein de cas de figure pour le dépôt de signalement, voici ceux qui fonctionnent : 
- Dépôt d'un signalement par l'occupant avec **uniquement** des critères NDE (testé sur le 63 et le 89)
- Dépôt d'un signalement par un tiers avec **uniquement** des critères NDE (testé sur le 63 et le 89)

----

🔴 Les cas suivants affichent l'erreur "Erreur lors de l'enregistrement du signalement ! Nos équipes ont été informées du problème." : 
- Signalement par occupant : 
    - En dehors des territoires d'expé NDE (testé sur le 19 et 64)
    - Sur les territoires d'expé NDE si uniquement des critères classiques (testé sur le 89)
    - Sur les territoires d'expé NDE si critères NDE + critères classiques (testé sur le 63)
- Signalement par tiers : 
    - En dehors des territoires d'expé NDE (testé sur le 06)
    - Sur les territoires d'expé NDE si uniquement des critères classiques  (testé sur le 89)
    - Sur les territoires d'expé NDE si critères NDE + critères classiques (testé sur le 89 et 63)
- Cas particulier : si on sélectionne que des critères NDE mais en mettant "moyen" en gravité (qui, du coup, ne déclenche pas la procédure NDE)

**Comment by hmeneuvrier** [comment]
Erreurs sentry sans doute liées : 
https://sentry.incubateur.net/share/issue/fd55bd9efbf9439abe0d8ba7713552ad/
https://sentry.incubateur.net/share/issue/258ab49030274b94b78d1bc6c9b09f38/

**Comment by hmeneuvrier** [comment]
https://sentry.incubateur.net/share/issue/fd55bd9efbf9439abe0d8ba7713552ad/ C'est bien cette erreur qui empêche le dépôt de signalement avec des criticités non NDE.
C'est curieux, en localhost, dans notre base, la migration sur la criticité a créé des tableaux vides pour toutes les criticités non NDE.
Sur la staging, la valeur est NULL conformément à la migration : 
        `$this->addSql('ALTER TABLE criticite ADD qualification JSON DEFAULT NULL');`        
Mais c'est pour ça qu'on n'a jamais eu le pb en local au dépôt d'un signalement. Je fais un fix.
