### ISSUE TITLE
[BO - Edition NDE] Impossible de valider les modifications

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1094]
1. Je suis agent de l'ADIL sur le territoire de l'Yonne
2. Je suis sur un signalement NDE
3. Dans l'encart NDE, je clique sur modifier 
4. Je remplis les champs dans la modale
5. Je clique sur valider -> rien ne se passe

![image](https://user-images.githubusercontent.com/97226289/226987363-999697f6-1cb6-4842-bad9-a391edc5e165.png)

**Comment by hmeneuvrier** [comment]
Pour moi Erreur si radioboutons non remplis (dateDernierBail), 

puis erreur 500 à la validation 
https://sentry.incubateur.net/share/issue/740f249a20ee4ed5be55b6a18e68620d/
