### ISSUE TITLE
[BO - Liste Signalements] La pagination ne fonctionne pas

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1109]
- Le bouton page suivante ne marche pas au delà de la 2nde page
- le bouton page précédente n est pas cliquable, 
- le numéro de page reste sur 1 même si on va à la dernière page

**Comment by arnaudchouk** [comment]
RT meurthe et moselle a un pbm quand utilise filtres
Exemple : filtre étiquettes [CoTech HI]+ date de création (en 2023)  =100 dossiers sur 4 pages .. mais la fonction "page suivante" ne fonctionne pas.
Si  je clique sur le N°, cela semble fonctionner mais c'est la page 1 qui reste bleutée, donc je ne sais pas où j'en suis..
