### ISSUE TITLE
[Correction de données] corriger les 4521 signalements avec une valeur is_imported à null

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1136]
https://histologe-metabase.osc-fr1.scalingo.io/question/134-etat-de-is-imported-par-mois

![image](https://user-images.githubusercontent.com/33071753/229752031-34297a7e-be2b-4b73-bc33-d0936d91d49a.png)

**Comment by sfinx13** [comment]
En plus de la copie d'écran , je joint les commit d'octobre ou l'ajout de la colonne `is_imported` dans la table signalement avec comme valeur par défaut à `false`.
Donc tous les signalement crée depuis le site à partir d'octobre ont une valeur à false

https://github.com/MTES-MCT/histologe/commit/3d1c0e950ac50df7cab381bc2aa612b55960828e
https://github.com/MTES-MCT/histologe/commit/24b2fceb05519b77835efbb5f95a0e361334bece

Les imports de signalement effectuées en décembre/janvier ont une valeur à true

**Comment by hmeneuvrier** [comment]
Penser à voir avec @arnaudchouk au moement de la sortie car ça aura un impact sur la demande de feedback aux usagers

> Arnaud Choukroun
[il y a 2 heures](https://mattermost.incubateur.net/betagouv/pl/bwfgra9unfra3eu4aapcdatoey)

sur ce sujet de mail auto sur la base pas adressee lors du 1er envoie, est ce qu avant de mettre en prod vous pourrez me prevenir et patienter pour qu on se mette d accord avec les territoires concernes ? Il me faudra juste l info de combien de signalements sont concernes egalement
