### ISSUE TITLE
Un utilisateur sans partenaire et sans territoire n'est pas présent dans la liste des comptes archivés

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1145]

**Comment by hmeneuvrier** [comment]
J'ai repéré un bug sur les responsables territoires qui ne remontent pas dans la requête, je corrige ici : https://github.com/MTES-MCT/histologe/issues/1164

**Comment by sfinx13** [comment]
J'ai fermé le ticket j'ai vu que tu l'as passé en done au mois de mai @hmeneuvrier
