### ISSUE TITLE
[BO - Tableau de bord] Ne pas compter les signalements importés

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1146]
Dans le compteur des signalements sans suivi, exclure les signalements sans suivi du compteur

**Comment by hmeneuvrier** [comment]
@mathildepoulpux toujours d'actualité ? je ne suis pas sûre de comprendre la description

**Comment by mathildepoulpux** [comment]
Oui parce que j'ai écrit trop vite 😅 
Ca concerne cette carte : 
![image](https://github.com/MTES-MCT/histologe/assets/97226289/0636142b-46ab-4bf2-bd77-b397f595541b)

Et l'idée c'était d'exclure les signalements importés.
Vu que c'est en prio basse depuis 1 an et que je vais bosse sur la refonte du dashboard, je pense qu'on peut le fermer !
