### ISSUE TITLE
[Performance] Créer une application histologe-preprod / Déconnecter metabase de la production 

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1152]
Afin d'alléger la base de donnée de production, il faudrait déconnecter metabase de la base de donnée de production et la faire pointer vers une application de pre-production qui serait mise à jour selon une fréquence qui reste à définir
 
Celle ci serait déployé de la même manière que l'application `histologe-prod` c'est à dire un déploiement automatique activé sur la branche `main`

De plus ça permettrait à chacune des applications d'avoir ses propres ressources.

Il n'est pas possible de faire cela sur l'application histologe-staging car elle permet de tester les développements terminés de la plateforme.

**Comment by hmeneuvrier** [comment]
il y a une discussion sur le canal ops  qui discute de la maniere d augmenter les perf 
https://mattermost.incubateur.net/betagouv/pl/8hforp6ittn7jqfnnhixb6wb5w

**Comment by sfinx13** [comment]
Autre discussion metabase
https://mattermost.incubateur.net/betagouv/pl/k9k4wtjcmtgtxj7gbkrn7sisoh
