### ISSUE TITLE
[BO - Fiche partenaire] Edition utilisateur - ajouter espace entre les options

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1154]
Je suis SA
Sur une fiche partenaire
Je clique sur le bouton d'édition d'un utilisateur
A la question "recevoir des emails", les options sont collées
Il faudrait ajouter un espace avant le 2ème bouton radio
![image](https://user-images.githubusercontent.com/97226289/231425539-0c034ce4-e205-44c5-90d9-4ac7b1071a1a.png)

**Comment by hmeneuvrier** [comment]
J'avais déjà corrigé ça dans ce qui a été déployé hier aprèm, je ferme
![image](https://user-images.githubusercontent.com/33071753/231704475-bf12d999-dc6a-4f4f-a020-bbe36886277e.png)
