### ISSUE TITLE
[BO - Création partenaire] Modifier la mention "optionel" pour les champs ESABORA

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1159]
Je suis responsable territoire
Je crée un partenaire type Commune / SCHS
Les champs ESABORA sont affichés
Ils ont la mention "optionel" (en plus y a une faute) alors que les autres champs facultatifs ont la mention "facultatif"
-> Pour les 2 champs ESABORA il faudrait remplacer "optionel" par "facultatif"

![image](https://user-images.githubusercontent.com/97226289/231700105-4aab1639-3360-40d8-ae64-8d67f1c2699b.png)

**Comment by hmeneuvrier** [comment]
En plus il y a une faute à optio**n**el :D
