### ISSUE TITLE
[BO - Edition partenaire] Accès aux signalements hors périmètre lorsqu'on change le territoire d'un partenaire

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1172]
Je suis SA
J'ai un partenaire Partenaire 13-04 sur le territoire du 13 
Je modifie le partenaire pour changer son territoire et mettre le 04
Lorsque l'agent du Partenaire 13-04 se connecte : il a encore accès aux signalements du 13 qui lui ont été affectés avant le changement de territoire 
![image](https://user-images.githubusercontent.com/97226289/231815264-58a04910-f23b-44f3-bc54-0749628de2fd.png)

On peut m'affecter des signalements du nouveau territoire : 
![image](https://user-images.githubusercontent.com/97226289/231816091-7326a4a3-cdb7-4be4-b9f9-efb30bf32d1c.png)

Je me retrouve donc avec des signalements de 2 territoires différents.
Je ne devrais voir / gérer que les signalements du mon territoire actuel.

**Comment by hmeneuvrier** [comment]
@mathildepoulpux cela signifie que quand on transfère un partenaire d'un territoire à un autre, on doit supprimer toutes les affectations de l'ancien territoire quels que soient leur statut ?

**Comment by mathildepoulpux** [comment]
Alors c'est OK pour les affectations en cours et en attente.
Par contre, j'ai toujours accès à un signalement de mon ancien territoire : 
![image](https://user-images.githubusercontent.com/97226289/235464569-b24ba314-bb5f-44fe-9272-02bcec573483.png)

Je suis user
J'étais sur le territoire du 13
Je suis maintenant sur le 04
