### ISSUE TITLE
[BO Signalement] Export

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1186]
Decalage dans l'intitulé des colonnes
A priori il y a plusieurs zones de décalages
voir mail Prioul transfere le 19/04/23

**Comment by sfinx13** [comment]
Faut-il envisager un retour de la colonne géolocalisation ?
Voici le ticket de @mathildepoulpux 
https://github.com/MTES-MCT/histologe/issues/666

**Comment by arnaudchouk** [comment]
la colonne geoloc ne les interesse pas je pense

**Comment by mathildepoulpux** [comment]
On peut enlever la colonne isSituationHandicap d'ailleurs, vu qu'on pose plus la question dans le formulaire

**Comment by sfinx13** [comment]
Elle n'est pas présente dans l'export

**Comment by mathildepoulpux** [comment]
Eh bah parfait :D
