### ISSUE TITLE
Changer le lien de démo dans les mails automatique à la création de compte

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#1194]

**Comment by mathildepoulpux** [comment]
Dans l'email login_link_email, modifier le lien vers la démo : 

Première fois sur Histologe ?
Inscrivez-vous à nos sessions de formation [en cliquant sur ce lien](https://app.livestorm.co/mte/demonstration-histologe).


Lien à mettre: https://app.livestorm.co/mte/demonstration-histologe
