### ISSUE TITLE
[Import Données - Ardeche]

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1206]
Importer données
https://drive.google.com/file/d/1mvt5_sZZzCL6nHprp1WCq8dYpU79Qg7X/view?usp=share_link

**Comment by sfinx13** [comment]
Dans l'import de signalement, il faut prendre en compte les : 
* Situation(s) suspectée(s) 
* Nouvel algo de criticité dans l'import des signalement

**Comment by sfinx13** [comment]
@arnaudchouk j'ai du adapté le script pour prendre en compte ce qui a été fait dernièrement (nouvel algo score, quaifications signalement)

**Comment by sfinx13** [comment]
@arnaudchouk tu peux regarder sur staging https://histologe-staging.incubateur.net/bo/signalements/ avant, on pourra le faire mardi sur la prod

**Comment by arnaudchouk** [comment]
bueno - on peut mep
