### ISSUE TITLE
[Dashboard - Metabase] Suivi relance auto

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1209]
ajouter dans les tableaux de bord de suivi relance auto, 

* le nombre de signalements ayant reçu au moins 2 relances auto ET qui n'ont eu aucune autre action depuis la 1ere relance (cad pas de suivi auto, pas de commentaire partenaire, pas de commentaire usager)
* la liste de ces signalements (sur le meme format comme le listing des signalements relances )

**Comment by hmeneuvrier** [comment]
Test première requête

`SELECT territory.zip, ville_occupant, is_logement_social,  s.reference, CONCAT('https://histologe.beta.gouv.fr/bo/signalements', '/', s.uuid) as lien
FROM signalement s
inner join territory on s.territory_id = territory.id
INNER JOIN (
  SELECT su.signalement_id
  FROM suivi su
  WHERE su.type = 4
  GROUP BY su.signalement_id
  HAVING COUNT(*) >= 2
) t1 ON s.id = t1.signalement_id
LEFT JOIN (
  SELECT su.signalement_id
  FROM suivi su
  WHERE su.is_public = true
    AND su.type <> 4
    AND su.created_at > (
      SELECT MAX(su2.created_at)
      FROM suivi su2
      WHERE su2.signalement_id = su.signalement_id
        AND su2.type = 4
    )
) t2 ON s.id = t2.signalement_id
WHERE t2.signalement_id IS NULL
[[and s.territory_id = {{idTerritory}}]]`
