### ISSUE TITLE
[QA] Pb de connexion à la base

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1217]
https://sentry.incubateur.net/organizations/betagouv/issues/35435/events/643bf489d51146399eabc536af9baeca/?project=61&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox&statsPeriod=14d

**Comment by sfinx13** [comment]
Bug lié lors d'un incident base de données coté sur scalingo.

**Comment by hmeneuvrier** [comment]
je ferme
