### ISSUE TITLE
[Relance Auto] Mail 3e relance sans réponse + création de suivi auto

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1242]
Envoyer un mail spécifique aux usagers si les 2 1eres relances n ont pas généré d action de leur part

* Proposer 2 boutons Poursuivre Procédure/Arrêter procédure 

* Si arrêt de procédure demandé par usager, créer un suivi auto usager Abandon procédure demanndé
* Si poursuite procédure demandé par usager, l'nevoyer sur la page de suivi et l'inviter à préciser s il y a du nouveau dans la situation pour créer un suivi

* contenu du mail
Bonjour Nom Prenom
Vous avez signalé un problème dans le logement au Adresse
Les services sont pleinement investis sur votre dossier
Cependant nous vous avons contacté par mail à 2 reprises afin de faire le point sur votre situation mais nos messages sont restés sans réponse de votre part
Votre situation a-t-elle évolué ? Merci d'indiquer si vous souhaitez poursuivre ou arrêter la procédure en cliquant sur les boutons ci-dessous. 

En cas d’absence de réponse de votre part, votre signalement pourra être clôturé par les services compétents.

Merci

**Comment by sfinx13** [comment]
> Si pas de réponse au 3e mail créer un widget "Usager sans réponse après 3 relance" sur dashboard Partenaires et RT pour leur permettre de cloturer les signalements concernés rapidement en affichant un listing trié avec ces signalements uniquement

@arnaudchouk pour la création de widget, ça sera un autre ticket #1249

**Comment by arnaudchouk** [comment]
si abandon > plus de relance > creation du suivi usager Abandon procedure
si poursuite procedure > relance J+45 (dans ce cas il y aura eu un retour usager à une relance)
si pas de reponse > plus de relance > bascule dans la liste des signalements sans retour usager apres 3 relance > a cloturer par territoires
