### ISSUE TITLE
[BO - Signalement] Créer suivi automatique visible après acceptation affectation

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1245]
* Créer à J+1 après 1ere acceptation d'une affectation un suivi visible + envoi du mail informant d'une mise à jour de signalement

"Suite à votre signalement le ou les partenaires compétents sur votre dossier ont été informés et ont validés la prise en charge de votre dossier. 
Vous serez bientôt contacté(e) pour des informations complémentaires ou pour programmer une visite du logement. 

N’hésitez pas à partager toute information qui vous semblerait pertinente. Nous reviendrons vers vous également afin de nous assurer de l’avancée des démarches."

**Comment by sfinx13** [comment]
Est ce envisageable de créer le suivi directement et non à j+1 ? @mathildepoulpux

**Comment by mathildepoulpux** [comment]
Pour moi oui !
Pourquoi tu avais pensé à J+1 @arnaudchouk  ?

**Comment by arnaudchouk** [comment]
c etait pour donner encore un peu plus de temps aux acteurs avant la relance auto - mais plus ou moins un jour ca change pas grand chose

**Comment by arnaudchouk** [comment]
Message auto suite affectation - message créé au nom des agents des communes 
ca doit être fait comme pour les messages auto par Histologe - on ne peut pas créer des suivis au nom de personnes tierces, cela crée une responsabilité juridique de la personne mentionnée
ex sur le 06 
2023 -527
2023-528

**Comment by emilschn** [comment]
Problème signalé par Arnaud sur le 2022-938 dans le territoire 06 suite à réouverture

Autre souci que je vois d'après le code : 
- 2 partenaires sont affectés
- A accepte (donc suivi) puis cloture
- B accepte : création nouveau suivi

**Comment by arnaudchouk** [comment]
autre ajustement 
Ce message /suivi ne devrait pas concerné les signalements importés
