### ISSUE TITLE
[Relance auto] Page suivi Ajout mention

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1247]
Les services compétents ont bien pris en charge votre dossier et vous contacteront bientôt si ce n'a pas encore été fait. N'hésitez pas à partager toute information qui vous semblerait pertinente.

**Comment by hmeneuvrier** [comment]
@mathildepoulpux @arnaudchouk On ne comprend pas trop cette carte. Est-ce que c'est l'ajout de ce texte sur la page de suivi usager ? Est-ce que c'est ça, mais uniquement s'il arrive sur la page de suivi via un mail de relance auto (ce qui implique d'avoir une page de suivi différenciée dans ce cas) ? Ou est-ce que ça a un lien avec #1245 ?

**Comment by arnaudchouk** [comment]
de memoire ce qu on avait evoque c etait de l integrer de maniere générique sur la page comme élément de rassurance d un usager qui vient sur la page de suivis. A confirmer avec mathilde

**Comment by mathildepoulpux** [comment]
Oui, c'était ça. 
Après si on met déjà cette mention dans le suivi envoyé à l'usager après acceptation de l'affectation, c'est pas la peine de le remettre sur la page de suivi je pense !

**Comment by arnaudchouk** [comment]
ca me va - il sera toujours temps de compléter la page de suivi egalement

**Comment by hmeneuvrier** [comment]
> Oui, c'était ça. Après si on met déjà cette mention dans le suivi envoyé à l'usager après acceptation de l'affectation, c'est pas la peine de le remettre sur la page de suivi je pense !

ok du coup je le ferme
