### ISSUE TITLE
[Relance auto] Création d'un nouveau widget sur le dashboard

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1249]
Créer un widget "Usager sans réponse après 3 relances" sur dashboard Partenaires et RT pour leur permettre de cloturer les signalements concernés rapidement en affichant un listing trié avec ces signalements uniquement

**Comment by hmeneuvrier** [comment]
n lien vers la liste des signalements qui n'ont aucun commentaire usager suite aux 3 relances + usagers ayant indiqué qu'ils veulent abandonner la procédure

Pour les agents et admin partenaire : les signalements en cours avec affection acceptée 
Pour les RT : tous les signalements concernés sur le territoire 
Super admin : tous signalements concernés de tous les territoires 
[4:35 PM](https://mattermost.incubateur.net/betagouv/pl/f6o8uz6a7i89zbyp8kqezisuay)

Pour le nom du widget je propose : "Suggestion de clôture" 
Description : Retrouvez et clôturez les signalements pouvant correspondre à un abandon de procédure par l'usager 

Compteur : nb de signalements concernés avec un statut en cours

**Comment by mathildepoulpux** [comment]
Attente du #1320 pour pouvoir le tester
