### ISSUE TITLE
[FO & BO - Signalement] Champs Date de Naissance

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1269]
Ajouter champs date de naissance à remplir:
* si occupant allocataire
* champ obligatoire si occupant = declarant
* optionnel si declarant tiers

Ce champs existait avant et est peut etre toujours dans les tables
Ajouter l info sur le signalement côté BO à proximité des infos allocataires

**Comment by hmeneuvrier** [comment]
Tout ce que je trouve est un champ NaissanceOccupants qui ne contient pas des dates à proprement parler

![image](https://github.com/MTES-MCT/histologe/assets/33071753/2b46b131-bd6e-4d14-a1c0-b12a7e460f06)

**Comment by arnaudchouk** [comment]
ca ne fera pas l'affaire il faut la date exacte...

**Comment by emilschn** [comment]
Je pars de la fonctionnalité Visites pour le mettre en place, pour ne pas faire la partie BO 2 fois pour pas grand chose :)

**Comment by emilschn** [comment]
@arnaudchouk si l'utilisateur n'est pas allocataire, on lui propose quand même le champ facultatif (au cas où ce soit utile plus tard) ou on ne l'affiche pas du tout ?

**Comment by arnaudchouk** [comment]
dans le formulaire actuel je ne suis pas certain que ce soit utile de l afficher - 
dans le prochain ca pourrait etre le cas

**Comment by emilschn** [comment]
Si jamais vous voulez tester, c'est dispo sur l'app de test des visites @arnaudchouk @mathildepoulpux

**Comment by mathildepoulpux** [comment]
Pour le déclarant occupant
Il faudrait indiquer que le champ date de naissance est obligatoire : 
![image](https://github.com/MTES-MCT/histologe/assets/97226289/5e8cc1ed-a723-40b7-8dba-93c6a4a26f15)

**Comment by mathildepoulpux** [comment]
Je suis super admin
Je veux modifier un signalement où il est indiqué qu'il s'agit d'un allocataire CAF et où la date de naissance est renseignée
![image](https://github.com/MTES-MCT/histologe/assets/97226289/e077e9ad-ffcf-4ae4-b916-dc5a1795150d)

Dans le formulaire, la case CAF est bien cochée, mais seule la question "Numéro allocataire" apparaît
![image](https://github.com/MTES-MCT/histologe/assets/97226289/7ac0b7bd-6382-44b8-a039-468934ee5e4e)

Si je veux afficher la date de naissance, je dois cliquer sur une autre option puis re-cliquer sur "CAF"
Ce qui a pour effet de supprimer la date de naissance déjà renseignée depuis le FO 
![image](https://github.com/MTES-MCT/histologe/assets/97226289/ad6d4e16-3eca-4c3e-88ab-996f114fe52f)

-> Si l'usager a coché la case "CAF" ou "MSA", il faut que le champ soit affiché dans le formulaire BO, avec les données renseignées en FO
