### ISSUE TITLE
[API] Mise à jour API Commune - code insee

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1303]
S'appuyer sur l'api maintenu par l'insee, voir le thread
https://mattermost.incubateur.net/betagouv/pl/t9cywee8q3fktp16ftrx5r411a

**Comment by emilschn** [comment]
Codes postaux actuellement stockés dans les fixtures : https://www.data.gouv.fr/fr/datasets/codes-postaux/#/resources
Datent de 2019

Codes postaux actualisés (via INSEE) : https://www.data.gouv.fr/fr/datasets/code-officiel-geographique-cog/

Le format n'est pas le même.

Possibilités :
- utiliser l'API de l'INSEE : à étudier
- utiliser les exports CSV déjà disponibles et faire une mise à jour annuelle
  - soit remplacer le fichier existant, soit ajouter un fichier annuel
  - créer une commande qui fait un diff avec la base de données
    - supprimer les communes qui n'existent plus
    - ajouter les communes nouvelles

**Comment by hmeneuvrier** [comment]
Mise à jour une fois/an avec les csv mis à jour de l'insee
Faire l'import, mise à jour de la table avec ajout de communes inexistantes, (et suppression des communes qui n'existent plus ?)
Vérifier avec les codes insee qui sont dans la conversation mattermost, voir s'ils sont dans les csv générés sur le site de l'insee

**Comment by numew** [comment]
En fait je ne trouve aucune ressource qui soit meilleure que celle que l'on utilise déjà : 
- Les fichiers de l'INSEE ne contiennent pas de colonne code postal (dommage car les codes INSEE 59298 et 59355 sont bien présent dedans)
- Dans "[Base officielle des codes postaux](https://www.data.gouv.fr/fr/datasets/base-officielle-des-codes-postaux/)" les nom des commune sont en majuscule non accentués et de toute façon les codes INSEE 59298 et 59355 ne sont pas non plus présent.
