### ISSUE TITLE
[FO - Contenus] Corrections

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1309]
retours du 06 sur les infos procédures du site
[Histologe - Signalez vos problèmes de logement.pdf](https://github.com/MTES-MCT/histologe/files/11652264/Histologe.-.Signalez.vos.problemes.de.logement.pdf)

**Comment by mathildepoulpux** [comment]
Sur la page de validation, après dépôt du signalement. Modifier les contenus suivants : 

Pour tous les types de procédure : modifier `Partenaires impliqués` en `Partenaires éventuels`

Partie procédure de non décence
- Dans les mesures possibles, retirer la mention `Lettre de mise en demeure`

Partie procédure d'infraction au RSD
- Dans les exemples de désordres : remplacer `La peinture est abîmée et contient du plomb` par ``
- Dans les mesures possibles : remplacer `Arrêté municipal` par `Lettre de mise en demeure`

Partie procédure d'insalubrité
- Dans les désordres : modifier le premier en `Il n'y a pas de fenêtre ni de ventilation dans mon logement`
- Dans les mesures possibles : remplacer `Arrêté municipal` par `Arrêté préfectoral`

Partie procédure de mise en sécurité
- Dans les partenaires impliqués : remplacer les partenaires actuels par `SCHS` et `Mairie`
