### ISSUE TITLE
FO et BO - Avoir la possibilité, au sein d'un champ de saisie du signalement de pouvoir déplacer le curseur à l'aide des flèches directionnelles du clavier : facilite la correction d'erreurs de frappe.

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1311]
Exemple : je saisis mon nom et je veux corriger la 3ème lettre : je suis obligée de cliquer au bon endroit pour modifier cette lettre et je ne peux pas revenir avec les flèches

**Comment by hmeneuvrier** [comment]
@arnaudchouk c'est toujours le cas ça ?

**Comment by arnaudchouk** [comment]
a priori c est ok dans le nouveau form
