### ISSUE TITLE
Carto Punaises/Histologe

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1317]
Dans un premier temps, il faut ajouter la latitude et la longitude sur les signalements dans Punaises : https://github.com/orgs/MTES-MCT/projects/3?pane=issue&itemId=30042134

Dans un deuxième temps voir pour faire une carte de chaleur :
https://www.patrick-wied.at/static/heatmapjs/plugin-leaflet-layer.html

**Comment by arnaudchouk** [comment]
Investiguer carte de chaleur
