### ISSUE TITLE
[BO-Signalement] Acces aux documents signalement fermes

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1318]

**Comment by hmeneuvrier** [comment]
Effectivement, cela vient de la correction d' @emilschn sur le hover des documents : https://github.com/MTES-MCT/histologe/commit/01483d1ffb0130738431448c28d49314196c2fb4

**Comment by arnaudchouk** [comment]
impossible d ouvrir un document sur un signalement fermé
test en SA et RT
ex signalement 2023-31 sur le 06

**Comment by hmeneuvrier** [comment]
effectivement, chelou, je regarde s'il y a eu un pb de merge

**Comment by hmeneuvrier** [comment]
ok après un redéploiement

**Comment by arnaudchouk** [comment]
ok pour moi
