### ISSUE TITLE
[BO - Visite] Modifier champ date pour avoir le date picker

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1337]
Dans le BO, dans la modale visite, la date doit être entrée à la main dans le champ
![image](https://github.com/MTES-MCT/histologe/assets/97226289/31ddb671-bee5-49f5-ad1f-5d29e814424c)

Il faudrait le remplacer par le champ date dispo dans le [DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/champ-de-saisie) qui permet d'afficher le calendrier en cliquant sur l'icône : 
![image](https://github.com/MTES-MCT/histologe/assets/97226289/9985a586-4fb3-4509-bdae-8560edebf5e6)

**Comment by emilschn** [comment]
Hmm ça fonctionne sur Firefox mais pas Chrome. Ca va peut-être nécessiter la MAJ du dsfr :cold_sweat:

**Comment by mathildepoulpux** [comment]
OK, bah on laisse comme ça pour le moment
je crée une carte pour la MAJ du DSFR, ce serait bien d'être sur la dernière version !
