### ISSUE TITLE
[BO - Visite] Ne pas afficher tous les champs si visite non effectuée

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1339]
Je suis SA
Je veux ajouter une visite déjà effectuée
Quand on renseigne une date par le passé, les 5 champs sont affichés : 

![image](https://github.com/MTES-MCT/histologe/assets/97226289/471911ef-dce7-4479-b9ff-54cc51ff3829)

Quand une visite n'a pas pu être effectuée, ça n'a pas de sens de demander si l'occupant, le propriétaire étaient présents, ni le rapport de visite.
Il faudrait modifier le comportement : 
- Si sélection `Visite effectuée` = affichage des champs comme actuellement
- Si sélection `Visite non effectuée` = affichage du champ commentaire uniquement

**Comment by emilschn** [comment]
Le champ "conclusion de visite" est déjà masqué, mais je m'étais dit que ça avait du sens quand même de laisser les champs de présence occupant/proprio.
Exemples : 
- l'occupant est présent mais la visite n'est pas faite parce que le propriétaire est absent et nécessaire.
- le propriétaire est présent mais l'occupant est absent donc ils ne peuvent pas rentrer

Qu'en penses-tu @mathildepoulpux  ?

**Comment by mathildepoulpux** [comment]
Ah oui vu comme ça effectivement
