### ISSUE TITLE
[BO - signalement] Comportement étrange interrupteur dans modale suivi

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1341]
Ce dont on a parlé  @emilschn du comportement de l'interrupteur quand on le sélectionne puis clique à côté.
Faudrait qu'il ait le comportement prévu dans le DSFR

![image](https://github.com/MTES-MCT/histologe/assets/97226289/69d268b1-0588-4c2e-9c98-85c186faafd3)

**Comment by emilschn** [comment]
@mathildepoulpux tu m'avais dit que ça avait miraculeusement disparu, ça ?

**Comment by mathildepoulpux** [comment]
Non 😄 
Là je viens de tester quand je clique ça me fait ça : 
![image](https://github.com/MTES-MCT/histologe/assets/97226289/511d69ef-bf7c-4f2a-a319-bd2881aa711a)


Faut que je clique ailleurs pour que l'affichage soit correct
