### ISSUE TITLE
[Technique] MAJ du DSFR

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1348]
Passer sur la dernière version du DSFR pour utiliser les derniers éléments, corriger des petits bugs, assurer l'accessibilité & être "beta compatible"

**Comment by hmeneuvrier** [comment]
Faire sur la branche des visites ou une fois les visites mergées sur develop

**Comment by sfinx13** [comment]
#1647
#1630 
#1631 
#1632 
#1633 
#1635 
#1636 
#1647
