### ISSUE TITLE
[Emails usager] Vérifier qu'il n'y a pas de mail de visite déjà envoyé 

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1365]
### Règles actuelles : 
- il est possible de créer une visite sur un signalement dont les affectations sont en attente (afin de ne pas boquer le travail des responsables de territoire)
- Quand on crée une visite (future ou passée), un email est envoyé à l'usager
- Un email est envoyé à l'usager quand la première affectation est acceptée, pour éviter que la relance auto parte trop tôt

### Cas concerné
- Signalement avec des partenaires affectés et toutes les affectations en attente
- Au moins un partenaire a la compétence visite

#### Flow : 
1. Le RT crée une visite
2. Un email visite est envoyé à l'usager
3. Un partenaire accepte l'affectation
4. Un email "première affectation acceptée" est envoyé à l'usager
**--> C'est étrange pour l'usager qui reçoit d'abord un email en lui disant qu'une visite est programmée ou qu'un rapport de visite est dispo PUIS un email lui disant que les partenaires ont confirmé la prise en charge...**

#### Solution
Vérifier si un email visite a été envoyé ou non : 
- Dans le cas où un email visite a été envoyé : ne pas envoyer l'email "première affectation acceptée"
- Dans le cas où aucun email visite n'a été envoyé : envoyer l'email "première affectation acceptée"

**Comment by sfinx13** [comment]
@mathildepoulpux 
On a pas d'email usager (première affectation acceptée) c'est un plutôt un suivi  

![image](https://github.com/MTES-MCT/histologe/assets/5757116/9bc7f16d-dc7d-4a81-b4d3-f6a142fe9f14)

Le mail que l'usager reçoit est un le mail standard 'Nouvelle mise à jour de votre signalement' avec le suivi auto

![image](https://github.com/MTES-MCT/histologe/assets/5757116/e36bae74-1607-42cf-94b5-a0701f12d39e)


Du coup je propose de ne pas ajouter de suivi auto de première affectation lorsqu'une visite a été déjà été planifié ou effectué. 

ça te va ?

**Comment by sfinx13** [comment]
@mathildepoulpux 
On a pas d'email usager (première affectation acceptée) c'est un plutôt un suivi  

![image](https://github.com/MTES-MCT/histologe/assets/5757116/9bc7f16d-dc7d-4a81-b4d3-f6a142fe9f14)

Le mail que l'usager reçoit est un le mail standard 'Nouvelle mise à jour de votre signalement' avec le suivi auto

![image](https://github.com/MTES-MCT/histologe/assets/5757116/e36bae74-1607-42cf-94b5-a0701f12d39e)


Du coup je propose de ne pas ajouter de suivi auto de première affectation lorsqu'une visite a été déjà été planifié ou effectué. 

ça te va ?

**Comment by sfinx13** [comment]
@hmeneuvrier réponse de @mathildepoulpux c'est OK
