### ISSUE TITLE
[Esabora SCHS] Investigation Pau

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1378]
Voir email transféré le 15/06/2023

**Comment by sfinx13** [comment]
Activation interconnexion https://histologe.beta.gouv.fr/bo/partenaires/470/voir

**Comment by hmeneuvrier** [comment]
`2023-178	2024-07-15 08:19	SCHS Pau	sync_dossier	failed	Ce web service est actuellement rendu indisponible par la variable $ea_param["ws"]["mult"] du fichier de configuration de l'application. (401)`

**Comment by sfinx13** [comment]
Je ferme le ticket, personne a l'air de ce soucier de l'interconnexion de Pau.
