### ISSUE TITLE
[BO - Signalement] Notifications

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1384]
ne pas générer de notification ni de mail pour l'agent/partenaire qui est à l'origine dui suivi

**Comment by hmeneuvrier** [comment]
à voir si ce n'est pas déjà le cas partout ?

**Comment by emilschn** [comment]
Je viens de vérifier le comportement actuel pour qu'on se mette d'accord. Le voici ci-dessous.
@arnaudchouk tu pourras me valider ce qui est souhaité ?

**Situation actuelle**
Imaginons USER_A1 et USER_A2 qui appartiennent à PARTNER_A
Quand USER_A1 ajoute un suivi :
- USER_A1 reçoit une notification
- USER_A2 reçoit une notification
- PARTNER_A reçoit un e-mail
- USER_A2 reçoit un e-mail

**Situation voulue**
- USER_A1 ne devrait pas recevoir de notification
- USER_A2 doit recevoir une notification
- PARTNER_A : ?
- USER_A2 doit recevoir un e-mail

**Comment by arnaudchouk** [comment]
de ce que j ai compris des attentes :

    USER_A1 ne devrait pas recevoir de notification
    USER_A2 ne devrait pas recevoir une notification
     USER_A2 : ne devrait pas recevoir de mail
  PARTNER_A : doit recevoir le mail 

sur partner A c etait pas si evident mais je pense que c est pas inutile de laisser le mail pour les partner qui ont bcp de dossiers et utilisateurs

**Comment by arnaudchouk** [comment]
question @sfinx13 quand on dit mail a PARTNER c est bien le mail generique (et pas tous les comptes user du partner) ?

**Comment by sfinx13** [comment]
> question @sfinx13 quand on dit mail a PARTNER c est bien le mail generique (et pas tous les comptes user du partner) ?

oui @arnaudchouk c'est le mail générique
