### ISSUE TITLE
[FO - Formulaire] Lister toutes les questions, clés etc. (hors désordres) dans un excel

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1390]

**Comment by mathildepoulpux** [comment]
Tout est là : https://docs.google.com/spreadsheets/d/12uJcJAWNm9W5R_A6Eh5vwhtLy2ThBNz3CCdkws-ZeIs/edit#gid=0

J'ai essayé de mettre les éléments qui relèvent d'une même clé de trad (à mon sens) à la suite pour qu'on puisse mieux réaliser combien y en a à créer.

J'ai mis des variables pour 2 éléments (à vous de voir après hein) : 
- {{service}} c'est Histologe, mais je me dis que vu qu'on va bientôt changer de nom c'est pas plus mal
- {{type_chauffage}} qui peut avoir 3 valeurs : 
    - Electrique
    - Gaz, bois, éthanol ou fioul 
    - Indéterminé

@hmeneuvrier @sfinx13 @emilschn 
J'ai pas mis les messages d'info / warning / erreur, ni le contenu des écrans d'intro ou intermédiaire.
Est-ce que je mets tout ça dans un autre onglet ? A part ?

**Comment by hmeneuvrier** [comment]
Voir si on peut factoriser les écrans de coordonnées occupant / déclarant / bailleur en ajoutant des conditionnalités sur certaines questions seulement, et pas sur les écrans en entier

**Comment by emilschn** [comment]
@mathildepoulpux 
Merci pour tout le travail, on trouve le tableau top !

Est-ce que tu confirmes que les infos s'afficheront dans l'ordre où ça a été mis dans le tableau ?

On a commencé à pas mal le retoucher pour essayer de trouver un format final, donc ne t'étonne pas si tu vois quelques colonnes complémentaires.
On a notamment ajouté un type écran qui nous sert de référence et sous lequel on peut lier les champs.

Pour les messages de feedback, on pense que c'est mieux de les avoir dans les onglets existants sur une ligne spécifique, avec les conditions d'affichage que tu as déjà mises en place, si ça te convient. Plutôt que de mettre dans un onglet à part.  On l'a fait en exemple pour les infos sur les proprios.

**Comment by hmeneuvrier** [comment]
@emilschn @sfinx13 j'ai fini de revoir le premier onglet du fichier excel, il y a quelques commentaires et cases en jaune (notamment pour @mathildepoulpux ) mais je suis rassurée par la faisabilité de la chose.
Je n'ai pas créé les clés pour chaque ligne par contre.

@mathildepoulpux tu verras j'ai pas mal retravaillé, en 
- ajoutant des lignes pour chaque écran
- en factorisant au maximum pour ne pas avoir des doublons pour chaque profil
- en ajoutant les commentaires que tu as commencé à mettre dans l'onglet Autre. Je les ai intégré dans le premier l'onglet, l'idée étant vraiment d'avoir une ligne par élément, de manière linéaire, avec un système de clé qui permet de définir à quel écran ou sous-écran ça appartient

Pour un des derniers écrans, celui qui permet d'éditer des parties ou d'ajouter les infos complémentaires, j'ai ajouté pas mal de lignes pour correspondre au wireframe (sinon je ne comprenais plus trop l'organisation) https://xd.adobe.com/view/b2df12c5-32a1-469d-90cc-144854dea9da-e78c/screen/30c9a4a8-3dab-4f54-916c-2fbe01b4db1c/
Ce n'est peut-être pas du tout ce que tu voulais faire ?

**Comment by hmeneuvrier** [comment]
Reste : 
- tous les slugs des questions
- remplacer lignes 6 à 11 par composant adresse
