### ISSUE TITLE
[BO - Signalement Importés] Affectations clôturés mais signalement non-clôturé

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1398]
Territoire Isere - signalement 2021-6923
https://histologe.beta.gouv.fr/bo/signalements/803db3ea-4662-4f9c-91c3-35c66d63df4b
Indiqué comme en cours dans le listing

En tant que SA, quand j'ouvre le signalement tout à l'air normal et le bouton cloturer apparait
![image](https://github.com/MTES-MCT/histologe/assets/93710194/9580012c-24d6-441d-825c-eced12d1b67d)

Par contre quand je me connecte à l aide d un compte test RT cree au sein du partenaire DDT, la page de signalement apparait grisée (cloturee) avec boutons reouvrir DDT/Tous
Pourtant toujours noté en cours dans le listing
![image](https://github.com/MTES-MCT/histologe/assets/93710194/7e4cba94-0d16-42b5-811f-c0dd5cc9f40a)

**Comment by emilschn** [comment]
Cette logique est déjà en place (et était déjà en place lors de l'import) : 
- Si il y a un statut de fermeture, on ferme
- Sinon, si il y a un motif de cloture ou une date de cloture, on ferme aussi.


Je viens de regarder le fichier :
- il n'y a pas de colonne `statut`
- il y a des colonnes `motif_cloture` et `date_cloture`

**Fonctionnement attendu**
Sur les lignes où il y a un motif ou une date de cloture : les affectations ET le signalement sont fermés.

**Fonctionnement inattendu**
Sur les lignes où il n'y a rien dans ces colonnes (dont le signalement en question) :
- le signalement n'est pas fermé : ça semble normal
- les affectations sont fermées, comme tu le signales : ça semble anormal
Je ne vois pas ce qui crée ce comportement, ce n'est pas prévu dans le code.

A priori, le signalement a été mis à jour lors de l'import (il existait déjà auparavant). Mais je ne pense pas que ça peut expliquer.

Bref, je sèche un peu pour l'instant @hmeneuvrier @sfinx13

**Comment by arnaudchouk** [comment]
un signalement ouvert peut etre cloture par tous les partenaires - ca ce n est pas anormal

de ce que je comprends si la ddt qui est RT est affectee et qu elle a cloture le signalement, le statut Partenaire affecté prend le dessus sur son affichage (page grisee car partenaire fermé)
alors qu a priori un compte RT et Partenaire à la fois devrait avoir la version RT toujours affichee (donc page accessible avec le bouton fermer affiché)

**Comment by emilschn** [comment]
Ok, donc ce que tu signales est une partie du souci, ça peut se corriger.

Ce que je signale et qui me surprend, c'est que pendant l'import, les affectations ont été immédiatement cloturées, alors que je ne vois pas spécialement de raison pour ça. Et ce n'est pas le seul signalement de cet import qui est dans ce cas-là.

Mais si on corrige ce que tu signales, les RT pourront cloturer le signalement, et ça permettra d'ajuster.
Je vais déjà voir pour corriger ça, puisque ça au moins, je comprends pourquoi ça le fait :)

**Comment by arnaudchouk** [comment]
j ai fouillé les mails - il n est pas impossible qu ils aient demandes à ce que les signalements soient importés sous le statut en cours, avec des partenaires affectes mais avec le statut cloturé
