### ISSUE TITLE
[BO - Signalement] La visite est créée deux fois

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1402]
Empecher la création de visite en double -
En cas de latence, plusieurs clic sur enregistrer cree autant de visites que de clic

**Comment by mathildepoulpux** [comment]
Proposition : une fois cliqué, modifier le bouton pour en mettre le passer en mode inactif avec l'icône fr-icon-refresh-line et le texte "En cours..."
Je sais pas si c'est faisable @emilschn  ?

**Comment by emilschn** [comment]
C'est fait, mais sans reproduire le souci d'origine

**Comment by mathildepoulpux** [comment]
Je sais pas comment le tester pour le coup 🤷‍♀️

**Comment by sfinx13** [comment]
on ferme @mathildepoulpux  @emilschn ?

**Comment by emilschn** [comment]
pour moi, oui, et on rouvrira un nouveau ticket si le souci réapparait !
