### ISSUE TITLE
[BO - Signalement] Problème connexion Chalon en Champagne à Esabora

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1407]
La ville de chalon sur saone a parametre elle meme ESABORA pour se connecter à Histologe
Nous voyons des erreurs mais ils ne semblent pas les recevoir
* ils souhaitent des details sur les erreurs
* liste des IP serveur Histologe

**Comment by emilschn** [comment]
Le SCHS de Chalon sur Saone n'est pas connecté.

Par contre `Mairie de Chalons-en-Champagne` l'est.
De ce que j'analyse : le partenaire n'est affecté qu'à 2 signalements.
Les 2 affectations ont été acceptées en janvier et février.
Donc la connexion n'était pas encore fonctionnelle, donc les dossiers n'ont pas été liés à un dossier sur Esabora.
Depuis la mise en place de la connexion, on essaie de récupérer des informations avec une liaison qui n'existe pas, donc on ne peut rien avoir :)

**Comment by arnaudchouk** [comment]
comment on teste ca @emilschn 
en prod on voit ca 
![image](https://github.com/MTES-MCT/histologe/assets/93710194/5ead29c0-a2a3-48af-aeb4-122d8019746e)

**Comment by emilschn** [comment]
Pour 2023-1 et 2023-16, je pense qu'il faudrait désaffecter / réaffecter la commune. Le dossier n'a jamais été envoyé depuis Histologe vers Esabora.
Sinon, il y a 2 autres signalements (2023-113 et 2023-130) qui se synchronisent correctement.

**Comment by arnaudchouk** [comment]
ok donc on peut cloture merci
