### ISSUE TITLE
[BO - Notifications] Sanitize pour le texte des notifications

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1408]
Territoire 06
Rôle RT - page notification
Affichage non responsive - boutons non affichés + pas de modification de l affichage selon la taille de la fenetre
![image](https://github.com/MTES-MCT/histologe/assets/93710194/77b6c548-4c0f-4574-b1b0-76e4539a65a4)

**Comment by hmeneuvrier** [comment]
Reproductible en SA sur la 3ème page de notification

Vient du suivi


2023-167 | 27 juin 2023 à 16:36:53 | Bonjour, Vous n'avez pas répondu aux diverses sollicitations du service d'hygiène afin de réaliser la visite de votre logement. Je vous invite à prendre contact avec Mme Chaillan à  marie-josee.chaillan@ville-nice.fr , sans manifestation de votre part  nous serons dans l'obligation de clôturer votre dossier. Cordialement. | PRIOUL Stéphane
-- | -- | -- | --

avec des styles `style="white-space: nowrap;"` dans des spans

**Comment by hmeneuvrier** [comment]
quand on enlève ce style, la page s'affiche de nouveau bien

**Comment by hmeneuvrier** [comment]
Corrigé par @numew dans https://github.com/MTES-MCT/histologe/issues/2499
