### ISSUE TITLE
[BO - Signalement] Ajout de doc derrière fenêtre saisie suivi

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1421]
la fenetre ajout de document dans la partie suivie s affiche derriere la fenetre de saisie du suivi rendant impossible l'ajout du doc

**Comment by arnaudchouk** [comment]
vu que tu es sur le sujet 
j ai fait une demo NDE ce matin et normalement il y a l acces aux document courriers types - mais j ai pas pu les utiliser vu que je ne voyais pas la fenetre
est ce que vous pouvez vous assurer que c est toujours en place

**Comment by emilschn** [comment]
Ok, j'ouvre un autre ticket
