### ISSUE TITLE
[Back] Mock API - Récupération des questions avant profil

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1423]
## Description
Afin de ne pas bloquer le développement des différents composants coté front-end, un mock devra être disponible à travers un endpoint. 
Cet endpoint fournira des résultats lorsqu'une valeur sera renseigné au paramètre `profil`. 
Les valeurs des différents profils sont listé ci-dessous

### Arborescence et liste des profils
La liste des profils respecte l'arborescence suivante
```
.
└── Tous
    ├── Tous les occupants
    │   ├── Locataire
    │   ├── Bailleur occupant
    ├── Tous les tiers
    │   └── Tiers particulier
    │   └── Tiers pro
    │   └── Service de secours
    │   └── Bailleur
```

| Libellé                 | Slug                      |
|-------------------------|---------------------------|
| Tous                    | tous                      |
| Tous les occupants      | tous-les-occupants        |
| Locataire               | locataire                 |
| Bailleur occupant       | bailleur-occupant         |
| Tous les tiers          | tous-les-tiers            |
| Tiers particulier       | tiers-particulier         |
| Tiers pro               | tiers-pro                 |
| Service de secours      | service-de-secours        |
| Bailleur                | bailleur                  |

### Exemples

Récupération des questions communes 
```
GET /api/questions?profil="tous"
```

Récupération des questions selon le profil `tous-les-tiers`
```
GET /api/questions?profil="tous-les-tiers"
```

Récupération des questions selon le profil `locataire`
```
GET /api/questions?profil="locataire"
```

 
## Comportements attendus
Les réponses attendues sont très inspiré de form.io qui est une plateforme web qui permet de créer des formulaires orienté composants. Vous trouverez la liste des composants dans #1425 

Par définition un composant comporte les propriétés suivantes.

### Design
Cette liste n'est pas exhaustive et peut être amené à évoluer si besoin

*Exemple: Champs texte*

```json
{
  "type": "textfield",
  "label": "Etage",
  "description": "",
  "slug": "etage",
  "validate": {
    "required": true,
    "custom": "^\\d{2}$"
  }
}
```
*Exemple: Choix unique* (La valeur show pourra être évalué)
```json
{
  "type": "only-choice",
  "label": "Le logement est au RDC",
  "description": "",
  "slug": "le-logement-est-au-rdc",
  "values": [
    {
      "label": "Oui",
      "value": "oui"
    },
    {
      "label": "Non",
      "value": "non"
    }
  ],
  "conditional": {
    "show": "data.type_logement === 'appartement'"
  }
}
```
*`data` fait référence aux données du formulaire remplies.*
### Propriété

Propriété | Description
-- | --
type | Spécifie le type de composant, dans cet exemple **textfield**. (La liste exhaustive se trouve dans le ticket #1390 )
label | Définit le libellé du composant **(exemple: libellé d'une question)**
slug | Représente la clé ou **l'identifiant unique** du composant, utilisé pour identifier le composant dans les données soumises.
validate | Spécifie **les règles de validation** pour le composant. Dans cet exemple, la propriété *"required"* est définie sur true, ce qui signifie que le champ est obligatoire. De plus, la propriété *"custom"* utilise une expression régulière pour valider le format.
conditional | Permet de définir **une condition pour afficher ou masquer ce composant** en fonction de la valeur d'un autre composant. Dans cet exemple, la propriété *"show"* est définie sur "true", ce qui signifie que ce composant sera visible si l'adresse est remplie.
values |  Définit les **différentes options du champ de type choix-unique ou choix-multiple**. Chaque option est un objet avec deux propriétés : *"label"* et *"value"*.
css | ....
action | ....

### Type

Type | Slug
-- | --
Address| address
Textfield | textfield
OnlyChoice | only-choice
MultipleChoice | multiple-choice
Date | date
Hour | hour
Counter | counter
Upload | upload
Button | button
Checkbox | checkbox
Screen | screen
Subscreen | subscreen
Error | error
Warning | warning
Info | info
Link | link
DisorderList | disorder-list

### Requête avec la valeur `tous` à profil

*Requête*
```
GET /api/questions?profil="tous"
````
*Réponse*
```json
[
  {
    "type": "screen",
    "label": "Introduction",
    "slug": "introduction",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eu erat vel urna viverra pellentesque. Sed ac odio libero. Aliquam tristique neque vestibulum, ultrices sapien id, bibendum nisl.",
    "components": [
      {
        "type": "button",
        "label": "Suivant",
        "slug": "suivant_introduction",
        "action": "next"
      },
      {
        "type": "button",
        "label": "Annuler",
        "slug": "annuler_introduction",
        "action": "cancel",
        "css": "link"
      }
    ]
  },
  {
    "type": "screen",
    "label": "Adresse du logement",
    "slug": "adresse_logement",
    "components": [
      {
        "type": "autocomplete",
        "label": "Commençons par l'adresse du logement",
        "slug": "adresse_logement",
        "description": "Tapez puis sélectionnez l'adresse dans la liste",
        "css": "text-xl"
      },
      {
        "type": "button",
        "label": "Afficher tous les champs",
        "slug": "afficher_champs",
        "action": "link"
      },
      {
          "type": "subscreen",
          "label": "Complément d'adresse",
          "slug": "complement_adresse",
          "conditionnal": "....."
          "components": [
            {
              "type": "textfield",
              "label": "Etage",
              "slug": "etage"
            },
            {
              "type": "textfield",
              "label": "Escalier",
              "slug": "escalier"
            },
            {
              "type": "textfield",
              "label": "Numéro d'appartement",
              "slug": "num_appartement"
            },
            {
              "type": "textfield",
              "label": "Autre",
              "placeholder": "résidence, lieu-dit...",
              "slug": "autre"
            }
          ]
      {
        "type": "button",
        "label": "Suivant",
        "slug": "suivant_introduction",
        "action": "next"
      }
    ]
  },
  {
    "type": "screen",
    "label": "Signalement concerné",
    "slug": "signalement_concerne",
    "components": [
      {
        "type": "only-choice",
        "css": "text-xl",
        "label": "Votre signalement concerne...",
        "slug": "signalement_concerne",
        "values": [
          {
            "value": "Le logement que vous occupez",
            "slug": "logement_occupez"
          },
          {
            "value": "Un autre logement",
            "slug": "autre_logement"
          }
        ]
      },
      {
        "type": "only-choice",
        "label": "Vous êtes...",
        "css": "text-xl",
        "slug": "vous_etes_logement_occupez",
        "values": [
          {
            "label": "Locataire du logement",
            "value": "locataire"
          },
          {
            "label": "Propriétaire du logement",
            "value": "proprietaire"
          }
        ],
        "conditional": {
          "show": "data.signalement_concerne === 'logement_occupez'"
        }
      },
      {
        "type": "only-choice",
        "label": "Vous êtes...",
        "css": "text-xl",
        "slug": "vous_etes_autre_logement",
        "values": [
          {
            "label": "Un particulier",
            "value": "particulier"
          },
          {
            "label": "Un ou une professionnelle",
            "value": "professionnelle"
          },
          {
            "label": "Le bailleur du logement",
            "value": "bailleur"
          },
          {
            "label": "Un service de secours",
            "value": "service_secours"
          }
        ],
        "conditional": {
          "show": "data.signalement_concerne === 'autre_logement'"
        }
      },
      {
        "type": "only-choice",
        "label": "Plus précisément...",
        "slug": "plus_precisement_proprietaire",
        "values": [
          {
            "label": "Un particulier",
            "value": "particulier"
          },
          {
            "label": "Un organisme ou société",
            "value": "organisme_societe"
          }
        ],
        "conditional": {
          "show": "data.vous_etes_logement_occupez === 'proprietaire'"
        }
      },
      {
        "type": "only-choice",
        "label": "Plus précisément...",
        "slug": "plus_precisement_bailleur",
        "values": [
          {
            "label": "Un particulier",
            "value": "particulier"
          },
          {
            "label": "Un organisme ou société",
            "value": "organisme_societe"
          }
        ],
        "conditional": {
          "show": "data.vous_etes_autre_logement === 'bailleur'"
        }
      },
      {
        "type": "only-choice",
        "label": "S'agit-il d'un logement social ?",
        "slug": "logement-social-service-secours",
        "css": "text-xl",
        "values": [
          {
            "label": "Oui",
            "value": "oui"
          },
          {
            "label": "Non",
            "value": "non"
          },
          {
            "label": "Je ne sais pas",
            "value": "ne-sais-pas"
          }
        ],
        "conditional": {
          "show": "data.vous_etes_autre_logement === 'service-secours'"
        }
      },
      {
        "type": "only-choice",
        "label": "S'agit-il d'un logement social ?",
        "slug": "logement-social-pas-service-secours",
        "css": "text-xl",
        "values": [
          {
            "label": "Oui",
            "value": "oui"
          },
          {
            "label": "Non",
            "value": "non"
          }
        ],
        "conditional": {
          "show": "data.vous_etes_autre_logement !== 'service-secours'"
        }
      },
      {
        "type": "button",
        "label": "Suivant",
        "slug": "suivant_introduction",
        "action": "next"
      }
    ]
  }
]
```
## Ressources
https://help.form.io/userguide/form-building
https://formio.github.io/formio.js/app/examples/

**Comment by hmeneuvrier** [comment]
@sfinx13 Plutôt que d'utiliser les slugs des types de composant que tu as listé, est-ce qu'on peut mettre les noms des composants tels qu'ils sont définis en Vue ? ça simplifie le code côté Vue


SignalementFormAddress
SignalementFormButton
SignalementFormCheckbox
SignalementFormCounter
SignalementFormDate
SignalementFormDisorderList
SignalementFormError
SignalementFormHour
SignalementFormInfo
SignalementFormLink
SignalementFormMultipleChoice
SignalementFormOnlyChoice
SignalementFormScreen
SignalementFormSubscreen
SignalementFormTextfield
SignalementFormUpload
SignalementFormWarning

**Comment by sfinx13** [comment]
> @sfinx13 Plutôt que d'utiliser les slugs des types de composant que tu as listé, est-ce qu'on peut mettre les noms des composants tels qu'ils sont définis en Vue ? ça simplifie le code côté Vue
> 
> SignalementFormAddress SignalementFormButton SignalementFormCheckbox SignalementFormCounter SignalementFormDate SignalementFormDisorderList SignalementFormError SignalementFormHour SignalementFormInfo SignalementFormLink SignalementFormMultipleChoice SignalementFormOnlyChoice SignalementFormScreen SignalementFormSubscreen SignalementFormTextfield SignalementFormUpload SignalementFormWarning

@hmeneuvrier ça me va par contre on laisse l'excel comme il est pour la lisibilité, le mapping sera fait en fichier de config coté back, pas nécessaire de le stocker en base pour éviter des migrations qui n'ont très peu de valeur
