### ISSUE TITLE
[Front] Socle technique avec un composant

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1424]
## Description
Le formulaire sera une app VueJS pour faciliter la réactivité.
Elle communiquera avec le back via une API (via un mock pour le moment, cf #1423 )
L'ensemble est inspiré de form.io, mais nous n'utilisons pas strictement form.io ni les librairies js ou vuejs existantes liées 

Le formulaire se construira dynamiquement en fonction des composants reçus de l'API. cf article https://javascript.plainenglish.io/generate-api-driven-forms-in-vue-a2a9cb263bd2

### Arborescence des composants
request.ts : contient tous les appels à l'API
store.ts : initialise les différentes données nécessaires
TheSignalementAppForm.vue : le composant principal qui contient tout le formulaire
les autres sont les différents composants utilisés dans le formulaire (manquent peut-être les composants liés aux désordres)
```
.
└── assets
    ├── vue
    │   ├── components
    │   |   ├── common
    │   |   ├── formulaire
    │   |   |   ├── request.ts
    │   |   |   ├── store.ts
    │   |   |   ├── TheSignalementAppForm.vue
    │   |   |   ├── SignalementFormAddress.vue
    │   |   |   ├── SignalementFormAutocomplete.vue (?)
    │   |   |   ├── SignalementFormButton.vue
    │   |   |   ├── SignalementFormCheckbox.vue
    │   |   |   ├── SignalementFormCounter.vue
    │   |   |   ├── SignalementFormDate.vue
    │   |   |   ├── SignalementFormDisorderList.vue
    │   |   |   ├── SignalementFormError.vue
    │   |   |   ├── SignalementFormHour.vue
    │   |   |   ├── SignalementFormInfo.vue
    │   |   |   ├── SignalementFormLink.vue
    │   |   |   ├── SignalementFormMultipleChoice.vue
    │   |   |   ├── SignalementFormOnlyChoice.vue
    │   |   |   ├── SignalementFormScreen.vue
    │   |   |   ├── SignalementFormSubscreen.vue
    │   |   |   ├── SignalementFormTextfield.vue
    │   |   |   ├── SignalementFormUpload.vue
    │   |   |   ├── SignalementFormWarning.vue
```

## Livrables

S'arrêter à 3 composants pour envoyer la PR (avec un json "en dur", un screen, 2 texfield, un bouton, un deuxième screen)
Composant Screen
Composant Textfield (avec des conditions d'affichage)
Composant Bouton (passage à un deuxième screen)

La route à utiliser : https://histologe.beta.gouv.fr/nouveau-formulaire/signalement

Il faudra un ComponentResolver pour réussir à afficher les écrans avec les bons composants à partir du type reçu de l'API

- [x] Créer le json en dur de validation du socle technique
- [x] Créer le composant TheSignalementAppForm
- [x] Créer le composant SignalementFormScreen
- [x] Créer le composant SignalementFormTextfield
- [x] Créer le composant SignalementFormButton

## Ressources
https://form.io/
https://formio.github.io/formio.js/
https://github.com/formio/vue 
https://javascript.plainenglish.io/generate-api-driven-forms-in-vue-a2a9cb263bd2
https://blog.logrocket.com/making-components-dynamic-vue-3/
https://vuejs.org/api/built-in-special-elements.html

**Comment by sfinx13** [comment]
https://blog.logrocket.com/making-components-dynamic-vue-3/

**Comment by hmeneuvrier** [comment]
S'arrêter à 3 composants pour envoyer la PR (avec un json "en dur", un screen, 2 texfield, un bouton, un deuxième screen)
Composant Screen
Composant Textfield (avec des conditions d'affichage)
Composant Bouton (passage à un deuxième screen)

**Comment by hmeneuvrier** [comment]
https://histologe.beta.gouv.fr/nouveau-formulaire/signalement
https://histologe.beta.gouv.fr/nouveau-formulaire/envoi
