### ISSUE TITLE
[BO - signalement] - Tracer la suppression d'un signalement

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#143]
Ajouter la saisie obligatoire d'un motif de suppression du signalement (et vérifier le traçage qui/quand dans la base) et Ajouter une alerte vers usager pour suppression.
liste de motifs  : doublon, faux signalement, autre territoire, autre

**Comment by mathildepoulpux** [comment]
Vérifier si on peut supprimer avant avoir accepté ou refusé le signalement.
Idéalement, il faudrait : 
1. Refuser avec motif
2. Supprimer le signalement
