### ISSUE TITLE
[FO - Signalement] La Réunion

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1488]
Ne plus relancer les signalements sur ce territoire fermé
Décider si les signalements sont archivés, fermés ou non modifiés

**Comment by sfinx13** [comment]
Vu en point dev/ux fermer les signalements

**Comment by sfinx13** [comment]
Les utilisateurs de la réunion ont aussi été archivés (37) ne peuvent plus se connecter
