### ISSUE TITLE
[BO - Signalements] Investiguer relances auto

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1499]
* signalements sans suivis a partir du dashboard
* je filtre en ne prenant que ceux ouverts apres debut janvier 2022 pour eviter les importés
* je tombe sur des signalements dont les dernieres actions remontent à ...2022 et ne sont pas relancés automatiquement...
ex
2022-316 Marseille
2022-193 Contes
2022-265 Marseille...

**Comment by hmeneuvrier** [comment]
Les signalements indiqués par Arnaud n'ont jamais eu de relance auto (logique puisque dernier suivi en 2022) :
https://histologe.beta.gouv.fr/bo/signalements/620d25126df25
https://histologe.beta.gouv.fr/bo/signalements/620d2538d9f8e
https://histologe.beta.gouv.fr/bo/signalements/621dec1ab4e80

C'est donc la troisième requête de relance auto qui est en cause (je viens de créer des questions pour les 3 pour analyser sur Metabase) : 
https://histologe-metabase.osc-fr1.scalingo.io/question/307-troisieme-requete-demande-de-feedback-signalement-s-without-suivi-public-from-more-than-45-days

A première vue, on a encore un trou dans cette troisième requête car les signalements n'ayant JAMAIS eu de suivi public n'y apparaissent pas.

**Comment by hmeneuvrier** [comment]
J'ai une requête alternative : 

SELECT s.id AS signalement_id, s.created_at, MAX(su.created_at) AS last_posted_at, CONCAT('https://histologe.beta.gouv.fr/bo/signalements', '/', s.uuid) as lien
FROM signalement s
LEFT JOIN (
    SELECT signalement_id, MAX(created_at) AS created_at
    FROM suivi
    WHERE (type = 4 OR is_public = 1)
    GROUP BY signalement_id
) su ON s.id = su.signalement_id
WHERE s.statut NOT IN (1, 6, 7, 8)
AND s.is_imported != 1
AND s.is_usager_abandon_procedure != 1
[[AND s.territory_id = {{idTerritory}}]]
GROUP BY s.id
HAVING DATEDIFF(NOW(), IFNULL(last_posted_at, s.created_at)) > 45
ORDER BY last_posted_at;

**Comment by hmeneuvrier** [comment]
@arnaudchouk j'ai corrigé la requête, elle est en relecture.
Je l'ai transposée dans Metabase : https://histologe-metabase.osc-fr1.scalingo.io/question/307-troisieme-requete-demande-de-feedback-signalement-s-without-suivi-public-from-more-than-45-days
Il y a 291 signalements qui sont passés entre les mailles du filet, si tu veux vérifier d'ici la relecture et la mise en ligne

**Comment by hmeneuvrier** [comment]
J'ai aussi créé des questions avec les deux premières requêtes si ça peut t'intéresser : 
https://histologe-metabase.osc-fr1.scalingo.io/question/305-premiere-requete-demande-de-feedback-signalement-s-for-which-the-two-last-suivis-are-technicals-and-the-last-one-is-older-than-30-days
https://histologe-metabase.osc-fr1.scalingo.io/question/306-deuxieme-requete-demande-de-feedback-signalement-s-for-which-the-last-suivi-is-technical-and-is-older-than-30-days
