### ISSUE TITLE
[Metabase] Upgrade metabase

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1507]
Voir thread https://mattermost.incubateur.net/betagouv/pl/x6cwhfp54bgo3puhxbzccfrzur

**Comment by emilschn** [comment]
Metabase est mis à jour.
La documentation aussi : https://github.com/MTES-MCT/histologe/wiki/D%C3%A9ploiement-de-Metabase
J'ai pas la même URL de buildpacks que le reste de beta, mais bon :) On devrait s'en sortir !
