### ISSUE TITLE
[Back] Gérer les différentes règles de validation pour les endpoints drafts POST et PUT

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1519]
- Gérer les doublons de signalements (même adresse/même nom)
- ...

**Comment by hmeneuvrier** [comment]
@mathildepoulpux il faudra avant de partir nous dire comment définir un doublon (même adresse, même nom, quels statuts de signalement etc.) et ce qui passe en cas de doublon (envoi de mail, lien vers le signalement ?)

**Comment by mathildepoulpux** [comment]
C'est Arnaud qui s'en occupe cf. #87

**Comment by emilschn** [comment]
La gestion des doublons est spécifiée dans le ticket lié par Mathilde.
Pour ce ticket, je regarde quelles règles de validation on peut ajouter (donc la partie spécifiée par `...` dans la description :sweat_smile: )
