### ISSUE TITLE
[BO - Signalement] Absence de suivi pour clôture de signalement

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1530]
Absence de notification de cloture sur signalement cloturé en janvier 2023
2023-32 sur le 06

**Comment by sfinx13** [comment]
Pour info les notifications de plus de 30 jours sont supprimées. @arnaudchouk

**Comment by arnaudchouk** [comment]
ok
c est dans le fil de suivi qu il n y avait pas d info egalement
![image](https://github.com/MTES-MCT/histologe/assets/93710194/d168896b-1e7d-4388-8a6f-3e98f30bfb49)
il devrait y avaoir l info de cloture

**Comment by emilschn** [comment]
[Infos tech]
A priori clôturé le 12/01/2023 pour tous les partenaires (9h53 en BDD)
La donnée `closed_by_id` n'a pas été remplie.
BREVO : Les mails de clôture ont été envoyés à l'usager et aux partenaires d'après les logs (10h53 Brevo)
SENTRY : On n'a pas d'historique d'erreur à cette époque-là.

On est pourtant bien passé dans le `SignalementClosedSubscriber`, car les mails ont été envoyés.

GITHUB 
Le code actuel était déjà en place à cette date-là :
- un suivi aurait dû être créé
- la donnée closedBy aurait du être remplie

**Comment by hmeneuvrier** [comment]
@arnaudchouk 
Le sujet est trop vieux pour qu'on ait suffisamment d'élément pour savoir d'où ça vient.
On propose de fermer ce ticket, et de le rouvrir si jamais le souci se reproduit.
OK pour toi ?

**Comment by arnaudchouk** [comment]
ok
