### ISSUE TITLE
[Back] Revoir l'algo de calcul de criticité

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1546]
Coefficients calculés par catégorie BO et zone dans le fichier excel

Questions à trancher : 
- 1 seul score calculé comme précédemment ? 
C'est-à-dire
```

1. on additionne les coef de toutes les précisions "zone logement", et de toutes les précisions "zone batiment".
2. On ramène à 100 chacun de ces scores par rapport au max possible
3. On fait une moyenne de ces 2 scores
4. on majore de 10% si enfants

```
- 1 score logement et 1 score batiment ? (et quid d'une majoration enfant?)
- 1 score par catégorie ?
- 1 score calculé par catégorie mais ensuite une moyenne de tous ces scores
- Est-ce que le score est toujours un score sur 100 ?

**Comment by hmeneuvrier** [comment]
On calcule le score comme avant
On enregistre les scores batiment et logement (rajouter 2 colonnes dans le signalement)

**Comment by mathildepoulpux** [comment]
Sur la fiche signalement BO
- Sous le titre Déclaration usager, ajouter un lien simple "En savoir plus" qui renvoie vers cette page de la doc : https://documentation.histologe.beta.gouv.fr/partenaires/premiers-pas-sur-histologe/presentation-de-linterface#score-de-criticite-et-prequalification-comment-ca-marche 
- Sous le Score de criticité, ajouter, entre parenthèses `(Score bâtiment : XX% - Score logement : XX%)`

Sur la liste des signalement 
- Afficher uniquement le score global

**Comment by hmeneuvrier** [comment]
Mathilde
[3:35 PM](https://mattermost.incubateur.net/betagouv/pl/ycbccyrgyibh7rxyxoetm35tja)

Ah bah en fait le "En savoir plus" on peut le mettre en dessous

**Comment by hmeneuvrier** [comment]
TODO : 
- renommer certaines catégories BO (fixtures, et fichier à revérifier et pusher sur le bucket
- Changer le front pour que certains critères ne soient plus cumulables
- Revoir les max scores
