### ISSUE TITLE
[Front] Mettre à jour les filtres

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1549]

**Comment by mathildepoulpux** [comment]
Pour moi, si y a rien de bloquant, plutôt à faire avec la story de refonte de la liste des signalements + système de filtre

**Comment by hmeneuvrier** [comment]
cf https://github.com/MTES-MCT/histologe/issues/950

**Comment by emilschn** [comment]
Doublon avec #950 . On ferme ici.
