### ISSUE TITLE
[Back] Mettre à jour l'export csv liste de signalements

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1555]

**Comment by arnaudchouk** [comment]
idealement reprendre toutes les infos de la fiche - et permettre à  utilisateur de selectionner les données qu il veut exporter

**Comment by emilschn** [comment]
Vu ensemble :
- on reprend les désordres
- on corrige les infos des visites si il y a des choses à corriger

J'ouvre un autre ticket (à spécifier) sur l'export avec TOUT + une modale de sélection des données
