### ISSUE TITLE
[Back] Suppression tables inutiles, code mort

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1562]

**Comment by hmeneuvrier** [comment]
https://github.com/MTES-MCT/histologe/security/code-scanning

**Comment by sfinx13** [comment]
https://github.com/MTES-MCT/histologe/pull/2086#discussion_r1452116209

**Comment by hmeneuvrier** [comment]
cf https://github.com/MTES-MCT/histologe/issues/1131

**Comment by emilschn** [comment]
Code mort :heavy_check_mark: 
Pas de tables inutiles.
