### ISSUE TITLE
[BO- Signalement] Déclarant Tiers

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1568]
Un occupant saisi un suivi suite à la redirection intégrée dans le mail de validation du signalement
Le suivi est créé mais par le compte du tiers déclarant avec le nom , prénom et partenaire du tiers déclarant
Les logs sur brevo montrent bien que l occupant a cliqué sur le lien du mail mais pas le partenaire
signalement:
https://histologe.beta.gouv.fr/bo/signalements/a2b55c2d-b936-4a2d-9245-71cf5726b6ab

Peut etre en lien avec les tickets
https://github.com/MTES-MCT/histologe/projects/4#card-90019470
https://github.com/MTES-MCT/histologe/projects/4#card-90009559

**Comment by sfinx13** [comment]
@arnaudchouk j'arrive pas à le reproduire

**Comment by arnaudchouk** [comment]
j avoue c etait bizarre
peut etre specifique au territoire ?

**Comment by sfinx13** [comment]
> j avoue c etait bizarre peut etre spécifique au territoire ?
Faut voir avec la dernière livraison si le cas se reproduit car le comportement doit rester identique peu importe le territoire

**Comment by hmeneuvrier** [comment]
@arnaudchouk On ferme, ça a du être corrigé par les dernières livraisons. Si ça se reproduit on rouvrira
