### ISSUE TITLE
[FO - Formulaire] Souci de validation quand un champ n'est pas visible

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#1592]
Message d'Hélène :
```
J'ai aussi remarqué qu'il restait un souci sur la validation, car on a parfois des soucis pour passer à l'écran suivant quand un champ non-visible volontairement est caché. 
J'avais pourtant fait une correction pour ça (SignalementFormScreen.vue, fonction isRequired() subscreen?.classList.contains('fr-hidden') === false ) 

Mais je crois que la css fr-hidden n'est pas toujours appliquée au bon niveau, ça fait partie des choses que je sais avoir un peu baclées
```

Exemple : sur la page `Avez-vous fait une demande de logement social ou de relogement ?`
Si on répond "Non" et "Non", on ne peut pas passer à la suite car la date de naissance est obligatoire

**Comment by sfinx13** [comment]
Autre exemple (adresse du proprietaire non obligatoire pour le service de secours) 
![image](https://github.com/MTES-MCT/histologe/assets/5757116/96b186ad-4706-4c0a-97cd-c8bd98b12573)
