### ISSUE TITLE
[BO - Comptes archivés] Valeur vide dans la liste des partenaires

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1638]
Je suis SA
Je vais sur la liste des comptes archivés
Je veux filtrer par partenaire
Il y a une valeur vide sélectionnable
![image](https://github.com/MTES-MCT/histologe/assets/97226289/5a8abdce-e40b-4ec6-a3bb-b83988cd7e67)

Quand je la sélectionne : aucun utilisateur n'est trouvé
Idem sur staging (où y a même 2 fois une valeur vide)

**Comment by sfinx13** [comment]
j'ai archivé ces partenaires @mathildepoulpux
