### ISSUE TITLE
[Front] Compléter SignalementFormDisorderOverview avec le contenu des désordres

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#1657]

**Comment by hmeneuvrier** [comment]
@emilschn je suis en train de revoir les règles de validation sur les checkbox des désordres. Maintenant aucune checkbox n'est requise, ce qui veut dire qu'on peut être dans une catégorie de désordres, ne sélectionner aucun désordres et passer à la suite. Ce qui me parait ok côté utilisateur (car il a pu prendre une catégorie et se rendre compte qu'aucun désordre ne lui correspond)
@mathildepoulpux tu es ok avec ça ?

Mais je pense du coup que la catégorie ne doit plus apparaitre dans le résumé si aucun désordre n'est sélectionné.  Donc peut-être à prendre en compte dans cette tâche.

Qu'en penses-tu @mathildepoulpux

**Comment by mathildepoulpux** [comment]
Oui et oui :D
