### ISSUE TITLE
[Front][Mock] Ne pas proposer l'écran les pièces à vivre lorsque l'usager saisit 1 pièce 

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1662]
NI le champs de saisie du nombre de pièce

## Type et composition
![image](https://github.com/MTES-MCT/histologe/assets/5757116/d3db5741-d04d-4d0c-8ede-73c6cbe76075)

Les pièces à vivre
![image](https://github.com/MTES-MCT/histologe/assets/5757116/4af58ce3-d0f5-4b43-b434-3cfa957ed35b)

**Comment by sfinx13** [comment]
@hmeneuvrier  il est plus d'actualité voir le thread https://docs.google.com/spreadsheets/d/12uJcJAWNm9W5R_A6Eh5vwhtLy2ThBNz3CCdkws-ZeIs/edit?disco=AAAA4vOPMAY

**Comment by hmeneuvrier** [comment]
Cela a été corrigé pour l'apparition du champ "Quel est le nombre de pièces à vivre ?" (dans une PR précédente je pense)

Et j'ai revu avec @mathildepoulpux , le deuxième écran "Les pièces à vivre" doit être affiché dans tous les cas, même si on choisit "pièce unique"

Donc rien à faire, je cloture le ticket
