### ISSUE TITLE
[Back] Remplir les 3 tables de désordres à partir du fichier xls

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1665]

**Comment by hmeneuvrier** [comment]
Je viens de voir ton commentaire sur le risque de suroccupation dans la PR #1716
Dans le fichier des question l'onglet "nouvel algo" https://docs.google.com/spreadsheets/d/12uJcJAWNm9W5R_A6Eh5vwhtLy2ThBNz3CCdkws-ZeIs/edit#gid=1647854560 
Sur les lignes 52 / 53 on en parle, les règles de décence c'est : 

    Allocataire :
        nb d'occupants / pièces à vivre <= 2
        :arrow_right: au dessus de 2 occupants / pce à vivre c'est suroccupation
    Non allocataire :
        Si 1 occupant, taille logement > = 9m²
        Si 2 occupants, taille logement > = 16m2
        Chaque occupant supplémentaire : + 9m²

Pour les logements qui ne répondent pas aux critères, on ajoute un tag "Risque de suroccupation"

**Comment by hmeneuvrier** [comment]
Todo : 

- [ ] Faire la liaison entre les tables créées là #1427 et la table Signalement
- [ ] Faire une commande pour remplir les 3 tables avec ce quu'il y a ici https://docs.google.com/spreadsheets/d/12uJcJAWNm9W5R_A6Eh5vwhtLy2ThBNz3CCdkws-ZeIs/edit#gid=1647854560
- [ ] Dans SignalementBuilder() faire la fonction withDesordres() (à détailler)

**Comment by hmeneuvrier** [comment]
Slugs définis sauf pour la partie "Type et composition" qui ne sont pas du tout des désordres.
Je reviendrai dessus après avoir avancé sur le SignalementBuilder. (car ça ne changera pas le fonctionnement de la commande)
Donc demain, commande

**Comment by hmeneuvrier** [comment]
Création d'un ticket à part pour l'enregistrement des déordres lors de la conversion d'un draft en signalement #1954

**Comment by hmeneuvrier** [comment]
restent à faire les tests
