### ISSUE TITLE
[BO - Signalement] Notifications multiples pour des communes de l'Oise

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1666]
Dpt 60 - Ville de Méru recoit mails de notifications (nouveau signalement, nouveau suivi...) plusieurs fois d'affilé

---

Autre alerte identique :

`Nous recevons sur la boite histologe la reponse automatique de la commune de senlis (oise) au mail de notification - et on constate une dizaine d envois identiques`

**Comment by sfinx13** [comment]
https://mattermost.incubateur.net/betagouv/pl/t3p6q36qobgq8bi4hasap936oo
