### ISSUE TITLE
[QA] Timeout sur génération d' un signalement en PDF avec 76 photos 

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1677]
## Description

Sur ce signalement il y a 76 photos https://histologe.beta.gouv.fr/bo/signalements/965b7c3d-eaca-417c-9683-8a46184edfa3  qui génére des timeout lors de la génération de PDF

**Comment by sfinx13** [comment]
@mathildepoulpux @arnaudchouk 
Si le PDF n'est pas généré avant 2 minutes, le service plante.

Est ce qu'on pourrait désactiver la génération PDF ou la non prise en charge des photos sur un nombre de photo trop important ?

Le nombre de photo reste à définir en fonction des investigations à faire.

Pour info on a 121 signalements qui ont plus de 20 photos

**Comment by sfinx13** [comment]
Autre effet de bord c'est l’interconnexion et l'envoi de ces photos

**Comment by sfinx13** [comment]
Lien sentry
https://sentry.incubateur.net/organizations/betagouv/issues/64372/?query=is%3Aunresolved&referrer=issue-stream

https://sentry.incubateur.net/organizations/betagouv/issues/57495/?project=61&query=is%3Aunresolved&referrer=issue-stream

https://sentry.incubateur.net/organizations/betagouv/issues/64371/?project=61&query=is%3Aunresolved&referrer=issue-stream

**Comment by arnaudchouk** [comment]
je pense qu on pourrait limiter le nombre de photos telechargeables oui
mais idealement ce serait associe avec un choix de photo à telecharger

**Comment by hmeneuvrier** [comment]
Saidi AHAMADA
> Je voudrais revenir sur ce ticket! Pour moi faudra revoir la feature. 
> 
> il ne faudrait pas générer le PDF à la volée au delà d'un certain nombre de photos mais envoyer le pdf par mail 
> 
> Tu me diras ce que tu en pense dans ce cas la ça serait une évolution.

**Comment by hmeneuvrier** [comment]
Etude des dernières erreurs : 
http://histologe.beta.gouv.fr/bo/signalements/08c7d0e2-ed95-40eb-a123-0723ea94c21c : 24 photos
http://histologe.beta.gouv.fr/bo/signalements/6cf0facb-ea12-4203-8187-504ffcf71d9f : 38 photos

**Comment by sfinx13** [comment]
Décision prise en point dev/ux généraliser l'envoi par mail de l'export pdf
