### ISSUE TITLE
[QA] Problème de doublon

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1679]
Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '457-32965' for key 'PRIMARY'" at /app/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php line 62

https://sentry.incubateur.net/organizations/betagouv/issues/25276/?project=61&query=is%3Aunresolved&referrer=issue-stream

**Comment by numew** [comment]
Impossible à reproduire
