### ISSUE TITLE
[QA] Historique - remplacer les mails qui ne respectent pas le standard RFC par inconnu@histologe.fr

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1681]
## Pré-requis
Créer la boite mail inconnu@histologe.fr  (alwaysdata)

A généraliser pour les imports de signalement 
## Thread
https://mattermost.incubateur.net/betagouv/pl/he6jrcppypn1upiuqsoajs4m1y

**Comment by hmeneuvrier** [comment]
TODO : 
- créer la boite mail
- faire une migration pour changer dans la table Signalement les mails non conformes par inconnu@histologe.fr, ou les changer à la main pour éviter une migration trop longue (email déclarant, email occupant et email propriétaire)

**Comment by sfinx13** [comment]
https://sentry.incubateur.net/organizations/betagouv/issues/66868/?project=61&query=is%3Aunresolved&referrer=issue-stream

**Comment by hmeneuvrier** [comment]
Géré dans https://github.com/MTES-MCT/histologe/issues/1893
