### ISSUE TITLE
[BO - Signalement] Signalement refusé par RT

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1684]
Un signalement est déposé par un usager
Un RT prend connaissance du signalement sans le valider
Il clique sur le bouton Refuser le signalement, car non valable

* le signalement est officiellement refusé
* il apparait dans le listing tous les signalements mais sans statut
![image](https://github.com/MTES-MCT/histologe/assets/93710194/21d1cc5e-c543-4b3b-af8d-4843bdc3a90e)
* il est pourtant bien clos (grisé)
![image](https://github.com/MTES-MCT/histologe/assets/93710194/9b6eede9-3991-48c7-8456-79cb88a13a97)
* mais il est toujours comptabilisé hors des signalements clôturés - 
vérifiable sur la plateforme staging en cliquant sur signalement sans suivi, puis en sélectionnant le filtre aucun partenaire
![image](https://github.com/MTES-MCT/histologe/assets/93710194/eeaeb454-b2d4-44d2-a75f-093342e312ae)
* les signalements qui apparaissent sans statut sont refusés
![image](https://github.com/MTES-MCT/histologe/assets/93710194/77c1c911-d017-4121-b345-ba3996d2cd80)

* ces signalements sont dans les faits clos, il faudrait donc les considérés comme tels dans les statistiques et les filtres - tout en écrivant le statut Refusé dans la colonne statut

**Comment by hmeneuvrier** [comment]
@arnaudchouk Pour les filtres, j'ai ajouté le statu "Refusés", est-ce que ça te va ?

![image](https://github.com/MTES-MCT/histologe/assets/33071753/5ae4fe6c-3e1a-4153-8aad-4b7e3221b34c)

**Comment by hmeneuvrier** [comment]
Pour les statistiques, c'est déjà hors comptabilité puisqu'il y a une case à cocher pour comptabiliser les signalements refusés, donc je ne sais pas trop ce qu'il faut faire ?

**Comment by arnaudchouk** [comment]
je crois que ce que je dis sur la comptabilisation c est que ca apparait dans les signalements sans suivis sur le dashboard
mais comme il est refusé, il n est pas à afficher dans ce listing car ce listing ne doit prendre en compte que des signalements vivants

**Comment by arnaudchouk** [comment]
sur ton ecran ils apparaissent avec le motif refuse
moi ce n etait pas le cas ca explique peut etre

**Comment by arnaudchouk** [comment]
a priori c est bon
si je selectionne signalement sans suivi + signalement refusé j ai 0
de meme si je selectionne signalement sans suivi + aucun partenaire je n ai plus de signalement en cours dans le listing
