### ISSUE TITLE
[New form - Ecran zone desordre] Bouton précédent ne fonctionne pas

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1688]
Version : Mobile - Android 13
Navigateur : Chrome v. 115 (115.0.5790.166)

Sur l'écran où on choisit la zone de désordre
Je clique sur le bouton précédent
Rien ne se passe

https://github.com/MTES-MCT/histologe/assets/97226289/1bb3ad48-741c-4e62-91f6-cde88d372e67

**Comment by hmeneuvrier** [comment]
En tant que locataire je ne reproduis pas.
Je vais essayer les autres profils

**Comment by hmeneuvrier** [comment]
Je reproduis en bailleur occupant

J'ai aussi le pb en tiers particulier, quand je reviens dans la première partie de questions (donc pas forcément le précédent depuius les zones, mais l'arrivée sur la détermination du profil)
on a des GET en boucle : 
http://localhost:8080/api/questions?profil=tiers_particulier

**Comment by hmeneuvrier** [comment]
Ok, le pb vient d'ici, je pense qu'il faut vérifier si on a les données avant de refaire un initQuestionsProfil

`          } else {
            // on fait un appel API pour charger la suite des questions avant de changer d'écran
            requests.initQuestionsProfil(this.handleInitQuestions)
          }`

**Comment by hmeneuvrier** [comment]
Bon en fait ce sont juste des slugs faux dans certains boutons previous. J'ai corrigé les json
