### ISSUE TITLE
[New form - logement - chauffage] Corriger les appellations type chauffage

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1708]
Quand on indique "Je ne sais pas" pour le type de chauffage
C'est reporté en "nsp", il faudrait écrire `inconnu` à la place
![image](https://github.com/MTES-MCT/histologe/assets/97226289/98354076-4cbf-426c-88db-02f27c7fc295)

De la même manière, quand on sélectionne "Gaz, bois, éthanol ou fioul"
On reporte uniquement "Gaz", il faudrait écrire le label complet `Gaz, bois, éthanol ou fioul`

Aussi, quand on sélectionne "Electrique"
On le reporte sans accent (en minuscule), il faudrait écrire `électrique`

**Comment by sfinx13** [comment]
Va nécessiter de faire appel au dictionnaire

**Comment by hmeneuvrier** [comment]
Corrigé dans la PR en cours d'Emilien : https://github.com/MTES-MCT/histologe/pull/1673/files

![image](https://github.com/MTES-MCT/histologe/assets/33071753/234bfedc-4734-4637-a731-f19a897513e0)

![image](https://github.com/MTES-MCT/histologe/assets/33071753/e00de7b5-6efb-4761-9b50-0a78e85cf5fc)

@mathildepoulpux : est-ce que ça te va si plutôt qu'inconnu c'est "Ne sait pas" (pour être raccord avec les autres endroits ou 'nsp' est utilisé, sinon on change la valeur, on passe de 'nsp' à 'inconnu'
![image](https://github.com/MTES-MCT/histologe/assets/33071753/44ff03fe-3772-4cba-82b2-bf8c788d2f9e)

**Comment by hmeneuvrier** [comment]
@mathildepoulpux a mis un pouce, je ferme
