### ISSUE TITLE
[New form - logement - chauffage] Pb condition affichage question DPE

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1709]
Je suis usager
Propriétaire occupant
J'ai répondu "Je ne sais pas" pour la question du DPE dans la partie Type et compo du logement
Sur mon problème de chauffage, on me pose les questions sur mon DPE
![image](https://github.com/MTES-MCT/histologe/assets/97226289/ba6ccd87-41b2-4c7f-a916-3f3a6e7e7e46)

**-> On devrait les afficher uniquement si j'ai répondu "Oui" à la question DPE**
cf. ligne 51 / onglet désordres logement du [tableau](https://docs.google.com/spreadsheets/d/12uJcJAWNm9W5R_A6Eh5vwhtLy2ThBNz3CCdkws-ZeIs/edit#gid=258317181)

------

Aussi, les questions suivantes sur le DPE dépendent des réponses données
- La question `Quelle est la consommation en énergie finale indiquée sur le DPE ? (kWh/m²/an) ` doit être affichée si on répond "En 2023" à la question `Quand le DPE du logement a-t-il été réalisé ?`
- Les questions `Quelle est la superficie de votre logement ? (m²)` et `Quelle est la consommation en énergie indiquée sur le DPE ? (kWh/an)` doit être affichée si on répond "Avant 2023"

Là, elles sont toutes affichées par défaut

**Comment by mathildepoulpux** [comment]
C'est toujours le cas

**Comment by hmeneuvrier** [comment]
@mathildepoulpux est-ce que le problème que tu as est toujours exactement comme sur le  screenshot mis il y a 2 semaines, où est-ce que maintenant c'est comme ça ?

![image](https://github.com/MTES-MCT/histologe/assets/33071753/a0916fad-97cd-4113-80e7-57cb6a4e27e2)

Car si c'est comme ma screenshot à moi (comportement que je reproduis), alors c'est corrigé dans la PR https://github.com/MTES-MCT/histologe/pull/1771 (j'ai fait le test)

**Comment by hmeneuvrier** [comment]
@mathildepoulpux comme la pR 1771 a été mergée, je te propose de restester le comportement sur la staging :) Merci !
