### ISSUE TITLE
[New form - procédure] Modifier champ texte réponse de l'assurance

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1712]
Il faudrait modifier ce champ text en text area
Ce sera + lisible dans la mesure où on peut copier / coller le contenu d'un email dans ce cas par exemple
![image](https://github.com/MTES-MCT/histologe/assets/97226289/1781d752-f132-424d-ab00-a8b91f87726b)

**Comment by sfinx13** [comment]
ça serait donc un nouveau composant
