### ISSUE TITLE
[New form - info complémentaires] A déplacer après le récap

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1714]
J'accède à la partie info complémentaires après la procédure
Je suis censée accéder au récap
La page "info complémentaires" est accessible depuis le bouton dédié sur le récap
Il faut la déplacer dans le flow
![image](https://github.com/MTES-MCT/histologe/assets/97226289/d6dc1cb8-6945-4338-9520-1baf73d610cc)

**Comment by sfinx13** [comment]
@mathildepoulpux comme tu l'as dit dans la description, ça serait accessible uniquement lorsqu'on clique sur le bouton "Ajouter des information"  ?
Mais pas dans le flow

**Comment by mathildepoulpux** [comment]
Oui !

**Comment by hmeneuvrier** [comment]
Accessoirement je corrige la faute dans le titre :)

**Comment by mathildepoulpux** [comment]
Je laisse celui ci ouvert parce que actuellement, quand je clique sur le bouton "Ajouter des infos complémentaires", je suis renvoyer vers l'écran "mes coordonnées"

**Comment by hmeneuvrier** [comment]
@mathildepoulpux ça sera corrigé quand cette PR sera mergée : https://github.com/MTES-MCT/histologe/pull/1751

**Comment by mathildepoulpux** [comment]
Sur la page récap, la partie "informations complémentaires" n'apparaît pas
Je suis déclarant tiers pro 

![image](https://github.com/MTES-MCT/histologe/assets/97226289/8fbee361-618f-4bda-b893-05fec2082a64)

**Comment by mathildepoulpux** [comment]
Par contre, c'est OK pour le profil locataire occupant

**Comment by hmeneuvrier** [comment]
Ok, je n'avais mis cette partie que pour les occupants, car on ne l'avait que dans les questions des occupants, mais je pense qu'on a juste mal lu le excel (qui est un peu bordélique à cet endroit, il faut le dire...:p )

**Comment by mathildepoulpux** [comment]
Je remets ici ce que je t'ai listé sur Mattermost

**Tiers particulier et pro :**
- La situation du foyer
    - Est-ce que le foyer est bénéficiaire du RSA (revenu de solidarité active) ?
    - Est-ce que le foyer est bénéficiaire FSL (Fonds de solidarité pour le logement) ?
    - Quel est le montant du loyer, sans les charges ?
    - Est-ce que le foyer a fait une demande de relogement ou de logement social ?
    - Quand le foyer a-t-il emménagé dans le logement ?
- Le logement
    - Le logement est sur combien d'étages ?
    - En quelle année le logement a-t-il été construit ?

**Tiers bailleur :** 
- Situation des locataires
    - Quelle est la date d'effet du bail ?
    - Est-ce que le paiement des loyers est à jour ?
    - Quel est le montant du loyer, sans les charges ? 
    - Est-ce qu'un préavis de départ a été déposé pour le logement ? 
- Le logement
    - Le logement est sur combien d'étages ?
    - En quelle année le logement a-t-il été construit ?
- Ma situation personnelle
    - Êtes-vous bénéficiaire du RSA (revenu de solidarité active) ? 
    - Êtes-vous bénéficiaire FSL (Fonds de solidarité pour le logement) ? 
    - Quel est votre revenu fiscal de référence ? 
    - Quelle est votre date de naissance ? 

**Bailleur occupant :** 
- Ma situation personnelle
    -  Êtes-vous bénéficiaire du RSA (revenu de solidarité active) ? 
    -  Êtes-vous bénéficiaire FSL (fonds de solidarité pour le logement) ? 
    -  Quel est votre revenu fiscal de référence ? 
- Le logement
    - Votre logement est sur combien d'étages ?
    - En quelle année votre logement a-t-il été construit ?
