### ISSUE TITLE
[BO - Signalement] Suivi à supprimer

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1721]
Territoire 48
Signalement 2023-17
Supprimer Suivi C Carriere Partenaire CAF du 1309 - Texte de remplacement :" Erreur dossier"

**Comment by hmeneuvrier** [comment]
@arnaudchouk toujours d'actualité ? A mettre en TODO si c'est le cas.

**Comment by hmeneuvrier** [comment]
Faire https://github.com/MTES-MCT/histologe/issues/2326 plutôt et laisser Arnaud supprimer le suivi tout seul

**Comment by arnaudchouk** [comment]
https://histologe.beta.gouv.fr/bo/signalements/a25efd6e-1d72-445d-8a1b-675731b26c38

**Comment by hmeneuvrier** [comment]
Suivi supprimé
