### ISSUE TITLE
[Brevo - Tracking] Email

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1727]
Ajouter les balises aux mails transactionnels (listés ici : https://github.com/MTES-MCT/histologe/wiki/Emails) pour tracker les données dans l'outil stat intégré

Usagers | Tag suivi brevo
-- | --
Email |  
accuse_reception_email | Usager Accusé Reception   Signalement
validation_signalement_email | Usager Validation Signalement
refus_signalement_email | Usager Refus Signalement
nouveau_suivi_signalement_email | Usager Nouveau Suivi Signalement
closed_to_usager_signalement_email | Usager Cloture Signalement
A créer Date de visite | Usager Date Visite Prevue
A créer Rappel date visite | Usager Rappel Visite Prevue
A créer Modification date visite | Usager Modification Date Visite   Prevue
A créer Conclusion visite | Usager Conclusion Visite   Disponible
A créer Conclusion visite non effectuée | Usager Visite Non Effectuee
A créer Annulation visite | Usager Annulation Visite Prevue
  |  
Pro |  
Email |  
new_signalement_email.html.twig | Pro Nouveau Signalement
affectation_email | Pro Nouvelle affectation
nouveau_suivi_signalement_back_email | Pro Nouveau Suivi Signalement
closed_to_partner_signalement_email | Pro Cloture Partenaire
closed_to_partners_signalement_email | Pro Cloture Signalement
Reactivation compte | Pre Reactivation de Compte
A créer   Date de visite | Pro Date Visite Prevue
A créer   Date de visite à renseigner | Pro Date Visite Manquante
A créer   Rappel de visite J-2 | Pro Visite Prevue Rappel
A créer   Conclusion de visite à renseigner J+2 | Pro Conclusion Visite A Remplir
A créer   Conclusion de visite disponible | Pro Conclusion Visite Disponible

**Comment by sfinx13** [comment]
Usagers	| Tag suivi brevo
-- | --
Email |  
accuse_reception_email | Usager Accusé Reception   Signalement
validation_signalement_email | Usager Validation Signalement
refus_signalement_email | Usager Refus Signalement
nouveau_suivi_signalement_email | Usager Nouveau Suivi Signalement
closed_to_usager_signalement_email | Usager Cloture Signalement
nouveau_suivi_visite_created_to_usager_email | Usager Date Visite Prevue
nouveau_suivi_visite_future_reminder_to_usager_email | Usager Rappel Visite Prevue
nouveau_suivi_visite_rescheduled_email | Usager Modification Date Visite   Prevue
nouveau_suivi_visite_edited_email | Usager Conclusion Visite   Disponible
nouveau_suivi_visite_aborted_email| Usager Visite Non Effectuee
nouveau_suivi_visite_canceled_email  | Usager Annulation Visite Prevue
  |  
Pro |  
Email |  
new_signalement_email.html.twig | Pro Nouveau Signalement
affectation_email | Pro Nouvelle affectation
nouveau_suivi_signalement_back_email | Pro Nouveau Suivi Signalement
closed_to_partner_signalement_email | Pro Cloture Partenaire
closed_to_partners_signalement_email | Pro Cloture Signalement
login_link_email | Pre Reactivation de Compte
nouveau_suivi_visite_created_to_partner_email | Pro Date Visite Prevue
nouveau_suivi_visite_needed_email | Pro Date Visite Manquante
nouveau_suivi_visite_future_reminder_to_partner_email | Pro Visite Prevue Rappel
nouveau_suivi_visite_past_reminder_to_partner_email | Pro Conclusion Visite A Remplir
nouveau_suivi_visite_confirmed_to_partner_email | Pro Conclusion Visite Disponible

**Comment by sfinx13** [comment]
Ajout d'un nouveau tag contact
