### ISSUE TITLE
[New form - ecran logement social] Ajouter condition montant allocation

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1752]
Repéré suite au test de Thibault
Sur l'écran logement social, la question `Quel est le montant de votre allocation ?` est affichée par défaut
Or il faudrait qu'elle soit affichée uniquement si on répond `Oui` à la question `Recevez-vous une aide ou allocation logement ?`
![image](https://github.com/MTES-MCT/histologe/assets/97226289/fb870a8c-76a7-4ecf-8604-f4007c20a653)

**Comment by hmeneuvrier** [comment]
C'est pourtant déjà le cas dans le code, c'est chelou

**Comment by hmeneuvrier** [comment]
Je ne reproduis pas, avant de cocher une réponse : 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/e881b18f-aea2-471b-8c34-262eaf9d27b7)

Après avoir coché NON : 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/bd3cb32e-bd1e-45e2-afef-56c05c6eaaa5)

**Comment by hmeneuvrier** [comment]
J'ai fait le test en Locataire, je vais essayer en bailleur occupant (même si le json est identique pour les deux)

**Comment by hmeneuvrier** [comment]
Je fais le test en bailleur-occupant, je ne reproduis pas non plus: 

![image](https://github.com/MTES-MCT/histologe/assets/33071753/c576a442-9964-450e-8218-05f730052ee0)

![image](https://github.com/MTES-MCT/histologe/assets/33071753/1073f6ab-10a2-4500-8840-d4e6b26b88d8)

**Comment by hmeneuvrier** [comment]
@mathildepoulpux je suis désolée, mais il me faudrait un cas de reproduction précis

**Comment by mathildepoulpux** [comment]
- Locataire
- Logement social
- Appartement
- 55m²
- Pièce unique
- Zone de désordre : les 2
- 4 personnes, pas d'enfant - 6 ans

**Comment by hmeneuvrier** [comment]
Draft de reproduction sur la staging {"uuid":"25a729ae-daa4-4943-b2c6-665242423337"}

En mettant exactement les mêmes infos que sur ton draft, je ne reproduis pas...

![image](https://github.com/MTES-MCT/histologe/assets/33071753/533153f6-7b6a-4654-b6fc-975f0c490ab3)
