### ISSUE TITLE
[BO - Utilisateur] Création d'un utilisateur avec un email déjà existant

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1764]
https://mattermost.incubateur.net/betagouv/pl/8y4ramyjjbfrbyk1retbzd97he

![image](https://github.com/MTES-MCT/histologe/assets/5757116/81302c05-3a3f-4a10-ae43-67519a23acae)

**Comment by hmeneuvrier** [comment]
Voir si utilisateur créé via Import ou via IHM

**Comment by hmeneuvrier** [comment]
Super bizarre...
Pour l'utilisateur avec le mail habitat@spl-dreux.fr
Du 22 septembre au 26 septembre, 2 mails par jour, bloqués, pour "Activez le compte" (le compte restant a été créé le 7 septembre) je crois que Saidi en a supprimé 1 le 25 ou 26 septembre.
Puis encore un mail "Activez votre compte" les 2 et 3 octobre (encore bloqués), puis des mails de signalement et de suivis bien délivrés. Et le 9 octobre, à nouveau un mail "Activez votre compte" qui cette fois-ci a été délivré et cliqué...

**Comment by hmeneuvrier** [comment]
bon, j'ai réussi à reproduire, je sais d'où ça vient.
Il suffit quand on créé un utilisateur de terminer par remplir l'adresse mail (déjà existante) puis de cliquer sur le bouton sans cliquer nulle part ailleurs, et la vérification de l'existence de l'adresse mail ne se fait pas, car on n'a pas détecté le changement du champ email avant de valider.
![image](https://github.com/MTES-MCT/histologe/assets/33071753/073f7eb4-6c87-4f6d-a191-87b6d4c0f6e9)

![image](https://github.com/MTES-MCT/histologe/assets/33071753/f46f4146-1ef1-46c4-b90d-13b47ce92106)
