### ISSUE TITLE
[Matomo] Ajouter balises / dimensions personnalisées

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1772]
📝 En tant que chargée d’animation, j’aimerais pouvoir tracker les actions des partenaires sur la plateforme afin de connaître et analyser leurs comportement.
- tracker l'usage de la plateforme de la connexion à la déconnexion
- définir le temps d'affectation d'un signalement pour un RT
- comparer les gros territoires aux plus petits
- différencier RT de partenaire
- tracker chaque type de partenaire
- comparer les territoires récents aux plus anciens
- 6 RT (Bouches du Rhône, Corse du Sud, Alpes de Haute Provence, Pyrénées Atlantiques, Charente Maritime, Pas de Calais)
- 3 caf, 3 ARS, 3 communes, 3 bailleurs, 3 ADIL, 3 SOLIHA

Pour cela : 
- [ ] créer 3 dimensions personnalisées dans Matomo : 
    - rôle
    - territoire
    - partenaire
- [ ] Mettre à jour les CGU
- [ ] Ajouter la bannière cookies (cf. [Gestionnaire de consentement](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/gestionnaire-de-consentement) du DSFR )

**Comment by sfinx13** [comment]
@mathildepoulpux je me pose la question s'il ne faudrait pas activer la bannière de consentement **uniquement dans le BO pour l'instant** pour les territoires concernés ?

**Comment by mathildepoulpux** [comment]
Oui, idéalement !
Après je me demande si ça vaut vraiment le coup de s'arrêter à 6 territoires dans la mesure où les dimensions personnalisées seront en place : on peut tous les tracker non ?

**Comment by sfinx13** [comment]
@mathildepoulpux une fois que c'est en place on peut tout tracker

**Comment by mathildepoulpux** [comment]
Edition des CGU, remplacer la partie 6.10 actuelle par: 

### 6.10 – Cookies
En tant qu’éditeur de la présente Plateforme, le responsable de traitement pourra faire usage de cookies. 
Un cookie est un fichier texte déposé sur votre ordinateur par la Plateforme lorsque vous la consultez. Cela nous permet de mesurer le nombre de visites et de comprendre quelles sont les pages les plus consultées afin d'améliorer la Plateforme.

Nous utilisons [Matomo](https://matomo.org/), un outil [libre](https://matomo.org/free-software/), paramétré pour être en conformité avec la [recommandation « Cookies » ](https://www.cnil.fr/fr/solutions-pour-la-mesure-daudience)de la CNIL. 

#### Site public (usagers)
Matomo nous permet de mesurer l'audience du site public (fréquentation et utilisation) à des fins d'amélioration du service, dans le respect de la recommandation de la CNIL. 
Votre adresse IP est anonymisée. Il est donc impossible d’associer vos visites sur la plateforme à votre personne.

A retenir : 
- Les données collectées ne sont pas recoupées avec d’autres traitements.
- Le cookie déposé sert uniquement à la production de statistiques anonymes.
- Le cookie ne permet pas de suivre la navigation de l’internaute sur d’autres sites.
- Les traceurs ont vocation à être conservés sur le poste informatique de l’Internaute pour une durée allant jusqu’à 13 mois.

#### Site privé (agents)
Le site privé n'est accessible qu'aux agents exerçant une mission de service public, après création et activation d'un compte.

Matomo nous permet de mesurer la fréquentation et les habitudes de navigation des agents. Ces cookies de statistiques nécessitent l'utilisation d'un bandeau cookies.
Le bandeau de cookie est affichée à la connexion au back-office. L'agent peut alors accepter, refuser ou paramétrer ses cookies.  Son choix est enregistré pour une durée de 13 mois ou jusqu'à suppression des cookies du navigateur.

**L’utilisation des cookies est facultative** et peut être à tout moment bloquée par l’utilisateur. Pour cela, l’utilisateur peut configurer son navigateur web. Pour apprendre à paramétrer l’utilisation des cookies en fonction de votre navigateur, rendez-vous sur [le site de la CNIL en cliquant ici](https://www.cnil.fr/fr/cookies-les-outils-pour-les-maitriser).

A retenir : 
- Les données collectées ne sont pas recoupées avec d’autres traitements.
- Le cookie déposé sert uniquement à la production de statistiques anonymes.
- Le cookie ne permet pas de suivre la navigation de l’internaute sur d’autres sites.
- Les traceurs ont vocation à être conservés sur le poste informatique de l'agent pour une durée allant jusqu’à 13 mois.

**Comment by sfinx13** [comment]
https://mattermost.incubateur.net/betagouv/pl/ufhe6nimhbbcpco5u7m9tq9tuh

**Comment by sfinx13** [comment]
Dimensions personnalisés activé pour tous les partenaires
