### ISSUE TITLE
[Esabora] Remplacer Esabora par SI-SH dans les messages de suivi

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1776]
## Description (voir mail Jean Marc DGS)
Remplacer « ESABORA » par « SI-SH » dans les messages liés à l’interconnexion entre « Histologe ß à SI-SH » ?

**Comment by sfinx13** [comment]
@arnaudchouk est ce qu'on devrait faire la même chose pour SCHS ?

**Comment by arnaudchouk** [comment]
on a pas eu de demande en ce sens
leurs si n ont pas de nom simple

**Comment by sfinx13** [comment]
Test staging OK @hmeneuvrier 
Pour le dossier https://histologe-staging.incubateur.net/bo/signalements/c219dbe4-a486-4c64-9175-38130937b4c3
![image](https://github.com/MTES-MCT/histologe/assets/5757116/9d0b5ad1-3913-453d-aa39-7ae81eb54da4)
