### ISSUE TITLE
[Export] ajouter statut visite et coordonnées GPS

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1782]
Dans le fichier d'export, ajouter les colonnes:
- Statut de la visite (à programmer / planifiée / effectuée / annulée / non effectuée)
- Les coordonnées GPS (on l'avait enlevé mais ils faudrait les remettre car c'est utile pour alimenter les SI)

**Comment by sfinx13** [comment]
#1795 remettre les noms de fichiers

**Comment by hmeneuvrier** [comment]
En profiter pour traiter cette erreur : https://sentry.incubateur.net/organizations/betagouv/issues/67882/?project=61&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d

**Comment by hmeneuvrier** [comment]
TODO : 

- [ ] corriger décalage nom de colonnes/contenu #1186 
- [ ] ajouter geolocalisation
- [ ] ajouter Statut de la visite (à programmer / planifiée / effectuée / annulée / non effectuée)
- [ ] ajouter noms de fichiers et de photos
