### ISSUE TITLE
[BO-Signalement]Edition ou Reouverture

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1807]
Des signalements importés ne répondent aux contraintes d'enregistrement : absence de desordre selectionne ou de commentaire
Si on souhaite modifier un de ces signalements, impossible de valider et enregistrer
ex
- Dossier n° 2021-1729 CODE INSEE 24520 Adresse exact SARLAT et pas
BERGERAC ;
- Dossier n° 2019-1349 CODE INSEE 24437 Adresse exact ST LAURENT DES
VIGNES (24100) mais je ne peux rajouter la mairie ;

**Comment by arnaudchouk** [comment]
Cela semble etrepareil pour la reouverture de signalements ayant les memes caracteristiques 
https://histologe.beta.gouv.fr/bo/signalements/2570580b-f3f3-4d9d-9400-4b55d8a1d43e

**Comment by numew** [comment]
Les cas d'édition avaient été traité par la PR #2043 
Le cas ouverture/fermeture est traité par la PR #2129
