### ISSUE TITLE
[Front] Désordres dans la page signalement BO

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#1811]
En attente de #1954 

https://xd.adobe.com/view/3cae505c-cf52-408c-a800-0bdd78e695f2-69fd/

Solutions possibles : 

- un twig par desordre_categorie avec des "if" pour afficher les textes
- Mettre tous les textes dans les labels de desordre_precision
- un mélange des deux ?

- récupérer les fichiers par slug pour mettre le bouton d'affichage de photos

**Comment by hmeneuvrier** [comment]
Penser à récupérer les criticités ou les désordres selon le type de signalement, par exemple dans SignalementController.php
           ` 'signalementQualificationNDECriticite' => $signalementQualificationNDECriticites, `

**Comment by hmeneuvrier** [comment]
TODO : 

- [ ] afficher les désordres dans la page de signalement, classés par zone et par catégorie BO
- [ ] afficher un bouton pour les photos liées
- [ ] mettre à jour les intitulés de précisions dans les fixtures
- [ ] mettre à jour les intitulés de critères dans les fixtures
- [ ] mettre à jour les intitulés précisions et critères dans le fichier
- [ ] Récupérer les criticités liées au NDE pour affichage (voir ci-dessus)

**Comment by hmeneuvrier** [comment]
que faire quand on clique sur ce bouton "Voir les désordres" --> afficher les miniatures ou descendre dans la page

**Comment by hmeneuvrier** [comment]
- [ ] Dédoubler certaines précisions pour restituer les informations dans la fiche signalement

**Comment by hmeneuvrier** [comment]
Vu avec Mathilde, le diagnostique plomb n'a pas à être ajouté dans le bloc des désordres (mais j'ai corrigé son slug pour qu'il soit pris en cmpte dans les fichiers)
