### ISSUE TITLE
[BO - Esabora] Email de reporting - problème de compteur sur les synchronisation visite et arrête

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1824]
## Description
Après l'éxécution de la commande en prod
```php
php bin/console app:sync-esabora-sish-intervention
```` 

Nous recevons dans le mail de confirmation des valeurs qui ne sont pas tout représentatives de la réalité
 
![image](https://github.com/MTES-MCT/histologe/assets/5757116/bb16bb8e-b953-4563-901e-925faab6bb5d)

## Comportement attendu
Voici des chiffres de la sync du 17 octobre

| Succés | Echec |
|-----------|-----------|
| ```select count(*) from job_event where (action like '%sync_dossier_arrete%' or action like '%sync_dossier_visite%') and created_at like '%2023-10-17%' and status like '%success%';```| ```select count(*) from job_event where (action like '%sync_dossier_arrete%' or action like '%sync_dossier_visite%') and created_at like '%2023-10-17%' and status like '%failed%';```|
| Total: 1801   | Total 1  |

**Comment by hmeneuvrier** [comment]
Corriger aussi la deuxième ligne mettre `synchronisations en échec`
