### ISSUE TITLE
[QA] Problème d'enregistrement de signalement

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1829]
https://sentry.incubateur.net/organizations/betagouv/issues/67989/?project=61&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d

**Comment by hmeneuvrier** [comment]
Problème lorsque les gens sont restés trop longtemps sur le dernier onglet (durée de validité du token)
TODO : 
- vérifier si les signalements ont finalement été créés
- voir avec @mathildepoulpux pour changer le message d'erreur de "réessayer dans 1 heure" à "problème de validité du token, retournez sur l'onglet précédent puis revenez sur celui-ci  pour en générer un tout neuf"

**Comment by mathildepoulpux** [comment]
Nouveau message d'erreur : 
`Oups... Il semblerait que vous ayez passé trop de temps sur cette étape ! Retournez à l'étape précédente puis continuez le formulaire pour régler le problème. Si cela ne fonctionne pas, veuillez réessayer plus tard.`

**Comment by hmeneuvrier** [comment]
Magnifique  !

**Comment by hmeneuvrier** [comment]
Le seul évènement encore disponible dans Sentry correspond à un signalement qui a finalement été déposé
