### ISSUE TITLE
[BO - Etude Reprise données] Bas Rhin 67

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1853]
Fichier test avec documents zip
Valider que c est ok pour import
https://drive.google.com/drive/folders/1thPioR5O_Jy2NaLQ-HTpYrT2-vP9JKXR?usp=sharing

**Comment by emilschn** [comment]
**Choses à faire avec ce fichier de test** 

- modification de la commande de slugify pour que ça prenne en compte un fichier csv classique de signalement
- uploader les fichiers sur le bucket
- tester si l'import fonctionne avec les fichiers slugifiés

**Comment by emilschn** [comment]
@arnaudchouk je suis en train de finir mes tests dessus, ça devrait être ok avec l'organisation de fichier transmise.
On a fait un dev qui va être en relecture sous peu.

Par contre, il faudra impérativement qu'ils reprennent les bons noms de colonne du fichier de base (sans ajouter des majuscules ou retirer des accents) pour ne pas nous faire perdre trop de temps :) 
Et aussi : ne pas mettre de sauts de ligne dans les cases, si possible.
je suis obligé de le retraiter à la main. Quand c'est 4 lignes pour tester, ça va, mais si c'est c'est plein de lignes, ce sera plus compliqué.
Merci :)

**Comment by emilschn** [comment]
@arnaudchouk le dev a été validé, il est sur staging, il sera en ligne prochainement
Je ne sais pas si ils ont commencé à bosser dessus, mais ils peuvent, en tout cas.

**Comment by arnaudchouk** [comment]
@emilschn qu entends tu par commencer à bosser dessus?

**Comment by emilschn** [comment]
Faire le tableur avec tous les signalements, et mettre tous les fichiers dans les bonnes colonnes (vu qu'ils nous avaient envoyé un fichier de test)
