### ISSUE TITLE
[BO - Compte Utilisateur] Partenaire SELI - Dpt 87

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1862]
Supprimer Partenaire id 4318
Desarchiver Partenaire id 4388 + supprimer email generique opahrulimoges@se-limousin.fr pour creer user opahrulimoges@se-limousin.fr

**Comment by emilschn** [comment]
@arnaudchouk 
- 4318 : archivé
- 4388 : désarchivé
- 4388 : mail générique opahrulimoges@se-limousin.fr supprimé
Je vous laisse créer l'utilisateur ?
