### ISSUE TITLE
[Formulaire - Intro] Corriger la faute

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1864]
Sur le premier écran modifier nécéssaires en `nécessaires`
![image](https://github.com/MTES-MCT/histologe/assets/97226289/5d1038b8-a01d-4d15-beec-580497714c69)

**Comment by hmeneuvrier** [comment]
Rendu inutile par https://github.com/MTES-MCT/histologe/issues/1868
