### ISSUE TITLE
[Form - Avant de commencer] Ajouter des informations

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1868]
Suite aux tests utilisateurs, on note qu'il manque des informations en début de formulaire pour l'accompagner sur le signalement,
-> Ajouter des infos sur l'écran Avant de démarrer
![image](https://github.com/MTES-MCT/histologe/assets/97226289/3249d749-df2a-4333-b4db-0a2b66d2bcee)

### Avant de démarrer
Vous allez pouvoir signaler votre problème de logement. 
Après cette page, cela vous prendra **environ 25 minutes**. 
Avant de commencer, lisez bien les conseils ci-dessous.

### Comment déposer un signalement ?
Pour déposer votre signalement, il faut remplir toutes les étapes du formulaire et répondre à des questions sur :
- L'état du logement
- L'adresse du logement
- Le logement en général (taille en m², nombre de personnes vivant dans le logement, etc.)

Si possible, préparez les documents suivants : 
- Des photos des dégâts dans le logement
- Les coordonnées du bailleur (propriétaire) 
- Si vous les avez : le bail, l'état des lieux et le DPE du logement
- Si concerné : le numéro d’allocataire

Message d'info: `Un signalement complet permet une meilleure prise en charge du dossier !`

### Qui aura accès à mon signalement ?
Les informations demandées sont nécessaires au bon traitement du signalement. 
Elles seront **uniquement partagées avec les administrations compétentes** pour traiter votre dossier.

### Est-ce que je peux déposer un signalement pour quelqu'un d'autre ?
Oui. Vous pouvez déposer un signalement pour une autre personne. Assurez-vous d'avoir sa permission et préparez les informations sur son logement.
 
----
[La maquette est à jour 🔗](https://xd.adobe.com/view/bc30ff7e-1d5e-4e6d-a90b-b4afb64c3693-e963/screen/90a2e743-3fdd-45cb-8204-5a8886c015bd)
Il faut probablement changer les boutons pour les mettre dans une zone d'action fixe sur mobile

**Comment by hmeneuvrier** [comment]
@mathildepoulpux est-ce qu'on doit garder l'illustration ?
Est-ce que tu es sûre pour mettre les boutons dans le footer plutôt quà la fin ? (sur les captures j'ai mis les boutons en doublons aux deux endroits pour que tu vois ce que ça donne)

![image](https://github.com/MTES-MCT/histologe/assets/33071753/6c9eccb2-f17b-47ea-b99c-516e64fab181)
![image](https://github.com/MTES-MCT/histologe/assets/33071753/2c345e48-a30a-4a43-8b15-ae9e3e1ef40e)
![image](https://github.com/MTES-MCT/histologe/assets/33071753/4ed2880a-11ec-4d4c-bc48-dd859f7fade6)
![image](https://github.com/MTES-MCT/histologe/assets/33071753/cafee7f7-27b0-4074-80dd-d1d371bac16d)
![image](https://github.com/MTES-MCT/histologe/assets/33071753/896b09b3-4122-4b7c-894f-91acd4f53c27)

**Comment by mathildepoulpux** [comment]
On peut enlever l'illustration effectivement
Et on peut garder les boutons à la fin finalement, ça me choque pas
