### ISSUE TITLE
[Form - Ecran votre signalement concerne] Reformuler la question type logement et ajouter "en savoir plus"

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1869]
Sur cet écran
Modifier la question `Votre signalement concerne...` par `Vous déposez un signalement...`
Réponses : 
- `Votre logement` devient `Pour vous-même`
- `Un autre logement` devient `Pour quelqu'un d'autre`

![image](https://github.com/MTES-MCT/histologe/assets/97226289/23dfc055-6f55-4ccb-b0a8-a5ba4b55143b)

Ajouter un label cliquable sous le titre `En savoir plus`
Au clic -> ouverture d'une modale

Titre : En savoir plus
Texte : Vous déposez un signalement pour vous-même lorsque vous avez un problème dans le logement dans lequel vous vivez.
Vous déposez un signalement pour quelqu'un d'autre quand vous déposez un signalement pour une autre personne qui rencontre des problèmes dans son logement et qui ne vit pas avec vous.

https://github.com/MTES-MCT/histologe/assets/97226289/a1d82758-6c19-481b-961a-683014189e74

**Comment by hmeneuvrier** [comment]
A faire avec https://github.com/MTES-MCT/histologe/issues/1871

**Comment by hmeneuvrier** [comment]
Décision : faire un nouveau composant qui comprend le FormInfo et l'ouverture de la modale au clic
