### ISSUE TITLE
[Form - type de problème] Ajouter "en savoir plus" sur plusieurs écran

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1871]
Suite aux tests utilisateurs, on note une confusion entre logement et bâtiment.
Pour éviter la confusion, on ajoute un label cliquable "En savoir plus" sur plusieurs écrans : 
- L'écran zone_concernee
- L'écran ecran_intermediaire_les_desordres

Quand on clique sur le label > ouverture d'une modale avec les infos suivantes : 
Titre : En savoir plus
Texte : 
Les désordres sur le bâtiment concernent :
- La structure du bâtiment (toit, murs porteurs, les façades, sol)
- Les caves et sous-sol
- Autour du bâtiment
- Pour les immeubles : les parties communes

Les désordres sur le logement concernent tous les problèmes à l'intérieur du logement (aération, chauffage, moisissure, équipements, etc.).

https://github.com/MTES-MCT/histologe/assets/97226289/2fe11c13-6031-47eb-9e5f-0a69a153218b

![image](https://github.com/MTES-MCT/histologe/assets/97226289/202a5d89-5c88-4d2d-9b83-eef3628d537f)

**Comment by hmeneuvrier** [comment]
A faire avec https://github.com/MTES-MCT/histologe/issues/1869

**Comment by hmeneuvrier** [comment]
Décision : faire un nouveau composant qui comprend le FormInfo et l'ouverture de la modale au clic
