### ISSUE TITLE
[Form - Récap désordre] Déplacer le message à l'administration

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1875]
Suite aux tests utilisateurs, on note une frustration de parfois ne pas trouver son problème ou de ne pas pouvoir apporter d'informations complémentaires.
De plus, on sait que les agents se fient beaucoup à la description saisie par les usagers.

-> Déplacer le champ "Message à l'administration" de la page récap globale vers sur la page de récap des désordres (un seul champ une fois tous les désordres saisis)
-> Le champ reste facultatif
-> Dans le récapitulatif global, on ajoute ce qui a été saisi dans la partie désordres

![image](https://github.com/MTES-MCT/histologe/assets/97226289/3967a728-2816-455b-99e2-dcc9ec615a71)

On modifie l'intitulé et la description de la question
Intitulé : `Informations complémentaires`
Desc : `Vous pouvez apporter des précisions sur votre situation.`

**Comment by hmeneuvrier** [comment]
Config json + récap à modifier
