### ISSUE TITLE
[QA - Sentry] Impossible d'envoyer de mail de visite (email not valid)

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#1893]
https://sentry.incubateur.net/organizations/betagouv/issues/65433/events/abe2fb2f53f44b439d495f830273d9b6/

**Comment by hmeneuvrier** [comment]
https://sentry.incubateur.net/organizations/betagouv/issues/85674/?project=61&query=is%3Aunresolved+email&referrer=issue-stream&statsPeriod=14d&utc=truev

https://sentry.incubateur.net/organizations/betagouv/issues/85735/?project=61&query=is%3Aunresolved+email&referrer=issue-stream&statsPeriod=14d&utc=true

https://sentry.incubateur.net/organizations/betagouv/issues/85837/?project=61&query=is%3Aunresolved+email&referrer=issue-stream&statsPeriod=14d&utc=true

https://sentry.incubateur.net/organizations/betagouv/issues/65433/?project=61&query=is%3Aunresolved+email&referrer=issue-stream&statsPeriod=14d&utc=true

**Comment by emilschn** [comment]
Plutôt que corriger ce souci directement, est-ce qu'on pourrait avoir une alerte sur les fiches signalement qui indiquent que les adresses mail ne sont pas correctes ?
Typiquement, dans les coordonnées du foyer de ce signalement, le mail n'est pas correct : https://histologe.beta.gouv.fr/bo/signalements/e4854cf5-1420-40fd-b64e-23d0c83c351e

**Comment by emilschn** [comment]
Requête pour trouver tous les mails de déclarant non valides

`SELECT *  FROM `signalement` WHERE `mail_declarant` NOT REGEXP '^[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9._-]@[a-zA-Z0-9][a-zA-Z0-9._-]*[a-zA-Z0-9]\\.[a-zA-Z]{2,63}$' AND `mail_declarant` != '';`
