### ISSUE TITLE
[Expé] Test automatisation affectation

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1894]
Territoire(s) concerné(s) : 93
On cherche à tester l'affectation automatique basée sur le code INSEE du signalement.

-> Affecter automatiquement le signalement pour les partenaires type `Commune / SCHS` ayant au moins 1 utilisateur et le code INSEE du signalement.

**Comment by hmeneuvrier** [comment]
Faire en sorte qu'on plus ajouter facilement des territoires pour cette expé

**Comment by emilschn** [comment]
Vu avec Arnaud : l'affectation se fait dès la création du signalement (et pas à l'acceptation)
