### ISSUE TITLE
[BO - Dashboard] Augmenter taille police titre des widgets

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1895]
Je sais pas pourquoi sur le dashboard, la police du titre des widgets a été réduite
On dirait qu'elle est plus petite que la description du widget, c'est un peu étrange
![image](https://github.com/MTES-MCT/histologe/assets/97226289/8bc33825-9125-4e0a-9c67-795d9df2960f)

**Comment by hmeneuvrier** [comment]
ok, trouvé, ça vient de 
https://github.com/MTES-MCT/histologe/pull/1788/files#diff-d13a8211e279e3a10ecd1057a8ba0448ff64d2f221ac72d98e8bb4345a669dea

l'ajout de la css
```
h3 a {
    font-size: 0.8rem;
    color: #000091;
}

```
