### ISSUE TITLE
[ESABORA - SCHS] Grasse Hygiene - Dpt 06

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1912]
Signalement 2023-909 (https://histologe.beta.gouv.fr/bo/signalements/4efbaa20-77b9-4755-87cd-39f6d0884866) rejeté par le systeme
Meme apres modification du complément d adresse

**Comment by emilschn** [comment]
Données envoyées à Esabora pour analyse

**Comment by arnaudchouk** [comment]
je contacte le 06 pour accord de leur part

**Comment by arnaudchouk** [comment]
fait le 23/11/23 à 15h12

**Comment by emilschn** [comment]
Erreur plus précise reçue lors de l'affectation :

`{"code":"WS_ERR_SQL","message":"1366 - Incorrect string value: '\\xCC\\x81s.pd...' for column 'iaff_docobserv' at row 1"}`

Suite à échange avec Esabora, ça pourrait être du à un caractère spécial.
Probablement dans le champ d'observation des pièces jointes (d'après ce que je comprends de l'erreur de retour).

Avec les mêmes fichiers
- je ne reproduits pas sur l'environnement de test qu'ils nous ont mis à disposition
- ils n'ont pas de soucis non plus en testant sur leur appli de test

Ils répondent

> Ceci dit, vu le message je pense que c’est bien un pbe de caractère passé.
> On ne peut pas trop traiter cela de notre côté (et même si on le faisait, ce serait très long à être propagé sur les différents sites).
> Il serait préférable de le gérer de votre côté.
> En plus on a une grosse variété de base de données utilisées sur site et on ne peut pas exclure que cela joue vu le message.

On peut aborder le problème de deux manières :

1/ Le résultat est aléatoire sur leurs différents environnements. Donc c'est un souci qu'ils doivent gérer eux.

2/ Comme ils le soulignent, ça irait probablement plus vite si on faisait un truc de notre côté, en corrigeant l'encodage de la donnée envoyée.

**Comment by emilschn** [comment]
@arnaudchouk on a modifié le titre des fichiers en base de données, pour voir si le souci vient de là ou non (on tatonne un peu) ; possible de des-assigner Grasse et ré-assigner de nouveau ? :)

**Comment by arnaudchouk** [comment]
c est fait @emilschn

**Comment by emilschn** [comment]
@arnaudchouk Merci !
Il restait un accent... tu peux refaire ? (désolé !) (sinon je peux le faire, mais mon nom va apparaitre et ils vont s'inquiéter haha)

**Comment by arnaudchouk** [comment]
done @emilschn

**Comment by emilschn** [comment]
Merci @arnaudchouk 
L'import dans Esabora a fonctionné. Tu peux leur signaler

**Pour dev**
Correction à mettre en place : remplacer le titre du fichier `title` par le nom du fichier `filename`

**Comment by sfinx13** [comment]
@emilschn ne pas oublier la PR pour 
> Correction à mettre en place : remplacer le titre du fichier title par le nom du fichier filename
