### ISSUE TITLE
[BO - Traitement image] Commande de traitement de photos (Miniature, Resize)

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#1929]
> Pour l'existant (éventuellement autre ticket) : soit on fait la même chose à la volée à l'affichage du signalement, soit un script qui passe la nuit, et qui traite des batchs de photos --> à discuter

## Description
Après avoir mis à disposition les services de resize et de génération de miniature, faire une commande permettant pour chaque signalement d'un territoire de générer des miniatures et de resizer les images

## Comportement attendu
- [ ] La commande doit avoir comme argument le code zip du térritoire

**Comment by sfinx13** [comment]
### Exécution de la commande

#### Nombre d’élément sur le bucket  
```
aws s3 ls s3://[BUCKET_URL]/ | wc -l
55026
```

 

Lancement de la commande sur staging
```
$ scalingo -a histologe-staging run sh
$ php bin/console app:create-signalement-photo-variants 13
```

[Capture vidéo du 28-11-2023 16:09:39.webm](https://github.com/MTES-MCT/histologe/assets/5757116/09489ce3-b46b-4d5a-bf8a-ac4853830cbe)

**Comment by sfinx13** [comment]
Sans doute des pdf qui sont taggé comme image
![image](https://github.com/MTES-MCT/histologe/assets/5757116/ce1ec389-65d5-4e91-b4f8-cd61c709a1cc)

**Comment by numew** [comment]
> Sans doute des pdf qui sont taggé comme image

Oui aujourd'hui que ce soit sur le nouveau ou ancien formulaire rien ne force que ce soit des image qui soient envoyés dans upload d'image, il faudrait idéalement changer le type de ces fichiers la.
