### ISSUE TITLE
[SISH] Pas de calais

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1937]
* 2023-1066
* 2023-1067
* 2023-1081
erreur synchro "push_dossier_personne"

**Comment by emilschn** [comment]
@arnaudchouk 
Pour les deux premiers, il y a des "/" dans le déclarant, avec 2 noms différents ; ça ne me surprendrait pas que ce soit ça qui bloque.

**Comment by arnaudchouk** [comment]
on peut leur demander de modifier pour voir mais comme il y en a un 3e qui n est pas concerné je ne pensais pas que cela vienne de là

**Comment by emilschn** [comment]
@arnaudchouk 
Je viens de re-regarder.
En fait, le problème ne vient pas de `push_dossier_personne`, mais de `push_dossier` tout court (qui se fait avant, et si il est en échec, il bloque l'envoi suivant)
Lors de l'envoi du dossier lui-même, il y a eu un timeout.
Est-ce que ça peut être du à des photos trop lourdes ?
Il y en a dans les 3 signalements : 

- https://histologe.beta.gouv.fr/bo/signalements/23cd74e2-27e0-4736-9f96-9204b14d2cbf ; 
- https://histologe.beta.gouv.fr/bo/signalements/024ca085-4db0-4e23-a2d8-6c0fd05e335a ; 
- https://histologe.beta.gouv.fr/bo/signalements/0c6b17a8-2aaf-4010-8a19-56307c7fa8cf

Du coup, le problème ne viendrait pas de chez nous, mais plutôt de chez Esabora ?
- soit parce que le timeout est trop court
- soit parce que ça met longtemps à télécharger
- soit parce qu'ils devraient télécharger les fichiers en asynchrones, une fois qu'ils ont reçu les chemins

Ca te semble probable, @sfinx13  ?

**Comment by arnaudchouk** [comment]
d autres dossiers avec plus de dossiers ont déjà été importés
donc soit c est un pbm qui vient d apparaitre
soit c est une autre origine

**Comment by sfinx13** [comment]
@emilschn @arnaudchouk ça sera mieux avec de meilleurs messages d'erreurs, je me met dessus

**Comment by emilschn** [comment]
Les meilleurs messages d'erreur corrigeront les erreurs 400, mais là on était en timeout sur push_dossier :)

**Comment by sfinx13** [comment]
@emilschn oui désolé je vois des erreur 400 partout :-D

Ce signalement contient une trentaines de photos,
https://histologe.beta.gouv.fr/bo/signalements/0c6b17a8-2aaf-4010-8a19-56307c7fa8cf
Possible qu'on soit en timeout, c'est d'ailleurs un point que nous n'avons jamais abordé lors de nos échanges avec Esabora.
Faudrait confirmer avec eux, les contraintes en terme de timeout, on pourra ajuster en conséquence pour les gros dossiers

Apres pour les deux premiers dossiers me choque moins, peut être le délai de téléchargement des photos comme tu dis

Pour résumé, je partage l'hypothèse

**Comment by arnaudchouk** [comment]
ca a l air ok
