### ISSUE TITLE
Implémenter la CSP (réduction des attaques XSS)

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#1952]
Content Security Policy (CSP) header not implemented

~~X-XSS-Protection header not implemented~~ (Voir commentaire)

X-Content-Type-Options header not implemented

http://dashlord.mte.incubateur.net/dashlord/url/histologe-beta-gouv-fr/securite/#http

https://github.com/search?q=org%3AMTES-MCT%20CSP&type=code

**Comment by sfinx13** [comment]
> Non-standard: This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
