### ISSUE TITLE
[QA - Sentry] Unable to copy

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#1962]
https://sentry.incubateur.net/organizations/betagouv/issues/86715/?project=61&query=is%3Aunresolved+Unable+to+copy&referrer=issue-stream&statsPeriod=14d&utc=true

**Comment by hmeneuvrier** [comment]
https://sentry.incubateur.net/organizations/betagouv/issues/99402/?environment=prod&project=61&query=is%3Aunresolved+unable+to+copy&referrer=issue-stream&statsPeriod=14d
