### ISSUE TITLE
[BO - Signalement] Mauvais code Insee enregistré

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#1966]
Le signalement avec id 23812 a eu une adresse et un code postal en corse mais un code insee en Martinique

Supposition : quelqu'un a sélectionné une adresse en Martinique puis a saisi l'adresse en Corse par la suite, sans que le code Insee ne se mette à jour

On a déjà fait des correctifs à ce sujet. Le signalement date d'avril 2023. Ca a peut-être été corrigé entre temps.

Voir si c'est reproductible avec ancien formulaire, nouveau formulaire, fiche signalement

**Comment by numew** [comment]
Je fais la même supposition qu’Émilien. Via la fiché signalement si on enregistre une adresse (exemple en Martinique) puis qu'on veux la modifier par une entrée manuelle (pas en la sélectionnant dans la base adresse) on peux se retrouver avec des incohérence.

![info_addresse](https://github.com/MTES-MCT/histologe/assets/7130780/a15578c3-518e-4498-97b6-c0b4fe4d27ae)

Quoi qu'il en soit on à pas de contrôle de cohérence entre les différente information adresse à l'édition
