### ISSUE TITLE
[FO/BO - Signalement] Vidéo

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1971]
Bloquer l'upload de vidéos sur le site

**Comment by hmeneuvrier** [comment]
BO : 
- On ne peut plus ajouter de vidéos en passant par le bouton "ajouter des photos" (messages d'erreur dans la nouvelle modale)
- On peut ajouter des vidéos en passant par le bouton "ajouter des vidéos", du coup ensuite elles sont ouvertes dans une nouvelle fenêtre du navigateur et jouées via le navigateur, est-ce que c'est gênant @arnaudchouk ?

Dans la future page de suivi usager le fonctionnement sera le même je pense

Dans la page actuelle de suivi usager, on ne peut pas joindre de vidéos d'après mes tests, ni sur le bouton photos, ni sur le bouton documents

Dans le formulaire on peut mettre des vidéos pour les photos de désordre et aussi sur les boutons de documents (bail, état des lieux, dpe, diagnostique plomb) --> je vais rendre l'ajout de vidéos impossible pour les documents dans le formulaire, car ça n'a pas de sens pour les documents qui sont typés. Mais pour les désordres, je me demande, car maintenant les "vidéos de désordres" apparaissent dans la liste et sont donc ouverts dans une fenêtre de navigateur, ce qui est pas mal, mais on ne voit plus leur rattachement à un désordre donné... Je pense qu'il vaut mieux interdire aussi, qu'en penses-tu @arnaudchouk ?

**Comment by hmeneuvrier** [comment]
Vu avec Arnaud, on bloque l'ajout de vidéos partout BO et FO en attendant de le gérer spécifiquement

**Comment by sfinx13** [comment]
Je suis pour garder eml et msg (mail), on peut les ouvrir via un client mail

**Comment by hmeneuvrier** [comment]
> Je suis pour garder eml et msg (mail), on peut les ouvrir via un client mail @hmeneuvrier

@sfinx13 d'après mes recherches, il n'y a pas de type mime spécifique pour eml et msg, mais c'est le type `application/octet-stream` et c'est pas ouf d'autoriser ce type mime, non ?
Sinon il faut faire une double vérification avec l'extension... tu en penses quoi ?

**Comment by hmeneuvrier** [comment]
ok pour la double vérif
