### ISSUE TITLE
[FO - Page de suivi] Rendre le rapport de visite visible

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#1983]
Je suis usager
Il y a eu une visite de mon domicile
Une conclusion de visite a été renseignée
Un rapport de visite (document) a été ajouté
![image](https://github.com/MTES-MCT/histologe/assets/97226289/f5aa61e7-c9ad-4ce6-84dd-88504d7d2f7c)

Sur ma page de suivi usager, je vois bien le suivi de la conclusion de visite 
![image](https://github.com/MTES-MCT/histologe/assets/97226289/7df973f2-b82d-418e-ac83-0b8a61794493)

Par contre, le rapport (document), n'est pas disponible sur ma page de suivi

Il faudrait ajouter le lien vers le rapport (en téléchargement) à la fin du suivi.

-> à faire après correction du #1980

**Comment by arnaudchouk** [comment]
le rendre également visible pour les partenaires dans les suivis/notification
