### ISSUE TITLE
[BO - Création compte] Creuse (23)

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#1985]
Créer les Partenaires Type EPCI et comptes associes

https://docs.google.com/spreadsheets/d/199B-aNWlT23eh8Wm9qdlDzlDTD9ZpLa9TEyqADvJVkE/edit#gid=0

**Comment by sfinx13** [comment]
il manque des mails utilisateur @arnaudchouk

**Comment by arnaudchouk** [comment]
arf .. je les contacte
