### ISSUE TITLE
[BO - Export PDF] Date entree dans les lieux

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2006]
Concerne : 
* les signalements qui n'ont pas de date d'entrée dans les lieux renseignés
Probleme : 
* 23/09 par défaut inscrit sur le pdf
* Si pas de date : laisser vide ou ecrire NC

**Comment by hmeneuvrier** [comment]
@arnaudchouk je ne reproduis pas, j'ai N/R pour la date d'entrée dans les exports pdf des signalements qui n'ont pas de date d'entrée : 

![image](https://github.com/MTES-MCT/histologe/assets/33071753/780d60f8-5aa9-43eb-a054-87b5572f69d6)

**Comment by arnaudchouk** [comment]
j ai le 2022-554 sur le 06
mais en le regardant je comprends pas pourquoi j ai ecrit ca comme ca .. dsl

* les signalements qui n avaient pas de date d entree dans les lieux au moment de la migration le 230922, ont a priori eu la date de migration saisie par defaut en date d entree
* donc les exports reprennent cette mauvaise date
le pbm ets sur la date inscrite par defaut sur les signalements lors de la migration, pas un pbm de date generee au moment de l export

**Comment by emilschn** [comment]
Si on le fait pour tous ceux qui sont à ces dates là et qui ont un id entre x et y, on devrait pas trop se tromper ?

**Comment by arnaudchouk** [comment]
autre critere possible
date de signalement < date d entree dans les lieux
