### ISSUE TITLE
[Comptes archivés] Tagger les mails des comptes archivés pour éviter les doublons

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2035]
Lorsqu'on archive un user, on tag le champ email pour qu'il n'y ait plus de doublon @date-archivage

Dans l'affichage de la liste des comptes archivés, on masque le tag

Corollaire : lorsqu'on le désarchive, on commence par vérifier qu'il n'y ait pas de doublon, puis on détag

**EDIT**
Tagger le mails partenaire lors de la suppression de celui ci

**Comment by hmeneuvrier** [comment]
TODO : 

- [ ] à l'archivage d'un utilisateur et d'un partner on tag le mail
- [ ] au désarchivage, on vérifie que le mail n'est pas utilisé ailleurs, et on affiche une alerte si besoin
- [ ] on fait une commande pour taguer les mails de tous les utilisateurs et partenaires archivés
