### ISSUE TITLE
[Reprise de données] Sarthe (72)

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2039]
Importer les données
https://drive.google.com/drive/folders/1ltCtDIUNPWxzMsoKvkBP_HTRC_IZlvex?usp=sharing

**Comment by arnaudchouk** [comment]
soucis sur l import de la sarthe https://github.com/MTES-MCT/histologe/projects/4#card-91367450

* les affectations avaient comme separateur partenaire "&" mais a priori ca n a pas ete identifié, donc la plupart n ont pas ete affectes quand plus d un partenaire - à corriger
* un signalement aurait été dedoublé : le 2023-52 > 2023-74384 et il semble que des signalements deposes ensuite ont ete incrementes  a partir de ce chiffre : à corriger et recaler les ref
* 2 coquilles sur des signalements : 2029 ou lieu de 2019 : 
modifier ref 2029-1197 par 2019-1197 et 2029-983 par 2019-983 (déjà modifié dans le fichier)

**Comment by sfinx13** [comment]
Confirmé sur mattermost, on supprime les signalements de la Sarthe 
https://github.com/MTES-MCT/histologe/issues/2077
