### ISSUE TITLE
[QA - Sentry] Problème transition visite

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#2050]
https://sentry.incubateur.net/organizations/betagouv/issues/78267/?project=61&query=is%3Aunresolved&referrer=issue-stream

**Comment by emilschn** [comment]
Je ne reproduits pas.
J'ai vérifié le signalement concerné en prod, il est bien passé en CANCELED.
Je ne sais pas trop quoi faire de plus pour l'instant.
