### ISSUE TITLE
[BO - Visite] Catégoriser le rapport  de visite uploadé par les agents

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#2058]
## Description

Le type  `PROCEDURE_RAPPORT_DE_VISITE` doit être rattaché au fichier uploadé rapport de visite 

https://github.com/MTES-MCT/histologe/blob/main/src/Entity/Enum/DocumentType.php

![image](https://github.com/MTES-MCT/histologe/assets/5757116/27501dc5-4b59-4dd4-8622-16d63db58fd0)

Prévoir une migration pour les documents existants

**Comment by hmeneuvrier** [comment]
Géré dans le nouvel espace documentaire https://github.com/MTES-MCT/histologe/issues/2198
