### ISSUE TITLE
[FO - Signalement] Ne pas tester de correspondance entre code Insee et code postal

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2081]

**Comment by numew** [comment]
Détection du problème : 
https://mattermost.incubateur.net/betagouv/threads/4hm59euegbbiprxwd7pjni6ata

Fil tech
https://mattermost.incubateur.net/betagouv/threads/dstar5cgn3dhmyh7tckm6cck5o

**Comment by hmeneuvrier** [comment]
Lié à ça : https://github.com/MTES-MCT/histologe/issues/1303 ?

**Comment by hmeneuvrier** [comment]
Lié ? https://github.com/MTES-MCT/histologe/issues/1966

**Comment by hmeneuvrier** [comment]
Lié ? https://github.com/MTES-MCT/histologe/issues/2064
