### ISSUE TITLE
[Metabase] Signalements avec Motif Cloture modifie

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2092]
Identifier les signalements refermés pour tous avec le motif Autre après avoir été réouverts
(si possible, ayant un motif initial de cloture différent de Autre)

**Comment by numew** [comment]
Même problème que #2040 donc déja corrigé par #2043

**Comment by numew** [comment]
Voir https://histologe-metabase.osc-fr1.scalingo.io/question/1109-signalement-clotures-avec-le-motif-autre-ayant-des-suivi-cloture-pour-tous-les-partenaire-avec-un-autres-motifs
