### ISSUE TITLE
[BO - Signalement] Mettre le type de logement dans la partie "composition"

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2104]
Je me rends compte que ça a plus de sens de mettre le type de logement (appartement / maison / autre) avec la composition du logement, dans les blocs et dans la modale d'édition.

![image](https://github.com/MTES-MCT/histologe/assets/97226289/010829fd-4869-47c2-87ce-cb61578111e2)

**Comment by mathildepoulpux** [comment]
Je suis super admin
Je veux modifier la composition du logement
Dans la modale, je modifie le type de logement pour "Autre" 
Je remplis le champ "précision" 
Quand je valide la modale, j'ai cette erreur : 
![image](https://github.com/MTES-MCT/histologe/assets/97226289/8a6061d7-5eac-4079-b0ca-bffe86ef2bf9)

**Comment by emilschn** [comment]
@mathildepoulpux merci, c'était pas lié au type de logement, mais au fait que la superficie est vide
J'ai corrigé le souci dans une nouvelle PR. Mais si tu veux tester le type de logement, tu peux mettre un nombre dans la superficie :)
