### ISSUE TITLE
[BO - Liste signalement][Back] Ajout des nouveaux filtres et des nouvelles options aux filtres existants

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2118]
[BO - Listing signalement] Ajouter "refusé" dans les choix du filtre statut #851
[BO - Liste signalements] Permettre de filtrer les partenaires par territoire pour le SA #634
[BO - Liste des signalements] Permettre aux agents de filtrer par arrondissement dans le filtre commune #858

**Comment by sfinx13** [comment]
Il va rester ce ticket à traiter 
Intégrer la liste des EPCI via l'API Geo https://github.com/MTES-MCT/histologe/issues/2423
