### ISSUE TITLE
[FO] Recevoir / récupérer le lien vers la page de suivi par mail

### ISSUE THREAD

**Issue by numew** [MTES-MCT/histologe#2124]
avoir un CTA sur la fiche de signalement qui permet d'envoyer automatiquement un mail à l'usager avec le lien pour accéder à son signalement.

**Comment by numew** [comment]
Je pense qu'on pourrait aussi proposer ou envoyer automatiquement le mail avec le(s) lien(s) de suivi quand un utilisateur tente la procédure de mot de passe perdu avec son adresse car ca semble arriver

**Comment by mathildepoulpux** [comment]
> Je pense qu'on pourrait aussi proposer ou envoyer automatiquement le mail avec le(s) lien(s) de suivi quand un utilisateur tente la procédure de mot de passe perdu avec son adresse car ca semble arriver

Le lien de suivi vers quoi ?

**Comment by mathildepoulpux** [comment]
Idée pendant le présentiel : 
Ajouter un CTA sur la homepage (FO) permettant à l'usager de renseigner son email pour recevoir un lien vers la page de suivi.

A définir : si on demande juste l'email ou email + une autre info (le CP, le nom de famille...)

**Comment by mathildepoulpux** [comment]
## Envoyer le lien vers la page de suivi
Constats : les usagers envoient des mails par le formulaire de contact pour connaître l'avancée de leur signalement plutôt que de se rendre sur leur page de suivi.
Problème : perte de temps pour l'équipe et les territoires puisqu'on doit renvoyer ces mails aux territoires qui doivent ensuite entrer en contact avec les usagers pour leur partager les mêmes infos que sur leur page de suivi.

Besoin : permettre à l'usager de retrouver sa page de suivi

Solution : avoir un CTA permettant à l'usager de recevoir un lien vers sa page de suivi par mail.

### Parcours utilisateur
1. En tant qu'usager, j'accède à la page d'accueil ou de contact du site public
2. Dans la partie `Je veux accéder au suivi de mon signalement`, je renseigne l'adresse email du déclarant et l'adresse postale du logement (en autocomplete depuis la BAN)
3. Je clique sur `Recevoir mon lien de suivi par mail`

-> On cherche une correspondance : email déclarant et l'adresse postale

**Conséquences**
- On affiche un message : `Si un signalement correspond aux informations saisies, un email contenant le lien vers votre page de suivi sera envoyé. Consultez votre boîte mail et n'oubliez de regarder dans les emails indésirables (spam).`
- Si signalement : on envoie le mail de suivi sur l'adresse email renseignée
- Si pas de signalement : rien

### Contenu de l'email
_Objet :_ Lien vers votre page de suivi

_Corps :_ 
Vous avez demandé à recevoir un lien vers la page de suivi de votre signalement pour le logement situé {{adresse}}.
Pour rappel, votre page de suivi vous permet de : 
- Suivre l'avancée de votre dossier
- Ajouter des photos, des documents ou des précisions sur votre situation
- Envoyer un message à l'administration

**Conservez précieusement cet email pour pouvoir y accéder à tout moment.**

Pour accéder à votre page de suivi, cliquez sur le bouton ci-dessous :

_Bouton :_ [Accéder à ma page de suivi]
Si le bouton ne fonctionne pas, [cliquez ici]()

### Ressources
- [Maquette homepage avec CTA](https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/)
- [Maquette page de contact](https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/screen/d1f4a3f9-c5f6-4ed9-ad29-8665ae32fe17/)
