### ISSUE TITLE
[BO - Fiche signalement] Revoir l'UI

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2130]
Dans le cadre de l'OKR `Expliciter action attendue sur signalement / partenaire (visite, CR,…)`, j'ai bossé sur la tâche "redesign intermédiaire" de la fiche signalement dont [voici la maquette.](https://xd.adobe.com/view/e5855fd5-f654-4198-ab6e-3a6a27e60b65-b0d6/)

### Prérequis
Avoir fini le travail sur la gestion de doc #947 
Pour pouvoir distinguer les docs partenaires de ceux des usagers et pouvoir qualifier les docs partenaires.

### Fonctionnement 
**RT**
- Nouveau signalement (signalement non validé) : 
    - L'onglet Activité PDLHI est inactif tant que le signalement n'est pas validé par le RT
    - On atterrit donc sur le 2eme onglet par défaut (situation).
    - On ne peut pas effectuer les actions (boutons inactifs) tant que le signalement n'est pas validé, selon les règles actuelles
- Signalement validé 
    - l'onglet Activité PDLHI est actif, 
    - toutes les actions sont dispo selon les droits du user
    - on atterrit sur l'onglet Activité PDLHI par défaut

- Signalement refusé / signalement clôturé
    - On affiche tous les onglets
    - Actions non disponibles (boutons inactifs) selon les règles actuelles

**Pour les partenaires (agent / partenaire admin)** 
- Quand affectation en attente : 
    - on accède au signalement sur l'onglet activité PDLHI
    - on peut parcourir tous les onglets mais 
    - actions non disponibles (boutons inactifs)
- Une fois le signalement validé : 
    - on peut effectuer les actions selon les droits du user

Pour le reste, fonctionnellement rien ne change, on garde les mêmes actions avec les même règles qu'aujourd'hui.

### Affichage
**RT**
Sous les boutons de validation / refus, on ajoute le message d'info : 
`En tant que responsable de territoire, vous devez valider ou refuser ce signalement.`

**Agent / admin partenaire**
Sous les boutons validation / refus d'affectation, on ajoute le message d'info : 
`Vous devez accepter l'affectation pour pouvoir traiter le dossier.`

**Tous les rôles**
- Dans le header, à côté du nom, on ajoute le statut sous forme de label : 
    - Nouveau : icône warning-line + couleur warning
    - En cours : icône message-2-line + couleur success
    - Refusé : icône close-line + gris main
    - Clôturé : icône checkbox-circle-line + couleur error
- Dans le header, à côté de la date de dépôt, on ajoute le type de déclarant sous forme de label : sans icône + couleur yellow moutarge

**Comment by mathildepoulpux** [comment]
Si on peut en profiter pour faire ce ticket #2141 ce serait top 🙏

**Comment by hmeneuvrier** [comment]
Supprimer l'utilisation de tippy pour la création de tag, cf https://github.com/MTES-MCT/histologe/pull/2462#discussion_r1565341791

**Comment by hmeneuvrier** [comment]
@mathildepoulpux après analyse de la maquette et de tes specs, on réévalue en `Dev M` plutôt que `Dev XL`, et ça ne nécessite pas de découpage en ticket. Donc priorisez-le quand vous voulez !

**Comment by arnaudchouk** [comment]
@mathildepoulpux en repassant sur la maquette j ai vu ta remarque sur l onglet photo
Je pense que ce serait bien de le conserver - ca permet d avoir tout sur un seul onglet - une sorte de vue synthetique pour ceux qui le souhaitent

**Comment by mathildepoulpux** [comment]
Ca marche on le garde alors !
