### ISSUE TITLE
[Metabase] Signalements en cours sans partenaires actifs

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2148]
Liste des ref des signalements en cours + précision sur ZIP et statut import)

Pour lesquels
 AUCUN partenaire n'est actif sur le signalement (tous les partenaires affectés doivent avoir pour statut : soit en attente, soit clotures, soit refuse)
+
Si possible avoir l info : 
 + de 3 relances sans réponses/ - de 3 relances sans réponses
(Ou 2 listes séparees si plus simple)

**Comment by hmeneuvrier** [comment]
@arnaudchouk 
Pour la première partie, est-ce que tu veux les signalements qui n'ont aucun partenaire affecté ou pas ?

Je n'ai pas compris la 2è partie : 

`
Si possible avoir l info :

    de 3 relances sans réponses/ - de 3 relances sans réponses
    (Ou 2 listes séparees si plus simple)
`

de quel type de relance parles-tu ? des demandes de feedback ?

**Comment by hmeneuvrier** [comment]
https://histologe-metabase.osc-fr1.scalingo.io/dashboard/77-signalements-en-cours-sans-partenaires-actifs?idterritory=13&isimported=true

**Comment by arnaudchouk** [comment]
* oui : intégrer également les signalements sans aucun partenaire affecté non plus
* je parle effectivement des relances auto : si on peut avoir en plus l indication precisant si oui ou non le signalement a eu plus de 3 relances auto sans reponse c est top

**Comment by hmeneuvrier** [comment]
@arnaudchouk ok merci, je vais ajouter quelque-chose pour les relances auto.
J'ai mis le nombre de partenaires affectés par signalement, et un filtre sur le statut, car tous les signalements clos apparaissaient puisque les affectations sont égalements closes dans ce cas.
Ca te permettra d'affiner ce dont tu as besoin. (sachant qu'à part pour le filtre sur l'id de territoire, tu peux mettre plusieurs valeurs pour les filtres)

**Comment by hmeneuvrier** [comment]
Ajout de :
- Filtre de date (mois/année)
- Nombre affectations : tu choisis 0 dans la liste pour avoir tous les signalements avec 0 affectations
- Différent de 0 affectation : tu choisis 0 dans la liste pour avoir tous les signalements avec au moins 1 affectation

**Comment by hmeneuvrier** [comment]
Je clos le ticket
