### ISSUE TITLE
[FO - Page suivi usager] Revoir l'UI

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2149]
Dans le cadre de l'OKR `Capacité de suivi`, j'ai travaillé sur la refonte de la page de suivi usager.
Pour rappel, nous avons pris la décision de découper cette fonctionnalité en 3 versions.

Ce ticket concerne la V1, c'est-à-dire la refonte de l'UI de la page en reprenant les actions existantes et en ajoutant des liens.
La [maquette est dispo ici](https://xd.adobe.com/view/4797079d-89ff-4663-ba1e-fe00751dd621-12c4/)

### Fonctionnement
**Prérequis**

- [x] Avoir terminé le travail sur la gestion de documents (cf. #947 ) pour permettre de : 
    - Qualifier les documents à l'upload
    - Identifier les photos et documents comme provenant de l'usager (par opposition aux partenaires)
- [x] Avoir fait la page "Aides aux travaux"
- [x] Avoir fait la page "Obligations propriétaire / bailleur"

**Accès**
L'usager accède à sa page de suivi : 
- Depuis le bouton sur la page de confirmation d'envoi du signalement
- Depuis le lien dans l'email de confirmation
- Depuis le lien dans les emails de suivi / visite / etc.

On garde les règles d'accès actuelles pour les tiers déclarant et occupants.

### Affichage
On affiche un header avec : 
- Signalement {{ref}}
- Prénom Nom de l'occupant
- Date de dépot du signalement `Déposé le DD/MM/YYYY`
- Statut du signalement sous forme de label (nouveau, en cours, fermé)
- Message d'info qu'on peut fermer `Consultez vos échanges avec l'administration dans l'onglet **"Suivi du dossier"** et retrouvez les détails de votre signalement dans l'onglet **"Mes infos"**.`

On sépare ensuite le contenu en 2 onglets : 
- Suivi du dossier : contient les échanges avec les partenaires et permet d'envoyer un message avec photos et documents
- Mes infos : contient les détails du signalement et d'autres actions

#### Onglet Suivi du dossier
On affiche le message automatique avec la date d'enregistrement du signalement sous le titre de l'onglet.
On affiche les messages par ordre chronologique : 
- Les messages partenaires sont alignés à gauche
- Les messages du déclarant / de l'occupant sont alignés à droite

On propose un champ "message" à la fin des échanges avec 2 boutons secondaires : 
- Un bouton pour ajouter des photos -> ouvre le nouveau système d'upload de photos
- Un bouton pour ajouter des docs -> ouvre le nouveau système avec la qualif des doc

#### Onglet Mes infos
On reprend le récapitulatif du signalement (comme dans le formulaire), les boutons d'édition en moins.

Dans la partie coordonnées du bailleur, on ajoute l'action **Télécharger courrier bailleur**
Permet de télécharger le PDF du courrier à envoyer à son bailleur (le même qu'on envoie déjà en PJ du mail).
[Courrier dispo sur le drive ici](https://drive.google.com/file/d/1SvdaCfqrM0ZmcqHRGfh09Ek6Y_AbwrxY/view?usp=drive_link)

Règle d'affichage : 
- Si profil locataire
- Si tiers (tous profils hors bailleur)

ET si "bailleur prévenu" = non ou ne sais pas

Dans la partie désordres, on ajoute une partie **photos** : 
- Les photos sont affichées en miniature
- Clic sur une photo -> ouverture dans un nouvel onglet

A la fin, on ajoute un bloc **En savoir plus**, avec une liste de liens vers différentes pages : 
- [J'ai déposé un signalement, et après ?](https://faq.histologe.beta.gouv.fr/usager/traitement-signalement/evolution-dossier)
- [Propriétaire, locataire : les obligations](/entretien-logement-obligations-proprietaire-locataire)
- [Aides aux travaux](/aides-travaux-logement)
- [Politique de confidentialité](https://histologe.beta.gouv.fr/politique-de-confidentialite) 

### Signalements non ouverts
- **Signalement refusé** : on affiche la page, sans la possibilité d'effectuer les actions ajout de message / photos / documents + affichage d'un message d'info `Votre signalement a été refusé, vous ne pouvez plus envoyer de messages.`
- **Signalement clôturé** : on affiche la page, sans la possibilité d'effectuer les actions ajout de message / photos / documents + affichage d'un message d'info `Votre signalement a été clôturé, vous ne pouvez plus envoyer de messages.`
- **Signalement archivé** : on ne l'affiche pas. Donc si l'usager clique sur le lien de suivi il arrive sur une erreur 404.

----
### Versioning 
![Page suivi usager - Proposition versioning page suivi - dec 2023](https://github.com/MTES-MCT/histologe/assets/97226289/a73f1058-eec6-4642-bcd9-5dacfd10b467)

**Comment by arnaudchouk** [comment]
si un usager ajoute un doc dans son signalement et qu il souhaite le supprimer, il ne peut pas le faire sur la page de suivi
sachant qu un agent ne peut pas le supprimer non plus, le document ne peut pas etre retiré
il faut laisser la possibilité à l usager de retirer un doc s il s est trompé

**Comment by mathildepoulpux** [comment]
D'accord mais on ajoute ça à quel moment ?
- Dans la refonte UI (ce ticket) ?
- Dans la V2 ?
- Dans la V3 ?

**Comment by arnaudchouk** [comment]
le + tôt sera le mieux - mais si c'est un dev qui est plus que xs ca peut se faire en v2

**Comment by mathildepoulpux** [comment]
J'ajoute ça à la V2

**Comment by numew** [comment]
Pour l'instant on laisse l'affichage des pièces jointe dans le bloc (message html brut), l'affichage comme demandé sur la maquette sera faisable après réalisation du ticket #2430
![Screenshot 2024-04-23 at 15-57-49 Page suivi usager V1 - Mobile](https://github.com/MTES-MCT/histologe/assets/7130780/d489f39b-b061-4027-8242-86bdfa834009)

**Comment by mathildepoulpux** [comment]
Dans "Mes infos", utiliser le composant "callout" du DSFR pour la partie _Prévenez votre bailleur_

- Titre: `Prévenez votre bailleur (propriétaire) !`
- Description : `Il est recommandé d'informer le bailleur du logement des problèmes rencontrés dans le logement. Nous vous mettons à disposition un modèle de courrier à remplir et envoyer à votre bailleur. Cliquez sur le bouton ci-dessous pour le télécharger.`
- Bouton : icône arrow-down-line + `Télécharger le courrier`

- Couleur bordure : $brown-caramel-main-648
- Couleur fond : $brown-caramel-950

**Comment by arnaudchouk** [comment]
je n ai pas accès à la page de suivi
lorsque je recupere l url du bouton ca m envoie soit sur le bo si je suis connecte soit sur la page de connexion si je suis en navigation privée

**Comment by arnaudchouk** [comment]
**remarques :
 * un usager ajoute un doc sur la page de suivi et une photo : seule la photo est visible dans la page mes infos - alors que les 2 ont été ajoutés au meme moment, donne l impression d'une non reception du doc
 * si un signalement est archivé l'usager arrive sur la home avec message : " Erreur... Le lien utilisé est invalide, vérifiez votre saisie." - potentiellement il n'a pas eu d'autre message lui indiquant pourquoi son signalement a été archivé ; reflechir à une page spécifique pour les signalements archivés (une sorte de page 404, avec la fonction de recuperation de lien de suivi avec un message type : le signalement que vous recherchez n'est plus accessible. Nous vous invitons à récupérer un lien actif)
 
 ** onglet Mes infos - propositions : 
 * Ajouter un saut de ligne entre Titre Mes Infos et Adresse du Logement
 * Type et composition du logement - détails : ajouter bullet point devant chaque info
 * Situation du foyer - détails : ajouter bullet point devant chaque info
 * La Procédure : induit des infos sur la procédure en cours or il s'agit des démarches effectuées par déclarant - propose de reprendre plutôt le titre du bloc sur le bo : Procédures et démarches
 * réfléchir à l ajout des docs (voir plus haut)
 * en cas de bailleur non prevenu ou nsp, integrer les infos "Prevenez votre bailleur + doc" dans un bloc info coloré - c'est un message spécifique, pas une reprise d'infos de ma fiche de signalement
 
**Autre: 
 * Message auto en cas de refus "Signalement cloturé car non-valide avec le motif suivant..." devrait être Signalement **refusé** car non-valide avec le motif suivant
 * reflexion à mener sur la possibilité de supprimer un document ou photo en tant que déclarant

**Comment by mathildepoulpux** [comment]
Tests OK
Je ferme ce ticket puisque les choses restantes font l'objet d'autres tickets
