### ISSUE TITLE
[FO - Formulaire] Bloquage si superficie non-remplie

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2160]
Rencontré par Arnaud pendant les tests

Uncaught PHP Exception TypeError: \"App\\Specification\\Signalement\\SuroccupationSpecification::checkSuroccupation(): Argument #3 ($superficie) must be of type float, null given, called in /app/src/Specification/Signalement/SuroccupationSpecification.php on line 25\" at SuroccupationSpecification.php line 29","context":{"exception":{"class":"TypeError","message":"App\\Specification\\Signalement\\SuroccupationSpecification::checkSuroccupation(): Argument #3 ($superficie) must be of type float, null given, called in /app/src/Specification/Signalement/SuroccupationSpecification.php on line 25","code":0,"file":"/app/src/Specification/Signalement/SuroccupationSpecification.php:29"

**Comment by sfinx13** [comment]
J'ai pas réussi à reproduire sur la superficie @arnaudchouk 
![image](https://github.com/MTES-MCT/histologe/assets/5757116/85167175-973c-4f4f-93df-fcf61f5ef641)

**Comment by arnaudchouk** [comment]
@sfinx13 a priori t as testé en édition
Mon cas s est présenté au moment de la complétion du signalement - popup bloquante au moment de la validation sans message
Le champs etait facultatif, non rempli, mais bloquant

**Comment by sfinx13** [comment]
> @sfinx13 a priori t as testé en édition Mon cas s est présenté au moment de la complétion du signalement - popup bloquante au moment de la validation sans message Le champs etait facultatif, non rempli, mais bloquant

Merci @arnaudchouk  effectivement reproductible pour les tiers particulier, pro et service de secours
