### ISSUE TITLE
[FO - Adresse] Récupérer CP pour filtrer autocomplétion

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2163]
* Adresse et coordonnées
Lorsque l'on tape son adresse dans le champs adresse, les propositions qui apparaissent dans la liste ne tiennent pas compte du CP renseigné sur la Home page
Reprendre le même fonctionnement que sur Stop-Punaises

**Comment by arnaudchouk** [comment]
est ce que l on peut bloquer l autocompletion sur la base adresse correspondante au cp pour proposer que des rues en phase avec le cp renseigné ?
la j ai mis 34000 et ca me propose plein de villes
![Uploading image.png…]()

**Comment by sfinx13** [comment]
Il manque la copie d'écran mais peut être que la rue n'existe pas ?

**Comment by arnaudchouk** [comment]
en fait la rue existe car elle est proposée après 3 caractères saisis... mais lorsque l'on continue à taper le nom de la rue, là ca cafouille et il affiche la rue mais pour d'autres villes en priorité

**Comment by sfinx13** [comment]
Du coup est ce ticket doit rester ouvert ? @arnaudchouk

**Comment by arnaudchouk** [comment]
si vous me dites qu on ne peut pas faire mieux... on peut cloturer

**Comment by sfinx13** [comment]
o
