### ISSUE TITLE
[BO - Désordres] Chauffage/Confort

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2166]
Lorsqu'un désordre chauffage est sélectionné, indiqué l'information type de chauffage en plus 
Autrement l'info sur le type de chauffage n'apparait jamais
![image](https://github.com/MTES-MCT/histologe/assets/93710194/3b35f28e-1864-45d5-87dd-e5c5a3ac01ff)

**Comment by hmeneuvrier** [comment]
Faire comme pour le type de nuisibles "autres" (je ne sais plus exactement)
