### ISSUE TITLE
[BO - Signalement] Affichage champs obligatoires / facultatifs et des erreurs à l'édition

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2168]
### Parcours
Je suis SA
Je vais dans le BO sur le signalement https://histologe-staging.osc-fr1.scalingo.io/bo/signalements/e4d3c4a7-878b-404b-8424-4b3026d37757
J'ouvre la modale d'édition du bloc "Informations sur le logement"
J'enlève le nombre d'occupants
![image](https://github.com/MTES-MCT/histologe/assets/97226289/8cfb06cd-b7d6-4fd2-9165-a02d7199c9e3)

Je valide
-> J'ai une erreur en haut de page
![image](https://github.com/MTES-MCT/histologe/assets/97226289/ce47417d-7209-400b-819e-a6ed99710fba)

Dans la même modale, j'ai d'autres champs vides
![image](https://github.com/MTES-MCT/histologe/assets/97226289/1a0f9ecd-9bbd-42de-b5e6-c763c391b6cd)

Je peux valider sans les remplir
![image](https://github.com/MTES-MCT/histologe/assets/97226289/45d8ffe4-33de-48b0-b603-ca61f2159931)

### Problème
➡️ Je ne sais pas ce qui est obligatoire ou non, je le "découvre" quand il y a une erreur quand je suis de retour sur la fiche signalement.

### Comportement attendu :
- Indiquer les champs obligatoires dans la modale en ajoutant un astérisque à côté des labels
- Ajouter la mention `(facultatif)` sur les champs concernés
- Afficher les erreurs dans la modale, sous le champ, plutôt que sur la fiche signalement

![image](https://github.com/MTES-MCT/histologe/assets/97226289/1c9ace15-9964-4103-92b4-37d287d64620)

**Comment by hmeneuvrier** [comment]
Pas simple à faire, nécessite une grosse refacto.

Pour afficher les champs obligatoires par profils, il faudrait utiliser les formm Symfony
Pour afficher les erreurs sous les champs, il faut refaire en ajax

Ce serait pas mal d'avoir un tableau avec toutes les données obligatoires ou facultatives par profil

**Comment by hmeneuvrier** [comment]
Le tableau est fait : https://docs.google.com/spreadsheets/d/1hvhNHY5ZS-MtgbEBo8WCUrj4aKExJqMxGANP3Z1zDEg/edit?usp=sharing

**Comment by sfinx13** [comment]
Attendre que les PRs ci dessous soitent mergés 
* https://github.com/MTES-MCT/histologe/pull/2194
* https://github.com/MTES-MCT/histologe/pull/2196
* https://github.com/MTES-MCT/histologe/pull/2204
