### ISSUE TITLE
[BO - Edition] Recalcul Suroccupation

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2175]
Lorsque l'on édite un signalement
les scores s'ajustent et les tags également SAUF Suroccupation dans 1 cas : 

Si la variable Allocataire est modifiée lors de l'édition, le recalcul n'impacte pas le TAG Suroccupation (apparition/disparition)
* soit le calcul permettant de tagger en surrocupation n'est pas relancé 
* soit la méthode de calcul à appliquer selon le type Allocataire ou non n'est pas bien sélectionnée

**Comment by hmeneuvrier** [comment]
ok, allocataire est peut-être dans un bloc sur lequel je ne relance pas le calcul des qualifs, à vérifier
