### ISSUE TITLE
[BO - Signalement] Désordres - Absence de chauffage

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2183]
lorsque je selectionne absence de chauffage dans le logement, le désordre n est pas pris en compte
https://histologe-staging.osc-fr1.scalingo.io/bo/signalements/1870bac6-b8bb-4aff-a95f-1bf6b50e45eb
pas de score ni de desordre indique sur la fiche de signalement et ne declenche pas la nde alors que ce devrait etre pris en compte

**Comment by hmeneuvrier** [comment]
à vérifier

**Comment by hmeneuvrier** [comment]
En attente de réponse d'Arnaud sur la manière de faire : https://mattermost.incubateur.net/betagouv/pl/qury3imsrty7jy91zh68zk8fjr
