### ISSUE TITLE
[BO - signalement] Créer la modale d'upload de photos/documents

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2200]
cf specs : https://github.com/MTES-MCT/histologe/issues/947
https://github.com/MTES-MCT/histologe/wiki/Ajout-documents#ajout-de-documents-par-les-agents-bo

- [ ] BO - Créer modale ajout documents partenaires
- [ ] BO - Créer modale ajout documents situation usager

https://xd.adobe.com/view/3cae505c-cf52-408c-a800-0bdd78e695f2-69fd/screen/0c3f48bb-09e0-49bd-9251-1d45685f6cf8/

https://xd.adobe.com/view/3cae505c-cf52-408c-a800-0bdd78e695f2-69fd/screen/2d6299ec-c7ff-4f4b-ae2e-b311cd6932d0/

**Comment by sfinx13** [comment]
Axios : 
https://github.com/axios/axios?tab=readme-ov-file#-progress-capturing
