### ISSUE TITLE
[BO - signalement] Revoir les notifications en cas d'ajout photos/documents

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2201]
cf specs : https://github.com/MTES-MCT/histologe/issues/947

- [ ] BO - Revoir les notifs pour les nouveaux documents / nouvelles photos

**Comment by hmeneuvrier** [comment]
@mathildepoulpux je ne trouve d'info sur les notifications dans aucune spec, qu'est-on sensé faire ? Les seules notifications restantes sont les notifications de suivis. Donc concernant les photos/documents, on va avoir les mêmes changements sur les notifications qu'il y aura sur les suivis cf https://github.com/MTES-MCT/histologe/issues/2199 . Est-ce que c'est bon, ou est-ce que tu avais autre chose en tête ?

**Comment by mathildepoulpux** [comment]
Oui c'est bon !
