### ISSUE TITLE
[BO - Signalement] Soft Bounce- E reputation

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2213]
Remplir formulaire en ligne pour whitelister adress ip

*refused due to the sender IP found in ERS-DUL. For details, query the IP reputation on https://servicecentral.trendmicro.com/en-US/ers/.

Regarder sur brevo si necessaire les softbounce
https://app-smtp.brevo.com/log#66de0a82-ac7e-4a9a-ac2c-69b3992499d9

**Comment by hmeneuvrier** [comment]
![image](https://github.com/MTES-MCT/histologe/assets/33071753/0a971d10-46f9-469e-9fb5-8807b3060a01)

**Comment by hmeneuvrier** [comment]
Du coup, je m'en occupe

**Comment by sfinx13** [comment]
On est bon désormais, le temps a fait son effet j'a rien fait @arnaudchouk 

![Image](https://github.com/MTES-MCT/histologe/assets/5757116/6c5b6a00-19e6-4eb6-bb9d-04e91473dd1a)

Je ferme le ticket
