### ISSUE TITLE
[BO - Signalement] Suppression suivis - Mauvais dossier

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2214]
Supprimer les 3 suivis du 050224 de Mme Duvoisin 

https://histologe.beta.gouv.fr/bo/signalements/2bc03073-b196-45ef-8fa6-5fb48cc4349b

**Comment by emilschn** [comment]
C'est ok @arnaudchouk ; j'ai modifié le texte, comme on l'avait fait sur de précédents signalements
