### ISSUE TITLE
[QA - Sentry] Cannot assign null to property App\Entity\Partner::$users of type Doctrine\Common\Collections\Collection

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2216]
Uncaught PHP Exception TypeError: "Cannot assign null to property App\Entity\Partner::$users of type Doctrine\Common\Collections\Collection"

https://sentry.incubateur.net/organizations/betagouv/issues/84836/?query=is%3Aunresolved&referrer=issue-stream

**Comment by emilschn** [comment]
8 fois pendant les 10 minutes de la MEP, mais plus reproduit
Pas reproduit avec la copie de la prod en local
De côté pour l'instant

**Comment by hmeneuvrier** [comment]
Plus reproduit, je ferme
