### ISSUE TITLE
[BO - Signalement] Liste partenaire a affecter

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2223]
Retirer les précisions de compétences de la liste des partenaires dans la modale d affectation pour une meilleure lisibilité
![image](https://github.com/MTES-MCT/histologe/assets/93710194/29e71239-9011-4798-ad65-0a4c3a77bfb8)

**Comment by hmeneuvrier** [comment]
Le changement vient de ce commit : https://github.com/MTES-MCT/histologe/commit/b7609448e6ff517251d0b2f4269152f897e61759

![image](https://github.com/MTES-MCT/histologe/assets/33071753/de854300-09bb-4191-a1bb-b05c12c5cffe)

on appelle maintenant SignalementManager->findAllPartners avec un booleen $addCompetences à true dans tous les cas, ce qui ajoute les compétences à $partners['not_affected'] et elles sont du coup affichées (_modal_affectation.html.twig, lignes 34 à 38)

C'est quelque-chose qui a été créé l'année dernière pour la NDE, et comme on a étendu la NDE pour tous les territoires, ça a cet effet de bord.

On peut dans un premier temps faire un hotfix pour remettre comme avant.

@arnaudchouk 
Mais dans un second temps, que veut-on ? 
Est-ce qu'on veut n'afficher aucune compétence (et tant pis pour les territoires d'expé qui affichaient les compétences sur les signalements NDE ?)
Est-ce qu'on veut ne laisser les compétences que pour les signalements NDE que pour les territoires d'expé ? (en gros remettre commem avant grâce au hotfix)
Est-ce qu'on veut afficher les compétences pour les signalements NDE pour tous les territoires ?
Autres ?

**Comment by arnaudchouk** [comment]
@hmeneuvrier 
Je pense qu on peut retirer toutes les competences pour tous les territoires
On a diffusé le concept de compétence avec les visites, je pense que chaque territoire sera capable d'identifier quel partenaire a la compétence NDE
