### ISSUE TITLE
[Performance][QA] Optimisation JS

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#2232]
## Description
Une nouvelle organisation de fichier a été proposé a été proposé en sous répertoire dans les assets/controllers
Le nom du sous repertoire doit correspondre au nom de la route symfony
```
├── back_signalement_view
│   ├── album.js
│   ├── visite.js
````
Suite à  ça est né une réflexion sur le fait de diviser le fichier de build en plusieurs fichiers distincts. Par exemple, un fichier pour le frontend, un autre pour le backend, il faudrait pour cela faire un inventaire afin de savoir quel sont les fonctionnalités utilisé par quel brique (front ou back ?)

```twig
    {% block customscripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
```

```twig
    {% block customscripts %}
        {{ encore_entry_script_tags('app_front') }} pour le FO ?
    {% endblock %}
```

```twig   
 {% block customscripts %}
        {{ encore_entry_script_tags('app_back') }} pour le BO ?
    {% endblock %}
```

Autre réflexion serait de migrer vers assetmapper qui offirait plus de flexibilité et améliorerait la DX 

https://symfony.com/blog/upgrading-symfony-websites-to-assetmapper

Prendre en compte dans la réflexion les fichiers historiques et les migrer (pour ce qui restera) dans la nouvelle hierarchie
* public/js/const.js
* public/js/app.js

**Comment by hmeneuvrier** [comment]
En partie fait dans #2845  https://github.com/MTES-MCT/histologe/pull/2847

**Comment by sfinx13** [comment]
On peut donc fermer le ticket, faudrait à l'occasion regarder ce nouveau composant et voir ce qu'il apporte
