### ISSUE TITLE
[BO - Signalements] Filtres 93 inopérant

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2233]
https://mattermost.incubateur.net/betagouv/pl/j6th38b71bdexkjmmb5e7cwjkh

Signalement 2024-10
le tableau de bord m'a signalé l'existence de cette clôture mais au moment de clique sur l'encadré "clôture partenaire", la liste de dossier est vide

le tableau de bord n'indique plus l'existence de ce dossier
en appliquant le filtre "fermé chez au moins un partenaire" dans la liste des signalements, ce dossier n'apparait pas.
dur a reproduire mais quand je vais sur le listing total il y a bien le  signalement cloture par l unnique partenaire

**Comment by emilschn** [comment]
Lié à ça : https://github.com/MTES-MCT/histologe/issues/944
Le fonctionnement actuel est volontaire : ça prend les signalements qui ont au moins une affectation fermée + au moins une affectation ouverte.
Je ferme ce ticket.
A voir dans l'évolution du dashboard & des filtres.
