### ISSUE TITLE
[BO - Partenaire] Role RT impossible

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2234]
https://mattermost.incubateur.net/betagouv/pl/mjfi6dpzctr88jh98zt89do75r

**Comment by mathildepoulpux** [comment]
Dans le ticket d'origine #869 , il était prévu de mettre 3 états dans le filtre "Affectation": 
- `Ouvert chez tous les partenaires` = aucune affectation à closed
- `Fermé chez au moins un partenaire` = 1 affectation à closed ou + (en gros 1 minimum, mais moins que toutes)
- `Fermé pour tous les partenaires` = toutes les affectations closed / le statut du signalement est closed

Hélène a fait ensuite remarquer dans [un commentaire](https://github.com/MTES-MCT/histologe/issues/869#issuecomment-1443320797) que tout ne sera pas fait car "_besoin de le faire vite pour sortir le dashboard. Et pour laisser les 2 autres options (qui ont été faites mais commentées) il faut revoir l'UI car on ne peut pas cumuler les options_."

On a donc sorti uniquement ça, en se disant qu'on fera le reste plus tard.
![image](https://github.com/MTES-MCT/histologe/assets/97226289/ac202d48-6399-45dd-99b3-e1946f4ac063)

----
Un autre ticket a ensuite été créé pour faire le "reste" de ce filtre: #944 
Ce filtre n'a jamais été fait parce que moins prioritaire que d'autres sujets.

---
-> Il est maintenant prévu de finir ce travail dans la grosse story sur la liste des signalements (cf. #950 )

On aura alors un filtre affectation avec les options suivantes : 
- Accepté
- En attente 
- Clôturé par au moins un partenaire 
- Clôturé par tous les partenaires 
- Refusé

On pourra ensuite faire évoluer le dashboard pour que la carte "Fermé chez au moins un partenaire" comprennent les 2 valeurs `Clôturé par au moins un partenaire` et `Clôturé par tous les partenaires`
OU ajouter les signalements `Clôturé par tous les partenaires` dans la carte "Suggestions de clôture" (dans ce cas s'il y a une seule affectation partenaire et que le partenaire à clôturé, le signalement se retrouvera ici)

➡️ **Ma reco** : attendre de faire le travail sur la liste des signalements plutôt que changer le comportement d'un filtre.

**Comment by arnaudchouk** [comment]
ok clair
donc ce ticket est a fermer car non pertinent et rattaché à un autre
