### ISSUE TITLE
[BO - Signalement] Mauvaise identification du déclarant/occupant dans les suivis

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2256]
Va falloir qu'on revoit l'affichage declarant/occupant dans les suivis. Car sur ce signalement fait par un locataire, on a "DECLARANT" au lieu de "OCCUPANT"
https://histologe.beta.gouv.fr/bo/signalements/a6d5a6de-9c79-47c2-b24c-efab409b7911

Par contre, sur la liste de signalements c'est ok 

![image](https://github.com/MTES-MCT/histologe/assets/33071753/43344621-4092-4a8c-80dc-a259e7c8dc5c)

**Comment by emilschn** [comment]
Ah oui, c'est parce que sur le signalement que tu as relevé, la personne est à la fois déclarant et occupant
