### ISSUE TITLE
[FO - Signalement] Modifier les parties bail-dpe et info-procedure pour les tiers

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2275]
prevoir l ajout de doc autre en fin de form pour joindre fiche de signalement
https://www.notion.so/Retours-13-nouveau-form-9824be6ee217455384cfa3e106de543e

Ajouter toutes les questions procédures pour TOUS LES TIERS
Ajouter Ne sait pas en réponse si nécessaire

### To do
Ajouter / modifie les lignes dans [le tableau](https://docs.google.com/spreadsheets/d/12uJcJAWNm9W5R_A6Eh5vwhtLy2ThBNz3CCdkws-ZeIs/edit?gid=0#gid=0)
- Partie "Bail DPE" : lignes 122 / 123 / 127 / 129 / 132 / 133 / 135 / 138 / 141
- Partie "Infos procédure" : lignes 184 / 187 / 188 / 197

**Comment by arnaudchouk** [comment]
Nb: Preciser les contenus / formulations pour les différents profils tiers

**Comment by arnaudchouk** [comment]
ajouté dans le tableau lignes 180; 183 ; 184; 193

**Comment by mathildepoulpux** [comment]
- J'ai modifié "occupant" en "foyer" pour être cohérent avec le reste du formulaire
- J'ai adapté les réponses proposées (colonne J) pour les passer à la 3eme personne + ajouté l'option "je ne sais pas"
- J'ai passé la question "quelle a été la réponse de l'assurance" en facultatif -> je suis pas sûre que les tiers aient cette info

Maintenant c'est bon

**Comment by emilschn** [comment]
@arnaudchouk @mathildepoulpux 
Entre la description et les échanges, j'ai un peu du mal à savoir sur quelles lignes du tableau il faut se baser pour les modifications :)
