### ISSUE TITLE
[BUG Notification] envoyer email de suivi unique quand email occupant et déclarant sont identique

### ISSUE THREAD

**Issue by numew** [MTES-MCT/histologe#2282]
Avec le nouveau formulaire lors d'un dépot par l'occupant son email est dupliqué dans l'email déclarant ce qui provoque un envoi de notification en double sur la boite de l'usager.

**Comment by hmeneuvrier** [comment]
Oui effectivement : 
![image](https://github.com/MTES-MCT/histologe/assets/33071753/b74e2ca5-0025-4808-8547-01578e4b95bf)

Je passe en TODO car c'est simple à corriger, et ça risque de nous faire beaucoup de mails à envoyer si on double tous les mails pour les locataires et les bailleurs occupants
