### ISSUE TITLE
[BO - Signalements] Reprises de données Vosges

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2313]
Extrait de signalements à  importer pour test 
Instructions de téléchargement
Fichiers joints :

    Histologe_DDT88_20240301-1127.zip (110 Mo)
    Histologe_Extraction_Base_DDT88_20240304-1101.ods (133 ko)

2 fichiers, taille totale: 110 Mo.

Les fichiers seront disponibles jusqu'au mercredi 03 avril 2024 à 12:34 (CEST).
Vous pouvez télécharger les fichiers listés ci-dessus en cliquant sur le lien suivant :

**Comment by sfinx13** [comment]
J'ai supprimé le lien @arnaudchouk

**Comment by sfinx13** [comment]
Revue de l'excel: 
- Proposition de s'appuyer sur le type plutôt que le nom
- Absence des noms de fichiers dans le CSV

**Comment by arnaudchouk** [comment]
problème du type c est que tu vas potentiellement en avoir plusieurs du meme type non?
pour les noms de fichiers c est peut etre de ma faute... pour lui faciliter le taf je lui ai dit de mettre la ref de signalement au debut de tous les docs concernes

**Comment by arnaudchouk** [comment]
ok

**Comment by arnaudchouk** [comment]
tu as des exemples ?

**Comment by arnaudchouk** [comment]
@sfinx13 voir mail avec les donnees de prod a recuperer
