### ISSUE TITLE
[Pages publiques] Revoir le menu + création de nouvelles pages

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2321]
### Contexte
Dans le cadre de l'OKR "Embarquement bailleurs", nous avons défini la création de deux nouvelles pages: 
- Page d’information sur la responsabilité locataire / propriétaire ([voir sur Notion](https://www.notion.so/Page-statique-d-information-sur-la-responsabilit-locataire-propri-taire-fe14693a8b144e309995c51fa3066ef8?pvs=4))
- Page d’information sur les aides aux travaux ([voir sur Notion](https://www.notion.so/Page-statique-d-information-sur-les-aides-aux-travaux-pour-propri-taires-4c29ff0097e1496da236620c0392c813?pvs=4))

C'est l'occasion de reprendre le site public pour 
- corriger des éléments d'accessibilité 
- revoir les statistiques publiques
- ajouter la possibilité de récupérer le lien vers sa page de suivi
- revoir la page de contact

### Tâches
- [x] Changement de l'en-tête et du menu en desktop et mobile
- [x] Ajout d'un fil d'ariane
- [x] Revoir les balises title des pages
- [x] Page d'accueil: ajout d'un bloc `J'ai déposé un signalement et je veux accéder à mon suivi` cf.  #2124 
- [x] Création de la page `Quelles aides pour faire des travaux dans mon logement ?`
- [x] Création de la page `Entretien du logement : quelles obligations pour les propriétaires et les locataires ?`
- [x] Edition de la page `Qui sommes-nous ?`
- [ ] Edition de la page `Statistiques` cf. #1550 
- [x] Refonte de la page `Contact` cf. [prototype](https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/screen/d1f4a3f9-c5f6-4ed9-ad29-8665ae32fe17/)

⚠️ Tenir compte des commentaires présents sur [les maquettes des pages](https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/grid).

### Menu et navigation
Dans le header, on garde le lien de connexion vers l'espace pro uniquement.

On utilise l'élément navigation principale avec les items suivants : 
 - Lien direct `Accueil` : lien vers la homepage
 - Lien direct `Signalement` : 
- Menu déroulant `A propos` contenant les éléments suivants : 
   - `Qui sommes-nous ?` :
   - `Entretien du logement : les obligations` 🆕 
   - `Les aides aux travaux` 🆕 
   - `Statistiques d'usage` 
- Menu déroulant `Aide` contenant les éléments suivants : 
    - `Documentation` : lien externe vers https://faq.histologe.beta.gouv.fr/ 
    - `Contact` 

| Page | Title | slug | Lien maquette
| :--- | :--- | :--- | :---
| Accueil | Lutter contre le mal logement - Histologe | / | https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/
| Signalement | Signaler un problème de logement - Histologe | /signalement | Non concerné
| Qui sommes-nous | Qui sommes-nous ? - Histologe | /qui-sommes-nous | https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/screen/e7a6d353-93a7-48ce-b878-035b3189c441/
| Entretien du logement | Logement : les obligations des propriétaires et locataire - Histologe | /entretien-logement-obligations-proprietaire-locataire | https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/screen/39d3cb78-9ee1-410e-8ace-a8e1a2f8bd48/
| Aides aux travaux | Les aides aux travaux pour le logement - Histologe | /aides-travaux-logement | https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/screen/0b3a3bbf-237e-4520-9c74-b730d1517710/
| Statistiques | Statistiques d'usage - Histologe | /statistiques | https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/screen/c61af72f-bd7c-4361-a079-db7b1cba595e/
| Contact | Contacter Histologe | /contact | https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/screen/d1f4a3f9-c5f6-4ed9-ad29-8665ae32fe17/
| Mentions légales | Mentions légales - Histologe | /mentions-legales | Non concerné
| CGU Usager | Conditions générales d'utilisation - Histologe | /cgu | Non concerné
| CGU Agents | Conditions générales d'utilisation de l'espace pro - Histologe | /cgu-agents | Non concerné
| Politique de confidentialité | Politique de confidentialité - Histologe | /politique-de-confidentialite | Non concerné
| Accessibilité | Accessibilité : déclaration de conformité - Histologe | /accessibilite | Non concerné

**Comment by emilschn** [comment]
Manque la mise à jour du DSFR en version 1.11, notamment pour pouvoir avoir les bons picto pour la page d'obligations d'entretien

**Comment by mathildepoulpux** [comment]
Dans la mesure où il y a un ticket dédié ouvert pour les stats (#1550 ), je ferme celui-ci !
