### ISSUE TITLE
[BO] Commande gestion suivi : mise à jour visibilité et suppression

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#2326]
Suite à plusieurs demandes supports, il est temps d'avoir une commande pour changer la visibilité d'un suivi ou le supprimer.
(ça peut aussi être une fonctionnalité BO pour super admin)

**Comment by hmeneuvrier** [comment]
Plutôt une fonctionnalité Super Admin
Et du coup traiter les tickets #2330 et #1721

**Comment by hmeneuvrier** [comment]
Pas supprimé le suivi, mais mettre le texte "Ce suivi a été supprimé par un administrateur le jj/mm/aaa"

**Comment by hmeneuvrier** [comment]
Peut-être le faire en hotfix

**Comment by hmeneuvrier** [comment]
Mergé dans main (et non pas closed)
