### ISSUE TITLE
[FO - Signalement] Détecter les doublons

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2327]
En complément du #87 

### Flow
1. Je suis un usager, je saisis les coordonnées du logement
2. J'indique signaler un problème pour le logement que j'occupe (occupant ou bailleur occupant)
3. Je saisis mes coordonnées
4. Je clique sur suivant
5. On effectue une vérification sur l'adresse postale du logement et mon adresse email et on trouve une correspondance.
    - Le signalement n'est pas archivé 
    - Le statut du signalement est nouveau OU en cours
6. On m'affiche une modale "Ce signalement existe déjà"
7. A. Je clique sur "Recevoir mon lien de suivi"
    B. Je clique sur "Créer un nouveau signalement"

#### Conséquences "Recevoir mon lien de suivi"
- Affichage d'une page de validation avec le titre `Votre lien de suivi a bien été envoyé` et le message `Le lien vers votre page de suivi vous a été envoyé par email. Consultez votre boîte mail et n'oubliez de regarder dans les emails indésirables (spam)`
- Envoi de l'email: Lien vers votre page de suivi (cf. #2124 )
- Signalement non créé
- Brouillon non sauvegardé

#### Conséquences "Créer un nouveau signalement"
- On reprend le parcours du formulaire en passant à l'étape suivante

#### Contenu de la modale
Titre : `Ce signalement existe déjà`
Texte : `Il semblerait que vous ayez déjà déposé un signalement pour le logement situé {{adresse}}. Ce signalement est en cours de traitement.
Vous pouvez le compléter depuis votre page de suivi ou créer un nouveau signalement. 

Souhaitez-vous compléter le signalement existant ou en créer un nouveau ?
message warning : Créer un nouveau signalement pour le même logement risque de ralentir la procédure.

Boutons :
Primaire: `Recevoir mon lien de suivi`
Secondaire: `Créer un nouveau signalement`

https://github.com/MTES-MCT/histologe/assets/97226289/b15777b9-661a-451b-8c26-9b43f24f23c4

### Flow
1. Je suis un tiers déclarant, je saisis les coordonnées du logement
2. J'indique signaler un problème pour quelqu'un d'autre (tiers bailleur, pro, particulier, secours)
3. Je saisis mes coordonnées
4. Je saisis les coordonnées de l'occupant
5. Je clique sur suivant
6. On effectue une vérification sur l'adresse postale du logement, mon adresse email (déclarant) et le nom de l'occupant. On trouve une correspondance
    - Le signalement n'est pas archivé 
    - Le statut du signalement est nouveau OU en cours
7. On m'affiche une modale "Ce signalement existe déjà"
8. A. Je clique sur "Recevoir mon lien de suivi"
    B. Je clique sur "Créer un nouveau signalement"

⚠️ Pour la détection du nom de l'occupant, ce serait bien de traiter les accents. En gros que E = É / È / E, que I = I / Î / Ï etc. Je sais pas si je suis claire ?

#### Conséquences "Recevoir le lien de suivi"
- Affichage d'une page de validation avec le titre `Votre lien de suivi a bien été envoyé` et le message `Le lien vers votre page de suivi vous a été envoyé par email. Consultez votre boîte mail et n'oubliez de regarder dans les emails indésirables (spam)`
- Envoi de l'email: Lien vers votre page de suivi (cf. #2124 ) au déclarant
- Signalement non créé
- Brouillon non sauvegardé

#### Conséquences "Créer un nouveau signalement"
- On reprend le parcours du formulaire en passant à l'étape suivante

#### Contenu de la modale
Titre : `Ce signalement existe déjà`
Texte : `Il semblerait que vous ayez déjà déposé un signalement pour le logement situé {{adresse}} pour le compte de {{nom + prénom occupant}}. Ce signalement est en cours de traitement.
Vous pouvez le compléter depuis votre page de suivi ou créer un nouveau signalement. 

Souhaitez-vous compléter le signalement existant ou en créer un nouveau ?
message warning : Créer un nouveau signalement pour le même logement risque de ralentir la procédure.

Boutons :
Primaire: `Recevoir mon lien de suivi`
Secondaire: `Créer un nouveau signalement`

**Comment by mathildepoulpux** [comment]
Pour simplifier le parcours j'aurais tendance à dire : si l'usager refuse de recevoir le code de suivi pour le signalement existant -> on supprime le brouillon et il reprend le parcours en cours.

Avoir 2 modales d'affilée ça me paraît trop pour l'utilisateur.

**Comment by hmeneuvrier** [comment]
@mathildepoulpux quel que soit le profil, on enregistre le brouillon au moment ou on enregistre les coordonnées du déclarant. C'est donc à ce moment qu'on vérifie l'existence d'un doublon (que ce soit d'un signalement existant ou d'un brouillon). On ne peut donc pas,  pour un tiers déclarant, vérifier le nom et prénom de l'occupant, car on ne les a pas encore enregistré... 

C'est grave ?

**Comment by mathildepoulpux** [comment]
> @mathildepoulpux quel que soit le profil, on enregistre le brouillon au moment ou on enregistre les coordonnées du déclarant. C'est donc à ce moment qu'on vérifie l'existence d'un doublon (que ce soit d'un signalement existant ou d'un brouillon). On ne peut donc pas, pour un tiers déclarant, vérifier le nom et prénom de l'occupant, car on ne les a pas encore enregistré...
> 
> C'est grave ?

Je pense malheureusement que ça va poser problème pour les travailleuses sociales :/

**Comment by hmeneuvrier** [comment]
Vu ensemble, on renvoie la liste des signalements pour un mail déclarant + adresse avec les nom et prénom occupants et les infos complémentaires d'adresse.
Dans la modale on affiche cette liste avec des radio boutons pour choisir de quel signalement ou souhaite recevoir le lien de suivi

**Comment by mathildepoulpux** [comment]
Pour le cas tiers déclarant avec plusieurs signalements à la même adresse : 

![image](https://github.com/MTES-MCT/histologe/assets/97226289/f629df20-1ea8-4ada-a11d-855cc466b224)

Texte : 
Il semblerait que vous ayez déjà déposé plusieurs signalements pour le logement situé {{adresse}}.
Vous pouvez choisir compléter l'un de ces signalements ou de créer un nouveau signalement.

Pour compléter un des signalements ci-dessous, sélectionnez le signalement dans la liste puis cliquez sur le bouton "Recevoir mon lien de suivi".

Souhaitez-vous compléter le signalement sélectionné ou en créer un nouveau ?

message warning : Créer un nouveau signalement pour le même logement risque de ralentir la procédure.

**Comment by hmeneuvrier** [comment]
@mathildepoulpux il y a un cas à la marge que Numa a détecté : 

```
[il y a 1 heure](https://mattermost.incubateur.net/betagouv/pl/3sowqfeo93rdiqna4yw1zfmq6a)

J'ai un cas un peu à la marge, je le signale juste : si je dépose u signalement en tant que tiers [tier@mail.com](mailto:tier@mail.com), pour [locataire@mail.com](mailto:locataire@mail.com). Et que je je vais déposer un signalement en tant que locataire, avec mon nom/prénom email. ca me sort le signalement existant, mais le lien est envoyé sur [tier@mail.com](mailto:tier@mail.com)
```

est-ce qu'il ne faudrait pas également faire un check sur le profil ?

**Comment by mathildepoulpux** [comment]
Euh je sais pas, la solution qui vous paraît la plus adaptée !

**Comment by hmeneuvrier** [comment]
on fait comme Numa propose
