### ISSUE TITLE
[BO - Signalement] Supprimer suivi partenaire

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2330]
2023-180 - dpt Meuse
Supprimer commentaire partenaire (suivii interne) du 11/03 de Mme BONOMI

**Comment by hmeneuvrier** [comment]
https://histologe.beta.gouv.fr/bo/signalements/e34a86b4-f827-4314-b62e-fb9b054d44d0

@arnaudchouk si c'est toujours d'actualité, il faut le passeer en TODO, sinon ça ne sera pas fait avant des mois

**Comment by hmeneuvrier** [comment]
Et un de plus : https://mattermost.incubateur.net/betagouv/pl/smr4m5htpfyhbx9hj3tjo13dzy

**Comment by hmeneuvrier** [comment]
@arnaudchouk suivi supprimé pour https://histologe.beta.gouv.fr/bo/signalements/e34a86b4-f827-4314-b62e-fb9b054d44d0 (la Meuse)

suivi supprimé sur https://histologe.beta.gouv.fr/bo/signalements/a9884bfc-6a2d-49f0-abfd-68bce0baec84

**Comment by arnaudchouk** [comment]
vous etes formidables
