### ISSUE TITLE
[BO] Normaliser les noms des bailleurs publics

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#2340]
Edit : En profiter pour faire une reprise de données afin que les signalement sur bailleurs sociaux ayant un nom correspondant exactement à celui du fichier aient bien le lien bailleur_id

**Comment by arnaudchouk** [comment]
liste par departement : 
https://docs.google.com/spreadsheets/d/1dwpgfqW8quVQjN5dBoUPY2jiHuZ5pUPp/edit?usp=drive_link&ouid=103115680612514741617&rtpof=true&sd=true

**Comment by emilschn** [comment]
### Ce qu'il faut faire pour cette tâche

**En base de donnée**
Ajouter une nouvelle colonne dans bailleur : actuellement il n'y a qu'un nom, mais il faut aussi un nom d'enseigne

**Import**
Prendre le fichier, le transformer en csv et l'importer.
  - garder et compléter ceux qui existent déjà
  - ajouter ceux qui ne sont pas encore dans la BDD
  - refaire la correspondance entre bailleur et territoire (deuxième onglet)

Que fait-on des bailleurs qui ne sont pas dans cette liste et qui n'ont pas de liaison existante avec un signalement ?

**Signalements existants**
Migration pour faire une liaison bailleur_id avec les signalements qui sont sur le parc social et dont le nom correspond à une entrée existante

Est-ce qu'on fait une vérification en local pour faire une migration préalable pour corriger le nom des bailleurs qui ne correspondent à rien ? (= corriger les typos, etc.)


@sfinx13 @hmeneuvrier @numew  si vous avez des avis !

**Comment by numew** [comment]
Je suis en phase, hormis que ce qui ne sont plus dans la liste devrait être supprimés (y compris si des liens existent avec suppression des liens, ca me semble plus propre vu le peu de signalement qui seront concerné)
