### ISSUE TITLE
[Front] Améliorer accessibilité nouveau formulaire

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2341]
https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#topic-11
https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/

Sous-tickets déjà créés :
- [x] [Critère 1.X](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#topic-1) https://github.com/MTES-MCT/histologe/issues/2545
- [x] [Critère 6.X](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#topic-6) https://github.com/MTES-MCT/histologe/issues/2546
- [ ] [Critère 7.X](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#topic-7) https://github.com/MTES-MCT/histologe/issues/2547
- [x] [Critère 8.X](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#topic-8) https://github.com/MTES-MCT/histologe/issues/2543
- [x] [Critère 9.X](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#topic-9) https://github.com/MTES-MCT/histologe/issues/2544
- [x] [Critère 10.2 et 10.3](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#topic-10) https://github.com/MTES-MCT/histologe/issues/3112
- [x] [Critère 10.4](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#topic-10) https://github.com/MTES-MCT/histologe/issues/3113
- [x] [Critère 10.7](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-10-7) https://github.com/MTES-MCT/histologe/issues/2992
- [x] [Critère 10.8](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-10-8) https://github.com/MTES-MCT/histologe/issues/3117
- [x] [Critère 10.11](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-10-11) https://github.com/MTES-MCT/histologe/issues/3118
- [x] [Critère 11.1 à 11.4](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-1) https://github.com/MTES-MCT/histologe/issues/3035
- [ ] [Critères 11.5 à 11.8](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-5) https://github.com/MTES-MCT/histologe/issues/3115
- [x] [Critère 11.9](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-9) https://github.com/MTES-MCT/histologe/issues/3119
- [ ] [Critères 11.10 et 11.11](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-10) https://github.com/MTES-MCT/histologe/issues/3116
- [x] [Critère 11.12](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-12) https://github.com/MTES-MCT/histologe/issues/3120
- [x] [Critère 11.13](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-13) https://github.com/MTES-MCT/histologe/issues/2236
- [x] [Critère 12.7](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-12-7) https://github.com/MTES-MCT/histologe/issues/3184
- [x] [Critère 12.8](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-12-8) https://github.com/MTES-MCT/histologe/issues/2991
- [x] [Critère 12.9](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-12-9) https://github.com/MTES-MCT/histologe/issues/2993
- [x] [Critère 12.8](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-12-8) https://github.com/MTES-MCT/histologe/issues/3091

**Comment by hmeneuvrier** [comment]
https://github.com/MTES-MCT/histologe/issues/2236
