### ISSUE TITLE
[Front - Formulaire] Modifier les adresses hors BAN

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2342]
Plusieurs possibilités d'interface ont été évoquées. Elles ont chacune leur inconvénient.
Dans la mesure où nous allons bientôt utiliser le service RNB, nous faisons le strict nécessaire pour l'instant.

**Etat actuel**
Jusque là, seul le champ de recherche dans la BAN est accessible.
Au clic, il remplit 3 champs grisés avec les détails de l'adresse et 2 champs cachés contenant la géolocalisation et le code INSEE de la commune.

**Modifications**
Les 3 champs grisés deviennent des champs ouverts et modifiables par les utilisateurs.
Si l'utilisateur modifie un des 3 champs : on tag l'adresse comme "saisie manuelle" pour que les agents soient au courant.
Si l'utilisateur modifie le champ Code Postal ou Ville : on refait une recherche dans la BAN à partir de ces deux informations pour mettre à jour le code INSEE.

**Comment by hmeneuvrier** [comment]
cf https://mattermost.incubateur.net/betagouv/pl/bg6gasys5tn1djqmq5cukb6xny

**Comment by emilschn** [comment]
- [ ] Tag enregistré quand on saisit manuellement 
- [ ] Tag affiché en BO quand on saisit manuellement
- [ ] Rechercher code INSEE quand modification du champ Code Postal ou Ville

**Comment by arnaudchouk** [comment]
quand je modifie une adresse sur la fiche de signalement :
*  je ne vois pas de TAG sur le BO
* le point sur carto reste à l'ancienne adresse sélectionnée dans la liste BAN si je saisis l adresse dans le 1er champ ainsi que les suivants sans avoir effacé les infos au prealable - le point est bien reinitialisé si l'adresse saisie initialement dans le 1er champ est effacée avec le clavier avant de saisir nouvelles infos
(suite tests à venir)

**Comment by emilschn** [comment]
@arnaudchouk 
1/ Tu tiens au tag quand c'est modifié côté BO ? Dans ce cas, il faut modifier l'intitulé, parce que pour l'instant c'est `Cette adresse a été éditée manuellement lors de la déclaration.`
C'est important que les partenaires sachent qu'un usager a édité à la main. Mais est-ce que c'est important si c'est un partenaire qui édite ?

2/ OK pour la suppression totale des infos. C'est surprenant qu'il y ait un impact, mais je vais regarder.

3/ Tu n'arrives jamais au bout de la saisie, du coup ?
Tu as pu tester au moins au niveau ergonomique sans problème ?

**Comment by arnaudchouk** [comment]
j ai jamais vu le tag donc je ne sais pas
pour la modif côté BO ca a un seul intéret : indiquer pourquoi sur la carto c est pas au bon endroit - ce qui peut etre utile pour un agent lambda qui n a pas fait la modif - mais ca peut attendre une prochaine version

je n ai jamais pu finir un signalement effectivement
pour l ergonomie 
je propose de modifier le texte : "Votre adresse n'apparait pas dans la liste ? Cliquez sur saisir mon  adresse librement"

**Comment by emilschn** [comment]
J'ai pris en compte tes retours. Il faudra tester avec les modifications quand ce sera validé. On te tient au courant !
