### ISSUE TITLE
[Brevo - mails] Faire les paramétrages indiqués : configuration IP + balise rua

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2347]
Dans la doc Brevo : 

> Depuis le 1er février 2024, Gmail et Yahoo ont mis en place de nouvelles exigences en matière d'expéditeurs d'emails afin de protéger plus efficacement les boîtes de réception des utilisateurs contre les spams tout en garantissant la réception des emails légitimes.

Sur l'interface Brevo, ces 2 messages : 
![image (1)](https://github.com/MTES-MCT/histologe/assets/97226289/a75a516a-a9d5-4119-8867-fa3cbd322921)
![image](https://github.com/MTES-MCT/histologe/assets/97226289/6ba727e2-c857-4e4b-b6c1-5be98e73a1f6)

Voir comment configurer l'adresse IP et vérifier l'authentification du domaine. Les infos sont ici : 
https://help.brevo.com/hc/fr/articles/14925263522578-Se-pr%C3%A9parer-aux-nouvelles-exigences-de-Gmail-et-Yahoo-en-mati%C3%A8re-d-exp%C3%A9diteur-d-emails

➡️ Voir aussi #2213

**Comment by sfinx13** [comment]
Ajout des entrées DNS recommandé par brevo via notre gestionnaire de domaines [alwaysdata.com](https://admin.alwaysdata.com/)

* Domaine histologe.fr OK
* Domaine histologe.beta.gouv.fr OK
* IP dédié OK
![image](https://github.com/MTES-MCT/histologe/assets/5757116/80e6e002-6c8e-49c3-9029-3de22d430181)
