### ISSUE TITLE
[BO - Partenaires] Archiver les mails partenaires à la suppression d'un partenaire

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#2348]
https://mattermost.incubateur.net/betagouv/pl/8tfiw4zdf7gfzp6pb7d13g4mpr

Ajouter le suffixe `archived.xxxxxxx@domaine.com`

Pour info date de création et de mise à jour absente pour les partenaires

**Comment by numew** [comment]
doublon du #2035
