### ISSUE TITLE
[BO - Fiche signalement] Modifier les labels dans la composition du logement

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2361]
Pour plus de clarté pour les partenaires, modifiés les labels des désordres liés à la composition du logement dans la fiche signalement dans le BO.

Cf. [Le tableau nouvel algo](https://docs.google.com/spreadsheets/d/12uJcJAWNm9W5R_A6Eh5vwhtLy2ThBNz3CCdkws-ZeIs/edit#gid=1647854560) - Lignes 49 à 55 (éléments surlignés en jaune)

Slug critère | Précision
:-- | :--
desordres_type_composition_logement_cuisine | Pas de cuisine dans le logement mais accès à une cuisine collective
desordres_type_composition_logement_cuisine | Aucune cuisine (ni dans le logement, ni collective)
desordres_type_composition_logement_douche | Pas de SDB dans le logement mais accès à des douches collectives
desordres_type_composition_logement_douche | Aucune SDB ou douche (ni dans le logement, ni collective)
desordres_type_composition_logement_wc | Pas de WC dans le logement mais accès à des WC collectifs
desordres_type_composition_logement_wc | Aucun WC (ni dans le logement, ni collectifs)
desordres_type_composition_logement_wc | Les WC et la cuisine sont dans la même pièce

**Comment by hmeneuvrier** [comment]
Ok en prod.
Fixtures en PR
