### ISSUE TITLE
[FO - Form - nouvelle étape] Renvoyer les signalements "vides" vers une nouvelle page

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2363]
1. Je suis usager
2. Je renseigne un signalement sans aucun désordre
3. A la validation, on observe que : 
    - Aucun désordre n'est sélectionné dans logement et/ ou bâtiment
    - Le score de criticité = 0 
4. Je peux valider mon signalement
-> Cela pose un problème puisque ce sera forcément considéré comme un signalement hors PDLHI 

**Solution :** renvoyer l'usager vers une page l'invitant à compléter son signalement ou l'abandonner.

### Parcours
1. Je complète mon signalement 
2. Je valide mon dépôt
3. Vérif du draft : aucun désordre + criticité = 0
4. J'accède à une page "signalement incomplet"

### Page signalement incomplet 
Même modèle que la page envoi, sans le bouton je donne mon avis

_Titre :_ Votre signalement est incomplet
_Texte :_ 
D'après les informations saisies, nous ne sommes pas en mesure de valider votre signalement : aucun désordre n'a été renseigné pour ce signalement.
Les signalements sans désordre ne peuvent pas être pris en charge par notre service.

Nous vous invitons à vérifier votre signalement et compléter les informations dans les parties : 
- Type et composition du logement
- Désordres

Cliquez sur le bouton ci-dessous pour compléter votre signalement en renseignant au moins un désordre.

_Boutons :_ 
- Principal : `Compléter mon signalement` -> renvoi vers la partie "type et composition"
- Secondaire : `Abandonner mon signalement` -> le draft est archivé

**Comment by hmeneuvrier** [comment]
TODO : 

- [ ] ajouter une nouvelle page dans les json
- [ ] remplacer le `"action": "goto.save:confirmation_signalement",` du bouton d'enregistrement,  par une action spéciale
- [ ] dans `SignalementDraftManager` ne faire  $`signalement = $this->dispatchSignalementDraftCompleted($signalementDraft);` qu'après s'être assuré d'avoir des désordres et un score > 0, sinon renvoyer une information pour orienter l'action spéciale sur la nouvelle page

**Comment by mathildepoulpux** [comment]
1. Je suis locataire
2. Je saisis un signalement sans désordre
3. J'accède à la page "signalement incomplet"
4. Je retourne sur le formulaire et j'ajoute des désordres"
5. Lorsque j'arrive sur la page de récap des désordres, j'ai toujours les boutons "Je renseigne des désordres" et "Je passe à la suite", ce qui crée de la confusion
![image](https://github.com/MTES-MCT/histologe/assets/97226289/065ef413-25b8-414f-ad03-3754bb0cb0a0)

--> Il faudrait que, quand j'ai renseigné des désordres", j'ai les boutons "suivant" et "précédent"
