### ISSUE TITLE
[QA] Interdire (ou supprimer) les emojis dans les champs textes

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2370]
Le signalement https://histologe.beta.gouv.fr/bo/signalements/f4d3cdca-6945-4125-b149-334ef9bc67ea posssédait un emoji dans le champ detail

Suite à la tempête, j'ai un arbre qui est tombé sur la maison 🏠 qui engendre un logement non conforme. 

Quand on essayait d'affecter un partenaire ARS on ne pouvait pas. Erreur Sentry correspondante : 

https://sentry.incubateur.net/organizations/betagouv/issues/92686/?environment=prod&project=61&query=is%3Aunresolved&referrer=issue-stream

Uncaught PHP Exception Symfony\Component\Messenger\Exception\TransportException: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x8F\xA0 q...' for column 'body' at row 1" at DoctrineSender.php line 48

src/Messenger/InterconnectionBus.php in App\Messenger\InterconnectionBus::dispatch at line 26
In App
    public function dispatch(Affectation $affectation): void
    {
        /** @var DossierMessageFactoryInterface $dossierMessageFactory */
        foreach ($this->dossierMessageFactories as $dossierMessageFactory) {
            if ($dossierMessageFactory->supports($affectation)) {
                $this->messageBus->dispatch($dossierMessageFactory->createInstance($affectation));
            }
        }
    }
}

Supprimer les emojis dans les champs détails ? 
Ou juste ne pas les mettre dans l'interconnection ?

**Comment by hmeneuvrier** [comment]
Traiter avec #2132

Vérifier export pdf et export csv

**Comment by hmeneuvrier** [comment]
Autre exemple https://histologe.beta.gouv.fr/bo/signalements/70891bce-1b87-4f85-a29e-09360945d79b

Avant modif : `'espère que vous aller me donner un logement au plus vite svp 🙏 `

**Comment by sfinx13** [comment]
## Cause
J'ai fait ma petite enquête, le problème viendrait du charset `UTF8` définit dans la table messenger_messages 
**(utf8mb3_unicode_ci)** qui n'accepte pas les emoji qui est différent que celui de la table de suivi **(utf8mb4_unicode_ci)**

[D'ailleurs il n'y pas de jeu de caractère par défaut défini dans la conf doctrine](https://symfony.com/doc/current/reference/configuration/doctrine.html#:~:text=charset%3A%20%20%20%20%20%20%20%20%20%20%20%20%20%20utf8mb4)
## Pré-requis
- [ ] Demander à esabora si l'envoi d'emoji ne pose pas de problème ? 

## Solution
1. Il faudrait définir le charset dans la conf doctrine pour ne pas laisser la base de donnée la définir à notre place, faisons comme dans la doc `utf8mb4`c'est celle ci prend en charge le plus de caractère dont les emoji


3. Ajouter une migration sur la table migration_messages
`ALTER TABLE messenger_messages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

## Exemple

On arrive à insérer un emoji en base
![image](https://github.com/MTES-MCT/histologe/assets/5757116/2912083a-942e-4d53-8ef8-671b91bfa2bf)

**Comment by sfinx13** [comment]
Message de Jean Pierre
> Bref, je ne suis pas trop chaud pour recevoir ce type de caractères via les WS.
Si vous pouviez au moins les épurer avant envoi, cela me semblerait préférable.
