### ISSUE TITLE
[FO - page aides] Ajouter icône lien externe

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2387]
Sur la page aides, il manque l'icône external-link-line après les liens externes
![image](https://github.com/MTES-MCT/histologe/assets/97226289/a5573776-4e63-435e-a62b-d8aa1141223a)

-> il faudrait ajouter cette icône.
cf. [la maquette](https://xd.adobe.com/view/2ed33410-4ad7-4160-bfae-7aa1e3e3c1d0-7b80/screen/0b3a3bbf-237e-4520-9c74-b730d1517710/specs/)

![image](https://github.com/MTES-MCT/histologe/assets/97226289/335bd503-14e8-4995-af4d-e71e7aed36a8)

**Comment by hmeneuvrier** [comment]
Conflit avec une css de tooltip https://mattermost.incubateur.net/betagouv/pl/6i56ude3i7nx3petou3y6xfzao

**Comment by mathildepoulpux** [comment]
J'ai pas accès à ce message
