### ISSUE TITLE
[FO - page contact] Modifier le title

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2389]
Le title de la page /contact est `Contact - Histologe`
Ca devrait être `Contacter Histologe`

cf. #2321

**Comment by hmeneuvrier** [comment]
@mathildepoulpux c'est très important ?
Car dans chaque page on définit la première partie du titre de la page (le `{% block title %}`) et dans la page globale on fait un 

`<title>{% block title %}{% endblock %} - {{ platform.name }}</title>`

Donc ça fait faire un cas particulier dans le code pour un détail...
