### ISSUE TITLE
[QA] Déplacer les json de formulaire vers un autre emplacement

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#2393]
Aujourd'hui il se trouve sur [tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json](https://github.com/MTES-MCT/histologe/blob/develop/tools/wiremock/src/Resources/Signalement/questions_profile_locataire.json)

Nouvel emplacement `data/json/*.json` ?

Puis ignorer le dossier `tools` pour ne pas l'embarquer pour le déploiement via `.slugignore`

**Comment by hmeneuvrier** [comment]
Pour moi plutôt `assets/json/*.json`

ok pour toi @sfinx13 ?
