### ISSUE TITLE
[Front / BO] Champ accompagnement par travailleur social : impossible de sélectionner "Non"

### ISSUE THREAD

**Issue by numew** [MTES-MCT/histologe#2403]
Dans le formulaire à la question concernant l'accompagnement par un travailleur social si je sélectionne "Non" (en tant que locataire déclarant)

Dans le BO on perd la valeur, rien n'est affiché et si je tente de modifier le bloc "Situation du foyer"
- Impossible car le champ accompagnement est obligatoire
- Impossible de sélectionner non (car la valeur 0 est transformé en null par le déserialiseur)

Il semble que dans le BO on utilise toujours le champ "travailleur_social_accompagnement_declarant" et jamais la version "travailleur_social_accompagnement"

Corrections à faire 
- Dans le BO transformer les valeur 0 et 1 de ce champ en "oui"/"non" (éditer le template d'affichage en conséquences)
- Faire en sorte qu'un seul champ soit conservé à la transformation d'un brouillon en signalement (supprimer "travailleur_social_accompagnement") ?
- Faire une migration pour corriger les existants ?

**Comment by sfinx13** [comment]
Après investigation on utilise pas la bonne valeur dans le BO
`travailleur_social_accompagnement_declarant` est la case à cocher du screenshoot, la question est posé uniquement aux tiers pro

![image](https://github.com/MTES-MCT/histologe/assets/5757116/fde3b15c-2321-4064-8428-abc2ad037007)


Il faudrait donc utiliser `travailleur_social_accompagnement` dans le BO 

Les pro du BO remplissait cette valeur en pensant répondre à `Accompagnement par un ou une travailleuse sociale`

Comme la valeur `travailleur_social_accompagnement_declarant` n'a jamais été affiché de manière intentionnelle, on peut laisser comme ça et poser la question à Mathilde avant d'envisager une action (la seule que je vois c'est de remettre ce champs à null)
