### ISSUE TITLE
[BO - Fiche signalement] Ajouter info travailleur / travailleuse sociale

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2428]
Pour tiers déclarant pro
A la question `Cochez cette case si vous êtes la personne accompagnant le foyer` (travailleur_social_accompagnement_declarant) 
Si case cochée, on affiche l'info dans le bloc "Coordonnées du tiers déclarant", sur la ligne "Lien", on affiche la mention `Travailleur ou travailleuse sociale`

![image](https://github.com/MTES-MCT/histologe/assets/97226289/fecb3e25-42ac-4d64-b0b7-5358d8680d8e)

Remarque de Hélène : 
à noter côté tech : il faut faire une migration je pense

**Comment by numew** [comment]
@mathildepoulpux Aujourd'hui on a déja un lien "Pro" pour ce cas : 
![Screenshot 2024-04-09 at 17-27-08 Histologe](https://github.com/MTES-MCT/histologe/assets/7130780/ae112a11-2b26-484e-852c-4273b57b89ca)

Pour le cas des personnes ayant coché la case je rajouterais entre parenthèse "Travailleur social accompagnant", ca te va ?

**Comment by mathildepoulpux** [comment]
Oui !
