### ISSUE TITLE
[FO - page de suivi] Photos ajoutées au dépôt non affichées avant validation du signalement

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2436]
Je suis tiers déclarant
J'ai déposé un signalement avec photos
![image](https://github.com/MTES-MCT/histologe/assets/97226289/b8cec242-15fd-43f3-a5fd-3cc50c8acb1b)

Je valide le dépôt signalement
J'accède à la page de suivi, aucune photo visible
![image](https://github.com/MTES-MCT/histologe/assets/97226289/35681eef-ab14-4c2c-abd4-3b495bd7719d)

Pourtant, dans le BO, je vois bien les photos avant de valider le signalement
![image](https://github.com/MTES-MCT/histologe/assets/97226289/981a58ad-bf4f-4941-b5e9-f39b5b46a5c9)

Une fois le signalement validé, les photos sont visibles sur la page de suivi
![image](https://github.com/MTES-MCT/histologe/assets/97226289/fc921c5a-7b8a-4d21-87ec-e0a819c88c8c)

➡️ Comportement attendu : les photos et documents que j'ai ajoutés depuis le formulaire de dépôts devraient être visibles sur la page de suivi dès le dépôt du signalement.

**Comment by hmeneuvrier** [comment]
Je ne reproduis pas en local. Je viens de tester sur la staging et j'ai reproduis quand j'ouvre directement ma page de suivi, mais si je la rafraichis au bout de quelques secondes, je vois bien mes photos. C'est du à l'enregistrement asynchrone des photos, c'est normal on ne peut pas y faire grand-chose.
ou alors @mathildepoulpux remplacer le texte `Aucune photo à afficher` par un truc du genre `Aucune photo à afficher, si vous avez mis des phots dans votre signalement, rafraichissez la page pour les voir apparaitre` ?

**Comment by mathildepoulpux** [comment]
Ah oui remplacer le texte c'est pas mal !
