### ISSUE TITLE
[BO - Signalement] Photos non rattachées aux désordres

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2437]
Je suis tiers déclarant
J'ai déposé un signalement avec des photos rattachées au désordre `L'installation est dangereuse : les fils sont dénudés, les prises ne tiennent pas dans les murs, etc.`

![image](https://github.com/MTES-MCT/histologe/assets/97226289/b8cec242-15fd-43f3-a5fd-3cc50c8acb1b)

Dans le BO, les photos apparaissent mais ne sont pas rattachées au désordre en question

![image](https://github.com/MTES-MCT/histologe/assets/97226289/e2dfcaa5-b045-4227-9696-bbd2df790a06)

➡️ Comportement attendu : que les photos soient rattachées aux désordres auquel elles ont été associées sur le formulaire

**Comment by hmeneuvrier** [comment]
Effectivement, je reproduis, les File n'ont pas de desordreSlug.
Voici le payload du draft : 

`"desordres_logement_electricite_installation_dangereuse": 1,
    "desordres_logement_electricite_installation_dangereuse_details_photos_upload": [
        {
            "key": "photos",
            "file": "pigeon-66179d002b7c1.jpg",
            "titre": "pigeon.jpg",
            "filePath": "tmp/pigeon-66179d002b7c1.jpg"
        },
        {
            "key": "photos",
            "file": "pigeon-nid-appartement-66179d09b2c48.jpg",
            "titre": "pigeon_nid_appartement.jpg",
            "filePath": "tmp/pigeon-nid-appartement-66179d09b2c48.jpg"
        }
    ]
}
`

**Comment by hmeneuvrier** [comment]
D'après une rapide vérification sur Metabase, c'est depuis le 4 avril qu'il n'y a plus de desordreSlug pour les files

**Comment by hmeneuvrier** [comment]
Ok donc ça vient des changements dans le setDesordreSlug de l'entité File fait sur le commit https://github.com/MTES-MCT/histologe/commit/757f67028975867568c13180c0a0bc7e6a090efa#diff-efb705be4240485a34a0a7cca55154c6f3c2e2c8e0f7706b504b260ec3f5d9f6

pour la mise en place des suivis asynchrones. MEP 2.1.0 du 4 avril.
On n'a pas le signalement quand on traite l'enregistrement du fichier... donc il faut corriger ça sans tout péter...
et aussi faire une migration pour tous les signalements déposés depuis la MEP
