### ISSUE TITLE
[BO - Signalement - Visite] Ajouter suppression de photo de visite

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2448]
C'est un oubli total dans les specs, désolée 😭 

Il faudrait ajouter la possibilité de supprimer des photos de visite, au cas où il y a des erreurs.

**Flow**
- Clic sur le bouton de suppression
- Affichage d'une modale de validation:
- Titre : Supprimer la photo
- Texte: Vous êtes sur le point de supprimer la photo {{nom}}. Une fois supprimée, la photo ne sera plus visible dans le signalement. Si vous avez partagé la photo à l'usager, il n'y aura plus accès. Voulez-vous vraiment supprimer cette photo ?
- Zone d'action: boutons `Supprimer la photo` et `Annuler`
- Clic sur supprimer

**Conséquences**
- Retour sur la page signalement avec le success message `La photo a bien été supprimée.`
- Changements visibles dans la liste des photos de visite

NB : ça peut être fait après la mise en ligne si jamais

**Comment by hmeneuvrier** [comment]
Reste à faire : 

- [ ] comprendre pourquoi le bouton supprimer ne fait rien et pourquoi le bouton annuler et fermer suppriment le fichier
- [ ] harmomniser les noms et déplacer la modmale à côté de celle d'édition
