### ISSUE TITLE
[BO - Signalement] Impossible d'ajouter des photos à une visite

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2449]
Je suis agent
Je traite une signalement qui a déjà une visite avec des photos
Je crée une 2eme visite passée
Je veux ajouter des photos
Au moment de valider la modale
J'ai cette erreur
![image](https://github.com/MTES-MCT/histologe/assets/97226289/7ae0872f-5da2-42d3-a07c-e689c93de3ce)

-> J'ai testé plusieurs fois en SA et agent, sur des signalements avec d'autres visites et sans autre visite. J'ai toujours cette erreur.
C'est étrange parce que ce matin j'ai réussi sans problème 🤷‍♀️

**Comment by hmeneuvrier** [comment]
Pas reproduit en local ni sur staging ni sur la review app...

**Comment by hmeneuvrier** [comment]
@mathildepoulpux ok pour toi si je ferme ?

**Comment by mathildepoulpux** [comment]
Oui ! Comme dit c'était un truc étrange, j'ai pas reproduit non plus
