### ISSUE TITLE
[FO / BO - Signalement] Auteur document & photo non identifié quand ajout depuis formulaire

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2450]
- Je suis locataire
- Je dépose un signalement
- Dans le form, j'ajoute mon bail et mon état des lieux
![image](https://github.com/MTES-MCT/histologe/assets/97226289/52632f0b-0784-4218-b80b-15b3bc4fcd66)
- Je valide le signalement
- Dans le BO, les documents apparaissent mais il n'y a pas l'auteur du document
![image](https://github.com/MTES-MCT/histologe/assets/97226289/2114e3a9-8205-4d8f-b90d-26365a37e057)

Peut-être que ça a un lien avec le #2433 ?

**Comment by mathildepoulpux** [comment]
Je n'ai pas d'auteur non plus sur les photos ajoutées depuis le form

**Comment by mathildepoulpux** [comment]
Ah non pardon, j'ai bien le type de document, par contre je n'ai pas l'auteur (dans mon test, l'occupant du logement)
![image](https://github.com/MTES-MCT/histologe/assets/97226289/f173fa27-3eaf-42f6-a8ce-140283d63129)

**Comment by sfinx13** [comment]
@mathildepoulpux 
> Je n'ai pas d'auteur non plus sur les photos ajoutées depuis le form
Une reprise est possible vu avec @hmeneuvrier 
Peu de temps après la MEP que cette régression est apparu. 
On avait pas vérifier l'auteur des photos :-( (l'enthousiame de la MEP :-D)
La dépôt se fait en deux temps depuis https://github.com/MTES-MCT/histologe/issues/2240 
- Etape 1 : Soumission du formulaire
- Etape 2 : Envoi des photos

**Comment by mathildepoulpux** [comment]
Du coup ce sera corrigé pour les nouveaux dépôts avec la MEP de l'espace documentaire ?

**Comment by sfinx13** [comment]
> Du coup ce sera corrigé pour les nouveaux dépôts avec la MEP de l'espace documentaire ?

Oui ça sera déployé en même temps mais on exécutera le script de mise à jour pour les fichiers avant d'activer l'espace documentaire.
