### ISSUE TITLE
[Technique] Acheter un ou plusieurs noms de domaine proches du nom de domaine du service

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2468]

**Comment by arnaudchouk** [comment]
a priori le typosquatting est pris en charge par tristan @sfinx13

**Comment by hmeneuvrier** [comment]
Tristan Robert
[10:45 AM](https://mattermost.incubateur.net/betagouv/pl/xiu4jfhodig59cs3h1urgh8uza)

Salut. Pas au courant ou alors incompréhension. On peut le faire sur .developpement-durable.gouv.fr ou .logement.gouv.fr mais sur .beta.gouv.fr on n'a pas de marché pour le faire. Le plus rapide pour vous est de passer par les frais devs.
Arnaud Choukroun
[10:50 AM](https://mattermost.incubateur.net/betagouv/pl/qwq3cikhki83zchp1cgndmw6oh)

Salut
Je pense qu'il  a une incomprehension, mais chez nous (dsl)
Dans le cadre de la bascule stop punaises, il a fallu qu on se protege du typosquatting et effectivement tu as pris le lead sur ce point
dans le cadre de l homologation securite qui nous est demandée en urgence pour Histologe, a priori ce besoin est également pointé
est ce que la démarche est différente ? 
Tristan Robert
[10:52 AM](https://mattermost.incubateur.net/betagouv/pl/pfa8o7apsifmpjz3zj9e78ktxr)

oui car domaine .beta.gouv.fr 
Arnaud Choukroun
[10:53 AM](https://mattermost.incubateur.net/betagouv/pl/y1gkhqyiufnipfcaj86mmzjtny)

ok - et dans ce cas, il y a des reco particulieres pour eviter le typo squatting des domaines beta ?
Tristan Robert
[11:08 AM](https://mattermost.incubateur.net/betagouv/pl/4n39xdk6jprndewujqrazcondy)

il faut acheter des domaines proches. Vous pouvez demander à Dossier facile: ils l'ont fait pour leur sous domaine .beta.gouv.fr puis qaund ils ont migré vers .logement.gouv.fr c'est le ministère qui a pris en charge l'achat des domaines proches.

**Comment by hmeneuvrier** [comment]
Fabien Leborgne
[12:43 PM](https://mattermost.incubateur.net/betagouv/pl/9q3eacr9ftdmprk1jyi58qs1dr)

Hello Hélène,
D'après ce que je comprends, vous allez aussi passer en .gouv, c'est une très bonne nouvelle !
Pour réserver des noms de domaines, il faut ouvrir un ticket sur redmine sur le portail : https://portail-support.din.developpement-durable.gouv.fr/

Nous avons eu plusieurs interlocuteurs sur la demande, elles ont été traité par SG/DNUM/MSP/DIS/GO/PST. Je vous recommande de séparer vos demandes: Par exemple, de faire un ticket pour demander la reservation des noms de domaines pour éviter le cybersquattage et de faire une demande séparée pour le nom de domaine en .gouv.

NB:  Une demande de notre intrapreneur à la DICOM avait été faite en amont pour obtenir l'autorisation d'avoir le nom de domaine "dossierfacile.logement.gouv.fr"

Si tu as besoin de contact plus direct, nous avions été en relation avec RIES Léa la majorité du temps et avions aussi eu un point avec KUSTYAN Frédéric (Chef du groupe opérations) et DESVEAUX Sylvain (Administrateur de systèmes et réseaux au sein du Groupe Infrastructure et Réseau-Prestataire). :sweat_smile: 



Hélène Meneuvrier
[3:11 PM](https://mattermost.incubateur.net/betagouv/pl/n5knpj4e37dp98g61uka56c5uh)

Salut Fabien,
merci beaucoup pour ta réponse ! 
Je me suis un peu mal exprimée car nous ne passons pas encore en .gouv, mais c'est une tâche que nous devons faire avant un potentiel audit de sécurité.
Donc pour éviter le cybersquattage, même tant qu'on reste en beta.gouv.fr tu penses qu'il faut passer par ce portail ? Tristan nous a dit que nous devons les acheter nous-mêmes et les refacturer après.
Est-ce que tu as des conseils sur les noms de domaine à acheter ? Lesquels avez-vous choisi pour dossierfacile ?




Fabien Leborgne
[3:16 PM](https://mattermost.incubateur.net/betagouv/pl/o5bddtm3iffcufyby84wu695wo)

Le plus simple, est effectivement d'acheter vous-même et d'ensuite de refacturer c'est ce que nous avons fait au début de DF. Toutefois, c'est plus agréable pour nous de ne pas avancer les frais et cela évite également d'avoir à gérer les departs eventuel des freelances.
Nous avons pris les domaines suivants:
dossierfacile.fr
dossier-facile.fr
dossier-facile.com
dossierfacile.com
dossier-facile.org
dossierfacile.org

**Comment by hmeneuvrier** [comment]
@arnaudchouk ci-dessus ma conversation avec Fabien Leborgne de DossierFacile. Que fait-on de ça ? Est-ce qu'on achète les noms de domaine ? Est-ce qu'on demmande à Damien ? Est-ce qu'on laisse de côté pour l'instant ?

**Comment by arnaudchouk** [comment]
@hmeneuvrier donc il faudrait acheter histologe.com/.org/.fr
Si c est plus simple on peut demander à Damien sa carte

**Comment by hmeneuvrier** [comment]
On a déjà histologe.fr
peut-être histologe.com
et il faudrait peut-être acheter histologe.org

**Comment by sfinx13** [comment]
J'ai acheté le .org je ferme tout est bon
