### ISSUE TITLE
[BO - Signalement] Reprise de données Pas de Calais

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2481]
Data ici
https://docs.google.com/spreadsheets/d/16SZpYcek3QxhyIfnZCVRVlY5RPzWxDZo/edit?usp=drive_link&ouid=103115680612514741617&rtpof=true&sd=true

**Comment by numew** [comment]
Quelques erreurs sur les motifs de cloture (que je peux corriger à la main c'est pas méchant) : 
- "Absence de réponse" not found on 5 signalement(s)                                              
- "abandon de procédure" not found on 4 signalement(s)                                            
- "Départ ocuppant" not found on 2 signalement(s)                                                 
- "Travaux faits en cours" not found on 2 signalement(s) 

Pas mal d'erreur sur les partenaires : 
- Partner "CAF - CA LENS LIEVIN - LIEVIN" not found on 2 signalement(s)                                        
- Partner "AUCHEL – CABBALR (Béthune-Bruay" not found on 2 signalement(s)                                      
- Partner "Artois-Lys Romane)" not found on 11 signalement(s)                                                  
- Partner "CABBALR (Béthune-Bruay" not found on 11 signalement(s)                                              
- Partner "Artois-Lys Romane) – ARS – BETHUNE" not found on 2 signalement(s)                                   
- Partner "Artois-Lys Romane) – HERSIN COUPIGNY" not found on 2 signalement(s)                                 
- Partner "CC7V – ARS – HESDIN" not found on 2 signalement(s)                                                  
- Partner "CC7V –HESDIN" not found on 2 signalement(s)                                                         
- Partner "Artois-Lys Romane) – HOUDAIN" not found on 2 signalement(s)                                         
- Partner "CA LENS LIEVIN – LENS" not found on 2 signalement(s)                                                
- Partner "CAF – AIRE SUR LA LYS" not found on 2 signalement(s)                                                
- Partner "CAF – CAPSO" not found on 6 signalement(s)                                                          
- Partner "CUA - ARRAS" not found on 2 signalement(s)                                                          
- Partner "BEAURAINS - CUA" not found on 2 signalement(s)                                                      
- Partner "CAF - CA2BM" not found on 6 signalement(s)                                                          
- Partner "MDS LENS – BEUVRY - CABBALR (Béthune-Bruay" not found on 2 signalement(s)                           
- Partner "CAF - BILLY MONTIGNY - CA LENS LIEVIN" not found on 2 signalement(s)                                
- Partner "BOULOGNE SUR MER (Mairie/SCHS) - CAB" not found on 2 signalement(s)                                 
- Partner "BRIMEUX - CC7V" not found on 2 signalement(s)                                                       
- Partner "BRUAY LA BUISSIERE - CAF" not found on 2 signalement(s)                                             
- Partner "CARVIN – CA HENIN CARVIN" not found on 2 signalement(s)                                             
- Partner "CAF - CC7V - ARS" not found on 2 signalement(s)                                                     
- Partner "CUCQ - CA2BM" not found on 2 signalement(s)                                                         
- Partner "ARS - DESVRES" not found on 3 signalement(s)                                                        
- Partner "DIVION - CABBALR (Béthune-Bruay" not found on 2 signalement(s)                                      
- Partner "CA HENIN CARVIN - DROCOURT" not found on 2 signalement(s)                                           
- Partner "CA LENS LIEVIN - ARS - ELEU dit LEAUWETTE" not found on 2 signalement(s)                            
- Partner "Artois-Lys Romane) - ESSARS" not found on 2 signalement(s)                                          
- Partner "CA HENIN CARVIN - HENIN-BEAUMONT" not found on 5 signalement(s)                                     
- Partner "CAF - CA HENIN CARVIN - HENIN-BEAUMONT" not found on 2 signalement(s)                               
- Partner "ARS – ISBERGUES – CABBALR (Béthune-Bruay" not found on 2 signalement(s)                             
- Partner "CAF - ISBERGUES - CABBALR (Béthune-Bruay" not found on 2 signalement(s)                             
- Partner "LENS - CA LENS LIEVIN" not found on 4 signalement(s)                                                
- Partner "CA LENS LIEVIN - LENS" not found on 2 signalement(s)                                                
- Partner "CA LENS LIEVIN - LIEVIN" not found on 2 signalement(s)                                              
- Partner "LILLERS - CABBALR (Béthune-Bruay" not found on 2 signalement(s)                                     
- Partner "Artois-Lys Romane) - LORGIES" not found on 2 signalement(s)                                         
- Partner "Artois-Lys Romane) - LOZINGHEM" not found on 2 signalement(s)                                       
- Partner "CUA - MAROEUIL" not found on 2 signalement(s)                                                       
- Partner "CA LENS LIEVIN – MERICOURT" not found on 2 signalement(s)                                           
- Partner "Artois-Lys Romane) - NOEUX LES MINES" not found on 2 signalement(s)                                 
- Partner "NOYELLES LES VERMELLES - CABBALR (Béthune-Bruay" not found on 2 signalement(s)                      
- Partner "CA2BM - CAF" not found on 2 signalement(s)                                                          
- Partner "CA HENIN CARVIN - ROUVROY" not found on 2 signalement(s)                                            
- Partner "CAF – SAILLY SUR LA LYS - ARS" not found on 2 signalement(s)                                        
- Partner "SAINT EITENNE AU MONT - CAB" not found on 2 signalement(s)                                          
- Partner "CUA - SAINT LAURENT BLANGY" not found on 2 signalement(s)                                           
- Partner "SAINT POL SUR TERNOISE – CAF" not found on 2 signalement(s)                                         
- Partner "SALLAUMINES – ARS" not found on 2 signalement(s)                                                    
- Partner "CAF - CUA - THELUS" not found on 2 signalement(s)                                                   
- Partner "CUA - THELUS" not found on 2 signalement(s)                                                         
- Partner "CA LENS LIEVIN - ARS" not found on 2 signalement(s)                                                 
- Partner "WAMBERCOURT - CC7V" not found on 2 signalement(s)                                                   
- Partner "CA LENS LIEVIN - WINGLES - CAF" not found on 2 signalement(s)                                       
- Partner "CA LENS LIEVIN - WINGLES" not found on 2 signalement(s)                                             
- Partner "LIBERCOURT - CA HENIN CARVIN" not found on 2 signalement(s)                                         
- Partner "CAPSO - CAF" not found on 41 signalement(s)

**Comment by arnaudchouk** [comment]
ok j ai compris - le "-" dans les partenaires agit comme séparateur 
a priori pris 1 par 1 ils y sont tous

**Comment by numew** [comment]
Commande à passer suite à la prochaine mise en prod
