### ISSUE TITLE
[Documentation] Note Eval Besoin RSSI

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2483]
remplir doc
https://docs.google.com/document/d/1bli2dQO1Qki5_lYcb2oQFWOSSoINp1xb/edit?usp=drive_link&ouid=103115680612514741617&rtpof=true&sd=true

**Comment by arnaudchouk** [comment]
c est complété ? ou faut il que je jette un oeil avant envoi ? @hmeneuvrier

**Comment by hmeneuvrier** [comment]
@arnaudchouk il faut que tu complètes les trucs admin en bleu sur les 7 premières pages
