### ISSUE TITLE
[BO - Fiche usager - modale ajout documents] Modifier le texte

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2504]
Suite à des retours, on a modifié l'intitulé de la partie `Documents partenaires` en `Documents liés à la procédure`.
Il faut le répercuter dans le message d'info de la modale -> mettre `Documents liés à la procédure`

![image](https://github.com/MTES-MCT/histologe/assets/97226289/ecfe1868-b379-45b8-b751-5a670bfc86a0)

**Comment by hmeneuvrier** [comment]
@mathildepoulpux et dans le suivi aussi, non ?

**Comment by mathildepoulpux** [comment]
Exactement, bien vu
