### ISSUE TITLE
[BO - Teamnet] Intégrer interfaçage à iDoss

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2515]
**EDIT**
https://drive.google.com/drive/folders/1oH6EfN8raeA_-2iBNAX5LD0-j2M1aX_x?usp=drive_link

> Suite à notre réunion du 25 avril et comme convenu, vous trouverez ci-joint :
> Un document de spécification technique
Une collection postman

> Nous avons également rajouté la date d’expiration du token.
> Vous devez donc avoir tous les éléments techniques nécessaires pour l’écriture des développements de l’interface de votre côté.

> Je vous donnerais, en temps utile, le lien et les accès à notre version de TEST iDOSS qui comporte déjà le Webservice pour que vous puissiez faire des tests.
> Nous restons à votre disposition si vous avez besoin d’informations complémentaires.

**Comment by sfinx13** [comment]
J'ai testé la collection, les ws fonctionnent

**Comment by sfinx13** [comment]
Appel à faire à l'acception et non à l'affectation
