### ISSUE TITLE
[FO - Formulaire - Accessibilité - 8.X] Vérifier code source

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2543]
Critères 8.X du référentiel https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#topic-8

- [ ] [Critère 8.2](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-8-2) [A] : Pour chaque page web, le code source généré est-il valide selon le [type de document](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#type-de-document) spécifié ?
- [ ] [Critère 8.6](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-8-6) [A] : Pour chaque page web ayant un [titre de page](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#titre-de-page), ce titre est-il pertinent ?

**Comment by emilschn** [comment]
@sfinx13 @hmeneuvrier @numew 
Pour le titre de la page, ça avait été revu y'a pas longtemps.

Je n'ai pas trouvé de moyen pour tester le w3c du html généré par Vue correctement.
Il y a pas mal de réponses qui me semblent dépassées (+3 ans)
Si jamais vous trouvez une idée avec une recherche complémentaire, faites-moi savoir... Là comme ça, je sèche.

**Comment by hmeneuvrier** [comment]
@emilschn 

copy(document.documentElement.outerHTML);

ça met tout le code, même celui généré par Vue dans le presse-papier, et ensuite on peu le coller dans le validateur w3c

**Comment by hmeneuvrier** [comment]
Du coup je repasse en Todo pour qu'on le fasse sur chaque écran

**Comment by emilschn** [comment]
**WIP : Mes notes**
- Première erreur : il souhaite `<!DOCTYPE html>` mais c'est pas copié. Donc à ne pas prendre en compte.
- Dans les erreurs suivantes : on va devoir ajouter des propriétés artificiellement dans les composants, sinon elles sont ajoutées dans le DOM. Il y a peut-être mieux à faire.
