### ISSUE TITLE
[FO - Formulaire - Accessibilité - 7.X] [Audit terminé] Technologies d'assistance

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2547]
Critères 7.X du référentiel https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#topic-7

- [ ] [Critère 7.1](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-7-1) [A] : Chaque [script](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#script) est-il, si nécessaire, [compatible avec les technologies d'assistance](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#compatible-avec-les-technologies-d-assistance) ?
- [ ] [Critère 7.3](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-7-3) [A] : Chaque [script](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#script) est-il [contrôlable par le clavier et par tout dispositif de pointage](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#accessible-et-activable-par-le-clavier-et-tout-dispositif-de-pointage) (hors cas particuliers) ?

**Comment by hmeneuvrier** [comment]
- [ ] Composant Adresse à revoir (navigation au clavier)
7.3  Chaque[ script (ouvre dans une nouvelle fenêtre) ](https://accessibilite.numerique.gouv.fr/methode/glossaire/#script)est-il contrôlable par le clavier et par tout dispositif de pointage (ouvre dans une nouvelle fenêtre) (hors cas particuliers) ?

    Non conforme

    Impact majeur

La liste de résultats de recherche d’adresse ne peut être fermée lorsque l’on ne trouve pas l’adresse désirée. (ni au clavier ni à la souris)

Exemple(s) d’erreur(s)
Ouvrir l’image dans une nouvelle fenêtre

Faire en sorte de pouvoir cacher la liste des résultats de recherche d’adresse en appuyant sur la touche ECHAP ou en cliquant en dehors de la liste.

Voir :

    [Combobox Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/)
    [Editable Combobox With List Autocomplete Example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/)

- [ ] Vérifier que toutes les actions cliquables sont bien sur des boutons
- [ ] Vérifier qu'il y a "Nouvelle fenêtre" dans le titre des liens externes
- [ ]

**Comment by emilschn** [comment]
Pour les punaises, liste des choses remontées en 7.1 / 7.3 :
- les liens qui devraient être des boutons (déjà remonté par Hélène, à vérifier)
- l'utilisabilité de la saisie d'adresse (déjà remonté par Hélène)
- le focus qui repart en haut de page quand on ajoute/supprime un fichier (à vérifier)
- les erreurs doivent être des alertes avec un role=alert (à vérifier)
