### ISSUE TITLE
[FO - Signalement] Multiple création de signalement en cas d'erreur lors de la validation

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2576]
- Bloquer la possibilité de générer un nouveau signalement à partir d'un draft si le draft est déjà en signalement (pas mal de cas en prod)
- Correction du titre de popup "Ces signalements existent déjà"
- Rendre possible d'ignorer la popup "Ce signalement existe déja" quand pas de brouillon existant
- ~~Corriger le buq qui fait que l'on reste bloqué sur la page "Votre signalement est incomplet" même après ajout de désordre (d'abord ne pas mettre de désordre, en ajouter ensuite https://mattermost.incubateur.net/betagouv/pl/8eofthe8kfgm9m1sem77i7oske)~~ Non reproduit

**Comment by arnaudchouk** [comment]
je vous mets le lien vers matter avec les ex
https://mattermost.incubateur.net/betagouv/pl/ux6k4mhtx3yrmytdp7r35mssqc
