### ISSUE TITLE
[BO - Gestion users] Rendre telechargeable la liste des users actifs/inactifs à partir de la Home pour les RT

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2580]
on avait parlé de permettre aux RT de télécharger la liste des comptes users actifs/inactifs directement à partir du bandeau en haut de page dashboard
je ne le vois pas dans les tickets

**Comment by hmeneuvrier** [comment]
Arnaud Choukroun
[il y a 16 heures](https://mattermost.incubateur.net/betagouv/pl/be8bxocggp8ixfyia4thjwr95r)

mon idee en version Arnaud
quand le rt clic sur l info du bandeau, il télécharge le csv avec les infos renseignés des comptes concernes
[-16 h](https://mattermost.incubateur.net/betagouv/pl/k19d75ma9ing5nnbz9ztj78bpo)

mail nom prenom partenaire role

**Comment by hmeneuvrier** [comment]
@mathildepoulpux comme tu reviens bientôt (youpi) je te laisse jeter un oeil à ce ticket, plutôt que de faire un truc aujourd'hui qui pourrait ne pas te convenir.

**Comment by mathildepoulpux** [comment]
En terme de parcours utilisateur ça n'a pas de sens de faire le téléchargement au niveau du bandeau du dashboard.
Je serais plutôt d'avis de mettre une page "liste des utilisateurs" à dispo avec cette action (ce qui devrait pas être bien compliqué étant donné qu'on a déjà des listes de users existantes grâce à Numa !)

C'est une fonctionnalité uniquement RT / SA ?

**Comment by arnaudchouk** [comment]
Oui que RT/SA

**Comment by hmeneuvrier** [comment]
cf https://mattermost.incubateur.net/betagouv/pl/wtitocfuzfdixec8s8z4qxwmya

**Comment by mathildepoulpux** [comment]
Sera traité dans le #3084
