### ISSUE TITLE
[BO - Comptes archivés] En voulant réactiver un compte, ça indique que ce compte existe déjà (en précisant le compte en cours d'édition)

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2584]
Erreur affichée :
Un utilisateur existe déjà avec cette adresse e-mail. NOM PRENOM ( id XXX ) avec le rôle ROLE

**Comment by hmeneuvrier** [comment]
@numew c'est lié à quelle PR ce ticket ?
