### ISSUE TITLE
[BO - Filtre signalement] Retours suite à test

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2597]
Vu en présentiel : 

**Bugs :** 
- [ ] Sur les cartes, le prénom apparaissait parfois en double (dans le nom, et dans le prénom), vérifier si c'est comme ça en base ou s'il y a un bug
- [ ] Quand on commence par un tri alphabétique croissant, le tri alphabétique décroissant reste en croissant, et vice-versa
- [ ] Le tri n'est plus pris en compte quand on ajoute un filtre

**Améliorations (Mathilde est taguée quand ça nécessite une décision UX) :** 
- [ ] Changer le tri "plus récent"/"plus ancien" en utilisant la date de dernier suivi plutôt que la date de dépot (qui est redondant avec la référence)
- [ ] Sur la carte, ajouter le nom du bailleur et si c'est un bailleur privé/public sur la carte (cf @mathildepoulpux )
- [ ] Afficher les conclusions de visite sur la carte (remplacer les procédures suspectées cf @mathildepoulpux ?)
- [ ] Sur la fiche signalement, ajouter un bouton "retour à la liste filtrée) qui simule le bouton précédent du navigateur (cf @mathildepoulpux )

**Comment by sfinx13** [comment]
Je propose que ces améliorations soient dans un autre ticket
- Sur la carte, ajouter le nom du bailleur et si c'est un bailleur privé/public sur la carte (cf @mathildepoulpux )
-  Afficher les conclusions de visite sur la carte (remplacer les procédures suspectées cf @mathildepoulpux ?)

**Comment by mathildepoulpux** [comment]
> Je propose que ces améliorations soient dans un autre ticket
> 
> * Sur la carte, ajouter le nom du bailleur et si c'est un bailleur privé/public sur la carte (cf @mathildepoulpux )
> * Afficher les conclusions de visite sur la carte (remplacer les procédures suspectées cf @mathildepoulpux ?)
> * Sur la fiche signalement, ajouter un bouton "retour à la liste filtrée) qui simule le bouton précédent du navigateur (cf @mathildepoulpux )

C'est dans le #2666
