### ISSUE TITLE
[BO- Signalement] Message automatique visite

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2598]
Modifier le message automatique en cas d'information manquante sur la visite :
"La réalisation d'une visite est nécessaire pour caractériser les désordres signalés. Merci de renseigner la date ou les conclusions de la visite afin de poursuivre la prise en charge de ce signalement."

**Comment by emilschn** [comment]
@arnaudchouk 
Ce qu'il faut faire ici, c'est modifier le mail qui est envoyé quand la visite n'est pas prévue ?

Jusqu'à présent, c'était

```
Aucune information de visite n'a été renseignée pour le logement situé
--- adresse ---
Cliquez sur le bouton ci-dessous pour définir une date de visite ou renseigner des informations de visite.
```

C'est bien ce message que vous voulez changer ?

Donc on enlève l'adresse du message ?
Et on enlève l'indication qui demande de cliquer sur le bouton ?

Ou alors je comprends mal la demande :)

**Comment by arnaudchouk** [comment]
je parlais du suivi sur le fil de messages
![image](https://github.com/MTES-MCT/histologe/assets/93710194/547a4fc0-53ea-4a6d-810c-f78283af17d1)
l adresse n y est pas

**Comment by emilschn** [comment]
Ok ; le suivi est créé en même temps que le mail.
On modifie le mail aussi, ou juste le suivi ?

**Comment by arnaudchouk** [comment]
Juste le suivi dans un 1er temps je pense
