### ISSUE TITLE
[Technique] Améliorer la CSP

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2609]
https://observatory.mozilla.org/analyze/histologe.beta.gouv.fr

Content Security Policy 	
-20 	Content Security Policy (CSP) implemented unsafely.

This includes 'unsafe-inline' or data: inside script-src, overly broad sources such as https: inside object-src or script-src, or not restricting the sources for object-src or script-src.

**Comment by sfinx13** [comment]
On a cette alerte quand on build le projet 
 RECOMMEND  To create a smaller (and CSP-compliant) build, see https://symfony.com/doc/current/frontend/encore/vuejs.html#runtime-compiler-build

**Comment by sfinx13** [comment]
https://webpack.js.org/guides/csp/

**Comment by emilschn** [comment]
C'était un peu le sens de ma remarque lors de la retro :)

**Comment by hmeneuvrier** [comment]
`default-src 'none'; `--> empêche le chargement des svg contenus dans le dsfr malgré l'utilisation de `img-src 'self'`... je cherche une solution

**Comment by hmeneuvrier** [comment]
bon c'est chaud de retirer unsafe-unline pour style src, car il faut vraiment TOUT mettre dans des trucs externes

Et j'ai des soucis avec le profiler de symfony malgré [Made the toolbar compatible with Content Security Policy](https://symfony.com/blog/new-in-symfony-3-2-web-debug-toolbar-and-profiler-improvements#made-the-toolbar-compatible-with-content-security-policy)
Romain Neutron

Contributed by
[Romain Neutron](https://connect.sensiolabs.com/profile/romain)
in [#18568](https://github.com/symfony/symfony/pull/18568).

The new [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Using_Content_Security_Policy) HTTP response header helps you reduce XSS risks on modern browsers by declaring what dynamic resources are allowed to load via a HTTP Header.

If your application defines such a policy, the script-src or style-src directives could disallow unsafe inlines, which would prevent the loading of the web debug toolbar.

In Symfony 3.2 we made the web debug toolbar compatible with those kind of Content Security Policies. Internally this change required massive code updates, but for developers it will be completely transparent and it won't require any change in their applications.

**Comment by hmeneuvrier** [comment]
Pour le style, j'arrive à simplifier un peu les choses en ajoutant `style-src-attr 'self' 'unsafe-inline';`

**Comment by hmeneuvrier** [comment]
Utilisation de Nelmio Security Bundle en dernier recours.

Essayer de faire un ContentSecurityPolicyListener pour intercepter les nonces de la toolbar et générer des nonces aléatoirement pour les <script> et les <styles>

**Comment by hmeneuvrier** [comment]
'strict-dynamic' ne passe pas pour tinyMCE

**Comment by hmeneuvrier** [comment]
Mettre les différentes parties de la CSP dans un fichier de config en yaml et concaténer dans le listener

**Comment by hmeneuvrier** [comment]
En enlevant les nonces sur les styles (qui ont été externalisés) on échappe à plein d'erreurs sur tinyMCE, avec une CSP pas trop mmal.

Reste des js à externaliser : 

- [ ] templates/_partials/_modal_refus_affectation.html.twig : onclick="return confirm('Êtes-vous certain de vouloir refuser ce signalement ?')">
- [ ] templates/_partials/_modal_refus_signalement.html.twig : onclick="return confirm('Êtes-vous certain de vouloir refuser ce signalement ?')">
- [ ] templates/_partials/_modal_user_create.html.twig :  onchange="checkUserMail(this)" oninput="checkUserMail(this)"
- [ ] templates/_partials/_modal_user_edit.html.twig :  onchange="checkUserMail(this)" oninput="checkUserMail(this)"
- [ ] templates/back/account/index.html.twig :  onchange="this.form.submit()"
- [ ] templates/back/partner/_delete_form.html.twig :  onsubmit="return confirm('Êtes-vous sûre de vouloir supprimer ce partenaire ?');"
- [ ] templates/back/partner/index.html.twig :  onchange="this.form.submit()"
- [ ] templates/back/partner_archived/index.html.twig  :  onchange="this.form.submit()"
- [ ] templates/back/signalement/view/header.html.twig :  onclick="return confirm('Êtes-vous certain de vouloir acccepter ce signalement ?')"
- [ ] templates/front/suivi_signalement.html.twig :  onclick="const notice = this.parentNode.parentNode.parentNode; notice.parentNode.removeChild(notice)"

- [ ] virer le code commenté
- [ ] virer public/img/logo_ANCT_header.svg
- [ ] templates/back/cartographie/index.html.twig : déplacer le bout de js plutôt que de mettre un nonce
- [ ] templates/back/signalement/view/photos-album.html.twig : déplacer le bout de js plutôt que de mettre un nonce

- [ ] Faire des tests sur différents navigateurs
