### ISSUE TITLE
[BO - Signalement] Vosges - Suppression des fichiers .eml importés

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2615]
Liste (à vérifier) 
https://histologe-metabase.osc-fr1.scalingo.io/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MzIsImZpbHRlciI6WyJhbmQiLFsiZW5kcy13aXRoIixbImZpZWxkIiwzNTAsbnVsbF0sIi5lbWwiLHsiY2FzZS1zZW5zaXRpdmUiOmZhbHNlfV0sWyI9IixbImZpZWxkIiwyMjQseyJzb3VyY2UtZmllbGQiOjM1NH1dLDg5XV19LCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==

**Comment by hmeneuvrier** [comment]
@arnaudchouk faut-il le faire pour tous les signalements des Vosges ou seulement pour les signalements importés ?

**Comment by arnaudchouk** [comment]
ils ne sont pas lisibles a priori, donc tous je pense

**Comment by hmeneuvrier** [comment]
C'est juste que ça s'ouvre avec un client mail

**Comment by hmeneuvrier** [comment]
(juste pour compléter c'est un type de coument qu'on a décidé de garder sur la plateforme)

**Comment by arnaudchouk** [comment]
a priori c est trop compliqué pour eux et des infos sont accessibles à des partenaires qui arrivent eux, alors qu ils ne devraient pas, à les lire - donc supprimez tout :)

**Comment by hmeneuvrier** [comment]
ça a été fait aujourd'hui à 16h @arnaudchouk
