### ISSUE TITLE
[Signalement] Lors de la création de 2 signalements simultanés (à quelques secondes près), il peut y avoir des doublons de référence

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2622]

**Comment by emilschn** [comment]
Voir https://www.doctrine-project.org/projects/doctrine-orm/en/current/reference/transactions-and-concurrency.html#locking-support

**Comment by hmeneuvrier** [comment]
@sfinx13 ça peut avoir un rapport avec ton pb ? https://sentry.incubateur.net/organizations/betagouv/issues/107928/?environment=prod&project=61&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+my_teams%2C+none%5D&referrer=issue-stream&sort=inbox&statsPeriod=14d&stream_index=0

**Comment by sfinx13** [comment]
@numew depuis la MEP du 2/08 ça n'arrive plus donc ça c'est top.

J'ai réussi à simuler des appels concurrents à l'aide d'un petit script JS basé sur la collection Postman du projet, ce qui permet de reproduire le problème. Le script et la tâche Makefile sont inclus dans la PR.

Du coup avec la mise en place d'un verrou sur la lecture de la référence, englobé dans une transaction, plus aucun doublon de référence sur le même territoire (test effectué sur 10 appels concurrents).
