### ISSUE TITLE
[FO - Page de suivi] Mettre le focus sur le dernier message

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2631]
Je suis usager
J'ai un email m'indiquant une MAJ sur mon signalement
Je clique sur le bouton pour accéder à la page de suivi
J'arrive sur la page, en haut de la page
Problème : si j'ai déjà plusieurs échanges avec l'administration, je dois scroller pour accéder à la nouveauté

Solution : mettre le focus sur le dernier suivi (si possible)

**Comment by mathildepoulpux** [comment]
Ca ne fonctionne pas, j'arrive toujours en haut de page

**Comment by mathildepoulpux** [comment]
Je corrige : j'ai besoin d'utiliser la reviewapp avec mailtrap pour pouvoir tester

**Comment by emilschn** [comment]
Tu peux nous transmettre le lien que tu as eu, pour qu'on regarde ?

**Comment by mathildepoulpux** [comment]
https://histologe-staging-pr2624.osc-fr1.scalingo.io/suivre-mon-signalement/ef225bf3-eec8-348f-80b5-a0d5312f2039?from=igros@dbmail.com#suivi-last

**Comment by emilschn** [comment]
On a fait une MAJ avec une correction.
Ton lien n'est donc plus valable :)
Mais tu peux re-tester et nous faire un retour ? :)

**Comment by mathildepoulpux** [comment]
C'est bon ça marche !
