### ISSUE TITLE
[FO - Page de suivi] Problème lien de suivi une fois le signalement clôturé

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2633]
Signalement déposé par un tiers, test fait avec le profil tiers ET le profil occupant

- Je dépose un signalement
- J'accède à la page de suivi sans problème
- Mon signalement est clôturé
- Je reçois un mail de suivi
![image](https://github.com/MTES-MCT/histologe/assets/97226289/a63e56ea-7abf-4761-8fce-dbc0786eb87e)
- Quand je clique sur le lien depuis le mail -> J'ai une erreur
![image](https://github.com/MTES-MCT/histologe/assets/97226289/a3bc0d4f-d3f2-4faf-9cbd-c3c187c35f60)

NB : avant la clôture, je n'avais pas de problème pour accéder à la page de suivi

Comportement attendu (cf. #2149 ) : 
On affiche la page, sans la possibilité d'effectuer les actions ajout de message / photos / documents + affichage d'un message d'info `Votre signalement a été clôturé, vous ne pouvez plus envoyer de messages.`

**Comment by numew** [comment]
Je ne reproduit pas 
![Screenshot 2024-06-05 at 09-21-36 Histologe](https://github.com/MTES-MCT/histologe/assets/7130780/25116055-475e-47cc-a723-e8c7dc4b8e8f)
