### ISSUE TITLE
[BO - Modale renvoi lien de suivi] Retirer le point à la fin de l'URL

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2634]
Je suis SA
J'accède à la modale pour renvoyer le lien vers une page de suivi
Je veux copier / coller le lien dans la barre de mon navigateur
![image](https://github.com/MTES-MCT/histologe/assets/97226289/65a207a7-4913-4834-a05e-97a76c0475af)

-> On a vite fait de sélectionner le point à la fin de l'URL donc de se retrouver avec une erreur parce que l'adresse n'existe pas
Il faudrait juste retirer le point de la phrase pour éviter ça !

**Comment by hmeneuvrier** [comment]
@mathildepoulpux oui c'est bien d'enlever le . mais c'est encore mieux d'utiliser le bouton plutôt que de faire un copier/coller, car avec le bouton, le lien envoyé comporte l'adresse mail de l'usager, ce qui permet sur la fiche de suivi d'identifier qui poste ce nouveau suivi

**Comment by mathildepoulpux** [comment]
Oui je sais bien. C'est juste que ça risque d'arriver les copier / coller donc je préfère prévoir
