### ISSUE TITLE
[Relance Auto] Signalements non relancés

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2652]
Sur la base de l export genere sur metabase
https://histologe-metabase.osc-fr1.scalingo.io/question/195-dernier-suivi-des-signalements-avec-envoi-de-mail-automatique-et-commune-logement-social
28 signalements semblent avoir été oubliés dans les relances
Les ref/uuid concernees sont listees ci dessous pour avoir une base d investigation si le pbm se repend 
2021-1245	18/03/2024 07:01	https://histologe.beta.gouv.fr/bo/signalements/6227589d8f3ec
2021-1184	18/03/2024 06:24	https://histologe.beta.gouv.fr/bo/signalements/6227589a43bc7
2022-1512	28/02/2024 07:39	https://histologe.beta.gouv.fr/bo/signalements/637644b285b00
2023-74	29/01/2024 10:38	https://histologe.beta.gouv.fr/bo/signalements/5b654bb8-5a6d-4320-a957-03cdc869b5ee
2023-81	19/12/2023 05:13	https://histologe.beta.gouv.fr/bo/signalements/540ca3a3-b5c1-4a6d-a6b6-8167eabb7601
2022-150	17/12/2023 08:35	https://histologe.beta.gouv.fr/bo/signalements/635ba2fe3d8be
2023-57	07/12/2023 06:22	https://histologe.b

**Comment by hmeneuvrier** [comment]
@arnaudchouk les signalements que tu as listé ont tous une demande d'abandon de procédure de la part de l'usager, c'est pour ça qu'il n'y a plus de relances ensuite. 
Du coup je ne vois pas quel est le pb ?

**Comment by arnaudchouk** [comment]
je ne me rappelle plus
mais merci pour la precision - donc il faut absolument que les RT s en occupent sous peine qu ils ne les voient plus grace aux relances

**Comment by hmeneuvrier** [comment]
du coup je ferme ce ticket :)
