### ISSUE TITLE
[BO - Listing] Améliorations sur la liste et les filtres

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2666]
cf. #2597 

Des améliorations à faire ont été repérées pendant le présentiel de mai 2024 : 
1. Changer le tri "plus récent"/"plus ancien" en utilisant la date de dernier suivi plutôt que la date de dépot (qui est redondant avec la référence)
2.  Sur la carte, ajouter le nom du bailleur et si c'est un bailleur privé/public sur la carte
3.  Afficher les conclusions de visite sur la carte (remplacer les procédures suspectées)
4.  Sur la fiche signalement, ajouter un bouton "retour à la liste filtrée) qui simule le bouton précédent du navigateur 

### 1. Changer le tri
Dans la mesure ou l'ordre croissant / décroissant et le signalement plus ancien / plus récent sont similaires, on modifie la deuxième option. 
Dans les options de tri : 
- changer "le plus récent" en "Suivi le plus récent", en se basant sur la date du dernier suivi
- changer "le plus ancien" en "Suivi le plus ancien", en se basant sur la date du dernier suivi
![image](https://github.com/MTES-MCT/histologe/assets/97226289/4ba956eb-ab58-4221-a7cb-217ae10d6354)

-> cf. [les specs à jour](https://github.com/MTES-MCT/histologe/wiki/liste-signalements#tri)

### 2. Ajouter le nom du bailleur + si bailleur privé ou public sur la carte
Dans la mesure où ça fait ajouter des info sur une carte déjà bien pleine, je préfère attendre les retours et la prise en main des filtres pour faire cette amélioration.
➡️ **On verra + tard**

### 3. Afficher les conclusions de visite sur la carte
- Si signalement a une visite terminée
- Si conclusion de visite renseignée

On affiche les procédures renseignées dans la dernière visite complétée en remplaçant "Procédure(s) suspecté(s)" par `Procédure(s) constatée(s)` et en affichant les labels renseignés dans la conclusion de visite

![image](https://github.com/MTES-MCT/histologe/assets/97226289/000ecf02-6c93-4e38-8b3e-dbbd3e309316)

### 4. Ajouter un bouton "retour" sur la fiche signalement
Sur la fiche signalement, afficher un bouton "Retour" qui renvoie vers la liste des signalements filtrées (même comportement que le bouton "précédent" du navigateur).

![image](https://github.com/MTES-MCT/histologe/assets/97226289/48bb87df-dbbb-4329-9f22-35a479b7412c)

Je propose qu'on utilise le même modèle que celui sur les pages partenaires, en ajoutant juste une petite marge en dessous 👇 
![image](https://github.com/MTES-MCT/histologe/assets/97226289/168f1d2a-c655-43cb-b520-442a1fee18fe)

**Comment by sfinx13** [comment]
L'ajout d'une ancre ajoute une page dans l'historique du navigateur ça remet en question la solution prise ensemble. 
La conservation choisie est de conserver les filtres coté navigateur ainsi on a une gestion explicite du retour arrière.
