### ISSUE TITLE
[Sécurité] [FO] Masquer l'uuid des SignalementDraft en doublon trouvés

### ISSUE THREAD

**Issue by numew** [MTES-MCT/histologe#2677]
- La route `check_signalement_or_draft_already_exists` retourne l’uuid du DraftSignalement, étant donnée que cet uuid permet de
construire les routes `front_nouveau_formulaire_edit` et `informations_signalement_draft` autant dire qu’en connaissant l’adresse e-mail + adresse postale on peux facilement récupérer l’accès au brouillons. 
Solution : ne pas utiliser les uiid, j’ai pensé à l’id mais le problème c’est que comme cela va impacter aussi les route `archive_draft` et `send_mail_continue_from_draft` l’id est trop prévisible, donc il faudrait autre chose (peut être le checksum ?).
-> Proposition en stand up : Retourner uniquement sil un doublon a été trouvé ou pas et réutilisé les infos permettant de le trouver sur les autres routes 

- La route `check_signalement_or_draft_already_exists` retourne aussi potentiellement un ou une liste d’uuid de signalements existant, ceci dit ces uuid n’étant utilisé que coté BO ce n'est pas forcément problématique

**Comment by hmeneuvrier** [comment]
Ne reste qu'à tester le cas signalement existant + draft existant
