### ISSUE TITLE
[BO - Création compte] Blocage en cas de doublon de mail

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2726]

**Comment by emilschn** [comment]
@arnaudchouk si tu as quelques minutes pour décrire le problème, je suis preneur :)

**Comment by arnaudchouk** [comment]
on a recu ce mail , a priori le compte est archivé et ils ne peuvent pas le recreer

Sujet : 	compte histologe dans le 28
Bonjour Vikie,
Il existe un compte histologe pour la commune de VILLEMEUX-SUR-EURE dans le département 28 (Eure-et-Loir) avec l'adresse générique:" [accueil@villemeux.fr](mailto:accueil@villemeux.fr)"
Nous voudrions ajouter un utilisateur au nom de LEGAZ Jennifer avec comme adresse : "[secretaire.generale@villemeux.fr](mailto:secretaire.generale@villemeux.fr)".Histologe nous indique qu'il existe déjà!hors il n'apparaît pas dans les utilisateurs.

**Comment by hmeneuvrier** [comment]
Effectivement quand on regarde les utilisateurs au statut 2 dans Metabase, tous n'ont pas le suffixe .archived@

**Comment by hmeneuvrier** [comment]
ah punaise ! la commande notify-and-archive-inactive-accounts ne change pas le mail en cas d'archivage.

**Comment by arnaudchouk** [comment]
j'ai desarchivé le compte pour info

**Comment by hmeneuvrier** [comment]
https://histologe-metabase.osc-fr1.scalingo.io/question/1198-users-archives-sans-suffixe-archived

1755 comptes ont été archivés sans le suffixe .archived@ tous entre le 5 mai 2024 et le 9 juin 2024, sauf un qui a été fait le 21 juin 2024...

@numew ça peut te donner une piste pour le ticket https://github.com/MTES-MCT/histologe/issues/2730

**Comment by hmeneuvrier** [comment]
TODO : 

Faire un hotfix en corrigeant la commande  `notify-and-archive-inactive-accounts` et en faisant une mimgration pour désarchiver les 1755 comptes archivés sans le tag cf #2730 
Essayer de trouver comment a été archivé celui qui a été archivé le 21 juin
