### ISSUE TITLE
[Technique] Ajout Modsecurity sur scalingo

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2735]
https://mattermost.incubateur.net/betagouv/pl/5axhe4oj1bb5jjyp4e5ec3buoc

**Comment by hmeneuvrier** [comment]
Juste pour tenir au courant. Depuis jeudi dernier je suis en échange avec Michael du support scalingo pour ajouter momdsecurity.
J'ai créé une reviewapp histologe-staging-pr2746 en partant de [cette PR](https://github.com/MTES-MCT/histologe/pull/2746) sur laquelle j'ai ajouté le buildpack nginx et la var d'env ENABLE_MODSECURITY conformément à ses instructions.
Pour autant ça ne fonctionne pas, le test `curl -v -X INVALID_HTTP_METHOD https://histologe-staging-pr2746.osc-fr1.scalingo.io/`
me renvoie la page d'accueil et pas une erreur 403.
Il est dessus depuis vendredi.

**Comment by hmeneuvrier** [comment]
A l'instant, nouvelle du support scalingo : 

> Nous avons trouvé un fix, il faut qu'on le mette en production maintenant.

**Comment by hmeneuvrier** [comment]
J'ai testé le fix ça ne marche pas

**Comment by hmeneuvrier** [comment]
@sfinx13 que fait-on de ce ticket ? on l'archive ?

**Comment by sfinx13** [comment]
on le dépriorise. Faudra investiguer sur le SAAS
