### ISSUE TITLE
[QA] Erreur d'ouverture de fichier depuis MEP du 20 janvier

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2751]
https://sentry.incubateur.net/organizations/betagouv/issues/106549/?environment=prod&project=61&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0

Symfony\Component\HttpKernel\Exception\NotFoundHttpException

**Comment by hmeneuvrier** [comment]
lié ? https://sentry.incubateur.net/organizations/betagouv/issues/95280/?environment=prod&project=61&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1

**Comment by hmeneuvrier** [comment]
@emilschn je t'affecte ce ticket du coup... Pour l'instant j'ai juste fait des tests sur firefox/chromium et safari sur iPhone sans réussir à reproduire. (mes tests consistant à prendre un signalement sur lequel on avait eu une erreur d'affichage d'une photo, et à ouvrir cette photo depuis le BO et depuis la fiche de suivi usager)

**Comment by emilschn** [comment]
**[Enquête en cours...]**

J'essaie de voir les différents cas de figure...

### Cas 1
https://sentry.incubateur.net/organizations/betagouv/issues/106549/events/ab9ee6b51cfe4fed933be1dc1db531de/?project=61
Celui-ci, c'est un fichier d'export de signalement envoyé par mail. 
J'imagine que quand la personne a rouvert le fichier en cliquant dans le mail, elle n'était plus connectée.
Du coup, il y'a peut-être un petit souci d'UX ?

https://sentry.incubateur.net/organizations/betagouv/issues/106549/events/3ebcc01610bf4c97b903eb8e48449b4f/?project=61
Celui-ci est un rapport de visite
De la même manière : si on est connecté on le voit, sinon, non.
J'imagine qu'il a été affiché en cliquant sur "Afficher le document".
Mais si la personne a pu cliquer dessus, c'est qu'elle était autorisée à voir le document (voter SIGN_VIEW).
Donc ça ne devrait pas bloquer ?
Ca a l'air d'être la même personne que ci-dessus. Peut-être qu'elle a été déconnectée entre temps, et qu'elle ne pouvait plus rien ouvrir, logiquement...

Je laisse, et je préconise un changement UX pour ce cas de figure.

### Cas 2
https://sentry.incubateur.net/organizations/betagouv/issues/106549/events/755314bbaee94e828802875eda2ef96b/?project=61
Celui-ci, il y en a plusieurs dans la même seconde avec les mêmes terminaux. On peut imaginer que c'est la même personne.
Il n'y a ni token, ni uuid de signalement dans l'url. Logique que ça ne s'ouvre pas.
C'est pourtant un signalement récent.
C'est surtout ce problème qui a l'air récurrent, car il en crée de multiples les uns à la suite des autres. Je focalise mes recherches sur celui-ci.

**Comment by sfinx13** [comment]
Suite au résultat qui n'ont rien donné https://github.com/MTES-MCT/histologe/pull/2902 j'ai ré ouvert le ticket
On arrive au limite du csrf_token pour protéger les ressources pour un utilisateur non connecté, l'idée était bonne mais il va falloir s'appuyer sur une solution plus approprié non couplé à la session php. 

Une solution serait de signer les urls 
Voici un article avec un bundle developpé par les tilleuls
https://les-tilleuls.coop/blog/url-signer-bundle-creer-valider-url-signees-symfony
https://github.com/coopTilleuls/UrlSignerBundle?tab=readme-ov-file

Le bundle s'appuie sur la lib 
https://github.com/spatie/url-signer

Suite aux résultats insatisfaisants de la PR https://github.com/MTES-MCT/histologe/pull/2902, j'ai décidé de ré ouvrir le ticket. Nous atteignons les limites de l'utilisation de csrf_token pour protéger des ressources d'un utilisateur non connecté. Bien que l'idée initiale était intéressante, il est donc nécessaire de s'appuyer solution plus adaptée, non couplée à la session PHP.

Une solution serait de signer les URLs. Voici un article présentant le concept et un bundle développé par Les-Tilleuls :
* https://les-tilleuls.coop/blog/url-signer-bundle-creer-valider-url-signees-symfony
* https://github.com/coopTilleuls/UrlSignerBundle?tab=readme-ov-file

Ce bundle utilise la bibliothèque suivante :
* https://github.com/spatie/url-signer

Cette solution sera aussi utile pour le partage de document pour oilhi
