### ISSUE TITLE
[FO][BO - Signalement] Rendre la voie d'une adresse obligatoire, et refuser celles où il y a juste le numéro de la rue

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#2758]
* L'appliquer à toutes les adresses postales (Nouveau formulaire et édition BO)
* Rendre la voie obligatoire

**Comment by emilschn** [comment]
Si on découpe ça, on fait aussi un champ à part pour le complément d'adresse (bis, ter, etc.) ?
Et ça devient une liste déroulante ?

**Comment by emilschn** [comment]
On ne change rien à l'architecture, ni à l'interface.
Par contre, on fait une vérification complémentaire lors de la saisie pour s'assurer qu'il n'y ait pas juste un numéro
