### ISSUE TITLE
[BO - Affectation Automatique] Hérault

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2759]
Activation de l'affectation auto pour l Hérault en "désactivant" les signalements issus du parc public
Description du cénario attendu :
Périmètre : **signalements relevant du parc privé**

Pour les Communes disposant d'un SCHS :
* affectation automatique aux communes sur la base de leur code INSEE + CAF systématiquement (modification du Type Partenaire + ajout de tous les codes insee) + Travailleurs Sociaux (modification du Type Partenaire + ajout de tous les codes insee)

Pour les Communes sans SCHS :
* affectation automatique aux communes sur la base de leur code INSEE + CAF systématiquement () + Opérateur  (modification du Type Partenaire + ajout des codes insee) + EPCI  (modification du Type Partenaire + ajout des codes insee) + Travailleurs Sociaux (modification du Type Partenaire + ajout de tous les codes insee)

Pour les Communes à exclure :
* affectation manuelle (modification du Type Partenaire)

**Comment by hmeneuvrier** [comment]
Avoir en tête les spécs futures pour modéliser : https://github.com/MTES-MCT/histologe/issues/2689

**Comment by hmeneuvrier** [comment]
Proposition de specs en prenant en compte ce qui a déjà été fait pour le 93 et ce qui pourrait arriver dans le ticket #2689 
(mais je ne comprends pas toutes les specs pour l'Hérault, à clarifier avec Arnaud)

Création d'une entité AutoAffectationRule

| ID      |Territory       | Status      | profil_declarant      |    partner_type   |
|---    |---   |---   |---    |---   |
|       |       |       |       |       |
|       |       |       |       |       |
|       |       |       |       |       |

**Comment by arnaudchouk** [comment]
@hmeneuvrier 
lite des communes à ne pas affecter
Clermont l'Hérault 34079
Lodève 34142
Lunel 34145
Sète 34301

**Comment by hmeneuvrier** [comment]
@arnaudchouk j'ai créé un nouveau ticket pour l'Hérault : #2848
