### ISSUE TITLE
[BO - Territoire compétent] Non cohérence CP INSEE

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2761]
CP/INSEE : on a un cas tres special 
commune de Port-Sainte-Foy-et-Ponchapt est en dordogne, son code insee 24335
cependant son CP est 33220, donc en gironde

Resultat son signalement a orienté sur la gironde et refusé pour orientation vers la dordogne, comment on gere ca?

https://mattermost.incubateur.net/betagouv/pl/ppffch3xopdm5ruiz3do7hb1pr

Autre commune dans le meme cas Fougueyrolles : code postal en 33220 et un code insee 24189

**Comment by hmeneuvrier** [comment]
cf https://fr.wikipedia.org/wiki/Liste_des_communes_de_France_dont_le_code_postal_ne_correspond_pas_au_d%C3%A9partement
