### ISSUE TITLE
[BO - Modale Confirm] Modifier Modale "Suppression"

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2780]
Bcp de suppressions "non souhaitées" de signalements
https://mattermost.incubateur.net/betagouv/pl/j3dyu34ohpbx7fw4raqt3qw3gy

**Comment by mathildepoulpux** [comment]
# Ajouter une modale de suppression pour le signalement

## Conditions
- Avoir le rôle RT ou supérieur
- Avoir un compte actif sur la plateforme

## Flow
1. Accéder à la liste de signalement
2. Clic sur le bouton "supprimer le signalement"
3. Ouverture de la modale de suppression
    - Titre : Supprimer le signalement {{reference}}
    - Texte : Vous êtes sur le point de supprimer le signalement {{reference}} de {{fullname occupant}}. Une fois le signalement supprimé : 
        - Le signalement sera supprimé, **il ne sera plus accessible dans Histologe**.
        - Vous ne pourrez plus assurer le suivi du dossier.
        - Les partenaires ne pourront plus être affectés et les affectations en cours seront supprimées
        - L'usager ne pourra plus accéder au suivi de son signalement 
     Voulez-vous vraiment supprimer ce signalement ?
    - Zone d'action avec 2 boutons : `Oui, supprimer` et `Non, annuler` 
5. Clic sur "Oui, supprimer"

### Conséquences
- Retour sur la liste des signalements avec le success message `Le signalement a bien été supprimé.`
- Le signalement est archivé
- Le signalement n'apparaît plus dans la liste des signalements
- Les affectations en cours sont supprimées
- Les notifications liées au signalement sont supprimées
- Un mail est envoyé à l'usager
