### ISSUE TITLE
[Signalements] Revoir les références des signalements importés dans l'Oise

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2789]
Cf https://mattermost.incubateur.net/betagouv/pl/3iihdrjndffr8mz96kf1i55isc

TODO : 

- [x] corriger les références de signalements de l'Oise  :  Du coup pour l'Oise, pour les signalements importés :  `201204-060` deviendrait `2019-1204` (référence originelle `060-1204` et année de création `2019`), pour les signalements créés sur la plateforme en 2023, on reprend `2023` et on reprend la numérotation en fonction de ce qu'il y a en bdd
- [ ] Fournir un export des références avant et après avec l'uuid 
- [x] Définir comment on corriger les références des signalements hors Oise https://histologe-metabase.osc-fr1.scalingo.io/question/1220-signalements-references-bizarres --> on corrige aussi les signalements du 76 avec les exports avant / après (ça a merdé suite à l'import de signalements la semaine dernière)
- [ ] Pour ceux qui restent on verra au cas par cas car il en restera très peu
- [x] Revoir l'attribution des références au moment de l'import de signalements, on n'est pas assez regardant sur le format, il faut vraiment qu'on blinde pour s'assurer que les références commencent toujours par `aaaa-` où `aaaa` est l'année de création  du signalement. Ensuite on peut reprendre tous les **chiffres** de leur référence (enlever les `-`, `/` etc)
- [x] Complexifier src/Service/Signalement/ReferenceGenerator.php pour être sûrs d'avoir bien un format `aaaa-` (car on fait juste un explode sur `-` sans vérifier ce qu'on a ensuite dans $year

**Comment by sfinx13** [comment]
Ne plus importer des signalements avec des références bizarres
