### ISSUE TITLE
[BO - Signalement] Reaffecter Etiquettes

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2800]
probleme etiquettes supprimée
Dpt 62 : quelqu un a supprimé l Etiquette NON DECENCE de la liste
Probleme cela concerne 1737 signalements 
[liste ici ](https://histologe-metabase.osc-fr1.scalingo.io/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MjUsImpvaW5zIjpbeyJmaWVsZHMiOiJhbGwiLCJzb3VyY2UtdGFibGUiOjIzLCJjb25kaXRpb24iOlsiPSIsWyJmaWVsZCIsMjE0LG51bGxdLFsiZmllbGQiLDI3Myx7ImpvaW4tYWxpYXMiOiJUYWcgU2lnbmFsZW1lbnQifV1dLCJhbGlhcyI6IlRhZyBTaWduYWxlbWVudCJ9LHsiZmllbGRzIjoiYWxsIiwic291cmNlLXRhYmxlIjoyOSwiY29uZGl0aW9uIjpbIj0iLFsiZmllbGQiLDI3NCx7ImpvaW4tYWxpYXMiOiJUYWcgU2lnbmFsZW1lbnQifV0sWyJmaWVsZCIsMjcwLHsiam9pbi1hbGlhcyI6IlRhZyJ9XV0sImFsaWFzIjoiVGFnIn1dLCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDI3OSx7InNvdXJjZS1maWVsZCI6MjI0fV0sIjYyIl0sWyI9IixbImZpZWxkIiwyNjkseyJqb2luLWFsaWFzIjoiVGFnIn1dLCJOT04gREVDRU5DRSJdXX0sImRhdGFiYXNlIjoyfSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319): dpt62 + NON DECENCE

faire une requete pour supprimer l ancienne de ces signalements, créer une nouvelle etiquette NON DECENCE et l attribuer de nouveau à ces signalements

**Comment by sfinx13** [comment]
Les tags ont été désarchivés
