### ISSUE TITLE
[BO - Etiquettes] Suppression des doublons

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2836]
Dans le cadre du #2829 

Les infos sont dans [ce tableau](https://docs.google.com/spreadsheets/d/1E_RmaPgQw5IDaYUET0cRgrOsZYMvP5kb2Dv6V_YkQV8/edit?gid=729254158#gid=729254158), onglet "doublons à supprimer".

Ce qu'il faut faire, par ligne : 
1. Garder le tag noté "à conserver" (ID colonne C)
2. Le passer en uppercase
3. Appliquer le tag à conserver aux signalements concernés par les tags à supprimer sur la même ligne (doublons à supprimer et triples à supprimer)
4. Supprimer les tags notés à supprimer (ID doublon colonne F / ID triple colonne I)

**Comment by emilschn** [comment]
On vérifie que toutes les étiquettes de double ou triple sont actives.
On fait une requête qui modifient la liaison avec l'étiquette primaire.
On archive l'ancienne étiquette.
