### ISSUE TITLE
[BO - Affectation Automatique] Mise en place des règles pour l'Hérault

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2848]
**Copie du ticket #2759 ce dernier ayant été utilisé pour la mise en place technique de la v 2.0 de l'affectation automatique**

Activation de l'affectation auto pour l Hérault en "désactivant" les signalements issus du parc public
Description du scénario attendu :
Périmètre : **signalements relevant du parc privé**

Pour les Communes disposant d'un SCHS :
* affectation automatique aux communes sur la base de leur code INSEE + CAF systématiquement (modification du Type Partenaire + ajout de tous les codes insee) + Travailleurs Sociaux (modification du Type Partenaire + ajout de tous les codes insee)

Pour les Communes sans SCHS :
* affectation automatique aux communes sur la base de leur code INSEE + CAF systématiquement () + Opérateur  (modification du Type Partenaire + ajout des codes insee) + EPCI  (modification du Type Partenaire + ajout des codes insee) + Travailleurs Sociaux (modification du Type Partenaire + ajout de tous les codes insee)

Pour les Communes à exclure :
* affectation manuelle (modification du Type Partenaire)

@hmeneuvrier
lite des communes à ne pas affecter
Clermont l'Hérault 34079
Lodève 34142
Lunel 34145
Sète 34301

**Comment by hmeneuvrier** [comment]
Proposition de specs en prenant en compte ce qui a déjà été fait pour le 93 et ce qui pourrait arriver dans le ticket #2689 , et ce qu'il faut faire pour l'Hérault (vu avec Arnaud en meet)

Création d'une entité 

**AutoAffectationRule**

| id      |territory_id       | status      | profil_declarant      |    partner_type   | code_insee_include|code_insee_exclude|parc|allocataire|
|---    |---   |---   |---    |---   |---   |--- |---   |---   |
| 0      |94       |       1|all       |       COMMUNE_SCHS|partner_list|null       |       all|all      |
|1      |35       |       1|all       |       COMMUNE_SCHS|partner_list |34500, 34600      |       prive|all      |
| 2      |35       |       1|all       |       CAF_MSA|    all  |34500, 34600      |       prive|all      |
| 3      |35       |       1|all       |       CD|    all   | 34500, 34600      |       prive|all      |
| 4      |35      |       1|all       |       EPCI|  partner_list      |null    |       prive|all      |

**status** : 0 ou 1 pour pouvoir archiver la règle sans la détruire
**profil_declarant** : les 6 profils existants + `all` + `tiers` + `occupant`
**partner_type** : l'enum ParnerType existant
**code_insee_include** : soit `all` soit `partner_list` (tous ceux définis dans le partner) soit un tableau de code insee
**code_insee_exclude** : soit `null`, soit un tableau de codeInsee à exclure (jai mis 34500, 34600 pour exemple)
**parc** : `all` / `prive` /`public`/ `non_renseigne`
**allocataire** : `all` / `non` / `oui` /`caf` /`msa`

L'id 0 correspond à ce qui existe pour le 93.
Les id 1 à 4 correspondent à ce qu'il faut faire pour l'Hérault

Faire évoluer le service AutoAssigner ensuite pour récupérer toutes les règles attachées au territoire, et trouver les partenaires qui répondent à ces règles

**Comment by arnaudchouk** [comment]
fichier des affectations auto ici
https://drive.google.com/file/d/1nxX9rHlfLOH9mRN72EQHet0cH4ZKG4E-/view?usp=drive_link

**Comment by hmeneuvrier** [comment]
Règles nécessaires pour l'Hérault MISE A JOUR

**AutoAffectationRule**

| id      |territory_id       | status      | profil_declarant      |    partner_type   | code_insee_include|code_insee_exclude|parc|allocataire|
|---    |---   |---   |---    |---   |---   |--- |---   |---   |
|1      |35       |       ACTIVE|all       |       COMMUNE_SCHS|partner_list |34079, 34142, 34145, 34301      |       prive|all      |
| 2      |35       |       ACTIVE|all       |       CAF_MSA|    all  |34079, 34142, 34145, 34301      |       prive|all      |
| 3      |35       |       ACTIVE|all       |       CD|    partner_list   | 34079, 34142, 34145, 34301      |       prive|all      |
| 4      |35      |       ACTIVE|all       |       EPCI|  partner_list      |34079, 34142, 34145, 34301    |       prive|all      |
| 5      |35      |       ACTIVE|all       |       OPERATEUR|  partner_list      |34145,34002,34003,34017,34031,34056,34063,34068,34101,34136,34162,34182,34184,34199,34203,34207,34209,34285,34289,34311,34332,34172   |       prive|all      |
| 6      |35      |       ACTIVE|all       |       CCAS|  partner_list      |34079, 34142, 34145, 34301    |       prive|all      |


Ville de Béziers Péril --> changer de type de partenaire

Changer de type les 4 opérateurs suivants : 
```
GEFOSAT Coeur d’Hérault
GEFOSAT Lunel Or Thau
GEFOSAT Pic Cevennes
In Situ
```
Pour les autres opérateurs, vérifier si les codes insee sont bien définis dans les partenaires

Pour les CCAS vérifier si les codes insee sont définis dans les partenaires

Pour les CD, vérifier si les codes insee sont bien définis dans les partenaires


Le partenaire "CD 34" n'existe pas

La CAF 34 doit être affectée automatiquement, mais pas la MSA du languedoc (et c'est un seul type de partenaire)

3 partenaires de type DDT/M, mais un seul doit être affecté (et seulement si parc public ce qui ne pose pas de pb, mais je croyais que l'Hérault ne voulait les affectations auto que sur le parc privé)

**Comment by hmeneuvrier** [comment]
Conversation en cours avec @arnaudchouk ici https://mattermost.incubateur.net/betagouv/pl/j3qkzu4a1jr9fp654rqqqexrqy

**Comment by emilschn** [comment]
On ajoute une option de configuration pour pouvoir exclure des ID de partenaires
