### ISSUE TITLE
[QA] Truc bizarre sur src/Serializer/SignalementDraftRequestNormalizer.php

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#2860]
dans supportsDenormalization, ligne 85 on a 
` return SignalementDraftRequest::class === $type || TypeCompositionLogement::class;`

et ça fait réagir phpStan car la partie de droite est toujours vraie.
https://github.com/MTES-MCT/histologe/pull/2854#discussion_r1689941739

J'ai mis un phpstan-ignore en attendant, car j'ai tenté de mettre
`return SignalementDraftRequest::class === $type || TypeCompositionLogement::class === $type;`
ce qui me parait la chose logique.
Mais dans ce cas j'ai plein de tests qui pètent et si certains sont faciles à corriger d'autres le sont moins. J'ai surtout peur des effets de bords. Et je n'ai pas du tout travaillé sur ces normaliseurs, donc je ne sais pas si TypeCompositionLogement doit être dénormalisé par ce normaliseur (et dans ce cas il faut corriger tous les tests) ou si simplement on supprime la partie de droite car seul SignalementDraftRequest doit être supporté.

Besoin de l'avis de @sfinx13 pour savoir quoi faire

**Comment by sfinx13** [comment]
Oui je confirme c'est très bizarre,faut mettre les bon DTO 
Merci @hmeneuvrier, les tests et phpstan :-D
