### ISSUE TITLE
[BO - Notification] Bouton Marquer tout comme lu fonctionne en 2 fois

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2865]
Chaque lundi, Arnaud visite ses notifications et remet tout à zéro.
Vu en visio avec lui : la plupart du temps, 
- il clique une première fois sur le bouton Marquer comme lus, la page semble se recharger, mais rien ne s'est passé
- il clique une deuxième fois et ça fonctionne

Problème de cache ?

**Comment by emilschn** [comment]
J'arrive à reproduire.

**Comment by emilschn** [comment]
La requête n'est pas très optimisée, c'est peut-être lié à ça... Je tente ça...

**Comment by emilschn** [comment]
@arnaudchouk Numa a fait des optimisations sur la requête qui marque les notifications comme lues.
Tu pourras tester une prochaine fois et voir si tu reproduits toujours ?

**Comment by arnaudchouk** [comment]
ok si c est en prod ? je teste à la prochaine connexion Histologe
mais au delà d ece phenomene, c etat surtout de se questionner sur la possibilité que ce soit la meme "logique" sur l ajout de doc qui semble passer mais ne s affiche pas

**Comment by hmeneuvrier** [comment]
@arnaudchouk tu nous diras si on peut fermer ?

**Comment by arnaudchouk** [comment]
non ca m a fait la meme chose encore

**Comment by arnaudchouk** [comment]
@hmeneuvrier ce matin ca a fonctionné MAIS
Le dashboard lui n'est pas reinitialisé, 
Notif à 0 mais les cartes elles restent avec les décomptes non actualisés

![Image](https://github.com/user-attachments/assets/70c86899-5f2f-42d0-bd62-fa24b9bf7a0a)

**Comment by hmeneuvrier** [comment]
@arnaudchouk Je ne comprends pas ta remarque. Les notifications n'ont rien à voir avec les compteurs... 🤔 
Que tu supprimes les notifications ne rendra pas les nouveaux signalements "validés"

**Comment by arnaudchouk** [comment]
@hmeneuvrier quand je marque toutes les **notifs comme lues**
ca agit comme si j avais consulté les signalements, et donc mon tableau de bord est reinitialisé
du moins c est comme ca que ca fonctionnait

**Comment by hmeneuvrier** [comment]
Vu avec @sfinx13 il y a 3 widgets synchronisés avec les notifications
![image](https://github.com/user-attachments/assets/cb715082-6268-416c-ae37-f32143a127fb)

Sans doute une régression sur la gestion du cache

**Comment by hmeneuvrier** [comment]
@arnaudchouk en effet le cache n'était plus supprimé, une correction est en relecture (ça concerne seulement 3 widgets  "nouveaux suivis", "clotures globales", "clotures partenaires" )
