### ISSUE TITLE
[Metabase]  Requete

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2880]
Identifier les signalements cloturés pour tous avec le Motif logement décent / Pas d'infraction et qui ont été cloturé par un partenaire avec un autre motif

**Comment by emilschn** [comment]
J'ai regardé, mais je n'ai pas trop d'idée pour l'instant.
Quand quelqu'un clôture pour tous 
=> ça enregistre la valeur au niveau du signalement (table signalement -> "motif_cloture")
=> ça écrase les réponses données précédemment par les autres clôtures individuelles (table affectation -> "motif_cloture")

La seule sauvegarde qu'on a, c'est dans les suivis où on a enregistré le message
```
Le signalement a été cloturé pour Partenaire 13-02 avec le motif suivant
Insalubrité
```

Mais ça me semble pas hyper fiable comme recherche...

**Comment by arnaudchouk** [comment]
j ai tente un truc via des questions mais ca explique mes resultats
j ai fait un tableau croise avec motif cloture affectation et motif cloture mais j ai que quelques ecarts hors j ai vu des signalements avec des differences

est ce qu on peut construire une requete qui analyserait les le texte "Le signalement a été cloturé pour" sans prendre en consideration  "Le signalement a été cloturé pour tous" ?
et compter ces signalements en precisant a chaque fois le texte recherche dans le suivi : insalubrite, non decence,...

ensuite croiser chacun de ces resultats avec motif de cloture

**Comment by arnaudchouk** [comment]
merci je veux precisement analyser les cas où les RT indiquent logement decent apres que des travaux aient ete faits
pour pouvoir identifier la proportion reelle de logements decents au moment du depot de signalement

**Comment by emilschn** [comment]
OK...
Du coup, tu veux que je fasse quoi ? Je modifie le deuxième pour avoir les suivis travaux faits ?
Parce que ça ne ressemble pas à ce que tu disais dans le message précédent :)

**Comment by arnaudchouk** [comment]
non non c est ok avec ca je devrais me debrouiller
pour moi mes messages sont coherents :0

**Comment by emilschn** [comment]
Dans le premier :
`et compter ces signalements en precisant a chaque fois le texte recherche dans le suivi : insalubrite, non decence,...`

Dans le deuxième :
`les RT indiquent logement decent apres que des travaux aient ete faits`

C'est ce qui me semble contraire... mais peut-être que je n'ai pas compris une partie.
Si tu t'en dépatouilles, tant mieux ! :)

**Comment by hmeneuvrier** [comment]
@arnaudchouk on peut fermer ce ticket ?

**Comment by arnaudchouk** [comment]
yes
