### ISSUE TITLE
[BO - Utilisateurs] Mise en place de droits EPCI

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2888]
## Specs fonctionnelles

On ajoute un type de droit aux utilisateurs :

    Affecter des partenaires
        si code Insee non défini ou identique au sien

Ce droit est désactivé par défaut. Le RT et le SA peuvent l'éditer.

L'auto-affectation reste consignée au menu d'auto-affectation. On ne l'édite pas ici.

### Dans la page de création/édition d'un partenaire

1/ On indique ce droit dans la liste. On ajoute une colonne `Droits`. Et si l'utilisateur a le droit, on indique `Affectation`. Sinon rien.

2/ On peut modifier dans la modale d'édition d'utilisateur.

Un toggle s'affiche avec la mention suivante :

    Cet utilisateur peut affecter d'autres partenaires à ses signalements

### Dans la liste des utilisateurs

1/ On indique ce droit (comme ci-dessus)

2/ On ajoute la possibilité d'éditer directement, comme sur la page d'un partenaire.

3/ On ajoute un filtre `Droit d'affectation` avec `Oui` / `Non` / `Tous`

## Specs Tech

On ajoute une colonne rights dans la table User.
C'est une liste comme les rôles.

**Comment by hmeneuvrier** [comment]
Voir expression des besoins dans cette conversation : https://mattermost.incubateur.net/betagouv/pl/shiq6thwoirt9jfn1gw5np5y7a

Specs à faire par les dévs

**Comment by emilschn** [comment]
## Infos avant specs

### Demande Notion

    bcp de territoires ont mis en place des EPCI pour permettre l application des politiques LHI de maniere plus efficace - imposer un RT unique territorial implique parfois un retour de la charge d affectation sur la ddt, ce qui peut etre contre productif car moins de temps pour “piloter” les EPCI

    je souhaite qu’un EPCI puisse être le RT de son perimetre (memes competences RT: affectation, creation de visites, cloture des partenaires,… + creation des partenaires de son perimetre, des comptes agents+ stat perimetres epci) 
et que le RT Dpt puisse superviser/intervenir sur l ensemble des signalements et soit le decisionnaire unique de la cloture finale  pour tous

### Info Mattermost

    Pour les EPCI : 

    - Agissent sur leur périmètre uniquement (défini par des codes INSEE)
    - Validation et affectation automatique des signalements du périmètre de l'EPCI
    - Si refus de l'affectation auto -> parcours classique avec suggestion de clôture pour le RT
    - Peut affecter le signalement aux partenaires qui ont un code INSEE dans son périmètre ET ceux n'ayant pas de code INSEE
    - Ne gère pas les partenaires
    - La clôture reste au RT

    -> Plutôt que créer un nouveau rôle, on part sur une activation de fonctionnalité pour un partenaire défini (l'EPCI)

**Comment by emilschn** [comment]
## Ancienne idée
Créer un nouveau rôle entre RT et Partenaire pour pouvoir gérer les EPCI.

Il apparait néanmoins que les territoires sont tous différents et peuvent avoir des demandes qui évoluent. Un ensemble de droits à appliquer au Partenaire, plutôt qu'un rôle fixe, semblent plus appropriés pour permettre plus de souplesse de paramétrage.

## Specs
### Specs fonctionnelles
On ajoute les droits ci-dessous aux partenaires.
Si un utilisateur est RT, ses droits prévalent sur ceux du partenaire.
Les droits sont désactivés par défaut. Le RT et le SA peuvent les éditer.

Liste des droits :
- Gérer un partenaire (modifier le partenaire, créer/éditer/supprimer des utilisateurs)
- Affecter des partenaires (ajouter / supprimer des affectations)
- Ajouter des visites (ajouter / éditer / supprimer des visites) `note : doublon avec la compétence visite ?`
- Clôturer un signalement
- Voir les statistiques de tout le territoire

L'auto-affectation reste consignée au menu d'auto-affectation. On ne l'édite pas ici.

Les utilisateurs qui sont `Admin Partenaire` deviennent juste `Partenaire`.
On supprime le rôle `Admin Partenaire`.

### Specs UI
Dans la page d'édition des partenaires, on a une liste de cases à cocher qui sont :

Les utilisateurs de ce partenaire peuvent 
- [ ] éditer ce partenaire
- [ ] affecter d'autres partenaires aux signalements qui leur sont affectés
- [ ] ajouter de visite
- [ ] clôturer les signalements qui leur sont affectés
- [ ] voir les statistiques de l'ensemble du territoire

### Specs Tech
On ajoute une colonne `rights` dans la table `Partner`.

**Comment by arnaudchouk** [comment]
Concernant les doits du sous RT - 
en 1ere etape, partir sur la synthse mattermost (ne pas donner de droit de creation de partenaire, par ex)
egalement ne pas donner de droit sur les stats autre que son perimetre

**Comment by arnaudchouk** [comment]
Procéder par versions - à compléter
V1:
* donner droits d affectations/retrait d affectation à EPCI, si souhaité par RT - activable par SA
* affectation à partenaires de son périmetre INSEE + sans INSEE
* pas de modification de Dashboard requis à ce stade (travail accompagnement RT : si EPCI clôture <> fin du dossier selon EPCI sous RT)

**Comment by mathildepoulpux** [comment]
Vu au point du 17/10 : 

-> On permet d'activer les droits d'affectation par utilisateur.
- On met un bouton radio Oui / Non dans la modale d'édition de l'utilisateur
- On met l'info sur la liste des utilisateurs + on ajoute le bouton "édition" sur la liste

-> On ne peut pas retirer le droit d'affectation aux RT
