### ISSUE TITLE
[BO - Liste des signalements] Le tri par ordre croissant / décroissant ne fonctionne pas

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2900]
Le tri Ordre Décroissant /Croissant propose un tri erroné
ex: 
Ordre décroissant
2024-70
est avant
2024-240
il faut que les references soient triees en prenant la valeur complete

**Comment by sfinx13** [comment]
Est ce que tu aurais un lien ? Je n'arrive pas à reproduire

**Comment by arnaudchouk** [comment]
C est un problème d'affichage temporaire sur mon compte
Si je ne touche à rien, le tri n'est pas bon
Si je change le type de tri et je reviens c est bon

**Comment by sfinx13** [comment]
En regardant de plus près, le tri par défaut est bien descendant. 
Il n'y'a pas de raison que tu soit le seul à l'avoir. Je verrai avec l'équipe

**Comment by emilschn** [comment]
Je ne reproduits pas non plus.
A voir ensemble à l'occasion :)

**Comment by arnaudchouk** [comment]
J essaierai de vous montrer en visio

**Comment by sfinx13** [comment]
https://github.com/MTES-MCT/histologe/issues/3022
