### ISSUE TITLE
[BO - Export des signalements] Revoir la feature d'export

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2931]
**Besoin :** 
Les agents, surtout les RT, ont besoin de faire des exports de signalements réguliers pour : 
- Préparer les comités 
- Faire leur suivi statistique trimestriel / annuel

**Problèmes observés :** 
- L'import du fichier .csv sur excel, malgré les explications dans la documentation
- L'absence de flexibilité de la fonctionnalité

**💡 Solution proposée :** 
Une page d'export dédiée sur laquelle le user peut : 
- Choisir son format d'export (+1 pour l'accessibilité)
- Choisir les colonnes qu'il souhaite exporter

**A noter :** 
- Certaines colonnes sont affichées par défaut dans le fichier
- Le fichier est envoyé par mail à l'adresse du user actif, il y a donc un email à créer

**Ressources**
- [Les spécifications](https://github.com/MTES-MCT/histologe/wiki/exporter-la-liste-des-signalements)
- [Le prototype](https://xd.adobe.com/view/b150fb06-84a3-4aa6-a9f0-943c15282a10-e403/screen/cc98a63d-72ef-474e-a00e-98ef74cc4a6e/)

**Comment by sfinx13** [comment]
https://phpspreadsheet.readthedocs.io/en/latest/
