### ISSUE TITLE
[BO - Profil utilisateur] Consulter les CGU

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2932]
Accéder aux CGU agents depuis la page profil (cf. #108 )
- [specs](https://github.com/MTES-MCT/histologe/wiki/Gerer-le-profil#consulter-les-cgu)
- [prototype](https://xd.adobe.com/view/16386013-8dac-45bf-ad9e-760d94c1612a-436b/screen/4f0803cb-c038-4d06-a904-2fdcdc049a98/)

➡️ Il s'agit du contenu [de cette page](https://histologe.beta.gouv.fr/cgu-agents) affiché dans une modale

### User flow
1. Accéder à la page profil
2. Cliquer sur `Consulter les CGU`
3. Accéder à la modale

**Comment by hmeneuvrier** [comment]
Géré dans #108 je ferme
