### ISSUE TITLE
[BO - Modale] Uniformiser les modales

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#2960]
Remarque pertinente de Hélène : 
> Je me rends compte régulièrement qu'on a des manques de cohérences sur des éléments dans le BO.
> Comme notamment ce que tu nous as fait corriger au début de l'été sur les listes de territoire.
> On en a par exemple sur les modales. (une fleche avant le titre ou pas, alignement du bouton fermer, ordre des boutons du footer etc.).

Pour les modales, le mieux est de regarder celles sur la maquette la plus récente : [le profil utilisateur]
- Pas de flèche avant le titre
- Bouton fermer en haut à droite
- Zone d'action en bas de modale _avec une ombre portée_ (edit Hélène : non pas d'ombre, ce n'est plus dans le dsfr). La zone d'action contient 2 boutons alignés à droite
    - Principal : bouton valider à droite
    - Secondaire : annuler à gauche

(https://xd.adobe.com/view/16386013-8dac-45bf-ad9e-760d94c1612a-436b/screen/3cc7be23-f308-4e32-a66c-62124a3af09a)
![image](https://github.com/user-attachments/assets/4fe6c068-e136-4ff8-8f8f-f3e1d37a14d6)

**Comment by hmeneuvrier** [comment]
Penser à l'accessibilité avant de dupliquer la "modale idéale" sur toutes les modales (notamment je pense à l'inversion dans le DOM des boutons valider et annuler pour la navigation au clavier)

**Comment by hmeneuvrier** [comment]
En fait, il n'y a plus d'ombre dans le dsfr
