### ISSUE TITLE
[Fiche Signalement] Ajout Tags

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2962]
Ajouter dans l entete de la fiche de signalement les tag infos suivants pour faciliter la prise en charge
Parc privé/ Parc public
Allocataire : Oui / Non (peut etre sous forme de code couleur Allocataire vert / Allocataire Rouge)
Bailleur Averti : Oui / Non (peut etre sous forme de code couleur Bailleur averti vert / Bailleur averti Rouge)

**Comment by hmeneuvrier** [comment]
https://mattermost.incubateur.net/betagouv/pl/mnhmdn8xqpg4xgiibp77a55aey
