### ISSUE TITLE
[BO - Filtres] Affectation partenaire -AUCUN

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#2963]
Ajouter dans le filtre partenaire le parametre "AUCUN" afin de pouvoir selectionner les signalements sans affectation

**Comment by sfinx13** [comment]
Pour @emilschn @hmeneuvrier  c'est deja géré coté back 
http://localhost:8080/bo/list/signalements/?partenaires[]=AUCUN&isImported=oui&sortBy=reference&orderBy=DESC

Sinon pour le front je suis plus partant sur un bouton comme les signalements importés plus facile à gérer que rajouter AUCUN dans la liste déroulante

![Image](https://github.com/user-attachments/assets/3d665d11-513f-4dee-a059-db9f4296c4ec)

Vous en pensez quoi ?
