### ISSUE TITLE
Refaire la migration des dates d'intervention liée aux fuseau horaire

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#2976]

**Comment by sfinx13** [comment]
Réponse de scalingo, il va donc falloir que je fasse la migration en PHP

>  Désolé pour l'attente.

> Nous avions fait le choix de ne pas importer les données de timezone dans MySQL car il est généralement considéré comme une mauvaise pratique de gérer les timezone via les base de données, on conseille plutôt de garder UTC et de faire les conversion côté applicatif.

> Quelques références sur le sujet:
RDS: https://repost.aws/fr/knowledge-center/rds-change-time-zone
Heroku: https://help.heroku.com/XKRPVR53/how-to-change-the-timezone-setting-for-heroku-postgres

> Pierre
﻿Ingénieur @ Scalingo
