### ISSUE TITLE
[BUG] crash worker, export PDF, memory limit

### ISSUE THREAD

**Issue by numew** [MTES-MCT/histologe#2982]
Le conteneur worker crashe à chaque fois qu'il redémarre, il semble que certain export PDF dans la liste d'attente soient trop lourd et provoque le crash ce qui bloque toute la file d'attente

**Comment by sfinx13** [comment]
Augmenter la limite de temps pour le redémarrage volontaire du worker à 24 heures.
https://mattermost.incubateur.net/betagouv/pl/fsipx3aogbdg3pgaaw85gmrdnr
