### ISSUE TITLE
Corriger import de données pour natureLogement / typeLogement

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#3007]
Regarder ce qu'il y a dans ces 2 colonnes.
Faire un état des lieux de leurs valeurs, et de leur utilisation (notamment interconnexion)

Voir si on conserve les deux ou pas, ce qu'on fait lors de l'import de signalement....

**Comment by emilschn** [comment]
Actuellement, on initialise les deux avec la même valeur lors de la création d'un signalement.
Par contre, si on met à jour dans la fiche signalement, on ne met à jour que NatureSignalement.

Ma proposition : ne garder que `natureLogement`, et supprimer l'autre colonne.
Si dans la colonne `natureLogement`, on a une valeur autre que celles acceptées actuellement (`['maison', 'appartement', 'autre']`), on va chercher dans la colonne `typeLogement` si on a une info qui peut aider.

Nettoyage de `natureLogement`
- on garde `maison, appartement, autre`
- on transforme `vide` et `non renseigné` en `NULL`
- les autres, on met `NULL` et on renseigne le nombre de pièces si c'est pas renseigné

Nettoyage de `typeLogement`
- on met `maison, appartement, autre` dans `natureLogement` si c'est non-défini
- `CHAMBRE, STUDIO, T1..T6, PLUS` 
  - on met `appartement` si c'est pas rempli dans `natureLogement`
  - on convertit pour renseigner le nombre de pièces
-  `Batiment/Immeuble` : on met autre si nécessaire, et on renseigne la précision
