### ISSUE TITLE
[QA][BO - Export] Rendre la structure des données des visites plus prévisible

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#3030]
https://mattermost.incubateur.net/betagouv/pl/zr95x5a3bjrj9dwgys1ammz63r

**Comment by hmeneuvrier** [comment]
Pour tester la PR https://github.com/MTES-MCT/histologe/pull/3029, j'ai cherché des signalements correspondant au souci (sinon j'avais des timeout si je prenais la liste entière).
Pour le geoloc : http://localhost:8080/bo/signalements/620d26ab719bf ref 2019-1233
Pour la visite : http://localhost:8080/bo/signalements/94fa24fc-07a9-4bc2-83ad-71c14ce2a846 ref 2024-506

Et je me demande si le souci sur la structure des données ne vient pas des séparateurs.
Dans SignalementRepository->findSignalementAffectationIterable() on utilise le séparateur `||` entre 2 interventions, et le séparateur `|` entre chaque champ d'une intervetion, ce qui donne : `status|scheduled_at|occupantPresent||status|scheduled_at|occupantPresent`
Et dans SignalementExportFactory->getVisiteStatut() on explode sur ces séparateurs pour renvoyer un statusVisite reformatté. Mais que ce passe t-il si une donnée n'est pas présente sur une intervention, si on a par exeemple  `status|scheduled_at|||status|scheduled_at|occupantPresent`
Et la boucle sur les interventions est complètement paumée.
C'est ce qui se passe sur le signalement http://localhost:8080/bo/signalements/94fa24fc-07a9-4bc2-83ad-71c14ce2a846

![image](https://github.com/user-attachments/assets/9569a5ea-ca46-4b6b-9ac1-89e02557ec14)

**Comment by mathildepoulpux** [comment]
Pour les visites : 
- Ajouter une colonne "nombre de visites" avant la colonne "Date de visite"
- Afficher les infos de la dernière visite dans les colonnes dédiées
- Modifier les noms des colonnes pour ajouter le mot "dernière" : 
    - Statut de la dernière visite 
    - Date de la dernière visite
    - Ccl. de la dernière visite
    - Comm. de la dernière visite

C'est mis à jour dans les [specs](https://github.com/MTES-MCT/histologe/wiki/exporter-la-liste-des-signalements#d%C3%A9tails-du-fichier)
