### ISSUE TITLE
[FO - Formulaire - Accessibilité - 11.1 à 11.4] Champs et étiquettes

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#3035]
- [ ] [Critère 11.1](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-1) [A] : Chaque [champ de formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#champ-de-saisie-de-formulaire) a-t-il une [étiquette](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#etiquette-de-champ-de-formulaire) ?
- [ ] [Critère 11.2](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-2) [A] : Chaque [étiquette](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#etiquette-de-champ-de-formulaire) associée à un [champ de formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#champ-de-saisie-de-formulaire) est-elle pertinente (hors cas particuliers) ?
- [ ] [Critère 11.3](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-3) [AA] : Dans chaque [formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#formulaire), chaque [étiquette](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#etiquette-de-champ-de-formulaire) associée à un [champ de formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#champ-de-saisie-de-formulaire) ayant la même fonction et répétée plusieurs fois dans une même page ou dans un [ensemble de pages](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#ensemble-de-pages) est-elle [cohérente](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#etiquettes-coherentes) ?
- [ ] Penser à afficher une aide sur le format s'il y a des contraintes pour les champs (et notamment les types de documents autorisés pour les photos et documents)
- [ ] [Critère 11.4](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-4) [A] : Dans chaque [formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#formulaire), chaque [étiquette de champ](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#etiquette-de-champ-de-formulaire) et son champ associé sont-ils [accolés](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#accoles-etiquette-et-champ-accoles) (hors cas particuliers) ?

**Comment by emilschn** [comment]
**Problème 1 et 3**
![Image](https://github.com/user-attachments/assets/7ddcce15-c3e3-4e14-b648-bdf67721a0e2)

Pour regrouper les boutons radio, on se sert d'un `fieldset` comme recommandé par DSFR.
Il y a donc une balise `<legend>` à l'intérieur.
Problème : son contenu est vide.

L'idéal, pour ne pas tout casser, serait de prévoir une légende au-dessus des boutons radio. Mais je n'ai pas d'idée.

Un avis @mathildepoulpux ? :)

**Problème 2**
A corriger

**Comment by mathildepoulpux** [comment]
- Ecran "Vous déposez un signalement" : les 2 premiers boutons radio n'ont pas de label
Ajouter en legend  `Qui est concerné par votre signalement ?`

- Ecran "Vous souhaitez signaler des problèmes sur" : les 3 premiers boutons radio n'ont pas de label
Ajouter en legend `Quelle zone est concernée ?`
