### ISSUE TITLE
[BO - Dashboard / Menu / Profil] Mettre l'avatar en rond

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#3042]
Dans le BO, la photo de profil est affichée en carré dans le menu, sur le dashboard

![image](https://github.com/user-attachments/assets/df082192-11b5-43e1-a48d-ccb0ddf3284e)

 et sur la page profil+ dans la modale d'édition
![image](https://github.com/user-attachments/assets/bc7ff7e5-3d9c-4f38-b107-2bd3cb8971c9)

sur la maquette, elle est dans un cercle avec une bordure de la couleur `blue-france-main-525` (#6A6AF4)
![image](https://github.com/user-attachments/assets/71fa4353-c2e5-4ab5-b809-df3e4a5df738)

Il faudrait les modifier pour que ça corresponde à la maquette

**Comment by hmeneuvrier** [comment]
ah ah, c'est ce que @numew m'avait dit, mais dans les specs il n'était pas question de rond, j'ai cru que c'était ton fichier qui était comme ça :)
