### ISSUE TITLE
[BO - Fiche signalement] Afficher les partenaires affectés + leur statut même après clôture

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#3044]
Problème remonté par Arnaud : 

> avec la nouvelle fiche, on ne voit plus les partenaires affectés dans la partie Activité PDLHI une fois le signalement fermé. Il faudrait les rendre de nouveau visibles notamment pour faciliter l action de reouverture

Solution : afficher les partenaires + statuts même après clôture

**Comment by numew** [comment]
@arnaudchouk @mathildepoulpux selon le fonctionnement actuel : lors la cloture les affectation sont passés au statut clôturés / à la réouvertures elles passe en attente. Donc le statut des affectations d'un signalement clôturé sera toujours cloturé (sauf a modifier plus en profondeur note fonctionnement)

**Comment by mathildepoulpux** [comment]
Oui pour le moment on le fait avec le fonctionnement actuel, ils apparaîtront tous comme "clôturés" (sauf parfois ceux avec SISH si j'ai bien compris)
