### ISSUE TITLE
[Metabase] Réparer

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#3051]
rien ne marche, a base ne semble plus connectée

**Comment by emilschn** [comment]
La base existe toujours et est fonctionnelle, c'est celle de la preprod.
La méthode de connexion est la même que pour Stop Punaises. Or, le Metabase de Stop Punaises est fonctionnel.

L'erreur est du type suivant : `Error processing query: Socket fail to connect to host`

Je sèche un peu...
Si jamais quelqu'un d'autre veut regarder @numew @hmeneuvrier @sfinx13  :)

**Comment by sfinx13** [comment]
Mise à jour de la chaine de connexion suite à l'upgrade vers MySQL8
