### ISSUE TITLE
[Ouverture Territoire] La réunion

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#3059]
Grille d'affectation à importer ici : https://docs.google.com/spreadsheets/d/1Qn5w4bVoI-oJ1QGLBt3CuUBNUEgSYBlY/edit?usp=drive_link&ouid=103115680612514741617&rtpof=true&sd=true

**Comment by hmeneuvrier** [comment]
Pas mal de complications, cf https://mattermost.incubateur.net/betagouv/pl/ggtdb6rrfinotfjnhhi6t49wuo, mais c'est fait
