### ISSUE TITLE
[Metabase] Table Suivi plus synchronisée depuis le 29 avril

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#3085]
Signalement, Intervention, User, Affectation sont OK

je n'ai pas vérifié les autres

Dernier Suivi sur Metabase id 459928

**Comment by emilschn** [comment]
Il y a une image en base 64 (signature de mail ?) dans le suivi 459929
Voir pour le modifier en base, et vérifier ensuite le lendemain si l'import fonctionne à nouveau ?

**Comment by sfinx13** [comment]
Tout est rentré dans l'ordre avec la synchro de cette nuit je ferme le ticket

**Comment by sfinx13** [comment]
> Il y a une image en base 64 (signature de mail ?) dans le suivi 459929 Voir pour le modifier en base, et vérifier ensuite le lendemain si l'import fonctionne à nouveau ?

Tout est rentré dans l'ordre avec la synchro de cette nuit je ferme le ticket
