### ISSUE TITLE
[BO - Fiche signalement] Erreur CSP

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#3097]
![image](https://github.com/user-attachments/assets/e81a7d60-05c3-45a5-b7fc-b617848442e0)

**Comment by hmeneuvrier** [comment]
Sous firefox l'erreur se présente comme ceci : 
![image](https://github.com/user-attachments/assets/ba6d5f66-ef98-4162-bd5e-b6c354b2b9c0)


Mais c'est en fait une seule et même erreur qui est liée à la présence de l'extension VueJS Devtools sur la navigateur.
Rien à voir avec tinyMCE, même si elle disparait quand on enlève tinyMCE.

Je ferme le ticket
