### ISSUE TITLE
[FO - Formulaire - Accessibilité - 11.5 à 11.8] [Audit fait] Champs de même nature

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#3115]
### Critères concernés

- [ ] [Critère 11.5](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-5) [A] : Dans chaque [formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#formulaire), les [champs de même nature](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#champs-de-meme-nature) sont-ils regroupés, si nécessaire ?
- [ ] [Critère 11.6](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-6) [A] : Dans chaque [formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#formulaire), chaque regroupement de [champs de même nature](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#champs-de-meme-nature) a-t-il une [légende](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#legende) ?
- [ ] [Critère 11.7](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-7) [A] : Dans chaque [formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#formulaire), chaque [légende](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#legende) associée à un regroupement de [champs de même nature](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#champs-de-meme-nature) est-elle pertinente ?
- [ ] [Critère 11.8](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-8) [A] : Dans chaque [formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#formulaire), les [items de même nature d'une liste de choix](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#items-de-meme-nature-d-une-liste-de-choix) sont-ils regroupés de manière pertinente ?

### Auto-audit
Dans chacun des désordres, on a des listes de checkbox. Il faudrait les regrouper dans un fieldset.
Voir ce qui est possible de faire... :)

**Comment by hmeneuvrier** [comment]
cf discussion ici : https://mattermost.incubateur.net/betagouv/pl/4hwewm18ctb93rq1yb5k9eu5nr

**Comment by hmeneuvrier** [comment]
Gauthier Fiorentino
Le "de même nature" ne porte pas sur le type de l'input, mais sur la nature du contenu :

> pouvant être regroupés par la nature des informations attendues

Tu peux tout à fait imbriquer les `fieldset`, si c'est un seul gros formulaire, tu pourrais avoir un `fieldset` par écran/catégorie, et à l'intérieur, un fieldset par checkbox qui ajoute des nouveaux champs

(pas besoin de `fieldset` si la checkbox est autoportante et ne fait pas apparaitre de nouveau champ)
