### ISSUE TITLE
[FO - Formulaire - Accessibilité - 11.9] [Audité] Intitulés des boutons

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#3119]
### Critères concernés

[Critère 11.9](https://accessibilite.public.lu/fr/rgaa4.1/criteres.html#crit-11-9) [A] : Dans chaque [formulaire](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#formulaire), l'intitulé de chaque [bouton](https://accessibilite.public.lu/fr/rgaa4.1/glossaire.html#bouton-formulaire) est-il pertinent (hors cas particuliers) ?

### Auto-audit

**Comment by hmeneuvrier** [comment]
- [ ] En cas d'ajout d'un ou plusieurs fichier, le bouton "Supprimer" n'est pas assez explicite.
Aussi : penser à préciser la photo concernée dans les intitulés de lien et de bouton. Le numéro de la photo ne semble pas suffire. À défaut de pouvoir nommer chaque photo, on peut utiliser le nom du fichier dans ce cas.

- [ ] Dans la page de Validation du signalement, les boutons "éditer" ne sont pas assez explicites.
- [ ] Dans la page de Validation le bouton "ajouter des informations" n'est pas assez explicite
- [ ] Les boutons "suivant" et "précédent" doivent-ils préciser la page suivante et la page précédente ?
- [ ] Le lien "je donne mon avis" devrait-il être plus explicite ?
