### ISSUE TITLE
[Notification mails] Contenu de la notification de nouveau suivi

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#3140]
Actuellement, le texte est le suivant, et ne veut rien dire

Bonjour,
un nouveau suivi est disponible pour le signalement **#2023-120** sur votre plateforme Histologe par **KAUTZER Rylee**

**Comment by emilschn** [comment]
@mathildepoulpux @arnaudchouk @vikieache  à vos propositions :)

**Comment by mathildepoulpux** [comment]
Bonjour,
Un nouveau suivi de {{auteur (partenaire)}} est disponible pour le signalement {{ref}}.
Rendez-vous sur votre plateforme Histologe pour le découvrir.

[bouton]
