### ISSUE TITLE
[Email] Fournir une fois de plus la liste des emails à l'équipe produit 

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#3142]
Pouvez-vous nous fournir la liste des emails qu'on envoie par rôle ? 
Ainsi que ceux qu'on envoie sur les adresses emails génériques

Merci infiniment de votre patience 😁

**Comment by numew** [comment]
J'ai mis une version ici : https://www.notion.so/Notifications-mail-11c9671af8ed8100a33cc2c77c12003b
