### ISSUE TITLE
[BUG] Suppression doc sur formulaire dépot de signalement

### ISSUE THREAD

**Issue by numew** [MTES-MCT/histologe#3145]
Les boutons de suppression de doc sur le formulaire de dépôt ne fonctionne pas si on arrive sur l'écran depuis une page suivante/précédente, un bouton d'édition ou un lien de reprise de brouillon 

![Image](https://github.com/user-attachments/assets/4641e9b5-e9c0-4a0f-8ca8-86bc113b8bf4)

**Comment by hmeneuvrier** [comment]
Je n'arrive pas à savoir si ça ne  marche pas ou si c'est un bug d'affichage. Si je clique sur "Supprimer", il ne se passe rien à l'écran, mais si je met un nouveau fichier alors le fichier que j'ai tenté de supprimer n'apparait plus après rafraichissement de la liste
