### ISSUE TITLE
[BO - Signalement] Création d'une modale avec l'historisation des affectations / acceptations / refus / clotures

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#3166]
## UX
La modale est accessible aux SA et aux RT.
Pour ne pas ralentir le chargement de la page, on ne charge l'historique qu'à la demande.

### Présentation de la liste
La liste se présente sous la forme suivante (du plus récent au moins récent) :

#### ARS
| Date | Action | Id |
| -------- | ------- | ------ |
| 19/02/2020 à 15h30 | Denis (ARS) a clôturé son affectation [Motif de cloture] |AA|
| 19/02/2017 à 11h30 | Denis (ARS) a accepté son affectation |AA|
#### CAF
| Date | Action | Id |
| -------- | ------- | ------ |
| 21/02/2017 à 10h30 | Clara (CAF) a refusé son affectation [Motif de refus] |BB|
#### DDT
| Date | Action | Id |
| -------- | ------- | ------ |
| 30/03/2024 à 11h30 | Alice (DDT) a clôturé le signalement [Motif de cloture] |-|
| 25/03/2024 à 16h30 | Alice (DDT) a supprimé l'affectation du partenaire Saint-Clar |CC|
| 18/02/2017 à 14h30 | Alice (DDT) a affecté le signalement au partenaire Saint-Clar |CC|
| 18/02/2017 à 14h30 | Alice (DDT) a affecté le signalement au partenaire CAF |BB|
| 18/02/2017 à 14h30 | Alice (DDT) a affecté le signalement au partenaire ARS |AA|
| 18/02/2017 à 14h28 | Alice (DDT) a accepté le signalement |-|
#### Saint-Clar
| Date | Action | Id |
| -------- | ------- | ------ |
| 18/02/2017 à 15h30 | Bob (Saint-Clar) a accepté son affectation |CC|

### Où se trouve la liste ?

On passe le bouton existant `Affecter des partenaires` en bleu. On ajoute un bouton blanc `Voir l'historique des affectations`.
Ce nouveau bouton ouvre une modale qui affiche l'historique des affectations.

## Tech
Dans l'état actuel des choses, pour récupérer la liste des événements sur les affectations d'un signalement, on ne pourrait le faire que sur les affectations encore existantes. 
Mais si un agent affecte, puis supprime des affectations, on n'a pas la trace, sauf en utilisant la colonne `source` dont le contenu est de type `/bo/signalements/be827998-8a26-49b0-85a6-27d17092000b/affectation/toggle`
Proposition de Numa : ajouter une colonne `signalement_id` facultative que l'on peut utiliser dans des cas comme celui-ci.

**Comment by emilschn** [comment]
## UX
La modale est accessible aux SA et aux RT.
Pour ne pas ralentir le chargement de la page, on ne charge l'historique qu'à la demande.

### Présentation de la liste
La liste se présente sous la forme suivante (du plus récent au moins récent) :
| Date | Action |
| -------- | ------- |
| 25/03/2024 à 16h30 | Alice a supprimé l'affectation de Bob |
| 19/02/2020 à 15h30 | Denis a clôturé son affectation |
| 21/02/2017 à 10h30 | Clara a refusé son affectation |
| 19/02/2017 à 11h30 | Denis a accepté son affectation |
| 18/02/2017 à 15h30 | Bob a accepté son affectation |
| 18/02/2017 à 14h30 | Alice a affecté le signalement à Bob |
| 18/02/2017 à 14h30 | Alice a affecté le signalement à Clara |
| 18/02/2017 à 14h30 | Alice a affecté le signalement à Denis |

### Où se trouve la liste ?

#### Proposition 1 : dans la modale existante d'affectation
Quand on ouvre la modale d'affectation, on peut scroller dedans pour avoir accès à l'historique des affectations

#### Proposition 2 : nouveau bouton
On passe le bouton existant `Affecter des partenaires` en bleu. On ajoute un bouton blanc `Voir l'historique des affectations`.
Ce nouveau bouton ouvre une modale qui affiche l'historique des affectations.


## Tech
Dans l'état actuel des choses, pour récupérer la liste des événements sur les affectations d'un signalement, on ne pourrait le faire que sur les affectations encore existantes. 
Mais si un agent affecte, puis supprime des affectations, on n'a pas la trace, sauf en utilisant la colonne `source` dont le contenu est de type `/bo/signalements/be827998-8a26-49b0-85a6-27d17092000b/affectation/toggle`
Proposition de Numa : ajouter une colonne `signalement_id` facultative que l'on peut utiliser dans des cas comme celui-ci.

**Comment by numew** [comment]
Je porpose de rajouter quelques précisions (motif de refus/cloture et leur description) + une colonne id pour rapidement repérer ce qui se réfère à la même affectation

| Date | Action | Id
| -------- | ------- |
| 25/03/2024 à 16h30 | Alice a supprimé l'affectation de Bob |CC|
| 19/02/2020 à 15h30 | Denis a clôturé son affectation  [Motif de cloture] [Détails de la clôture] |AA|
| 21/02/2017 à 10h30 | Clara a refusé son affectation [Motif de refus] [Message aux partenaires] |BB|
| 19/02/2017 à 11h30 | Denis a accepté son affectation |AA|
| 18/02/2017 à 15h30 | Bob a accepté son affectation |CC|
| 18/02/2017 à 14h30 | Alice a affecté le signalement à Bob |CC|
| 18/02/2017 à 14h30 | Alice a affecté le signalement à Clara |BB|
| 18/02/2017 à 14h30 | Alice a affecté le signalement à Denis |AA|

**Comment by hmeneuvrier** [comment]
3 remarques : 

- concernant le bouton, je vote pour la proposition 2

- je pense qu'il faut aussi mettre l'historique du statut du signalement

- je pense qu'il faut rajouter le nom du partenaire en plus du nom utilisateur




| Date | Action | Id |
| -------- | ------- | ------ |
| 30/03/2024 à 11h30 | Alice (DDT) a clôturé le signalement  [Motif de cloture] [Détails de la clôture] |-|
| 25/03/2024 à 16h30 | Alice (DDT) a supprimé l'affectation de Bob (Saint-Clar) |CC|
| 19/02/2020 à 15h30 | Denis (ARS) a clôturé son affectation  [Motif de cloture] [Détails de la clôture] |AA|
| 21/02/2017 à 10h30 | Clara (CAF) a refusé son affectation [Motif de refus] [Message aux partenaires] |BB|
| 19/02/2017 à 11h30 | Denis (ARS) a accepté son affectation |AA|
| 18/02/2017 à 15h30 | Bob (Saint-Clar) a accepté son affectation |CC|
| 18/02/2017 à 14h30 | Alice (DDT) a affecté le signalement à Bob (Saint-Clar) |CC|
| 18/02/2017 à 14h30 | Alice (DDT) a affecté le signalement à Clara (CAF) |BB|
| 18/02/2017 à 14h30 | Alice (DDT) a affecté le signalement à Denis (ARS) |AA|
| 18/02/2017 à 14h28 | Alice (DDT) a accepté le signalement |-|

**Comment by mathildepoulpux** [comment]
- Proposition 2 aussi concernant les boutons, une nouvelle modale ça me paraît plus lisible
- Je suis d'accord avec Arnaud, pas la peine de mettre le commentaire de la clôture, le motif suffit
- Oui ajouter le nom du partenaire

Aussi, pour la présentation des infos, personnellement je rassemblerais par partenaire pour que ce soit + lisible pour les RT.
Ca donnerait :
- **Partenaire A [statut partenaire]**
   - Agent Y (partenaire A) a clôturé
   - Agent Y (partenaire A) a accepté
   - Agent 1  (partenaire RT) a affecté
- **Partenaire B [statut partenaire]**
   - Agent X (partenaire B) a clôturé
   - Agent X (partenaire B) a accepté
   - Agent 1  (partenaire RT) a affecté

▶️ Ca me semble + simple de retrouver l'info pour savoir à quel stade en est chaque partenaire rapidement.
Vous en pensez quoi ?

**Comment by emilschn** [comment]
Pourquoi pas, si c'est plus simple.
Je me rends pas compte du besoin : si c'est l'ensemble des actions, ou si c'est chaque action des partenaires :)
Du coup, sous forme de tableau aussi, avec la date ou non ?

**Comment by mathildepoulpux** [comment]
Sous forme de tableau ça me va, avec la date oui !

Pour moi le besoin c'est vraiment de savoir quel partenaire a accepté / refusé quoi et à quel moment

**Comment by emilschn** [comment]
Vu en direct avec Mathilde : 
- les partenaires sont classés par ordre alphabétique
- il y a un tableau par partenaire
- le nom du partenaire apparait dans un titre
