### ISSUE TITLE
[BO - Fiche signalement] Ajout grille de visite

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#3175]
procéder par versions sur cette évolution (à compléter)
objectif : accompagner a minima les communes sur la 1ere étape d'instruction : la visite
* A l'affectation d'un partenaire de Type Commune/SCHS ayant la compétence Visite
* Afficher sur la fiche de signalement (emplacement à préciser), un lien de téléchargement de grille de visite, avec un Info Message
* la grille sera par défaut la Grille Standard locale (à fournir par RT) et si pas de grille locale la Grille Standard Histologe (la modularité peut être vue dans un 2nd temps)
* un modèle de courrier type de convocation à visite peut être téléchargé sur la documentation en ligne
* une page de précisions des étapes à suivre sera ajoutée dans la doc en ligne

En cas d'ajout de grilles locales par les RT, créer page BO Base documentaire pour les RT

**Comment by sfinx13** [comment]
Profiter de ce ticket pour mettre en place la table file agnostique

**Comment by hmeneuvrier** [comment]
cf conversation https://mattermost.incubateur.net/betagouv/pl/gb1m9p1kujnobbz9bfsixsrkzc

**Comment by hmeneuvrier** [comment]
## UX

### Chargement de la grille de visite territoriale
#### Prérequis

- Avoir un compte actif sur la plateforme
- Avoir le rôle Responsable territoire ou supérieur

#### Accès

La liste des étiquettes est accessible depuis le BO (/bo/etiquettes) via le menu Outils admin > Etiquettes. Elle reprend la liste des étiquettes :

    Pour le RT : toutes les étiquettes de son territoire
    Pour le Super Admin toutes les étiquettes de tous les territoires

### Affichage de la grille de visite
#### Prérequis

- Avoir un compte actif sur la plateforme
- Avoir le rôle Responsable territoire ou supérieur
- Ou avoir un rôle utilisateur, mais au sein  d'un partenaire de type `Commune/SCHS` ayant la compétence `Visites`

#### Accès
Dans la fiche signalement, dans l'onglet `Activité PDLHI` au début de la partie "Visites", un lien de téléchargement de grille de visite, avec un Info Message (_texte à déterminer_)

## Tech

**Comment by sfinx13** [comment]
Je pense qu'on peut se passer de cette table fileTerritory
Je partagerai donc les champs de fileTerritory entre `file` et `file_signalement`
* territory_id (file)
* is_active (file)
* visibillity_parameters (file ou FileSignalement)

**Comment by mathildepoulpux** [comment]
Ah oui, du coup l'affichage de ces doc pour tout le monde 😅

**Comment by mathildepoulpux** [comment]
- On ajoute les documents en dur 
- On peut avoir un document par territoire, 
- Si un document n'est pas défini pour le territoire -> on met la grille par défaut
- Il faut prévoir de pouvoir tracker l'ouverture du document (envoi d'un événement personnalisé sur Matomo ?)
- Dans la partie Visite de la fiche signalement, on ajoute le lien vers le document
- On ajoute également le lien dans la modale d'ajout de visite
