### ISSUE TITLE
[Emails] Créer un email de demande d'ajout de doc

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#3221]
Suite aux entretiens agents et RT, il est remonté que de nombreux dossiers ne contiennent pas le bail ni l'état des lieux du logement, pourtant nécessaire dans le traitement du dossier.
Suite aux retours des différents RT, il est remonté que les déclarants mettent peu ou pas de photos de leur situation, ce qui pose problème pour la préqualification des dossiers.

Il faudrait donc envoyer un email aux déclarants + occupants pour leur demander d'ajouter ces pièces.

Prérequis :
- Concerne tous les profils déclarant (en fait les conditions à vérifier trierons déjà les envois)
- Le signalement a été créé

Conditions : 
1. Le déclarant a répondu OUI à au moins une de ces questions : `bail_dpe_bail` ou `bail_dpe_etat_des_lieux` ou `bail_dpe_dpe`
     - ET il manque un ou plusieurs documents parmi les types : `Bail` ou `Etat des lieux` ou `DPE`
2. OU le déclarant a sélectionné au moins 1 désordre nécessitant des photos 
     -  ET aucune photo n'a été ajoutée

### Contenu de l'email
Objet : Documents à fournir

Corps : 
Bonjour,

Vous avez signalé un problème pour le logement situé : {{ adresse }}
Votre dossier a bien été enregistré par nos services.

Afin de nous aider à traiter au mieux votre dossier, veuillez nous fournir : 
- le ou les documents suivants : {{documents}}
- des photos pour les désordres suivants : {{desordres}}
    
Cliquez sur le bouton ci-dessous pour accéder à votre dossier et y ajouter les documents !

[Bouton]

### Variables
Le contenu de l'email est variable en fonction des conditions remplies : 
- Si condition 1, on affiche que le premier tiret
- Si condition 2, on affiche que le 2nd tiret
- Si conditions 1 + 2, on affiche tout 

- Pour la variable {{documents}}, il faudrait afficher les textes suivants, séparés par une virgule s'il y en a plusieurs
   - Type bail : `le bail du logement`
   - Type Etat des lieux : `l'état des lieux réalisé à l'entrée dans le logement`
   - Type DPE : `le diagnostic de performance énergétique du logement (DPE)` 
- Pour la variable {{desordres}}, il faudrait afficher les critères, séparés par des slash /

**Comment by hmeneuvrier** [comment]
@mathildepoulpux 2 remarques / questions : 
- on n'a pas la liste des désordres nécessitant des photos ou pas, est-ce qu'on ne met pas cette info dès qu'on n'a pas de photo de désordre ?
- plutôt que d'envoyer ce mail, est-ce qu'on ne mettrait pass ce contenu (si besoin) dans le premier mail envoyé aux usagers ? Plutôt que d'envoyer 2 mails au même moment

**Comment by mathildepoulpux** [comment]
- On peut ça revient au même
- J'y ai pensé aussi, c'est ce qu'on faisait avec la NDE et au final les gens zappaient un peu le truc. J'ai peur que ça fasse pareil et que les usagers lisent en diagonal et n'ajoutent pas les doc demandés au final. On peut tester d'envoyer 2 mails et mettre un petit temps d'intervalle éventuellement ?

**Comment by emilschn** [comment]
OK pour le temps d'intervale
De votre expérience @mathildepoulpux @arnaudchouk @vikieache c'est quoi le délai entre la réception et le traitement ?
J'imagine quie c'est hyper variable (a fortiori selon les territoires)

Est-ce que si on met une journée d'écart, c'est trop ? Ou 2h ?
Est-ce que, plutôt qu'une notification par mail, il ne faudrait pas que ce soit un suivi public automatique au bout de 30 minutes ? Pour éviter que les partenaires ne renvoient la même demande ? (si on envoie un mail à l'usager, ils n'en auront pas conscience)

Qu'en pensez-vous ? :)

**Comment by arnaudchouk** [comment]
je ne suis pas sur d avoir compris les echanges sur ce ticket

ok avec ta remarque sur la création d un suivi qui permet à tout le monde d avoir l info
le delai entre reception et traitement est tres variable donc compliqué de repondre

**Comment by mathildepoulpux** [comment]
Un suivi public ça me semble mieux effectivement !
On peut partir là-dessus, avec un délai de 30min et on ajustera la temporalité si besoin.

Pour le contenu du suivi, faut reprendre le corps de l'email et remplacer `Cliquez sur le bouton ci-dessous pour accéder à votre dossier et y ajouter les documents !` par 
`Envoyez un message et ajoutez vos documents en pièce jointes !`
`Merci,`
`L'équipe Histologe`

**Comment by hmeneuvrier** [comment]
cf https://mattermost.incubateur.net/betagouv/pl/yq7i6eetx7gdtbc3nj8rtzg7wa

**Comment by emilschn** [comment]
Recommandation Saidi : s'appuyer sur le composant messenger, il est possible de gerer les envois différé (ça nous économise un cron)
https://symfony.com/doc/current/messenger.html#extending-messenger
