### ISSUE TITLE
[BO - Signalement] Intégration Type Zonage

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#3241]
Types de zones:
* OPAH
* OPAH-RU
* RHI
* ANRU
* PIG
* Permis de louer
* Permis de diviser
* EPCI

Reflexion supplémentaire:
* Creation de perimetre secteur TS ou bailleur social

**Comment by emilschn** [comment]
On ajoute "Autre" aussi ?

**Comment by arnaudchouk** [comment]
bonne idee
