### ISSUE TITLE
[Tech - email] Système de secours en cas d'erreur d'envoi

### ISSUE THREAD

**Issue by numew** [MTES-MCT/histologe#3260]
On a ponctuellement quelque erreur lors de l'envoi de notification email (brevo KO)
Il serait intéressant lors de ces erreurs de stocker les infirmations (destinataire, contenu..) des emails qui n'ont pas pu être envoyé afin de pouvoir les relancer aprés coup

**Comment by hmeneuvrier** [comment]
https://mattermost.incubateur.net/betagouv/pl/4upfiz6jp3nj3bmg4sshswi53c
