### ISSUE TITLE
[BO - zones] Ajouter des zones à exclure sur le partenaire

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#3287]
- Ajout d'un champ zone à exclure sur le partenaire (qui doit être pris en compte dans la fonction "findByLocalization")
- Proposer un champ texte à la création/édition d'une zone en plus de l'import via fichier pour pouvoir copier-coller le contenu WKT
- Proposer un template CSV modele / Proposer le lien vers le site de création de WKT

**Comment by hmeneuvrier** [comment]
@mathildepoulpux tu pourras nous faire une proposition UX pour ce ticket, car on a peur que ce soit difficile à comprendre pour les RT cette notion de "zone à exclure" ? merci d'avance

**Comment by mathildepoulpux** [comment]
Si @emilschn notre maître Capello à nous pouvait vérifier la syntaxe sur l'onglet périmètre et la page d'édition du périmètre ce serait top 🙏
