### ISSUE TITLE
[FO] Installer sites faciles

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#3294]
On va passer la partie publique du site (hors formulaire) sur le CMS [sites faciles](https://sites-faciles.beta.numerique.gouv.fr/documentation/installation/) 

Les avantages : 
- Ca permet à l'équipe déploiement / produit d'être indépendante sur la mise à jour
- C'est 100% DSFR compatible donc accessible

➡ Besoin : installer site facile sur un environnement auquel on aurait accès pour pouvoir mettre le site en place, créer les pages et appliquer les modif qu'on veut.
Et que quand on a fini, le dev puisse récupérer le site et le déployer !

Première étape identifiée par Numa : 
> l'installation c'est clairement la première étape à étudier de notre coté car on est pas du tout sur les même techno

**Comment by sfinx13** [comment]
# Retour sur l'installation et les tests

Finalement, je n'ai pas réussi à installer le projet en local via Docker, mais je n'ai pas insisté davantage.

J'ai refait une installation sur **Scalingo**, et cela a fonctionné dès la deuxième tentative (sans avoir besoin de contacter le support). Ça va le nom le nom sites-faciles est justifié :-p  

---

## Prérequis

1. **Serveur S3** :
   - Pour les tests, j'ai utilisé le serveur S3 de staging, à terme, il faudra prévoir un bucket dédié.

2. **Serveur de mail** :
   - Configuration avec **Brevo** mais en SMTP et non API 
---

## Remarques sur le workflow

- Plutôt que de cloner le projet en local et de le pousser (comme je l'ai fait au début), la documentation recommande de **forker le projet** donc j'ai forker et lier le projet au repo forké pour le déploiement. (C'est la branche qui est à déployer mais c'est marqué dans la doc)

- Je pense également qu'il serait préférable de créer un compte GitHub dédié à **Histologe** pour les déploiements, au lieu d'utiliser des comptes personnels.

---

## Résultat et observations

Le projet est accessible ici :  
[https://histologe-sites-faciles.osc-fr1.scalingo.io/](https://histologe-sites-faciles.osc-fr1.scalingo.io/)

- **CMS** : À l'utilisation, il reste assez facile, classique et ne pose pas de difficulté particulière.
- **Back-office** : L'interface est intuitive et agréable.
---

## Sécurité
Ils ont pas encore été audité, il faudra se renseigné sur leur prévision
![image](https://github.com/user-attachments/assets/cf484396-5283-4a8a-9483-28f1643e8f7b)

## Accessibilité
Pas encore audité comme sur histologe mais ça sera bloquant pour punaises 

## Technologie utilisée

Sites-faciles s'appuie sur un CMS open-source assez populaire https://github.com/wagtail/wagtail, faudra pas hésiter à leur proposer des améliorations et de nouvelles fonctionnalités comme : 
* Proposer des champs d'autocomplétion s'appuyant sur des API
* Soumission de formulaire via une API
* ect... 
* 
Amusez-vous bien
