### ISSUE TITLE
[FO - Form] Ajouter un champ "classe énergétique"

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#3295]
Remonté lors du club agent du 24/09

Dans le FO, dans l'écran `bail-dpe`, on pourrait ajouter un champ obligatoire `Quelle est la classe énergétique de votre logement ?` avec un dropdown avec les lettres de A à G + une option "je ne sais pas"

Sous la question, ajouter un [infobulle](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/infobulle) `En savoir plus` qui se déclenche au clic.
Dans l'infobulle, mettre le texte `La classe énergétique indique si le logement consomme beaucoup d'énergie ou non. La classe A est la meilleure, la classe G est la moins bonne.`

![Image](https://github.com/user-attachments/assets/b42f5be1-a3e1-4d42-8fe7-82dfb59fe1a6)

**Comment by hmeneuvrier** [comment]
@mathildepoulpux côté BO, sous DPE ?
![Image](https://github.com/user-attachments/assets/07949318-0f99-4cae-bd47-f633a52c62df)

**Comment by mathildepoulpux** [comment]
Oui !

**Comment by emilschn** [comment]
@mathildepoulpux 2 retours là dessus :
- dans le formulaire, on n'a des listes déroulantes que pour les sélecteur d'identifiant téléphonique ; on crée un composant spécialement pour ça ? ou on utilise une autre manière de faire ?
- on n'a pas non plus de bouton `En savoir plus` entre les questions et les réponses. Les fois où on en a, ils suivent le titre de la page. On peut peut-être l'afficher autrement ?

**Comment by hmeneuvrier** [comment]
Pour moi : le mettre aussi dans la fiche de suivi usager

**Comment by mathildepoulpux** [comment]
> @mathildepoulpux 2 retours là dessus :
> 
> * dans le formulaire, on n'a des listes déroulantes que pour les sélecteur d'identifiant téléphonique ; on crée un composant spécialement pour ça ? ou on utilise une autre manière de faire ?
> * on n'a pas non plus de bouton `En savoir plus` entre les questions et les réponses. Les fois où on en a, ils suivent le titre de la page. On peut peut-être l'afficher autrement ?

- La liste déroulante ça me paraît être le + adapté, y a trop de propositions pour que ce soit des boutons radios, et un champ de saisie c'est un peu bizarre si on doit le restreindre à juste certaines lettres non ?
- On peut mettre un lien textuel (cf. ici dans [le DSFR](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/lien/)) plutôt qu'un bouton

**Comment by mathildepoulpux** [comment]
Il faudrait retirer retirer la condition d'affichage de la question sur la classe énergétique (donc l'afficher tout le temps)
cf. [ce fil](https://mattermost.incubateur.net/betagouv/pl/mx5bi7sfytymfykij18nweqq6h) sur mattermost

**Comment by hmeneuvrier** [comment]
rahhh je viens de déployer tel quel dans la v2.8.2

**Comment by mathildepoulpux** [comment]
Oui j'ai vu ! C'est pas grave, on peut le prévoir pour la prochaine MEP ?
