### ISSUE TITLE
[API Albert] Etude + Test

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#3296]
Voir mail avec les infos token + doc API
1er cas d usage : analyser les suivis reçus au fil de l'eau pour les résumés en quelques mots afin de pouvoir les afficher, en 1 ligne sur la carte signalement, du listing

Test de prompt qui avait fonctionné sur Chatgtpt
"tu es un analyste de haute qualité
ton travail est de résumer en quelques mots uniquement, le contenu d'un email pour que n'importe qui puisse savoir l'essence de son propos"

**Comment by emilschn** [comment]
On fait une v0 de test : on crée un csv avec dans une colonne les liens vers des signalements, dans la deuxième le résumé proposé
Dans un premier temps, on crée le csv via une commande, qu'Arnaud proposera aux territoires pour tester l'appétence et l'efficacité (avant de faire mieux / différemment).

On crée donc une page accessible en super admin.
On donne plusieurs paramètres :
- territoire
- maximum de signalements
- prompt de contexte pré-rempli
On envoie le csv par e-mail à l'adresse de l'utilisateur
