### ISSUE TITLE
[Table Commune] Mise à jour Commune Pierre Bénite (69)

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#3327]
La commune Pierre Bénite à fusionné avec Oullins pour devenir Oullins Pierre Bénite
Depuis il y a "Erreur : le parametre code postal et code insee ne sont pas coherents" à l enregistrement de l adresse

https://www.insee.fr/fr/metadonnees/geographie/commune/69149-oullins-pierre-benite

**Comment by hmeneuvrier** [comment]
Dans le fichier codespostaux.csv on a : 

69600,69149,Oullins,OULLINS
69310,69152,Pierre-Bénite,PIERRE BENITE

**Comment by numew** [comment]
corrigé en passant les requêtes suivantes : 
```
UPDATE `commune` SET nom='Oullins-Pierre-Bénite' WHERE `code_insee` LIKE '69149';
INSERT INTO `commune` (`id`, `territory_id`, `nom`, `code_postal`, `code_insee`, `is_zone_permis_louer`, `epci_id`) VALUES (NULL, '70', 'Oullins-Pierre-Bénite', '69310', '69149', '0', NULL); 
```
