### ISSUE TITLE
[Criticité] Tag Insalubrité malgré score faible

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#3328]
conclusions de visite vs qualif
ce signalement a le tag insalubrite
https://histologe.beta.gouv.fr/bo/signalements/79688aa9-4dfb-4a17-ae25-0b2032a773d9#situation
pourtant bien que dans description il indique un certain nombre de desordres il n a selectionne que nuisible dans le formulaire - il a une criticite de 1,47
j ai verifie le tableau excel avec les tags et desordres et il ne devrait pas avoir le tag insa

**Comment by hmeneuvrier** [comment]
Je ne reproduis pas, en refaisant à peu près le même signalement, j'ai juste la qualification `NON_DECENCE`.

**Comment by hmeneuvrier** [comment]
Pour moi : 
- mettre la base de prod en local et faire des tests (changement de situation pour provoquer le recalcul)

**Comment by hmeneuvrier** [comment]
Pas de mise à jour des fixtures. Pas de mise à jour de ces désordre dans les migrations entre février et mai

**Comment by hmeneuvrier** [comment]
@numew et sa mémoire d'éléphant ont trouvé l'origine du pb.
cf #2312  et https://github.com/MTES-MCT/histologe/pull/2316

Il y a eu un bug entre la mise en prod du formulaire (14 février, 2.0.0) et la correcction ci-dessus  (8 mars, 2.0.3) : 

> Après analyse, pour le problème des désordres liés à la composition du logement, on affectait les désordres au signalement si la réponse à certaines questions était différente de "oui".
> Par exemple "la hauteur sous le plafond du logement est supérieur à 2 mètres". Si on ne répond pas oui, on a le désordre. Donc les Tiers déclarant qui ont répondu "je ne sais pas" ont un siignalement avec ce désordre.

La correction faite le 8 mars a permis de corriger ce pb, et a corrigé les signalements créés entre le 14 février et le 8 mars en enlevant ces désordres superflus, **mais sans recalculer les qualifications ni le score**.

Plusieurs solutions possibles : 
- sur ce signalement, modifier la composition du logement 2 fois de suite pour recalculer les qualifs et le score tout en revenant à l'état normal --> immédiat, mais ne cible que ce signalement, et laisse 2 suivis internes : 
![Image](https://github.com/user-attachments/assets/bbd7a04f-0437-447e-9472-9161473dc9ea)
- faire une commande (ou une migration?) pour executer les lignes suivantes sur tous les signalements créés entre le 14 février et le 8 mars 
```
$signalement->setScore($this->criticiteCalculator->calculate($signalement));
$this->signalementQualificationUpdater->updateQualificationFromScore($signalement);
```
--> pas immédiat, cible tous les signalements qui auraient aussi ce pb, (et même ceux qui n'ont pas ce pb), ne laisse pas de suivis (ou en laisse un si on veut)

**Comment by arnaudchouk** [comment]
Ok merci :)
ce serait pas mal d opter pour la 2nde solution
