### ISSUE TITLE
[BUG] crash affichage page d'une zone quand WKT mal formaté

### ISSUE THREAD

**Issue by numew** [MTES-MCT/histologe#3443]
Si on met n'importe quoi au lieu d'un WKT bien formaté : 
- cela fait planter l'affichage du détail de la zone (erreur SQL)
- si des partenaires sont attaché à la zone fait probablement aussi planté coté fiche signalement la reqûete pour lister les partenaire dispo

**Comment by sfinx13** [comment]
Des événements sont arrivés ce matin https://sentry.incubateur.net/organizations/betagouv/issues/138461/?project=61
