### ISSUE TITLE
[BO - Statistiques]

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#442]
Réactiver l'affichage des statistiques de la plateforme, en fonction de l'utilisateur connecté.
![image](https://user-images.githubusercontent.com/60881966/179187333-7aa8fe37-2579-47a7-9113-7ae0e4dedb4c.png)

**Comment by mathildepoulpux** [comment]
C'est une story entière, je close ce ticket et on ouvrira des issues dédiées
