### ISSUE TITLE
[FO - Création signalement]

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#451]
Sur version de TEST (447) - Impossible de créer un signalement avec des pièces jointes (images et/ou documents).

**Comment by emilschn** [comment]
Deux soucis ici a priori @sfinx13 

- Problème d'envoi de mail de debug avec donnée non valide
- Problème de déplacement de fichier car le dossier n'existait pas

J'ai fait des corrections dans la branche ci-dessous : 
https://github.com/MTES-MCT/histologe/tree/fix/451-upload-when-signalement

Tu pourras me dire ce que tu en penses ?

**Comment by Alban-64** [comment]
Testé ok
