### ISSUE TITLE
[FO - Accusé de réception usager] Mail reçu par l'usager 

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#452]
Sur le premier mail reçu par l''usager  la mention de la plateforme n'est pas correcte :
![image](https://user-images.githubusercontent.com/60881966/180161639-e0c85157-eb21-4d6f-96c5-707a5d5e2c24.png)

Problème identique sur les envois d'alerte affectation ou suivi.

A voir s'il faut supprimer cette mention avec le passage à l'utilisation version unique

**Comment by emilschn** [comment]
Je propose de supprimer sur la plateforme unique ; et de toute façon, ça continuera de s'afficher sur les anciennes ?

**Comment by Alban-64** [comment]
Testé ok
