### ISSUE TITLE
[BO - Détails du signalement] - Avant validation du signalement par un Partenaire/Utilisateur

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#454]
Sur version de test 447
Lorsqu'un partenaire, connecté avec un profil utilisateur, visualise le détails d'un signalement qui lui a été affecté, POUR L'ACCEPTER OU LE REFUSER, il peut déjà éditer le signalement ou générer le pdf du signalement : cela ne devrait pas être possible (puisqu'il n'a pas encore accepté le signalement)
![image](https://user-images.githubusercontent.com/60881966/180179637-2e3aa3ce-4c29-42ba-8840-56129390a0de.png)

Proposition : ne pas afficher les deux boutons tant que le profil utilisateur n'a pas accepté le signalement.
Remarque : ces boutons doivent-ils être présents pour un profil Responsable de territoire même s'il n'a pas encore validé le signalement ?

**Comment by mathildepoulpux** [comment]
Oui on devrait avoir le même affichage qu'avec un signalement fermé : il est grisé, sans ces boutons, ni le champ suivi tant que l'agent n'a pas accepté

**Comment by Alban-64** [comment]
Problème : Après qu'un responsable de traitement ait validé un nouveau signalement, les boutons n'apparaissent pas pour ce profil. Ils doivent être présents (et même peut-être avant validation pour ce profil). 
A faire : Faire apparaitre les deux boutons "Edition" et "PDF" pour un signalement validé par profil Responsable de territoire.

**Comment by Alban-64** [comment]
Exemple après validation d'un nouveau signalement validé par responsable de territoire :
![image](https://user-images.githubusercontent.com/60881966/184308013-26549aa9-ebe7-4ff8-922f-a9ca9fefce64.png)

**Comment by Alban-64** [comment]
Testé ok
