### ISSUE TITLE
[BO - Signalement détails] Reouverture pour Admin/Pour tous

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#455]
Impossible de réouvrir un signalement fermé pour tous si il a été importé Incomplet (manque d info type tel/mail) et sous le statut Fermé
Quand click sur Reouvrir pour Administrateur ou Réouvrir pour Tous > Apparition Message popup demandant confirmation > Validation > Page d erreur

Fonctionne si on édite le signalement pour compléter les infos
Une fois les modifications validées, la réouverture fonctionne

Plateforme 06
Role Admin 
Testé sur 2021-2137 et 2021-2034

**Comment by arnaudchouk** [comment]
apres avoir vu le statut modifié sur le listing pour Admin Histologe et apres avoir attendu quelques heures, le clic sur Reouvrir pour tous a finalement fonctionné
l identifiant du signalement de l url semblait indiquer un autre signalement (2021-2137)

**Comment by arnaudchouk** [comment]
pour les tests il faudrait importer quelques signalement issus du fichier antériorité 2020 ou 2019 du departement 06
https://drive.google.com/drive/folders/1prIoXoEe1WwlqAaKLyNfpncU_CAdraKH?usp=sharing

**Comment by sfinx13** [comment]
@arnaudchouk il y a des donées du 06 sur https://histologe-staging-pr516.osc-fr1.scalingo.io/

**Comment by arnaudchouk** [comment]
test ok
