### ISSUE TITLE
[BO- Signalement Détails] Ajout Document Impossible

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#457]
Role Responsable Territoire
BUG - Ajout document impossible
Signalement **2021-2137**
Signalement **2021-2344**

Comportement attendu :
Sur le BO, il est possible d'ajouter des documents à un signalement grâce à la fonctionnalité/bouton prévu
Normalement, au clic une boite de dialogue permet de sélectionner le document puis celui ci apparait dans sur la page du signalement dans la partie prévue à cet effet, et un suivi se crée

**Precision signalements : 
créés via un Import d'une base de données (fichier csv) de signalements de 2021
importé sous le statut FERME, sans document attaché**

Signalement **2021-2137** 
Réouvert le 27/07/22, suite à finalisation d'une procédure PLOMB
Doit ajouter Document Rapport
une fois le fichier à upload sélectionné, page d'erreur

![image](https://user-images.githubusercontent.com/93710194/181481801-3f66fec5-df00-4e5e-a7ca-1c99ddbfce77.png)

![image](https://user-images.githubusercontent.com/93710194/181484870-248f9a94-ca54-4906-a1ce-be864e7c18ed.png)

![image](https://user-images.githubusercontent.com/93710194/181482077-369a6156-bf36-418d-945b-b4f8ce71498c.png)

**Signalement 2021-2144** 
Réouvert le 28/07/22, suite à finalisation d'une procédure AP
Doit ajouter Document Rapport
**Memes resultats**

L'ajout de document sur des signalements de 2022 ne semble pas poser de problème à date

**Comment by sfinx13** [comment]
Requêtes SQL exécutées sur la plateforme 06 corrigent le problème des uploads photos et documents 
des signalements importés

```
update signalement SET documents = '[]' WHERE documents is NULL;
update signalement SET photos = '[]' WHERE photos is NULL;
```
fix appliqué sur la plateforme unique #478
