### ISSUE TITLE
[BO - envoi de mails 06] - envoi multiple notifs de suivi

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#458]
SCHS Nice indique recevoir à chaque fois 5 Notifications email pour un même évènement
Piste à creuser : le compte Partenaire Nice avait été modifié suite à la demande DDT car Péril et Hygiène étaient réunis sous un seul partenaire initialement

**Comment by mathildepoulpux** [comment]
Déplacé dans le ticket #515
