### ISSUE TITLE
[BO - Listing signalement] Supprimer les critères obsolètes du filtre

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#481]
Dans le BO, le filtre "Critères" contient des options obsolètes (critères non utilisés dans le formulaire de signalement).
![image](https://user-images.githubusercontent.com/97226289/186410125-1e3f8b63-6c22-45b6-b239-c8399218fd5a.png)

Aucun signalement n'est rattaché à ces critères. 
Il faut les supprimer pour plus de clarté dans l'usage.
La liste des éléments à conserver / supprimer est dispo ici : https://docs.google.com/spreadsheets/d/1YK1WzsiG4tacCwX2fLhhW2iIUKbC6osC/edit#gid=1898423288

**Comment by sfinx13** [comment]
@mathildepoulpux tu peux tester sur https://histologe-staging.incubateur.net/
