### ISSUE TITLE
[BO - Refus signalement] Success message affiché en double

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#486]
Je suis responsable territoire
Je refuse un nouveau signalement dans le BO
Le signalement est bien refusé mais le success message s'affiche en double
![image](https://user-images.githubusercontent.com/97226289/187479845-b8f8bb4f-0edd-4df4-a8b9-88e3131c6bd6.png)

Il ne faudrait l'afficher qu'une fois

**Comment by sfinx13** [comment]
@mathildepoulpux pas reproductible
