### ISSUE TITLE
Migration des territoires existants vers plateforme unique

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#502]
Planning migration : 
- [x] 14/09 : Tarn (81) 
- [x] 14/09 : Ardennes (08)
- [x] 15/09 : Finistère (29)
- [x] 15/09 : Rhône (69) 
- [x] 15/09 : Saône et Loire (71)
- [x] 19/09 : Puy de Dôme (63), 
- [x] 19/09 : Lot et Garonne (47) 
- [x] 19/09 : Corrèze (19)
- [x] 20/09 : Corse, 
- [x] 20/09 : Haute Garonne (31) 
- [x] 20/09 : MEL (59)
- [x] 21/09 : Pau (64)
- [x] 21/09 : Alpes de Haute Provence (04)
- [x] 22/09 : Alpes Maritimes (06)
- [x] 22/09 : Bouches du Rhône (13)

**Comment by sfinx13** [comment]
## Rapport TARN
| Tables                | Lines inserted | Total |
------------------------|--------------------|--------|
| config                | 1              | 5     |
| partner               | 13             | 90    |
| user                  | 28             | 182   |
| signalement           | 11             | 17    |
| suivi                 | 49             | 53    |
| affectation           | 14             | 15    |
| tag                   | 9              | 9     |
| signalement_critere   | 36             | 60    |
| signalement_criticite | 36             | 60    |
| signalement_situation | 21             | 31    |
| signalement_tag       | 4              | 4     |

**Comment by sfinx13** [comment]
## Rapport ARDENNES


| Tables                | Lignes insérées | Total lignes |
------------------------|--------------------|--------|
| config                | 1              | 6     |
| partner               | 16             | 106   |
| user                  | 25             | 207   |
| signalement           | 22             | 39    |
| suivi                 | 47             | 100   |
| affectation           | 35             | 50    |
| tag                   | 0              | 9     |
| signalement_critere   | 189            | 249   |
| signalement_criticite | 189            | 249   |
| signalement_situation | 67             | 98    |
| signalement_tag       | 0              | 4     |

**Comment by sfinx13** [comment]
## Rapport FINISTERE

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 7     |
| partner               | 77             | 183   |
| user                  | 60             | 268   |
| signalement           | 26             | 75    |
| suivi                 | 106            | 216   |
| affectation           | 84             | 141   |
| tag                   | 0              | 9     |
| signalement_critere   | 98             | 364   |
| signalement_criticite | 99             | 365   |
| signalement_situation | 60             | 171   |
| signalement_tag       | 0              | 4     |
+-----------------------+----------------+-------+

**Comment by sfinx13** [comment]
## Rapport RHONE

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 8     |
| partner               | 19             | 202   |
| user                  | 34             | 302   |
| signalement           | 51             | 126   |
| suivi                 | 192            | 408   |
| affectation           | 67             | 208   |
| tag                   | 7              | 16    |
| signalement_critere   | 211            | 575   |
| signalement_criticite | 211            | 576   |
| signalement_situation | 99             | 270   |
| signalement_tag       | 4              | 8     |

**Comment by sfinx13** [comment]
## Rapport SAONE ET LOIRE

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 9     |
| partner               | 25             | 227   |
| user                  | 26             | 328   |
| signalement           | 54             | 180   |
| suivi                 | 296            | 704   |
| affectation           | 296            | 504   |
| tag                   | 7              | 23    |
| signalement_critere   | 219            | 794   |
| signalement_criticite | 219            | 795   |
| signalement_situation | 98             | 368   |
| signalement_tag       | 23             | 31    |
+-----------------------+----------------+-------+

**Comment by sfinx13** [comment]
## Rapport PUY DE DOME

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 10    |
| partner               | 19             | 246   |
| user                  | 62             | 388   |
| signalement           | 69             | 251   |
| suivi                 | 183            | 889   |
| affectation           | 270            | 773   |
| tag                   | 0              | 23    |
| signalement_critere   | 306            | 1107  |
| signalement_criticite | 308            | 1110  |
| signalement_situation | 152            | 524   |
| signalement_tag       | 0              | 32    |

**Comment by sfinx13** [comment]
## Rapport Corrèze

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 11    |
| partner               | 25             | 271   |
| user                  | 31             | 419   |
| signalement           | 79             | 330   |
| suivi                 | 443            | 1332  |
| affectation           | 165            | 938   |
| tag                   | 34             | 57    |
| signalement_critere   | 406            | 1513  |
| signalement_criticite | 407            | 1517  |
| signalement_situation | 171            | 695   |
| signalement_tag       | 68             | 100   |

**Comment by sfinx13** [comment]
## Rapport LOT ET GARONNE

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 12    |
| partner               | 6              | 278   |
| user                  | 22             | 446   |
| signalement           | 40             | 370   |
| suivi                 | 206            | 1548  |
| affectation           | 157            | 1096  |
| tag                   | 0              | 59    |
| signalement_critere   | 333            | 1846  |
| signalement_criticite | 333            | 1850  |
| signalement_situation | 113            | 808   |
| signalement_tag       | 0              | 101   |
+-----------------------+----------------+-------+

**Comment by sfinx13** [comment]
## Corse du sud

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 13    |
| partner               | 12             | 307   |
| user                  | 24             | 505   |
| signalement           | 55             | 432   |
| suivi                 | 478            | 2054  |
| affectation           | 183            | 1296  |
| tag                   | 0              | 60    |
| signalement_critere   | 475            | 2377  |
| signalement_criticite | 475            | 2381  |
| signalement_situation | 149            | 974   |
| signalement_tag       | 0              | 101   |

**Comment by sfinx13** [comment]
## Haute garonne

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 14    |
| partner               | 20             | 327   |
| user                  | 86             | 591   |
| signalement           | 133            | 565   |
| suivi                 | 339            | 2393  |
| affectation           | 673            | 1969  |
| tag                   | 1              | 61    |
| signalement_critere   | 764            | 3141  |
| signalement_criticite | 764            | 3145  |
| signalement_situation | 301            | 1275  |
| signalement_tag       | 0              | 101   |

**Comment by sfinx13** [comment]
## Métropole de Lille

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 15    |
| partner               | 138            | 465   |
| user                  | 300            | 891   |
| signalement           | 124            | 689   |
| suivi                 | 912            | 3305  |
| affectation           | 561            | 2530  |
| tag                   | 5              | 66    |
| signalement_critere   | 758            | 3899  |
| signalement_criticite | 758            | 3903  |
| signalement_situation | 283            | 1558  |
| signalement_tag       | 2              | 103   |

**Comment by sfinx13** [comment]
## PAU
| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 16    |
| partner               | 13             | 478   |
| user                  | 41             | 933   |
| signalement           | 350            | 1043  |
| suivi                 | 3600           | 6940  |
| affectation           | 1066           | 3626  |
| tag                   | 0              | 67    |
| signalement_critere   | 2123           | 6039  |
| signalement_criticite | 2111           | 6031  |
| signalement_situation | 876            | 2442  |
| signalement_tag       | 0              | 106   |

**Comment by sfinx13** [comment]
## Alpes de Haute provence

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 17    |
| partner               | 40             | 518   |
| user                  | 104            | 1037  |
| signalement           | 473            | 1516  |
| suivi                 | 3322           | 10262 |
| affectation           | 668            | 4294  |
| tag                   | 14             | 81    |
| signalement_critere   | 843            | 6882  |
| signalement_criticite | 838            | 6869  |
| signalement_situation | 581            | 3023  |
| signalement_tag       | 1329           | 1435  |
+-----------------------+----------------+-------+

**Comment by sfinx13** [comment]
## Rapport Alpes Maritimes

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 0              | 17    |
| partner               | 110            | 628   |
| user                  | 311            | 1350  |
| signalement           | 3398           | 4918  |
| suivi                 | 8748           | 19070 |
| affectation           | 24635          | 28944 |
| tag                   | 4              | 88    |
| signalement_critere   | 8188           | 15077 |
| signalement_criticite | 8140           | 15016 |
| signalement_situation | 4553           | 7580  |
| signalement_tag       | 58             | 1504  |
+-----------------------+----------------+-------+

**Comment by sfinx13** [comment]
## Rapport Bouches du Rhône

| Tables                | Lignes insérées | Total lignes |
|-----------------------|--------------------|--------|
| config                | 1              | 18    |
| partner               | 153              | 781   |
| user                  | 404              | 1750  |
| signalement           | 7462              | 12549 |
| suivi                 | 16104          | 35174 |
| affectation           | 12808          | 41752 |
| tag                   | 3              | 91    |
| signalement_critere   | 41311          | 56388 |
| signalement_criticite | 41172          | 56188 |
| signalement_situation | 18300          | 25880 |
| signalement_tag       | 116            | 1620  |
+-----------------------+----------------+-------+
