### ISSUE TITLE
[FO - Form étape 4] Ajout de questions

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#506]
Après validation avec les territoires, il faudrait ajouter les questions ci-dessous dans l'étape 4 (Logement) du formulaire : 

![image](https://user-images.githubusercontent.com/97226289/188868297-178369ad-4502-4314-88a4-e6c302f6e486.png)

| Question | Type | Options | Obligatoire
| :--- | :---: | :--- | :---:
| Quelle est la nature du logement ? | Dropdown | Maison / Appartement / Autre | Oui
| Quelle est la superficie du logement (en m²) ? | Champ numérique | / | Non
| Avez-vous fait une demande de relogement ou de logement social ? | Boutons radio | Oui / Non / Ne sais pas | Oui

Position des questions : 
- Nature du logement & superficie -> Après le nb d'enfants
- Demande de relogement -> dernière question

**Comment by mathildepoulpux** [comment]
Normalement en base, on a déjà des champs prévus pour toutes ces infos.

Pour l'affichage dans le BO sur la fiche signalement, c'est déjà prévu pour la superficie (N°2 sur le screenshot), 
Il faut ajouter celui sur la nature du logement (N°1 sur le screenshot)
![image](https://user-images.githubusercontent.com/97226289/188868944-be0d04e2-6d11-4937-b064-d41431c13e60.png)


Et on a déjà prévu l'affichage pour la demande de relogement (N°3 sur le screen)
![image](https://user-images.githubusercontent.com/97226289/188869077-5eae098d-41f6-470d-8eba-337c867d431b.png)

**Comment by mathildepoulpux** [comment]
Le champ "superficie" ne devrait prendre que les caractères numériques.
J'ai pu entrer des lettres et passer à l'étape suivante sans message d'erreur
![image](https://user-images.githubusercontent.com/97226289/189169363-c8bc8f82-db97-4527-99ed-099978ed5155.png)

**Comment by mathildepoulpux** [comment]
Message d'erreur à ajouter : 
Veuillez saisir la superficie du logement au format numérique.

**Comment by sfinx13** [comment]
fix effectué sur https://github.com/MTES-MCT/histologe/pull/512
