### ISSUE TITLE
[BO- Export données] -Erreur si Filtre Etiquette

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#508]
L export de signalement sur les plateformes **ne fonctionne pas si on active le filtre Etiquette**
A savoir :  les données exportées sans filtre - donc avec toutes les données rattachées au signalement - ne récupèrent pas la donnée Etiquette
La fonction Etiquette a été ajoutée sur Histologe a posteriori (probable qu'aucune mise à jour de la fonction d export n'ait été faite suite à la création de cette nouvelle fonction

![image](https://user-images.githubusercontent.com/93710194/188933482-e3fca1d4-cfb7-4810-8f05-55dcbe328d20.png)

**Comment by mathildepoulpux** [comment]
Autant faire le #666 en même temps !

**Comment by sfinx13** [comment]
@arnaudchouk ce ticket est dans la dernière livraison 1.7.3
