### ISSUE TITLE
[BO - Signalements] Lorsqu'on va sur la page 2 de la liste, le bouton de suppression ne fonctionne pas

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#534]
Suite de la PR suivante : https://github.com/MTES-MCT/histologe/pull/530

Probablement lié à un onClick qui n'est plus défini

**Comment by sfinx13** [comment]
Même bug constaté sur les plateformes territoriales.
Reproduit sur https://habitat-indigne06.histologe.fr/bo/#

**Comment by mathildepoulpux** [comment]
Toujours d'actualité au 23/01/2023 -> testé sur staging

**Comment by sfinx13** [comment]
Ce bug ne sera pas traité sur la liste actuelle (traité sur la refonte https://github.com/MTES-MCT/histologe/issues/2102)
