### ISSUE TITLE
[BO - Liste signalements + Notif] Problème responsive : boutons d'actions non visibles

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#537]
En dessous d'une certaine taille, les boutons d'action du tableau ne sont plus visible et il n'y a pas de barre de défilement horizontale.

Ca pose problème pour les territoires > déjà remonté par le Finistère 
![image](https://user-images.githubusercontent.com/97226289/190644798-dde6420d-5e4a-4e99-8e6a-f853ac4d4ebd.png)

**Comment by arnaudchouk** [comment]
meme probleme sur la page notifications
affichage à 50% pour tout lire - 
![image](https://user-images.githubusercontent.com/93710194/197980045-8b96daaa-0abd-45e5-a627-68f7c63bfdd5.png)

**Comment by mathildepoulpux** [comment]
Pour les notifs, il faudrait tronquer le contenu dans le champ après un certain nb de caractères ou alors forcer un retour à la ligne après un certain nb de caractères

**Comment by arnaudchouk** [comment]
affichage pas ok sur le listing signalements
Chrome et Firefox
![image](https://user-images.githubusercontent.com/93710194/202172423-bc9a1ca9-ebaa-41d7-a834-f91ed2ed456e.png)

**Comment by mathildepoulpux** [comment]
Testé aujourd'hui : entre 1250 px et 1600px, les boutons de droite ne sont pas visibles à l'écran
![image](https://user-images.githubusercontent.com/97226289/235693529-55fcd02d-7cf6-45c3-bb7f-c593976227db.png)

**Comment by emilschn** [comment]
@mathildepoulpux @arnaudchouk Est-ce qu'on est ouvert à "couper" le nom des partenaires à un certain nombre de caractères dans la liste ?
Parce que c'est leur nom qui fait péter l'affichage quand il y en a des longs :)
Exemple d'affichage ci-dessous (avec une limite à 20 caractères)

![image](https://user-images.githubusercontent.com/5381875/237033366-93a95185-fda1-47c8-a8eb-66b738e7b1dc.png)

**Comment by arnaudchouk** [comment]
pour moi oui

**Comment by mathildepoulpux** [comment]
Oui
