### ISSUE TITLE
[Emails] Corriger le contenu des emails existants

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#542]
## affectation_email.html.twig

**Objet :** Un nouveau signalement vous attend sur Histologe

**Corps :** 
Un nouveau signalement vous a été affecté. Vous devez l'accepter pour commencer à en assurer le suivi. 
Cliquez sur le bouton ci-dessous pour consulter ce signalement et l'accepter.

Btn: **[Accéder au signalement]** 
Si le bouton ne fonctionne pas [cliquez ici]().

*****

## login_link_email.html.twig

**Objet :** Activez votre compte sur Histologe

**Corps :** 
Votre compte Histologe vous attend ! 
Cliquez sur le bouton ci-dessous pour activer votre compte et paramétrer votre mot de passe.

Btn: **[Activer mon compte]**
Si le bouton ne fonctionne pas [cliquez ici]().

Première fois sur Histologe ? Inscrivez-vous à nos sessions de formation [en cliquant sur ce lien.](https://eeedifh.r.bh.d.sendibt3.com/tr/cl/371KmkTRT1GZWkILWFNraKk693sKgWZfXZfBTl4IwmSquATa58eCPtaJgHG2GxJrZsEoaIpWVJak7WEM2NMLajzrIiu6tzvip1HtG1h53yrH-oRvtBt5l20re4ZAgTi0jn7nk_wKXEehBpCnp5onKerWZ3l__lHoNnzgxnMDHNOQrDzs7-hE6R3AiXM2YDSkVMqUCk5D2C6ihRRE8Lu3jehzu4_mHDzUy6FeqISy1JF0ExCdIvgzO1bR6XFrQWIgo1uzKgKy-T7cd4knB6kxcU2wBGSBR_mW_mvsqnsDB9eelQZbkYdMwpqdHafNCR2aIDY)

*****

## lost_pass_email.html.twig

**Objet :** Nouveau mot de passe sur Histologe

**Corps :**
Bonjour,
Vous avez demandé la récupération de votre mot de passe pour votre compte Histologe.
Cliquez sur le bouton ci-dessous pour vous en définir un nouveau.

Btn: **[Définir mon mot de passe]**
Si le bouton ne fonctionne pas [cliquez ici]().

Si vous n'êtes pas à l'origine de cette demande, vous pouvez ignorer ce message.

*****

## nouveau_suivi_signalement_back_email.html.twig

**Objet :** Nouveau suivi sur le signalement {ID signalement}

**Corps :**
Bonjour, 
Un nouveau suivi a été ajouté sur le signalement {ID signalement} par {Nom de l'auteur}{Nom du partenaire}.

Pour consulter ce suivi, cliquez sur le bouton ci-dessous.
Btn: **[Accéder au signalement]**
Si le bouton ne fonctionne pas [cliquez ici]().

⚠️ _NB: si c'est un suivi FO du déclarant, on remplace le nom de l'auteur et du partenaire par "le déclarant"_

**Comment by mathildepoulpux** [comment]
A tester en prod

**Comment by sfinx13** [comment]
C'est en prod @mathildepoulpux
