### ISSUE TITLE
[BO - Stats] Revoir le fonctionnement du filtre de date

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#564]
Dans le BO, page de stats
Quand on veut sélectionner une plage de date , deux soucis : 
1. On n'affiche que les mois se suivant dans le filtre -> c'est corrélé : pourquoi ?
2. sélectionner une nouvelle date de début ou de fin désélectionne toute la période
Ca crée des problèmes à l'usage. 

## Cas n°1
Par défaut, la période sélectionnée est des 6 mois précédents.
Quand j'ouvre le filtre, je vois la date de début, mais pas celle de fin : 
![image](https://user-images.githubusercontent.com/97226289/191519625-5513966f-47b0-483a-b117-45a58cf5375f.png)

J'aimerais pouvoir voir, le mois de la date de début et le mois de la date de fin côte à côté, même si ce ne sont pas des mois qui se suivent.
Dans mon exemple, ça veut dire que je veux voir affiché : 
- Date de début : mars 2022
- Date de fin : août 2022
![image](https://user-images.githubusercontent.com/97226289/191520175-ed2ed97d-6c41-4f47-b466-a49a73380cbc.png)

De la même manière, quand je sélectionne un mois spécifique dans la date de début ou la date de fin : je ne veux pas que l'autre se mette à jour.
Pour éviter les problèmes de date de fin antérieure, on peut rendre inactive les dates antérieures pour la partie "date de fin"

## Cas n°2
- J'ouvre le filtre
- Je veux modifier la date de fin uniquement
- Je sélectionne une date de fin
- La date de début est désélectionnée
- Je valide > je n'ai pas de données parce que c'est pas une plage de date mais une date unique

➡️ Ca rejoint le premier cas : il faut décorréler les 2 pour simplifier l'usage

![image](https://user-images.githubusercontent.com/97226289/191523139-60b4d536-fd33-4bb6-a2cd-9a6faf2e64bd.png)

**Comment by emilschn** [comment]
Pour le cas 1, c'est le fonctionnement du plugin utilisé, pas sûr qu'on puisse faire mieux.
Pour le cas 2, c'est clairement spécifié "permet de sélectionner une plage de dates" :) Donc il n'y a pas la possibilité de choisir juste une date de début ou juste une date de fin.
Je remets dans un sprint futur.

**Comment by arnaudchouk** [comment]
Ca a l air de fonctionner
Est ce que l on ne pourrait pas ajouter les données jour en barre en plus sur le graphique (en conservant la même échelle que la courbe) ? cc @mathildepoulpux 
cela permettrait à terme de visualiser les pics de signalements
Et rendrait le graphique plus visuel lorsque la plage de jours est d'1 mois
![image](https://user-images.githubusercontent.com/93710194/194520376-547ff9ce-941b-49fc-9c3f-75cc9457c66c.png)
