### ISSUE TITLE
Plateforme Unique : Affectation Partenaires - Sélection des partenaires "génériques" 

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#566]
Affectation:
il existe 2 types de partenaires : 
* les communes : rattachées à un ou plusieurs codes insee lors de leur création
* les "partenaires" : acteurs "génériques" d'un département (ex ARS, DDT, CAF, ...), sont concernés par toutes les adresses d'un département

Spécificités : les SCHS sont des acteurs **génériques et communaux** - vérifier qu'ils sont rattachés aux bons codes insee, même si à leur enregistrement dans le BO, la liste des codes INSEE ne sont pas demandés

Pour chaque signalement, proposer dans la liste des Affectations tous les partenaires génériques du département concerné

**Comment by sfinx13** [comment]
@arnaudchouk le hotfix a été appliqué.
