### ISSUE TITLE
[BO] Revoir l'incrémentation des références nouvellement crées

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#576]
- Création d'une commande pour mettre à jour les dernières références
- Revoir la gestion de la création des nouvelles références

 Territoires impactés
- [x] Bouches du Rhône 13  (18 signalements depuis la migration)
- [x] Finistère 29 ( 1 signalement depuis la migration)

**Comment by sfinx13** [comment]
Déployé [1.2.8](https://github.com/MTES-MCT/histologe/releases/tag/1.2.8)

**Comment by arnaudchouk** [comment]
un signalement semble ne pas avoir été correctement référencé
Bouches du Rhône
2022-20 déposé le 26 Septembre 2022
Positionné entre les signalements 2022-1874 et 2022-1875
![image](https://user-images.githubusercontent.com/93710194/192727367-0b59edcc-807b-400c-9e2e-b2397df8b3df.png)

**Comment by sfinx13** [comment]
en fait le 2022-20 n'a jamais existé @arnaudchouk

**Comment by arnaudchouk** [comment]
Si on peut lui affecter une reference coherente (un numero de ref en phase avec le signalement déposé juste avant et juste après) c est mieux oui

**Comment by sfinx13** [comment]
Trop risqué de faire le décalage à la mano, manuellement je ne peut changer que celui ci, ma proposition était 2022-(N+1)

**Comment by arnaudchouk** [comment]
pour le moment ne prenons aucun risque - soit la modification rend sa référence + logique soit on la laisse inchangée
