### ISSUE TITLE
[BO] Filtre signalement KO pour Agent SCHS

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#578]
A priori aucune pop-up ne s'affiche, voir avec l'utilisateur

**Comment by emilschn** [comment]
@arnaudchouk tu as eu plus d'infos à ce sujet ?

**Comment by arnaudchouk** [comment]
Aucun retour - je viens de le relancer

**Comment by arnaudchouk** [comment]
Retour du SCHS
Les filtres fonctionnent bien - 
Je ne clôture pas encore car il veut vérifier que dans la liste Ville, il visualise également les arrondissements de Marseille, ce qui est le cas pour moi

**Comment by mathildepoulpux** [comment]
L'issue du ticket (filtre qui fonctionne pas) est résolue, la demande d'afficher les arrondissements c'est une autre issue -> on a créé une issue dédiée pour ça, à prioriser dans le projet :)
