### ISSUE TITLE
[BO] Affectation non clôturés pour les signalements fermés

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#579]
Pourquoi ces signalements ont une affectation `Admin Histologe`ouverte c'es à dire en vert
-  -0001-836
-  -0001-694
-  -0001-638

**Comment by sfinx13** [comment]
Vérifier règle de gestion dans un premier de temps

**Comment by emilschn** [comment]
Vu que les clotures datent toutes les 3 du 16/02, est-ce qu'on ne pourrait pas conclure que c'était un bug temporaire, et cloturer les affectations ?
En fouillant dans le code, je ne vois pas de chose qui laisserait penser que ça pourrait se passer dans un cas normal.

@arnaudchouk @sfinx13

**Comment by arnaudchouk** [comment]
ok

**Comment by arnaudchouk** [comment]
ok
