### ISSUE TITLE
[BO] - Signalement - Accès / Acceptation impossible 

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#583]
Territoire 06
Role Resp Territoire DDT 06, Stephane Prioul

a valide et affecte un signalement (2022-809) a son propre partenaire
 quand il veut l'accepter message d erreur
 
![image](https://user-images.githubusercontent.com/93710194/192308534-a9eb19db-10bf-4980-92f6-f3db325709a2.png)

**Comment by sfinx13** [comment]
@arnaudchouk  Au delà d'un certain nombre d'affectations la page de signalement plante. Des optimisations vont être apportés

**Comment by sfinx13** [comment]
patch appliqué en attendant le temps d'implémenter une solution viable et pérenne
voir https://github.com/MTES-MCT/histologe/pull/587/files

**Comment by sfinx13** [comment]
**TODO**  

* Ne récupérer que les informations nécessaire dans la liste des partenaire non affecté au signalement, cad l'id et le nom du partenaire
* Charger cette liste au moment ou l'utilisateur clique sur le bouton.
