### ISSUE TITLE
[FO] Corse du Sud non référencée - Service inaccessible

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#591]
Les adresses ou CP de Corse du Sud ne donnent plus accès au service de dépot de signalement
Popup affiche le message 
![image](https://user-images.githubusercontent.com/93710194/192723800-6f2b194b-cddb-461e-88ee-f4366ed15d6b.png)

Les autres territoires sont ok

**Comment by sfinx13** [comment]
Déployé sur [1.2.9](https://github.com/MTES-MCT/histologe/tree/1.2.9)
