### ISSUE TITLE
[BO] Partenaire - Impossible de voir les boutons d'actions avec plusieurs code insee

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#597]
Anomalie au niveau de la commande d'import de la grille d'affectation empêchant le passage à la ligne
Nous devons avoir un badge par code postal 

![image](https://user-images.githubusercontent.com/5757116/193320746-a2fde107-661f-4588-98b7-47e56e037094.png)

**Comment by mathildepoulpux** [comment]
Il faudrait juste ajouter une marge entre les lignes et c'est bon
![image](https://user-images.githubusercontent.com/97226289/193855940-3dd60d86-4af9-4c47-b467-0ab3b6bc80d7.png)

**Comment by sfinx13** [comment]
@mathildepoulpux marge ajouté
