### ISSUE TITLE
[BO - signalement détails] label Partenaire

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#60]
Le terme Partner doit être remplacé par Partenaire sur les pages du BO : détails du signalement, affectation de partenaires, 
![image](https://user-images.githubusercontent.com/60881966/173598767-169461e0-4b89-4e5a-81d0-625177e3a842.png)
![image](https://user-images.githubusercontent.com/60881966/173599104-e47eceb2-71c3-4240-b9d7-aa955fb8214b.png)

**Comment by Alban-64** [comment]
Affichage toujours erroné sur cloture du signalement et lors de l'enregistrement d'un suivi suite à une modification du signalement. Corriger le label Partner par Partenaire.
![image](https://user-images.githubusercontent.com/60881966/179186872-6d56cce8-90a5-4439-bb45-d6118dc31cdf.png)
![image](https://user-images.githubusercontent.com/60881966/179187054-2ed95876-9e66-4cc2-98a0-20d5aeaf122d.png)

**Comment by emilschn** [comment]
Faut-il ajuster toutes les références à "partner" dans les CGUs ?

**Comment by Alban-64** [comment]
oui également.

**Comment by Alban-64** [comment]
testé ok
