### ISSUE TITLE
[BO] -Signalement - Partenaires Communes - Export PDF/Edition signalement

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#600]
Pour les partenaire "Commune" : 

Sur la page de signalement, le bouton export pdf (bouton vert) n'est plus présent pour les rôles Admin Partenaires et Agents
Mais il l est pour les Resp Territoires (cf image)
![image](https://user-images.githubusercontent.com/93710194/193824682-afc8fca5-e9bc-47cf-99f2-e868139c1ea4.png)

Il faudrait que cette fonctionnalité soit de nouveau accessible sur la version unique

**Comment by emilschn** [comment]
@arnaudchouk 
actuellement l'édition comme l'export pdf sont accessibles pour : les admin, les admin territoires, et les personnes affectées qui ont accepté le signalement.
Le fonctionnement me semble logique.
Est-ce qu'on change ce comportement ?

**Comment by emilschn** [comment]
@arnaudchouk j'ai tenté de reproduire ton souci mais je n'ai pas réussi :)

J'ai un partenaire de type commune.
J'ai un utilisateur dedans, testé en Admin et Admin territoire.
Le signalement est affecté.
L'utilisateur voit bien les boutons.

Tu aurais un cas spécifique sur la plateforme où tu arrives à reproduire le problème ?
