### ISSUE TITLE
[BO] Notifications - Ordonnancement sur la page Notifications

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#601]
Territoire 13
Role Responsable Territoire
Agent : carole.cardot@bouches-du-rhone.gouv.fr

suite à la récupération des notifications historiques, ces dernieres s'affichent sur sa page notification sans ordre de temporalité - voir ci dessous (je n ai pas le même affichage en tant que SA) : 
![image](https://user-images.githubusercontent.com/93710194/193855899-6882b628-a2ec-457d-9a63-21a9aac17ff2.png)
![image](https://user-images.githubusercontent.com/93710194/193855958-bb94fc61-b76e-49d4-b0fd-2c44e66bc0d1.png)

**Comment by mathildepoulpux** [comment]
j'ai testé et je reproduis pas
