### ISSUE TITLE
[BO] Signalement - Date de visite erronée suite migration

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#606]
Territoire 13
Remonté par Partenaire SCHS Marseille

Les signalements pour lesquels aucune visite n'avait eu lieu avant la migration, donc avec un champs vide, sont aujourd'hui notés comme ayant réalisé une visite le 24/09
De plus ce champs n'est pas éditable/modifiable, il est donc impossible pour eux de renseigner l'information au fur et à mesure

Il faudrait corriger ces signalements - mettre le champs date de visite à vide
Et idéalement rendre ce champs éditable (nécessite peut être un ticket additionnel)

**Comment by sfinx13** [comment]
@arnaudchouk c'est corrigé, tous les signalement qui avait une date de visite à 24/09 ont désormais un champs vide

Le rendre éditable est une évolution, il faudrait donc créer un nouveau ticket

**Comment by arnaudchouk** [comment]
Bien noté - je crée une carte
