### ISSUE TITLE
[Signalement] Champ "structureDeclarant" trop court

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#610]
Notification reçue le 07/10 à 9h25

An exception occurred while executing a query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'structure_declarant' at row 1

**Comment by sfinx13** [comment]
https://sentry.incubateur.net/share/issue/6e47a51828e34fc09ccc7535ee7d1326/
