### ISSUE TITLE
[FO] Page suivi usager - Ajout d'un suivi usager sur signalement clôturé

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#611]
Territoire Bouches du Rhône
Rôle : Resp Territoire
Signalement 2022-927
https://histologe.beta.gouv.fr/bo/s/627a76fb3d762

Le Resp Territoire nous indique qu un usager a pu compléter un suivi 2 mois après la clôture du signalement.
Cela ne devrait pas être possible.

**Comment by mathildepoulpux** [comment]
A vérifier : 
- Le responsable territoire reçoit une notif avec le suivi
- Qu'en est-il des partenaires affectés ?

**Comment by mathildepoulpux** [comment]
Je me dis qu'on devrait laisser cette possibilité mais de juste mettre UN commentaire après clôture, au cas où l'usager veut contester

**Comment by arnaudchouk** [comment]
Ca peut  - ca repondrait à une v0 d une procédure d'appel
Mais reste à savoir si
on limite dans le temps
comment on e met en avant auprès des RT
comment on indique à l usager qu il a cette possibilité
