### ISSUE TITLE
[BO - Détails du signalement] - Affichage des photos

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#62]
Retour du 06 : parfois les photos sont trop grandes pour être affichées en entier sur leurs écrans et pas de scroll possible.

**Comment by mathildepoulpux** [comment]
Doublon + corrigé

**Comment by mathildepoulpux** [comment]
Un problème sur quel navigateur ?
Tu as des screenshot ?

**Comment by arnaudchouk** [comment]
sur le mien - firefox derniere version
vue histologe
![image](https://user-images.githubusercontent.com/93710194/197241051-f8da5147-da43-451f-a644-b60a36e1f726.png)
photo entiere
![image](https://user-images.githubusercontent.com/93710194/197241123-7bfa54bf-b69c-47b5-baf1-b36323b70621.png)

**Comment by emilschn** [comment]
@mathildepoulpux @arnaudchouk 
Vous êtes opposés à ouvrir dans un nouvel onglet plutôt que dans une modal invisible ?
Je pense qu'il y aurait moins de soucis...

**Comment by arnaudchouk** [comment]
pas particulierement

**Comment by mathildepoulpux** [comment]
Je préfèrerais que ça reste sur la page mais c'est pas obligé
