### ISSUE TITLE
[FO - Form étape validation] Ajouter bouton pour autoriser la visite

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#620]
Absence de la question Visite autorisée sur le formulaire usager.
Champs complété par défaut par la mention Ne sait pas sur le BO

Est ce un oubli ou un champs à réintégrer sur la plateforme unique @mathildepoulpux ?

**Comment by mathildepoulpux** [comment]
Ajouter un toggle pour valider la visite à l'étape de validation du formulaire : 

![image](https://user-images.githubusercontent.com/97226289/195295896-4c40d74b-9268-403a-af74-557ada8b42c8.png)

Message : _En validant mon signalement, j'autorise les services compétents à programmer et effectuer, si nécessaire, une visite de mon domicile pour évaluer les désordres._

Erreur (si non activé) : _Vous devez accepter l'autorisation de visite pour transmettre votre signalement._

**Comment by emilschn** [comment]
J'étais en train de travailler là-dessus, mais je suis pas trop sûr parce que si c'est un tiers-déclarant, c'est un peu bizarre comme formulation ; et c'est un peu bizarre que le tiers accepte la visite pour l'usager, non ?

**Comment by arnaudchouk** [comment]
tu as raison
mais s il n accepte pas la visite il ne se passera rien - il doit avoir l autorisation pour déposer en tant que tiers, on peut peut etre partir du principe qu il demandera aussi l autorisation de visite, non?

**Comment by emilschn** [comment]
Mais il faut peut etre juste changer le texte du message, non ? :)

**Comment by arnaudchouk** [comment]
quand tu es un tiers declarant tu as deja ca
"Je certifie avoir le droit de déposer un signalement pour le compte d'un tiers."
Pour éviter un affichage différencié selon le type de déclarant on pourrait peut etre ecrire :
Message : En validant mon signalement, j'autorise les services compétents à programmer et effectuer, si nécessaire, une visite **au** domicile pour évaluer les désordres. non?

**Comment by arnaudchouk** [comment]
test concluant en tant qu occupant et tiers
Remarque Wording :
"En validant mon signalement, j'autorise les services compétents à programmer et effectuer, si nécessaire, une visite au domicile pour évaluer les désordres. "
Est ce que l'on raccourcirait pas :
"j'autorise les services compétents à programmer et effectuer, si nécessaire, une visite au domicile pour évaluer les désordres. "

**Comment by emilschn** [comment]
@mathildepoulpux ?

**Comment by mathildepoulpux** [comment]
On peut réduire si vous voulez
