### ISSUE TITLE
Contrôle manquant sur le numéro allocataire

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#621]
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'num_allocataire' at row 1"
https://sentry.incubateur.net/share/issue/6e47a51828e34fc09ccc7535ee7d1326/

L'usager à rempli sur le numéro allocataire `Doit régler un problème avec la caf`

**Comment by emilschn** [comment]
on fait une vérification front pour ça ?
