### ISSUE TITLE
[BO - Cloture] Aucun motif sélectionné par défaut

### ISSUE THREAD

**Issue by Tibo-aplus** [MTES-MCT/histologe#631]
Lorsque l'on cloture un signalement, le motif est par defaut sur RESOLU et permet la saisie sans y faire attention
Idealement il faudrait que le motif soit sur "A définir", et que la saisie soit grisée tant que le motif n est pas selectionné

-> Pour la clôture par partenaire & pour la clôture globale, peu importe le rôle

**Comment by mathildepoulpux** [comment]
Rôle : agent et supérieur
1. Dans le BO, sur une fiche signalement
2. Je clique sur "clôturer"
3. Sur le champ "motif", le motif "problème résolu" est sélectionné par défaut
**-> Il faut que, par défaut, aucun motif ne soit sélectionné et qu'on mette "Sélectionner un motif" en placeholder dans le champ** 

![image](https://user-images.githubusercontent.com/97226289/223192621-93c57304-5a7d-4e3d-b478-09b707460546.png)

**Comment by hmeneuvrier** [comment]
Fait en même temps que l'ajout de motifs de cloture  #810 dans la branche https://github.com/MTES-MCT/histologe/tree/feature/810-compl%C3%A9ter-motifs-de-cloture-rtpartenaires
