### ISSUE TITLE
[BO - Liste signalements] Permettre de filtrer les partenaires par territoire pour le SA

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#634]
Quand on est super admin, dans les filtres du listing de signalement il faudrait n'afficher que les partenaires du territoire sélectionné (quand un territoire est sélectionné) pour simplifier la navigation.

Exemple : je sélectionne "Ain" dans le filtre territoire > Seulement les partenaires de ce territoire sont affichés dans le filtre "Partenaires"

**Comment by sfinx13** [comment]
Je ferme le ticket sera fait dans le nouveau formulaire
