### ISSUE TITLE
[BO - Export] Revoir l'export des signalements

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#666]
### Prérequis
Avoir un compte actif sur la plateforme (peu importe le rôle)

### User flow
1. Se rendre sur le listing des signalements
2. Appliquer les filtres désirés
3. Cliquer sur "Exporter les résultats"

### Conséquences
Le fichier .csv des résultats est téléchargé sur l'appareil

### Formatage du fichier
- Type : csv
- Encodage : UTF8
- Nom du fichier : export-histologe-DDMMYYY (mettre la date du jour)
- Séparateur : point-virgule

### Colonnes
Le tableau ci-dessous détaille les colonnes à mettre dans le fichier et leur ordre d'affichage.
La colonne "Commentaire" précise le format de certaines données, notamment les colonnes où le texte doit être échappé car il peut contenir des points-virgules

Position | Nom colonne | Champ base | Description | Commentaire
-- | -- | -- | -- | --
1 | Référence | id | Référence du signalement | Exemple : 2022-125
2 | Déposé le | createdAt | Date de création du signalement | format DD/MM/YYYY
3 | Statut | statut | Statut du signalement (nouveau / en cours / fermé / refusé) |  
4 | Description | details | Description du signalement | Echapper le texte
5 | Nom | nomOccupant | Nom de l'occupant |  
6 | Prénom | prenomOccupant | Prénom de l'occupant |  
7 | Téléphone | telOccupant | Téléphone de l'occupant | Format +33606060606
8 | Téléphone | telOccupantBis | Téléphone secondaire de l'occupant | Format +33606060606
9 | Email | mailOccupant | Adresse email de l'occupant |  
10 | Adresse | adresseOccupant | Adresse du logement |  
11 | Code postal | cpOccupant | Code postal du logement |  
12 | Commune | villeOccupant | Commune du logement |  
13 | Code INSEE | inseeOccupant | Code INSEE de la commune du logement |  
14 | Etage | etageOccupant | Etage du logement |  
15 | Escalier | escalierOccupant | Escalier du logement |  
16 | Appartement | numAppartOccupant | Numéro d'appartement du logement |  
17 | Complément | adresseAutreOccupant | Complément d'adesse du logement |  
18 | Situations | situations | Situations (famille de désordres) déclarées | Séparées par un \|Echapper le texte
19 | Désordres | criteres | Critères (désordres) déclarés | Séparés par un \|Echapper le texte
20 | Etiquettes | Etiquettes | Les étiquettes associées au signalement | Séparées par un \|Echapper le texte
21 | Photos | photos | Oui / Non |  
22 | Documents | documents | Oui / Non |  
23 | Propriétaire averti | isProprioAverti | Propriétaire averti : oui ou non |  
24 | Nb adultes | nbAdultes | Nombre d'adultes dans le logement |  
25 | Nb enfants -6 ans | nbEnfantsM6 | Nombre d'enfants de moins de 6 ans dans le logement | Si pas d'info écrire "Non renseigné"
26 | Nb enfants + 6 ans | nbEnfantsP6 | Nombre d'enfants de plus de 6 ans dans le logement | Si pas d'info écrire "Non renseigné"
27 | Allocataire | isAllocataire | CAF / MSA / Non / Ne sais pas |  
28 | Numéro d'allocataire | numAllocataire | Le numéro d'allocataire | Si pas d'info écrire "Non renseigné"
29 | Nature logement | natureLogement | Appartement / maison / autre |  
30 | Superficie | superficie | Superficie du logement en m² | Si pas d'info écrire "Non renseigné"
31 | Nom bailleur | nomProprio | Nom du propriétaire |  
32 | Logement social | isLogementSocial | Le logement est un logement social : oui / non / ne sais pas |  
33 | Préavis de départ | isPreavisDepart | Le préavis de départ a été donné : oui / non / ne sais pas |  
34 | Demande de relogement | isRelogement | Une demande de relogement est en cours : Oui / non / ne sais pas |  
35 | Déclarant tiers | isNotOccupant | Il s'agit d'un déclarant tiers : oui / non |  
36 | Nom tiers | nomDeclarant | Nom du déclarant tiers |  
37 | Structure tiers | structureDeclarant | Structure du déclarant tiers | Echapper le texte
38 | Lien tiers occupant | lienDeclarantOccupant | Relation entre déclarant tiers et occupant |  
39 | Handicap | isSituationHandicap | Une personne en situation de handicap dans le logement : oui / non |  
40 | Criticité au dépôt | scoreCreation | Score de criticité à la création du signalement |  
41 | Visite le | dateVisite | Date de la visite du logement | format DD/MM/YYYY
42 | Occupant présent visite | isOccupantPresentVisite | L'occupant était présent pendant la visite : oui / non |  
43 | Dernière MAJ le | modifiedAt | Date de dernière modification du signalement | format DD/MM/YYYY
44 | Clôturé le | closedAt | Date de clôture du signalement | format DD/MM/YYYY
45 | Motif de clôture | motifCloture | Motif de clôture du signalement |  
46 | Criticité à la clôture | scoreCloture | Score de criticité à la clôture du signalement |

**Comment by mathildepoulpux** [comment]
Voir si possible de choisir le format pour l'avoir en xls.

**Comment by mathildepoulpux** [comment]
cf. corriger aussi le ticket #508

**Comment by sfinx13** [comment]
@mathildepoulpux tout a été revu sauf le numéro de téléphone, il faudrait mettre plus de contrôle à la saisie et on a aussi les numéro de la réunion, je ferme le ticket.
Créer un ticket dédié sur le format de téléphone avec prise en compte des DOM-TOM
