### ISSUE TITLE
[Territoire 69] Liste des communes à autoriser

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#673]
Le Rhône ayant une organisation spéciale, c'est la métropole de Lyon qui a la compétence pour gérer / piloter les signalements sur ses communes (et pas la DDT).
Aussi, il faudrait autoriser le dépôt de signalement sur ce territoire uniquement pour les communes suivantes : 

La liste est aussi [dispo sur le drive 🔗 ](https://docs.google.com/spreadsheets/d/1y6vebSTSwmOvxUoqPiwzfPmtXTJMzjn40pAbdMU5bi4/edit#gid=0)

Commune | Code INSEE | Code postal
:-- | :--: | :--:
Givors | 69091 | 69700
Grigny | 69096 | 69520
Lyon | 69123 | 69000
Lyon 1er arrondissement | 69381 | 69001
Lyon 2e arrondissement | 69382 | 69002
Lyon 3e arrondissement | 69383 | 69003
Lyon 4e arrondissement | 69384 | 69004
Lyon 5e arrondissement | 69385 | 69005
Lyon 6e arrondissement | 69386 | 69006
Lyon 7e arrondissement | 69387 | 69007
Lyon 8e arrondissement | 69388 | 69008
Lyon 9e arrondissement | 69389 | 69009
Lyon Satolas aéroport | 69901 | 69125
Oullins | 69149 | 69600
St Fons | 69199 | 69190
St Genis les Ollieres | 69205 | 69290
St Priest | 69290 | 69800
Vénissieux | 69259 | 69200
Villeurbanne | 69266 | 69100

**Comment by mathildepoulpux** [comment]
Je peux accéder au formulaire en essayant des CP qui sont pas dans le tableaux par exemple : 
69362
69250
69014

Normalement, si je rentre un CP qui n'est pas dans le tableau, je dois avoir la modale m'indiquant que le service n'est pas dispo sur mon territoire

**Comment by emilschn** [comment]
Donc on fait une première vérification sur CP au premier écran
Et on fait une deuxième vérification sur le code INSEE lors de la saisie de l'adresse ?

**Comment by emilschn** [comment]
Vu ensemble : faire la vérification lors de la saisie manuelle de CP

**Comment by mathildepoulpux** [comment]
Sur le formulaire, si j'ajoute le CP à la main, je suis bloquée pour tous les CP du département.

Exemple je renseigne le CP de la ville de Lyon (69002) : 

![image](https://user-images.githubusercontent.com/97226289/202163583-1465c8af-ef7a-4a51-94cf-3ee605ef6afb.png)


J'ai la modale d'avertissement quand je veux passer à l'étape 2: 

![image](https://user-images.githubusercontent.com/97226289/202163776-305d1ae4-c1cc-413c-acea-1c3dc9b3dafa.png)

**Comment by emilschn** [comment]
Cas à résoudre : 
- Je cherche une adresse dans le champ de recherche
- Je sélectionne une adresse
- Je change le code postal

Si on change le code postal, il faudrait supprimer le code Insee et le rechercher à nouveau pour être sur qu'il soit valide.
