### ISSUE TITLE
[Statistiques] Refactoriser pour avoir un fonctionnement commun entre back et front

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#675]
Les statistiques front sont mieux découpées. Il faudrait l'appliquer au back.

Modifier les fonctionnalités :

**Pour les stats backs :**
- une case à cocher "refusés" (comme actuellement)
- une case à cocher "archivés" (uniquement pour SA)
- une carte pour le décompte des refusés
- une carte pour le décompte des archivés (uniquement pour le SA ?)

**Pour les stats front :**
- on compte les "refusés" dans toutes les stats, et on ajoute le statut dans le graph
- on ne compte pas les archivés, nulle part

**Comment by arnaudchouk** [comment]
sur le meme sujet :
6 signalements nouveaux sur cote d or
![image](https://user-images.githubusercontent.com/93710194/203794939-8e5e1574-fee9-4f9a-86d7-ce5afcd07354.png)
mais seuls 4 nouveaux sur l onglet stats 
![image](https://user-images.githubusercontent.com/93710194/203795229-dc4ae49b-c6fb-4caa-a3eb-3e4c8dfe7240.png)
