### ISSUE TITLE
[FO - Saisie de téléphones]

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#69]
**Is your feature request related to a problem? Please describe.**
Proposer un masque de saisie ou aide à la saisie des numéros de téléphone. Par exemple, avec des espaces : 02 02 02 02 02 ou autre
Afin d'éviter les blocages lors de la saisie.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Prendre en compte les numéros étrangers par exemple :  +32478557043

**Comment by mathildepoulpux** [comment]
- [ ] Permettre la saisie de numéro de téléphone au format français : exemple 0606060606
- [ ] Permettre la saisie de numéro au format international : exemple +33606060606
- [ ] Permettre la saisie de numéro avec espaces : exemple 06 06 06 06 06
- [ ] Permettre la saisie de numéro avec des points : exemple 06.06.06.06.06 et transformer les points en espaces

**Comment by sfinx13** [comment]
Ticket fermé et remplacé par 
https://github.com/MTES-MCT/histologe/issues/1675
