### ISSUE TITLE
[BO - Notif] Historique remonte trop loin dans le temps

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#693]
Dans la liste des notifications, on est censé conservé les notif lues pendant 30 jours (cf. #176 )
Nous sommes le 08/11/2022 toutes mes notifs sont lues
Or, j'ai des notifs qui remontent jusqu'au 07/09/2022, soit 2mois avant : 
![image](https://user-images.githubusercontent.com/97226289/200589758-e8351633-0ea3-40e6-9e7c-fbc8d97f1456.png)

**Comment by sfinx13** [comment]
La tache a été planifié 1 fois par semaine, un message sera fait avec suppression des notifs de plus de 30 jours
