### ISSUE TITLE
[BO - Détails signalement] - Accès documents sur signalement cloturé

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#70]
**Is your feature request related to a problem? Please describe.**
Sur un signalement Cloturé, rendre possible le téléchargement de document ou consultation photos (aux partenaires affectés et responsables de territoires)

**Describe the solution you'd like**
Au clic, document accessible.

**Describe alternatives you've considered**

**Additional context**

**Comment by mathildepoulpux** [comment]
Corrigé
