### ISSUE TITLE
[BO] Envoyer une notification par mail à tous les utilisateurs ayant désactivé leur notifications avec un mail partenaire absent

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#706]
Certains signalements risque de ne trouver aucun utilisateur à notifier si aucun utilisateur décide de recevoir un email et que le mail partenaire est présent.

- Sauf si un email générique est enregistré pour le partenaire

**Comment by Tibo-aplus** [comment]
Faire extraction des utilisateur concernés et l'envoyer aux responsables de territoires

**Comment by hmeneuvrier** [comment]
Requête : `SELECT * FROM `partner` p WHERE p.is_archive = 0 AND (p.email IS null OR p.email = '') AND NOT EXISTS (SELECT NULL FROM `user` u WHERE u.partner_id = p.id AND u.is_mailing_active = 1 AND u.email IS NOT null AND u.email != '' AND u.statut = 1 GROUP BY u.partner_id);`

**Comment by hmeneuvrier** [comment]
Csv fourni sur Mattermost (572 résultats)

**Comment by hmeneuvrier** [comment]
SELECT p.id, p.nom, p.email, p.territory_id, t.name AS territory_name, u.nom, u.statut, u.email, u.is_mailing_active FROM partner p 
LEFT JOIN territory t ON t.id = p.territory_id
LEFT JOIN user u ON u.partner_id = p.id
WHERE p.is_archive = 0 AND (p.email IS null OR p.email = '') 
AND NOT EXISTS (SELECT NULL FROM user u WHERE u.partner_id = p.id AND u.is_mailing_active = 1 AND u.email IS NOT null AND u.email != '' AND u.statut = 1 GROUP BY u.partner_id);
