### ISSUE TITLE
[BO - Partenaire] - Partenaire "Habitat Porto Vecchio"

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#714]
Le partenaire semble dans sa totalité buggé
2 comptes user sont présents mais sans détail de derniere connexion, et précisés comme non activés alors qu'ils l'étaient à l'origine sur l ancienne plateforme

Cela génère un bug lorsque l'on essaie de créer un nouvel utilisateur (charlotte.breton@portivechju.corsica), en précisant que les 2 comptes historiques affichés sur la page sont déjà existants 
![image](https://user-images.githubusercontent.com/93710194/203103401-440e69fd-1e76-4cc4-aa58-93d4df7376a8.png)

A priori, les 2 utilisateurs peuvent se connecter malgré tout mais ne peuvent accéder au signalement

**Comment by mathildepoulpux** [comment]
Dans la mesure où on a revu la création de partenaire depuis, je pense que c'est corrigé
