### ISSUE TITLE
Procéder à des vérifications techniques automatiques de la sécurité du service

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#718]
Lors du développement du service et, autant que possible, dans le cas de l'achat d'un service sur étagère, procéder à des tests techniques automatiques de la sécurité du service.
Cette mesure permet de vérifier rapidement l'existence de vulnérabilités non corrigées parmi les vulnérabilités les plus connues.

**Comment by emilschn** [comment]
GitHub se charge automatiquement de vérifier les version des dépendance.
- Il lui arrive de créer des PR
- Il propose un onglet Code Scanning pour certaines failles détectées

De plus, la CI (SonarCloud, ...) tourne tous les jours et à chaque push.

**Comment by hmeneuvrier** [comment]
Oui c'est fait à travers la CI à la ligne 106 et ajouté à cela que features de github (onglet Sécurité) + ce que beta a mis en place (sonar entre autre)
