### ISSUE TITLE
Rendre public une procédure permettant de signaler un problème de sécurité

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#719]
Fournir publiquement une procédure permettant à une personne ou à une entité de signaler un problème de sécurité concernant le service numérique. Cette procédure doit préciser les conditions dans lesquelles un problème de sécurité peut être identifié et signalé et fournir un moyen non nominatif de contacter l'équipe en charge du service ou de sa sécurité (ex. email, formulaire de contact).
Cette mesure facilite l'identification et le traitement de problèmes de sécurité concernant le service.

**Comment by emilschn** [comment]
1/ Améliorer le readme pour donner des informations pour contribuer

2/ Mettre un lien dans le footer vers GitHub

**Comment by hmeneuvrier** [comment]
https://github.com/MTES-MCT/dialog/blob/main/docs/getting-started.md
