### ISSUE TITLE
[BO - Détails du signalement] - Affichage des images

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#72]
**Is your feature request related to a problem? Please describe.**
Sur certains écran, les images affichées en taille réelle sont trop grandes pour pouvoir être consultées en entier.

**Describe the solution you'd like**
A minima, permettre le scrolling sur l'écran pour ces images. 

**Describe alternatives you've considered**
Proposer un affichage adapté à la taille de l'écran ?

**Additional context**

**Comment by mathildepoulpux** [comment]
Corrigé
