### ISSUE TITLE
Mettre en œuvre une procédure de suppression des comptes inactifs

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#720]
Configurer le service en vue de prévoir la suppression régulière des comptes d'accès inactifs, en priorisant la suppression des comptes d'administration. Informer les personnes concernées avant toute suppression de compte.
Cette mesure permet d'éviter en priorité que des comptes demeurent actifs sans raison valable, afin de réduire le nombre de comptes susceptibles d'être usurpés par un acteur malveillant.

**Comment by emilschn** [comment]
A voir au niveau fonctionnel avec Arnaud et Mathilde.

Envoyer un mail qui indique de l'inactivité d'un compte pendant X mois.
- avertir suppression dans X jours
- proposer suppression directe

**Comment by arnaudchouk** [comment]
ok
la cnil recommande 2 ans - ca me parait long - on peut partir sur 1 an
alerte et proposition fermeture à 9 mois ?

**Comment by numew** [comment]
Ce qu'on pourrait faire et qu'on voit sur d'autres plateformes ce serait de 

- Envoyer un email en disant : votre compte Histologe va être supprimé dans X jours parce que pas d'activité depuis + d'un an. Si vous souhaitez le garder veuillez vous connecter (lien vers la page de loginl)
- Le même mail à j-7 
- Archiver le compte si rien n'a été fait

**Comment by mathildepoulpux** [comment]
Voir [cette conversation Mattermost](https://mattermost.incubateur.net/betagouv/pl/5ucgpdwwb3yuxd3jz1ohk3cm4o)
