### ISSUE TITLE
Fixer des contraintes de longueur et de complexité des mots de passe

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#721]
Fixer des règles de longueur et de complexité des mots de passe lors de la création d'un mot de passe ou de son renouvellement par un utilisateur ou un administrateur. Lorsque cela est possible, configurer le service pour interdire les mots de passe faibles.
Cette mesure permet de diminuer le risque de découverte et l'usurpation de mots de passe par des acteurs malveillants, par exemple en testant plusieurs mots de passe sur la base de mots du dictionnaire.

**Comment by emilschn** [comment]
Nécessite maquette front, à mettre en prio haute ensuite.

Prévoir une procédure de renouvellement généralisé des mots de passe avec un mail d'information.

**Comment by mathildepoulpux** [comment]
## Page de définition / reset du mot de passe
Utiliser le modèle [Création ou modification de mot de passe associé à un compte.](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/mot-de-passe/) du DSFR.

![image](https://github.com/MTES-MCT/histologe/assets/97226289/1a9c54f8-dfa3-4a34-bd56-77328cd8071f)

Texte desc additionnel : Choisissez un mot de passe sécurisé en respectant les conditions ci-dessous.

Votre mot de passe doit contenir : 
- 8 caractères minimum
- 1 majuscule minimum
- 1 minuscule minimum
- 1 chiffre minimum

Message d'erreur, à afficher en fonction des contraintes (plusieurs messages peuvent être affichés si plusieurs contraintes non respectées) : 
- `Le mot de passe doit contenir au moins 1 majuscule.`
- `Le mot de passe doit contenir au moins 1 minuscule.`
- `Le mot de passe doit contenir au moins 1 chiffre.`
- `Le mot de passe doit être composé d'au moins 8 caractères.`

## Page de connexion
Utiliser le modèle [Demande de mot de passe pour la connexion](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/mot-de-passe/) du DSFR.

![image](https://github.com/MTES-MCT/histologe/assets/97226289/63df5fa2-e1fd-43ac-97b0-743cad8035ab)

Message d'erreur : `Erreur d'identification. Veuillez vérifier votre email et votre mot de passe.`
