### ISSUE TITLE
Planifier le renouvellement régulier des mots de passe des administrateurs

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#724]
Configurer ou recommander à intervalle régulier le renouvellement des mots de passe des comptes d'administration.
Cette mesure permet d'éviter qu'un mot de passe ancien ou proche d'un mot de passe déjà utilisé toujours utilisé ne soit découvert et utilisé par un acteur malveillant.

**Comment by hmeneuvrier** [comment]
https://www.ssi.gouv.fr/uploads/2021/10/anssi-guide-authentification_multifacteur_et_mots_de_passe.pdf

**Comment by hmeneuvrier** [comment]
https://mattermost.incubateur.net/betagouv/pl/kbmnu1nmz78udfz7xamzj4moqr
