### ISSUE TITLE
[Procédure] Définir une procédure de gestion des incidents de sécurité

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#725]
Formaliser une procédure à suivre en cas d'incident de sécurité sur le service, pouvant inclure des éléments relatifs à la gestion technique de l'incident, la coordination des personnes concernées au sein de l'organisation, la communication aux utilisateurs et aux autres entités potentiellement impactées. Sauvegarder ce document dans un environnement sécurisé, déconnecté du service.
Cette mesure permet de préparer l'organisation à réagir de manière rapide et efficace en cas d'incident de sécurité affectant le service et à remédier à la situation.

**Comment by mathildepoulpux** [comment]
Je sais pas si c'est pertinent mais y a un modèle de rapport d'incident dispo ici : https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-securise-mon-produit/gerer-une-fuite-de-donnees/modele-de-rapport-dincident

**Comment by emilschn** [comment]
- Partie technique
- Partie com
- Partie post-mortem avec doc du commentaire de Mathilde

**Comment by hmeneuvrier** [comment]
cf réunion hier : 

> Bosser sur le plan de continuité et de reprise d'activités dès maintenant (présence des techs, contacts au ministère et tester la restauration de sauvegarde technique) -> fournir une première version d'ici le 1er juillet (fiche réflexe ? cf documentation de l'ANSI)

**Comment by emilschn** [comment]
Version de travail : https://github.com/MTES-MCT/histologe/wiki/Gestion-des-incidents-de-s%C3%A9curit%C3%A9

**Comment by emilschn** [comment]
@mathildepoulpux @arnaudchouk  @sfinx13 @hmeneuvrier @numew si vous avez du temps pour faire un retour, estimer ce qui manque à cette page, etc.
Je suis preneur :)

**Comment by mathildepoulpux** [comment]
Est-ce qu'il y a besoin qu'on soit plus précis sur les procédures en fonction de la gravité du problème ?
Genre si problème critique de sécurité, on fait ça, on prévient sous XX heures, etc. ?

**Comment by emilschn** [comment]
Dans la partie Réaction, ajouter un lien vers cette doc : https://github.com/MTES-MCT/histologe/wiki/Service-Indisponible

**Comment by emilschn** [comment]
Les partie **Réaction** et **Communication externe** ont été mises à jour.

**Comment by sfinx13** [comment]
Pour le post-mortem ici un exemple https://doc.scalingo.com/security/postmortems
