### ISSUE TITLE
[Technique] [MSS et Socle sécurité] Conserver l'historique des accès des administrateurs au service

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#728]
Lié à #2555

---

Lors de la configuration du service, activer la journalisation et la centralisation des accès des administrateurs, des utilisateurs et des applicatifs concourant au fonctionnement du service.
Cette mesure permet de faciliter la détection d'actions inhabituelles susceptibles d'être malveillantes et d'investiguer a posteriori les causes d'un incident de sécurité, en vue de faciliter sa remédiation.

---

On partirait sur une table sur la BDD interne avec les champs suivants :

    id (int)
    event (string)
    entity_name (string)
    entity_id (int nullable)
    created_at (datetime)
    user (int nullable)
    service (string nullable)

**Comment by emilschn** [comment]
Mettre en place un log des actions Ajout, Modification, Suppression

Pour chaque utilisateur ou API en liaison

**Comment by emilschn** [comment]
Discussion Mattermost :
Numa : a mon sens ce qui est demandé c'est un système de log classique, de notre coté on part sur un enregistrement en base de données ?
Saidi : Oui c'est ça

De mon côté, je pense aussi qu'on a plus besoin d'un système de logs classiques (type Monolog avec un service tiers).
Voir comment on peut interfacer ça pour récupérer les infos nécessaires.
Sinon, si on part sur un truc maison, justifier l'intérêt de le faire et les inconvénients que ça entrainerait.

**Comment by sfinx13** [comment]
Pour l'historique des accès des administrateurs, je propose une solution interne qui consiste à mettre en place une table de log classique qui enregistrera l'ensemble des actions de tous les utilisateurs, y compris celles des administrateurs.

C'est simple et efficace, on peut proposer une interface dédié aux utilisateurs pour consulter leur historique.

Je voyais plus un truc comme ce que fait Always data et d'autres pour tout ce qui est historique des actions
![Image](https://github.com/MTES-MCT/histologe/assets/5757116/1ec18cd6-519a-4d6d-9ef4-c96b00a83ca7)

**Comment by sfinx13** [comment]
Aujourd'hui monolog envoie les logs sur la sortie standard visualisable sur scalingo web ou en cli. 
Mais ça reste pas efficace pour faire de l'analyse (des grep en voici en voila)  

On pourrait se limiter à ça avec des ajouts de logs pour l'accès des admin mais j'ai lu que les logs étaient conservé 1 an 
https://doc.scalingo.com/platform/app/logs#:~:text=Log%20Drain%20feature.-,Log%20Retention,-Scalingo%20is%20a

Je partage donc le besoin d'envoyer les logs vers un service tiers mais pour un besoin plus général que l'intitulé du ticket.

Il existe des buildpack chez scalingo pour envoyer des logs vers un saas
https://doc.scalingo.com/platform/app/log-drain

Y'a un retour d'XP ici 
https://mattermost.incubateur.net/betagouv/pl/u57agid6pbdgunj65hbfs3tyaa

**Comment by emilschn** [comment]
@hmeneuvrier @sfinx13 @numew 

Proposition de table interne pour stocker les événements ci-dessous

**Table Log**
- id (int)
- event (string)
- entity_name (string)
- entity_id (int nullable)
- created_at (datetime)
- user (int nullable)
- service (string nullable)

1/ Je propose de séparer user/service pour pouvoir stocker si un événement est fait via appel depuis un cron/webservice, ou via une personne connectée.
Qu'en pensez-vous ? Vous avez une meilleure idée ?

2/ Est-ce que vous pensez qu'on doit stocker les infos qui sont insérées ? 
Avantage : peut permettre de comprendre certaines erreurs + savoir qui a fait telle ou telle modification (en cas d'édition multiple)
Inconvénients : RGPD + les logs vont vite gonfler la table

3/ Doit-on stocker les erreurs de login ? 
Je dirais que non. L'enjeu c'est plutôt de voir les vraies actions, donc pas les erreurs. Mais je préfère votre avis :)

**Comment by sfinx13** [comment]
https://dev.mysql.com/doc/refman/8.4/en/keywords.html#:~:text=LOCKS-,LOG,-LOGFILE

Pour éviter les effets de bords je propose event_log au moins on sort des mot clés de la base de données.

**Comment by numew** [comment]
A mon sens ce n'est pas vraiment du log (ou du moins pas tel que cela nous est demandé pour la sécu, ou l'on doit typiquement garder les erreurs de login), c'est plutôt de l'historisation donc j'aurais tendance à le nommer différemment.

La description correspond pas mal a ce que j'avais en tête pour le #2555 (qu'on peux supprimer je pense) sauf qu'il manque une colonne `changes` qui permettrait en effet de stocker les modifications apporté sur l'entité. 
Dans mon esprit c'est un système qui permet a terme et si besoin d'avoir un résultat de ce type pour une entité : 
![Capture d’écran 2024-06-25 073541](https://github.com/MTES-MCT/histologe/assets/7130780/799c738d-9e6d-4284-ba65-4f91340ef19a)

**Comment by sfinx13** [comment]
@emilschn 

1. 
Je propose qu’on se limite pour l’instant à historiser les authentifications des utilisateurs donc service sera pas utile dans le cadre de cette PR. 

2. 
Uniquement stocker les authentifications en succès 

Pas d’enjeu RGPD c’est des données qu’on possède déjà 

La table qui gonfle c’est pas un problème non plus. Juste prévoir plus tard la conservation sur une année glissante sur l'historique du type authentification, pour les autres types d'historique ça restera à définir 

3. 
Je partage aussi on ne stocke pas les échec de connexions. 

Suite au message de @numew  je propose history_entry à la place de ma première proposition event_log 

Stocker les changement ça se fera mais pas nécessaire de créer la colonne dans cette PR.

**Comment by emilschn** [comment]
Ok, merci pour vos retours ! :)
Vos réponses me conviennent.
