### ISSUE TITLE
Mettre en place une sauvegarde régulière des données dans un environnement non connecté au service numérique

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#731]
Sauvegarder les données traitées par le service, au moins une fois par semaine, dans un environnement sécurisé, déconnecté de ce dernier (ex. dans une autre machine virtuelle chiffrée, sur un ordinateur ou un serveur local déconnecté d'internet).
Cette mesure permet une restauration rapide des données, à partir de la dernière sauvegarde des données effectuée, en cas d'incident de sécurité qui conduirait à leur suppression ou les rendrait inaccessibles, par exemple, en cas d'attaque par rançongiciel.

**Comment by arnaudchouk** [comment]
ok pour l achat - faut passer par la carte de damien, l informer avant et recuperer la facture

**Comment by emilschn** [comment]
achat effectué, en attente de réception chez moi

**Comment by arnaudchouk** [comment]
top - si vous pouvez me transmettre la facture pour que je la mette dans le tableau de Damien c est top

**Comment by sfinx13** [comment]
Documentation https://github.com/MTES-MCT/histologe/wiki/Sauvegardes-internes
