### ISSUE TITLE
[BO - Signalement] Refus partenaire

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#738]
Problème d'actualisation statut partenaire - constaté sur Bouches du Rhône (23.11.2022) - Partenaire CAF

Lorsqu'un signalement est refusé par un partenaire, l'affichage de son statut (sur le listing et sur le signalement) doit basculé de Bleu à Rouge -
A l'inverse lorsqu'un partenaire Accepte un signalement, l'affichage de son statut bascule de Bleu à Vert

sur quelques signalements (voir liste) le suivi indique signalement refusé, tandis que le statut précise Accepté 
Signalement #2022-2168 - voir suivi CAF  + statut CAF (CREMONA Laurent)

Signalement 2022-2165 - pareil

2022-2168 - pareil

A l inverse - comportement normal
Signalement 2022-2167 - comportement normal - voir suivi + statut

**Comment by sfinx13** [comment]
@arnaudchouk  Malgré le fait que j'ai pas réussi à reproduire mais j'ai remarqué une chose, lorsqu'un partenaire accepte un signalement, il n'y a pas de suivi, donc l'utilisateur aurait pu très bien refuser et changer d'avis en acceptant finalement.

Les actions sont les suivantes :
- Ajout d'un suivi une fois le signalement accepté par un partenaire.
- Script de MAJ des statuts d'affectations d'un signalement (A exécuter uniquement sur demande)

**Comment by arnaudchouk** [comment]
@sfinx13 dans la 1ere et 2e version il y avait les suivis lors des acceptations et on a souhaité les retirer car cela créait des messages peu utiles dans les suivis - je pense qu il ne faut pas le reinstaurer à ce stade
je contacte M Cremona de la CAF pour vérifier s'il a modifié son choix après son 1er refus - je completerai le ticket suite à sa réponse

**Comment by sfinx13** [comment]
En conservant e ce comportement, on risque peut être de se reposer la question d'ici quelques mois :-D

**Comment by arnaudchouk** [comment]
vu le nombre de partenaires affectés ca faisait bcp de suivis a peu de valeur ajoutée a priori
on va voir la reponse de la CAF - s il a modifié on saura que c est pas un bug et qu il faut peut etre repenser le sujet
attendons de voir

**Comment by arnaudchouk** [comment]
Du coup @sfinx13 il faudrait retirer la notification sur l acception du signalement par les partenaires, tant qu on a pas revu l ensemble des notifications

**Comment by arnaudchouk** [comment]
Juste un comment pour voir si on peut modifier ce comportement assez vite - ça limite le pilotage des gros territoires - et ca impacte nos résultats du coup :/
