### ISSUE TITLE
[BO - envoi de mails 06] - envoi notifs de suivi

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#74]
Sur la plateforme 06, le compte Nice-Hygiène reçoit les notifications de suivi alors que tous les comptes sont configurés sur Notif=non
Semble lié à l'utilisation adresse générique (ajoutée sur compte) - Cette adresse ne devrait recevoir que les notifs d'affectation et non de suivi

**Comment by mathildepoulpux** [comment]
Sera corrigé avec le #515
