### ISSUE TITLE
[BO - Tableau Bord] Filtre et Date Dernier suivi

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#743]
Le listing de signalements fait apparaitre les infos de bases du signalement + la date dernier suivi/auteur du suivi
en faisant jouer les filtres pour afficher les signalements n'ayant fait l'objet d'aucun suivi de puis plus de 90 jours, j'affiche une liste de signalements 
Quand je regarde les différents onglets les derniers suivis indiqués sur le signalement datent bien de plus de 90 jours
![image](https://user-images.githubusercontent.com/93710194/203805397-9798c34a-aa6f-419e-bc92-e52d3f4e44ec.png)

Mais lorsque j ouvre le signalement les suivis sont plus recents
![image](https://user-images.githubusercontent.com/93710194/203805319-a6bf3493-1090-415d-8af8-872b79ff3dad.png)

**Comment by arnaudchouk** [comment]
par contre quand je cherche une de ces references sans appliquer de filtre - la date du dernier suivi à l air ok
a priori la fonction Filtre suivi datant de plus de x jours est mal calibré
il verifierait si parmi les signalements il y a des suivis qui remontent à plus de x jours ( à verifier)
alors que ce que l on souhaite comme info c est les signalements pour lesquels aucun suivi n a été publié depuis plus de x jours

**Comment by sfinx13** [comment]
Vu avec @arnaudchouk je ré-ouvre le ticket, pour constater le bug il faut aller vers les dernières pages de la liste de signalement

**Comment by emilschn** [comment]
- le filtre doit filtrer sur tous les suivis SAUF les "techniques" (qui sont générés seuls par la plateforme)
- le dashboard doit prendre en compte la même chose (en ajoutant une précision)

**Comment by hmeneuvrier** [comment]
dans la liste, si on active le filtre, on ne doit pas avoir les signalements qui ont des suivis dans cet intervalle, sauf si ce sont des suivis techniques

**Comment by hmeneuvrier** [comment]
il faudrait regarder quand le lastSuivi est mis à jour pour la table Signalement
[3:53 PM](https://mattermost.incubateur.net/betagouv/pl/c1feacur3frcfb3pwqswcnz8nc)

et du coup, si ça se trouve, quand on actionne le filtre, on n'est pas forcément obligé de faire une jointure, et peut etre qu'on peut juste se baser sur cette donnée là

**Comment by hmeneuvrier** [comment]
@mathildepoulpux Pour le dashboard, quelle phrase veux-tu mettre exactement pour préciser que les suivis "techniques" ne sont pas pris en compte (pour l'instant, il n'y a que le suivi "demande de feedback à l'usager, mais à terme il pourrait y en avoir d'autres)

**Comment by mathildepoulpux** [comment]
`Accédez aux signalements sans nouveau suivi partenaire ou usager depuis au moins 30 jours. `
