### ISSUE TITLE
[FO- Home Page] - Bandeau Stats

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#744]
Tout est faux il me semble au niveau stats - @mathildepoulpux une idee de refonte ?
![image](https://user-images.githubusercontent.com/93710194/203810008-40e366d8-4b36-4543-8951-60fbb531cfe9.png)

**Comment by mathildepoulpux** [comment]
Mettre les vraies stats ? 😄

**Comment by arnaudchouk** [comment]
ce serait déjà pas mal effectivement :)

**Comment by emilschn** [comment]
Voici ce que je propose ci-dessous. Est-ce que ça correspond à ce que vous attendez ?

1. **tous** les signalements (dont importés, refusés et archivés)
2. ceux qui **ne sont pas** en attente de validation, ni refusés, ni archivés (en % du chiffre 1)
4. ceux qui sont **fermés** (en % du chiffre 1)

**Comment by arnaudchouk** [comment]
ca me semble bien

**Comment by hmeneuvrier** [comment]
@arnaudchouk @mathildepoulpux Je viens de tester ce qu'a fait @emilschn sur mon poste, et ça marche. Je trouve quand même étrange d'afficher les résultats avec les signalements importés sur la page d'accueil, et quand on clique pour voir plus de stats, on a des chiffres différents car ils ne comprennent pas les signalements importés. Ca donne une sensation de bug

**Comment by arnaudchouk** [comment]
@hmeneuvrier effectivement c est bizarre - l'info agregee donnes importees n'interesse que l administration - on pourrait decider de s en passer sur le portail front - si @mathildepoulpux est ok avec ca, faisons comme tu dis, ne traitons que les donnees deposees

**Comment by emilschn** [comment]
Vu avec Mathilde : on enlève les importés

**Comment by arnaudchouk** [comment]
@emilschn @sfinx13 ou @hmeneuvrier 
question sur l ecart bandeau/page stats publiques - vu qu on essayait d avoir une coherence - l ecart est du aux signalements refuses/archives ? si oui ne vaudrait il pas les reinterger egalement sur le bandeau?

![image](https://user-images.githubusercontent.com/93710194/217051029-3c089b41-b298-4975-af7d-2c3d00ca2c81.png)

![image](https://user-images.githubusercontent.com/93710194/217051073-eb629c51-8082-4a1f-ae92-9fe8363cea17.png)

**Comment by emilschn** [comment]
Je rouver pour déterminer la différence (je pense que c'est lié au nombre de signalements enregistrés)

**Comment by emilschn** [comment]
@arnaudchouk la différence vient du faire qu'on ne compte pas les signalements archivés sur la page Stats. Donc le nombre est moins important, mais les pourcentages sont plus importants.
Est-ce qu'on supprime les archivés sur la page d'accueil, ou est-ce qu'on remet les archivés sur les Stats ?
Je suis plutôt pour la proposition 1 (puisque les archivés n'ont pas trop de sens à ce qu'on s'était dit, et ça augmentera le taux de résolution logiquement), mais à vous de voir.

**Comment by arnaudchouk** [comment]
ce qui m embete en supprimant les archivés c est qu on passe sous silence la partie "demandes doublon", qui faisait perdre du temps avant, et qu on aide à améliorer
à l inverse ce qui m embete en intégrant les archivés, c'est qu on intègre la partie "signalements tests" dans le décompte
du coup, pile ou face  ? :) 
on sait si les tests c est 90% des archives ou 10% ?

**Comment by emilschn** [comment]
c'est un peu difficile à estimer :) tu as une méthode pour ça ? :D

**Comment by arnaudchouk** [comment]
s il y a le mot test dans le contenu :)
blague à part je serais d avis de les conserver du coup

**Comment by emilschn** [comment]
Je ping quand même @mathildepoulpux parce qu'on a eu de longs débats dessus, il me semble :D

Mais du coup, ces "archivés" ne seront jamais considérés comme "résolus". C'est pas un peu bizarre, qu'une part ne puisse jamais être résolue parce que ce sont des erreurs ?

**Comment by arnaudchouk** [comment]
ils sont pas "clôturés" quand ils sont archivés ?

**Comment by arnaudchouk** [comment]
ok ok - perdons pas trop de temps
partons sur la non prise en compte des archivés - si un jour ca devient pressent de considérer les archivés/doublons on verra

**Comment by mathildepoulpux** [comment]
Oui je suis d'accord on compte pas les archivés
