### ISSUE TITLE
[BO - Signalement] Edition doit être impossible pour utilisateur si l'affectation n'a pas été acceptée

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#758]
Un partenaire peut éditer/modifier un signalement avant de l'avoir Accepté
Exemple 2022-993 - Dpt 06 - Signalement modifié par un partenaire qui ne l'a pas encore accepté

Visible également sur le Tableau de Bord - tous les signalements peuvent être Ouvert et Editer dès que l'on est affecté

L'édition ne devrait être possible sans acceptation que part le Responsable de Territoire et après Validation du Signalement

**Comment by mathildepoulpux** [comment]
cf. #454

**Comment by arnaudchouk** [comment]
Précisions comportements Roles
Administrateur/Utilisateur : ne peut pas editer de signalement avant de l'avoir accepté
Resp Territoire : ne peut pas éditer le signalement sans l'avoir validé avant

**Comment by hmeneuvrier** [comment]
Pour les Super Admin et les Resp territoire c'est bon.

Par contre en ce qui concerne les utilisateurs, on ne peut pas éditer le signalement mais on peut faire certaines actions (comme ajouter des documents) sans avoir accepté l'affectation

**Comment by arnaudchouk** [comment]
n peut laisser comme ca - si ils ne peuvent rien supprimer/modifier mais juste ajouter des docs/photos
