### ISSUE TITLE
[BO] Script import données signalement

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#761]
## Territoires à importer
- [x] 18 - Cher
- [x] 48 - Lozère
- [x] 73 - Savoie
- [x] 38 - Isère
- [x] 81 - Tarn

### Description
Importer les données historiques du territoires
Références à créer sur la base Année Création + Chiffres ref historiques 

### Commandes exécutés
```
php bin/console app:import-signalement 18
php bin/console app:import-signalement 48
php bin/console app:import-signalement 73
php bin/console app:import-signalement 38
php bin/console app:import-signalement 81
```
### Résultats
* 81 - 117 signalements importés
* 38 - 2760 signalements importés
* 73  - 10 signalements importés
* 48 - 52 signalements importés
* 18 - 929 signalements importés

Remarques: Ils ont tous été référencés en tant que signalement importé (non prise en comprise par les statistiques)

#### 2. Ne pas mettre de consignes dans le titre des colonnes
_Toutes les consignes de saisie doivent figurer dans les lignes d’après_ 
:-1: details - ~précisions sur le signalement par declarant~
:-1: Date cloture ~(si pas de date - réputé en cours)~
:-1: prenom occupant ~- si inconnu "NC"~
:-1: telephone occupant - ~si inconnu > "0000000000"~
:-1: mail occupant - ~si inconnu > "inconnu@inconnu.com"~
:-1: Partenaires à affecter ~(si vide = aucun)~

#### 3. Problème de typo sur titre de colonne
- **telelephone** declarant
- **Occuoant** présent lors de la visite ?
- **Occuoant** en situation handicap

#### 4. Problème d'homogénéité sur les valeurs booléens
- O/N
- Oui/Non
- ** Parc privé/ Parc public** => logement social

#### 5. Prise en compte de différent format de référencement
La référence du signalement n'est pas standardisé, voici les différentes références trouvées dans les fichiers excels
- Cher(18) -  `01-07`
- Isère(38) - `4303`
- Tarn(81) - `112/22`
- Lozère(48) - `00017-22`
- Savoir(73) - `H1012`

Le plus simple aurait été de mettre le numéro de référence sans l'année comme l'Isère

#### 6. Prise en compte de différents formats de date 
- YYYY/mm/dd
- dd/mm/YYYY
- YY/mm/dd

#### 7. Partenaires
Les libéllés des partenaires ne correspondent pas toujours à ce qu'il y a sur la plateforme
Exemple: Bourges **(**SCHS**)** ≠ Bourges SCHS

#### Ne pas fusionner les colonnes
Le titre d'une situation est une colonne fusionnée, pour faciliter l'import le nommage des colonnes est à effectuer
Exemple:
- Signalement - Securite occupants 1
- Signalement - Securite occupants 2
- Signalement - Securite occupants 3
- Signalement - Etat & Proprete logement 1
- ect...

#### 9. Pas d'homogénéité dans les critères
Parfois des critères, parfois des criticités, parfois des libellés qui ne sont pas en base de données.
Exemple:
- 18 - le chauffage ne fonctionne pas bien - mauvais état
- 38 - il y a régulièrement des traces d’humidité.
- 73 - La porte ferme difficilement et laisse passer l’air. La porte est facile à crocheter, il y a un espace entre le cadre et la porte, et pas d’isolation thermique
- 81 - Ventilation, Moyen de chauffage, Installation électrique
- 48 - Les escaliers intérieurs sont dangereux

#### 10. Suivi
Format de suivi standardisé non identifié donc  l'utilisateur système Histologe a été choisi comme créateur du suivi

#### Exemple dans le 81: 
:+1:  Le 81 facilite l'extraction avec un séparateur "-" par suivi mais le séparateur de date a été modifié, chaque suivi a pu être ajouté
```
2022-02-15 ouverture  visite Soliha CAF - 
2022-04-21 en cours Visite Soliha (consignation à partir de mai). Rapport en mairie pour MED. Orienter vers DLS (DDETSPP) - 2022-05-17 en cours Pas de nouvelle info. Département va faire une mise à disposition. ARS fait un point avec mairie.   - 
2022-06-21 en cours Faire un point. Mairie relancée pour MED. ARS : offre relogement refusée, si possible accompagnement social ++. Retour Département : difficile de faire adhérer aux accompagnements, RDV proposé pour solutions de relogement.  -
2022-07-26 en cours Relance mairie n°2 le 04/07 
 ```

#### Exemple dans le 38
:-1: Différents format de date de suivi, pas de séparateur entre les suivi,ce suivi a été copié en l'état
```
"06.04.2016 : 
Je prie la personne qui l'a ouvert de s'identifier ici en observation (merci d'indiquer n° de tél et de CAF).
En principe, n'estce pas l'ADIL qui ouvre un dossier decence?
3 appels (05,06 et 07/04) de l'ADIL à la locataire hier et ce jour sans réponse et sans possibilité de laisser de message.
09/05 : Msg ADIL laissé
22.11.16 Caf courrier transmis à l'allocataire en juin 16. toujours pas de réponse
Vu ADIL 22/11/2016. 
*
27/09/2019 : Suite demande xxxxx xxxx, reprise de contact entre ADIL et Mme xxxxxx, car toujours dans les lieux 
xxxxxxxxx@xxxxx
27/9/19 caf: reprise de contact avec mme xxxx. prédiagnostic enregistré ce jour + cr de visite de 2011
*
27/03/2020: déclaré insalubre suite COTECH du 26/03/2020

12.06.20 Caf: ajout documents: fiche prédiagnostic MOUS, jugement et arrêt cour d'appel"
````

**Comment by arnaudchouk** [comment]
@sfinx13 l import isere 38 n est pas bon 
il n y a aucun signalement clôturé et ils semblent pour la plupart affectés qu a l ADIL...
Je sais que tu l'as fait en urgence mais il va falloir qu on reprenne le doc en prio à ton retour parce qu ils sont pas les plus sereins depuis le debut

**Comment by sfinx13** [comment]
@arnaudchouk la colonne statut est vide dans l'excel, que statut dois je mettre ? 
Ok pour les partenaires

**Comment by arnaudchouk** [comment]
ok my bad - desole je n'avais pas pensé à ça @sfinx13 
la règle pour toutes les données reprises c'est si date de cloture/motif de cloture alors statut Fermé
Pour tout le reste En cours
et pour tous l'ensemble des statuts,  les partenaires mentionnés sur la ligne de chaque signalement doivent être affectés

**Comment by sfinx13** [comment]
@arnaudchouk pour info la reprise pour l’Isère est en revue de code

**Comment by arnaudchouk** [comment]
top merci @sfinx13

**Comment by sfinx13** [comment]
Ticket pour import des images https://github.com/MTES-MCT/histologe/issues/786
