### ISSUE TITLE
[BO06 - carto] Zone Opah

### ISSUE THREAD

**Issue by Alban-64** [MTES-MCT/histologe#77]
Les zones Opah ne sont plus représentées graphiquement sur la cartographie de la plateforme du 06.

**Comment by arnaudchouk** [comment]
Les zones OPAH du 06 ne sont plus présentes depuis la plateforme unique
j'ajoute @mathildepoulpux qui avait supervisé le sujet avec Alban

**Comment by mathildepoulpux** [comment]
J'ai rien supervisé, j'ai juste vu des screenshots que Sam m'avait envoyé (ci-dessous)
C'était en place à partir du 20/04/2022

![Image collée à 2022-4-20 17-26](https://user-images.githubusercontent.com/97226289/197171626-38294620-1819-4e68-b2bd-cf7d54f9202b.png)

![Image collée à 2022-4-20 17-2](https://user-images.githubusercontent.com/97226289/197171725-426e8c04-86b8-4ae0-8aa9-e19b439066a2.png)

**Comment by arnaudchouk** [comment]
ok - en tout cas ca a sauté 
et il y a egalement une demande en ce sens sur le 13

**Comment by mathildepoulpux** [comment]
Creation zones OPAH suppl - Bouche du Rhones

* communes d'Arles et de Tarascon

* Fichiers fournis par DDT - voir https://drive.google.com/drive/folders/10sKy4EblVsf3ebpJ6WBp0jlwgkszYAnE?usp=sharing

**Comment by sfinx13** [comment]
Plus d'actualité voir https://github.com/MTES-MCT/histologe/issues/2826
