### ISSUE TITLE
[BO - Importer données ] Isere

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#771]
Importer les données historiques du territoires

A noter que le referencement doit se faire sous le format Année importation - Ref historique

Les documents à rattacher seront fournis plus tard et a importer à ce moment la

le MDP du fichier Données est CD38

**Comment by emilschn** [comment]
Lorsque la colonne Statut n'existe pas dans le csv, le statut 0 (inexistant) est attribué dans le signalement.

**Comment by sfinx13** [comment]
@emilschn ok suivi dans #761 afin de centraliser dans le même ticket
