### ISSUE TITLE
[BO - Signalement ] Affectation 

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#773]
Grasse Hygiene, qui travaille avec ESABORA 

Affectation impossible signalement - 2022-1165

Mais celui ci a fonctionné 2022-1170

Difference principale - nombre de photos

**Comment by arnaudchouk** [comment]
@sfinx13 autre signalement qui semble poser pbm avec Grasse Hygiene ESABORA Signalement #2023-55
Affectation impossible egalement
les 2 ont bcp de photos + declaration par un tiers

**Comment by sfinx13** [comment]
@arnaudchouk A tester en prod

**Comment by arnaudchouk** [comment]
ok je dis au RT du 06 de tester un des signalements qui a bloqué
merci

**Comment by arnaudchouk** [comment]
ca à l air ok

**Comment by sfinx13** [comment]
Je rouvre le ticket @arnaudchouk il faut s'y prendre autrement pour les photos
