### ISSUE TITLE
[FO - Contact] Créer un suivi automatique lors de l'utilisation du formulaire de contact

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#777]
Lié à https://www.notion.so/Creer-un-suivi-automatique-lorsqu-un-mail-d-un-declarant-est-recu-sur-notifications-histologe-fr-9d60e864688d4a66bc068174f090dea0

**Comment by emilschn** [comment]
Attention : ne pas ajouter de suivi sur les clotûrés // attention aux déclarants vs occupants

**Comment by mathildepoulpux** [comment]
### Cas n°1 déclarant occupant - Signalement ouvert
**Prérequis :**
- Email expéditeur email = email déclarant d'un signalement
- Vérifier que le statut du signalement = ouvert

**Actions :**
- Ajouter un commentaire de suivi dans les suivis du signalement. Auteur du commentaire = nom du déclarant
- Ajouter le commentaire sur la page de suivi (FO) usager en y ajoutant la mention "Envoyé par email"
- Envoyer les notifications & emails "Nouveau suivi" aux partenaires affectés en fonction des règles en vigueur

### Cas n°2 Signalement fermé
Si le signalement est fermé -> on ne fait rien.
Les emails seront traités par l'équipe déploiement qui feront le lien avec les responsables territoires concernés.

### Cas n°3 tiers déclarant - signalement ouvert
**Prérequis**
- Email expéditeur email = email occupant d'un signalement*
- Vérifier que le statut du signalement = ouvert

**Actions :**
- Ajouter un commentaire de suivi dans les suivis du signalement. Auteur du commentaire = nom de l'occupant
- Ajouter le commentaire sur la page de suivi (FO) usager en y ajoutant la mention "Envoyé par email"
- Envoyer les notifications & emails "Nouveau suivi" aux partenaires affectés en fonction des règles en vigueur

*NB :  si l'email du destinataire n'est pas reconnu / ne correspond à aucun signalement -> on ne fait rien.
Il s'agit de signalements faits par des déclarants tiers dans lesquels l'email de l'occupant n'a pas été renseigné.
Les emails seront traités par l'équipe déploiement qui feront le lien avec les responsables territoires concernés.

**Comment by sfinx13** [comment]
Pour tester le suivi automatique se rendre sur https://histologe-staging-pr863.osc-fr1.scalingo.io/
## Compte utilisateur
> Pour tous les utilisateurs, le mot de passe est `histologe`

Territoire             | Partenaire                | Email                               | Rôle       
-----------------------|---------------------------|-------------------------------------|----------------------
N/A                    | Admin Histologe           | admin-01@histologe.fr               | ROLE_ADMIN 
Bouches-du-Rhône       | Admin Histologe 13        | admin-territoire-13-01@histologe.fr | ROLE_ADMIN_TERRITORY
Ain                    | Admin Histologe 01        | admin-territoire-01-01@histologe.fr | ROLE_ADMIN_TERRITORY
Bouches-du-Rhône       | Utilisateur Partenaire 13 | user-13-01@histologe.fr             | ROLE_USER_PARTNER
Ain                    | Utilisateur Partenaire 01 | user-01-01@histologe.fr             | ROLE_USER_PARTNER

## Email occupant

| Mail occupant                        |
|--------------------------------------|
| sabine86@barbier.fr                  |
| elodie.chartier@gmail.com            |
| leroux.alexandre@orange.fr           |
| yjoubert@fleury.fr                   |
| margaux.rey@club-internet.fr         |
| lacombe.suzanne@bernier.fr           |
| olivie.lejeune@pons.net              |
| nathalie71@peltier.com               |
| celine.carre@noos.fr                 |
| aduval@orange.fr                     |
| antoinette.guichard@club-internet.fr |
| dorothee85@lesage.fr                 |
| olivier79@wanadoo.fr                 |
| lorraine82@noos.fr                   |
| laure.guillet@petit.com              |


## Email déclarant
| mail_declarant             |
|----------------------------|
| rdupuis@traore.org         |
| benjamin55@fouquet.org     |
| gabriel21@club-internet.fr |

**Comment by sfinx13** [comment]
@mathildepoulpux

**Comment by mathildepoulpux** [comment]
Quand un nouveau suivi automatique est créé : 
- L'email "nouveau suivi" est bien envoyé au responsable territoire.
- ⚠️ L'email "nouveau suivi" n'est pas envoyé aux agents. 

Pourtant l'affectation sur ce signalement est acceptée  

![image](https://user-images.githubusercontent.com/97226289/216067649-c62df81a-a66d-491c-9d59-6cd63a7a9ccf.png)

et les notifs sont bien activées pour l'agent :

![image](https://user-images.githubusercontent.com/97226289/216067403-05714955-eed6-4d66-9ea2-6f46db06d15a.png)

**Comment by mathildepoulpux** [comment]
Bug identification suivi tiers déclarant / occupant depuis la page de suivi : 
1. Un tier déclarant a déposé le signalement
2. Je suis l'occupant du logement
3. Je clique sur le bouton pour accéder à la page de suivi 
4. J'ajoute un commentaire depuis la page de suivi (Le suivi est enregistré et apparaît bien comme venant de l'occupant dans le BO)
5. La page de suivi est actualisée avec le success message
6. Depuis cette page actualisée, je rajoute un suivi
7. Le suivi est enregistré comme venant du déclarant tiers, alors que je suis l'occupant 

➡️ On perd l'attribut _from=email_ dans l'URL de la page de suivi quand elle est actualisée après le dépôt du commentaire

**Comment by hmeneuvrier** [comment]
@mathildepoulpux j'ai corrigé ton deuxième bug (le rajout de from dans l'adresse mail)
Pour le premier, qu'est-ce qui te fait dire que ce n'est pas envoyé aux partenaires ? Dans mail catcher, je vois bien le mail envoyé aux 3 partenaires : 
![image](https://user-images.githubusercontent.com/33071753/216096753-5107023d-279a-4f4b-a576-beda424fcd10.png)

**Comment by mathildepoulpux** [comment]
@hmeneuvrier Moi je les voyais pas dans mailtrap ! 
Les affectations étaient acceptées ou en attente pour le signalement que t'as testé ?

**Comment by hmeneuvrier** [comment]
en attente apparemment

**Comment by mathildepoulpux** [comment]
> en attente apparemment

Moi c'était accepté, je sais pas si ça change quelque chose ?

**Comment by hmeneuvrier** [comment]
Pour le 3è je pense comprendre, quand on le rouvre, il garde sa date de cloture et son motif de cloture, et je pense que je regarde ça pour vérifier si on fait un suivi ou un mail.

**Comment by mathildepoulpux** [comment]
Bon bah écoute si tu reproduis pas c'est que c'est bon !

**Comment by hmeneuvrier** [comment]
@arnaudchouk @mathildepoulpux Actuellement 
quand un signalement est fermé  : 
- le  statut devient "fermé"
- sa date de fermeture est indiquée ainsi que son motif de fermeture (les deux étaient NULL avant)
quand un signalement est rouvert : 
- le statut devient "actif)
- sa date de fermeture et son motif de fermeture restent tels que définis au moment de la fermeture

Pour corriger le bug que vous avez détecté (merci pour vos tests dd'ailleurs), je regarde le statut pour ajouter un suivi, et non plus la date de fermeture. Mais on se demande s'il y a une raison historique à ce comportement ou si il vaut mieux qu'on remette à NULL date de fermeture et motif de fermeture au moment de la réouverture du ticket ?

**Comment by mathildepoulpux** [comment]
Si on les remets à NULL, ça veut dire qu'on garde pas trace de la réouverture ? Ou on a quand même un suivi qui l'indique ?

**Comment by arnaudchouk** [comment]
Il faut effectivement qu'on garde une trace sur le fil de suivis des differentes etapes que le signalement a connu

**Comment by hmeneuvrier** [comment]
Oui les suivis seront gardés, c'est juste l'état du signalement qui sera modifié. De toutes façons je ne vais pas le faire là, car il faut prendre le temps de vérifier les effets de bords, mais je peux créer une carte

**Comment by mathildepoulpux** [comment]
> Bug identification suivi tiers déclarant / occupant depuis la page de suivi :

C'est toujours le cas
![image](https://user-images.githubusercontent.com/97226289/216581523-09d38dfa-b3da-418e-afa0-370616a1521e.png)

**Comment by mathildepoulpux** [comment]
> Oui les suivis seront gardés, c'est juste l'état du signalement qui sera modifié. De toutes façons je ne vais pas le faire là, car il faut prendre le temps de vérifier les effets de bords, mais je peux créer une carte

Vu qu'on garde les suivis ça me va, on peut remettre à NULL la date et le motif ! Je te laisse créer la carte :)
