### ISSUE TITLE
[BO - Signalement] Suivi Usager

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#784]
Déclaration par un tiers Signalement 2022-510 - sur le 06
l occupante a ajouté un suivi - mais il est enregistré en tant que Declarant avec l identite de la declarante
Il aurait du faire apparaitre Occupant - identite occupant

**Comment by hmeneuvrier** [comment]
@arnaudchouk Ce n'est pas vraiment un bug. Comme l'occupant ne se créé pas de compte, il reçoit un mail avec un lien qui lui permet d'ajouter un suivi sur son signalement, mais sans se connecter. Donc la valeur "createdBy" reste à NULL. Et que ce soit l'occupant ou le déclarant qui utilise le lien de ce mail, ça revient au même techniquement. 

Par exemple, ici c'est l'occupant qui a déclaré son pb, et son suivi est quand même labellisé [déclarant] (mais il est les deux)
https://histologe.beta.gouv.fr/bo/s/630c778ddfd01

Je ne sais pas trop comment on pourrait modifier ça...

**Comment by arnaudchouk** [comment]
Merci Hélène
dans le 2nd cas il n y a pas de pbm, vu qu il a les 2 statuts
Dans le 1er on ne peut pas savoir qui vient sur le formulaire ? on ne peut pas l'identifier à partir du clic dans sa boite mail ? auquel on saurait que c est soit l occupant soit le declarant, vu qu on a normalement leurs mails
C est pas tres grave dans l absolu, mais ca prete à confusion au niveau des Responsables Territoriaux a priori

**Comment by hmeneuvrier** [comment]
J'ai pensé hier soir qu'on peut peut-être ajouter le mail destinataire dans le lien qu'on génère pour le bouton, auquel cas on pourrait effectivement identifier la personne. Il faut que je creuse dans le code pour vérifier si c'est faisable.  Je vois ça lundi

**Comment by mathildepoulpux** [comment]
Corrigé avec le #777
