### ISSUE TITLE
[BO - Import] ISERE 38 - Import des images

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#786]
Comprend la documentation
https://github.com/MTES-MCT/histologe/wiki/Reprise-de-donn%C3%A9es

**Comment by arnaudchouk** [comment]
on me relance sur le sujet - avez vous une idée de date de livraison ? 
s il y a des complications n'hésitez pas à me le préciser

**Comment by sfinx13** [comment]
Tout est prêt, validé de notre coté, ça dépend des tests sur les autres tickets qui sont en test, je relance sur le channel dev-ux

**Comment by sfinx13** [comment]
[OK] 1513 Signalement(s) updated

**Comment by sfinx13** [comment]
[rapport-import-isere.txt](https://github.com/MTES-MCT/histologe/files/10580574/rapport-import-isere.txt)
@arnaudchouk Tu trouveras les références de signalement dans ce rapport

**Comment by arnaudchouk** [comment]
pas de pbm pour faire evoluer les exigences
par contre je n'ai pas bien cerné ce qui a été ignoré ou non - preneur d'une explication (visio?) pour être en mesure de repondre à leurs questions le cas echeant
