### ISSUE TITLE
Intégrer Page - “Avant de commencer” : detail du process Histologe

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#794]
https://www.notion.so/Int-grer-Page-Avant-de-commencer-detail-du-process-Histologe-edbf7553811243aaa22d5d22e3135859

**Comment by mathildepoulpux** [comment]
https://www.notion.so/R-diger-synth-se-du-process-d-un-signalement-sur-Histologe-Raffiner-texte-611e6a91535d4f59ab5d8152ca7a38bf
