### ISSUE TITLE
Intégrer info “Détail de la procedure” issue de la pré qualification - page validation

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#797]
https://www.notion.so/Int-grer-info-D-tail-de-la-procedure-issue-de-la-pr-qualification-page-validation-c76a034476f541ad93361a3425877810

**Comment by mathildepoulpux** [comment]
Une fois le formulaire complété et le signalement déposé, l'usager accède à une page de validation.

Il faut y ajouter les informations sur les procédures.
cf. [la maquette](https://xd.adobe.com/view/90cdc937-b439-4aaa-9e9a-f7ad61c45dfc-c59e/screen/42eb2e33-8d73-4bbc-bcf9-ac6925fa77d9/specs/), les textes peuvent être récupérés dessus.

⚠️ Le widget "Je donne mon avis" est à ajouter en bas de page

**Comment by mathildepoulpux** [comment]
Je peux pas déposer de signalement donc je peux pas vérifier : 
Test avec un signalement sur le 64, signalement par occupant 
![image](https://user-images.githubusercontent.com/97226289/226662030-0bf1e1cd-f7af-4684-b3de-c43570de85a7.png)

**Comment by mathildepoulpux** [comment]
Le dépôt de signalement fonctionne sur le 63 avec uniquement des désordres non décence.
La page de validation est toujours l'ancienne par contre : 
![image](https://user-images.githubusercontent.com/97226289/226670719-7744322c-8bae-4736-90b9-bd754dc39a50.png)

**Comment by hmeneuvrier** [comment]
Pour le dépôt de signalement, peut-être lié à cette erreur à corriger : 
https://sentry.incubateur.net/share/issue/fd55bd9efbf9439abe0d8ba7713552ad/
