### ISSUE TITLE
[Punaises - BO] Editer une entreprise

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#8]
### Objectif
Modifier les infos d'une entreprise
[Voir maquette 🔗 ](https://xd.adobe.com/view/e8dc7a51-ae64-49a3-bda8-9ea816c79fe5-bd8f/screen/4a1b6e57-a925-4003-90aa-7aa96f69495f)
[Voir la microcopie 💬 ](https://docs.google.com/spreadsheets/d/1JeIJb1PKFHyAH6LIBxsH0HvYsGFw8KjN/edit#gid=344031466)
[Modèle email activation compte](https://my.sendinblue.com/camp/template/24/message-setup)

### Prérequis
Avoir un compte entreprise OU admin actif sur la plateforme

### User flow entreprise
1. J'accède à la page entreprise
4. Je clique sur le bouton "edition"
5. Je remplis les champs demandés dans la side modale 
**NB : message warning sous le champ email pour prévenir qu'il faudra valider la nouvelle adresse email pour continuer à accéder au BO**
6. Clic sur "valider"

![image](https://user-images.githubusercontent.com/97226289/173333584-bea0f21a-102b-4876-aaee-a553d0e6dfd2.png)

#### Conséquences entreprise 
- Si modif email : 
    - Modification des info entreprise
    - Déconnexion
    - Redirection vers page de login avec success message
    - Envoi d'un email d'activation au compte entreprise
- Sinon : 
    - Modification des info entreprise
    - Success message

### User flow admin
1. J'accède à la liste des entreprises
2. Je clique sur le bouton "edition" dans la liste des entreprises
3. Je modifie les champs dans la side modale 
**NB : message warning sous le champ email pour prévenir qu'il faudra valider la nouvelle adresse email pour continuer à accéder au BO**
4. Clic sur "valider"

#### Conséquences
- Success message
- Modification des info entreprise
- Envoi d'un email d'activation au compte entreprise si modification email

**Comment by emilschn** [comment]
manque logout et renvoi du mail d'activation
