### ISSUE TITLE
en cas d absence de suivi partagé sur 30 jours, envoyer mail de suivi automatique / demander feedback à l usager

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#800]
https://www.notion.so/en-cas-d-absence-de-suivi-partag-sur-30-jours-envoyer-mail-de-suivi-automatique-demander-feedbac-690f1fd32eac44a7abf968a46c2729cb

Envoyer un mail à l'occupant tous les mois pour savoir s'il est toujours dans le logement ou non

**Comment by mathildepoulpux** [comment]
Conditions : 
- Signalement ouvert & validé
- Au bout de 30 jours après validation du signalement, si pas de suivi partagé à l'usager
- Puis tous les 30 jours, si pas de suivi partagé à l'usager

Objet : Histologe : faites le point sur votre problème de logement !

Corps : 
Bonjour {prénom},

Vous avez signalé un problème dans le logement au {adresse logement}.
La situation a-t-elle évolué ? Les travaux ont commencé ? Un agent a visité le logement ? Vous avez quitté ou prévoyez de quitter le logement ?

Cliquez sur le bouton ci-dessous pour nous envoyer un message de mise à jour !

Bouton : Mettre à jour ma situation

Si le bouton ne fonctionne pas cliquez ici.

**Comment by hmeneuvrier** [comment]
@mathildepoulpux @arnaudchouk pour ne pas envoyer cette demande de feedback tous les jours à l'usager, il me faut noter quelque part le jour où j'envoie le mail. Je propose de créer un nouveau type de suivi, qui serait un suivi "technique" indiquant qu'un mail de demande de feedback a été envoyé ce jour-là. Côté technique, ça m'arrange de faire comme ça, et je trouve que ça a du sens côté fonctionnel, car on pourra très facilement faire des stats pour connaître le taux de feedback suite à l'envoi de ce mail (metabaaase <3 ).
Se pose la question de la visibilité de ce nouveau suivi. Voulez-vous qu'il soit totalement invisible ? Visible pour les super-admins (ce qui a le plus de sens selon moi) ? Visible pour les utilisateurs/partenaires ? 

Merci

**Comment by mathildepoulpux** [comment]
Je le mettrais visible pour les responsables de territoire et super admin

En mettant "message automatique" comme auteur et comme commentaire du suivi "Un message automatique a été envoyé à l'usager pour lui demander de mettre à jour sa situation."

**Comment by arnaudchouk** [comment]
je partage le point de vue de Mathilde - par contre faut qu il cela crée une notification ... je ne suis pas sur mais peut etre que l on reverra ce point au moment de la revue complete du sujet

**Comment by arnaudchouk** [comment]
t embetes pas - tous les suivis creent des notifs - je m interrogeais sur la pertinence d en creer un avec ce suivi - mais on verra plus tard
