### ISSUE TITLE
Différencier les motifs de clôture Partenaire/Resp Territoire

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#813]
https://www.notion.so/Diff-rencier-les-motifs-de-cl-ture-Partenaire-Resp-Territoire-721c76ebda6d4ffb930cfc9cb6ee4923

**Comment by arnaudchouk** [comment]
ca fera l objet d une revue plus complete des motifs mais à date je pense qu il n y a plus forcement besoin de differencier les motifs existants entre rt et partenaires
