### ISSUE TITLE
[BO - Signalement] Format Photo .heic

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#818]
Il semble qu un format photo soit mal pris en charge par la plateforme 
![image](https://user-images.githubusercontent.com/93710194/212371275-3a619e23-619e-46c4-950f-4fa8d20a229b.png)

Exemple : https://histologe.beta.gouv.fr/bo/s/0db158e3-a026-4bd6-996e-273eb8a7dda5 

la consequence est un cadre blanc 

sur mon environnement pc/firefox je suis parvenu a afficher dans la boite de dialogue l option Ouvrir dans un nouvel onglet
En cliquant dessus ca a téléchargé un document format ".heic" 
je peux l'ouvrir avec mon logiciel d'affichage photo et il y a bien une photo

Sur l environnement de Thibault pc/chrome il ne peut pas afficher cette option

il y a un certain nombre de signalements qui affichent ces cadres blancs, mais on ne savait pas pourquoi

**Comment by sfinx13** [comment]
@emilschn On a une exception sur la gestion des photo .heic, je la repasse en doing
https://sentry.incubateur.net/share/issue/b6af5c69c65648afa03b2aed12e6e67f/

**Comment by emilschn** [comment]
HEIC n'est pas géré par Imagick sur Scalingo dans l'immédiat. Voilà ce qu'ils m'ont répondu.

Pour le moment, le HEIC n'est pas supporté par notre buildpack Imagick.
Il est prévu de supporter ce format dans le futur mais je ne peux pas vous donner de date précise.
Cependant, vous pouvez utiliser d'autres buildpacks comme celui fournit dans cet article medium: https://medium.com/praaveen/compiling-imagemagick-with-heic-support-in-heroku-ubuntu-c5353413de19
Pour utiliser ce buildpack custom, vous pouvez suivre notre documentation: https://doc.scalingo.com/platform/deployment/buildpacks/custom

**Comment by sfinx13** [comment]
J'ai regardé en base, les signalements qui ont ce problème n'ont pas pu être déposé, on a 50 événements à ce jour depuis le 13 février. 
La possibilité temporaire en attendant d'investiguer sur les recommandations scalingo est de ne pas prendre en charge le format heic de manière explicite (je ping @mathildepoulpux )
Ce format n'est pas réservé qu'Apple d’après ce que je voit
