### ISSUE TITLE
Créer champ Date de visite prévue

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#830]
https://www.notion.so/Cr-er-champ-Date-de-visite-pr-vue-3b8ac651127b4c5faf5486f413f565a0

**Comment by mathildepoulpux** [comment]
![image](https://user-images.githubusercontent.com/97226289/224397075-dc2aa6d3-be33-4105-a60c-bc1f8e0bceea.png)

![image](https://user-images.githubusercontent.com/97226289/224397412-877bd5d6-dd0f-473b-9e13-b9ed6a213e4c.png)
