### ISSUE TITLE
Creer un suivi automatique lorsqu un mail d un declarant  provenant du formulaire de contact Home est recu sur la boite notifications@histologe.fr

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#837]
https://www.notion.so/Creer-un-suivi-automatique-lorsqu-un-mail-d-un-declarant-provenant-du-formulaire-de-contact-Home-es-884f0b3f101d4c5b9f02797f7891786e

**Comment by mathildepoulpux** [comment]
Doublon #777
