### ISSUE TITLE
Activer la feature : suivi auto - date de visite attendue si date de visite non renseignée après 15 jrs

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#838]
https://www.notion.so/Ajouter-suivi-auto-pour-rappeler-que-date-de-visite-est-attendue-si-date-de-visite-non-renseign-e--5ea1b02a8f3541b59477e4b8cd761345

**Comment by mathildepoulpux** [comment]
cf. commentaire sur #688 

Pour l'email "aucune date de visite renseignée à J+15 après affectation" et la notif "Aucune date de visite renseignée 15 jours après que le partenaire avec la compétence "visite" a accepté l'affectation"

-> Faire démarrer le compteur des 15 jours à la date de la mise en prod (date de mise en prod = jour 0 pour les signalements existants) pour éviter que les partenaires se prennent plein de notifs et emails d'un coup

**Comment by mathildepoulpux** [comment]
La feature est faite mais désactivée pour ne pas spammer les partenaires. 
A définir quand on l'active
