### ISSUE TITLE
Nombre de suivis signalements

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#840]
https://www.notion.so/Nombre-de-suivis-par-signalement-bf7350a5f86e4c379654520093fe3fec

**Comment by emilschn** [comment]
C'est peut-être un peu à spécifier, non, @mathildepoulpux  ?
Dans l'immédiat, je ne sais pas trop où on met cette stat :)

**Comment by hmeneuvrier** [comment]
@arnaudchouk  Petite question, je dois faire cette issue qui référence cet okr https://www.notion.so/Nombre-de-suivis-par-signalement-bf7350a5f86e4c379654520093fe3fec 
> Mesurer le nombre moyen de suivis par signalement, par territoire, par procédure, par critère, par partenaire

Pour le dashboard, @emilschn  et @sfinx13  suivent les maquettes de @mathildepoulpux  et ont déja implémenté *le nombre de suivi renseignés par des partenaires moyen par signalement * https://xd.adobe.com/view/788436dd-5c75-46d0-a1b8-790f1a120e29-2dd7/screen/6e237166-cffe-4118-bcff-273044ee3e69/

Par contre, on n'a pas le nombre de suivi moyen  ```par procédure, par critère, par partenaire``` 
Je peux le faire en code (enfin j'imagine, je n'ai pas encore regardé), mais où et comment ça se matérialise ?

**Comment by arnaudchouk** [comment]
@hmeneuvrier c est une vision LT qui sera peut etre pas utile suite aux resultats que nous aurons dans les premiers temps
Mais si ca devait etre fait, je pense que c est uniquement pour le SA dans un premier temps, avec simplement des filtres activables sur la partie dediee à cet indicateur par exemple, qui permettent de calculer plus precisement l'indicateur nombre moyens de suivis

**Comment by sfinx13** [comment]
On va lancer une étude sur un outil qui s'appelle metabase(dashboard) qui pourra répondre à certains OKR pour les super admin. Certains SE l'utilisent et ça apporterait une grande plus value niveau pilotage.

**Comment by hmeneuvrier** [comment]
@emilschn a créé une issue pour la mise en place de Metabase : https://github.com/MTES-MCT/histologe/issues/880

**Comment by emilschn** [comment]
En ce qui concernet le nombre de suivi moyen par procédure, par critère, par partenaire, est-ce que je comprends bien :

1/ Par procédure = moyenne du nombre de suivis par signalement sur chaque type de procédure
Il s'agit bien de RSD, etc. ?

2/ Par critère = moyenne du nombre de suivis par signalement dont le critère est XXX

3/ Par partenaire = moyenne du nombre suivis par signalement affecté à un partenaire

C'est bien ça ?
Idéalement, on ajoute des filtres par territoire et par date pour l'évolution dans le temps ?

**Comment by arnaudchouk** [comment]
oui c est ca  mais on reparlera peut etre de la pertinence de tous ces sous decoupages à Paris - vous en pensez quoi ?

**Comment by emilschn** [comment]
Je suis en train de les mettre en place sur Metabase :)
Au pire, ça fera une bonne démo pour Paris, justement.

**Comment by emilschn** [comment]
Les statistiques ont été reportées sur le Metabase en ligne : https://histologe-metabase.osc-fr1.scalingo.io/dashboard/2-statistiques-sur-le-nombre-de-suivis
Est-ce qu'on envisage de mettre en place des filtres ou pas nécessaire pour l'instant ? Je n'ai pas encore compris exactement comment on pouvait les mettre en place simplement.

**Comment by emilschn** [comment]
Tout est possible, tu le veux sous quelle forme, et sur quel tableau ?
Là l'avantage c'est qu'on va pouvoir créer des TB pérennes rapidement. Donc si tu as une idée de stat précise, dis-moi, et je vois ce qu'on peut faire !

**Comment by arnaudchouk** [comment]
pour ce qui est des suivis :
il serait bien de voir sous forme de tableau
nombre de suivis moyens partagés à usager, de suivis crees par usagers, et suivis privés, par territoire, par partenaire
et la même chose mais par période de création - Trimestre ou Mois

Pour le reste des besoins je prefere prendre un peu de temps de penser les stats nécessaires et faire un ticket global - ok pour toi ?
