### ISSUE TITLE
[Territoire 69] Modifications communes à autoriser + règles affectation

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#841]
Le Rhône ayant une organisation spéciale, ce sont les métropoles qui gèrent / pilotent les signalements sur ses communes (et pas la DDT).

Actuellement, seules les signalements sur les communes de la métropole de Lyon sont possibles. (cf. #673 )
La Communauté d'Agglomération de l'Ouest Rhodanien (COR) souhaite participer. Sauf que (plot twist !) la métropole de Lyon ne souhaite pas que la COR voit ses signalements et inversement.

Il faudrait : 
- autoriser le dépôt de signalements pour les communes de la COR (cf. tableau ci-dessous)
- masquer l'affichage des signalements de la Métropole de Lyon pour la COR
- masquer l'affichage des signalements de la COR pour la Métropole de Lyon

**Communes à autoriser**
| Commune | Code INSEE | Code Postal
| :--- | :---: | :---:
| AFFOUX | 69001 | 69170
ANCY | 69006 | 69490
AMPLEPUIS | 69008 | 69550
CHAMBOST-ALLIÈRES | 69037 | 69870
CHENELETTE | 69054 | 69430
CLAVEISOLLES | 69060 | 69870
COURS | 69066 | 69470
CUBLIZE | 69070 | 69550
DIÈME | 69075 | 69170
GRANDRIS | 69093 | 69870
JOUX | 69102 | 69170
LAMURE-SUR-AZERGUES | 69107 | 69870
LES SAUVAGES | 69174 | 69170
MEAUX-LA-MONTAGNE | 69130 | 69550
POULE-LES-ÉCHARMEAUX | 69160 | 69870
RANCHAL | 69164 | 69470
RONNO | 69169 | 69550
SAINT-APPOLINAIRE | 69181 | 69170
SAINT-BONNET-LE-TRONCY | 69183 | 69870
SAINT-CLÉMENT-SOUS-VALSONNE | 69188 | 69170
SAINT-FORGEUX | 69200 | 69490
SAINT-JEAN-LA-BUSSIÈRE | 69214 | 69550
SAINT-JUST-D'AVRAY | 69217 | 69870
SAINT-MARCEL-L'ÉCLAIRÉ | 69225 | 69170
SAINT-NIZIER-D'AZERGUES | 69229 | 69870
SAINT-ROMAIN-DE-POPEY | 69234 | 69490
SAINT-VINCENT-DE-REINS | 69240 | 69240
TARARE | 69243 | 69170
THIZY-LES-BOURGS | 69248 | 69240
VALSONNE | 69254 | 69170
VINDRY-SUR-TURDINE | 69157 | 69490

**Partenaire COR**
Il faudra donc créer un partenaire COR contenant les responsables territoires qui verront les signalements de la COR.
| Nom | Prénom | Email | Role
| :--- | :--- | :---- | :----
| L'Héritier | Valérie | valerie.lheritier@c-or.fr | Responsable territoire
| Fournier | Jean | jean.fournier@c-or.fr | Responsable territoire
| Uzel | Fanny | fanny.uzel@c-or.fr | Responsable territoire

@sfinx13 On en avait discuté avec Chouaïb, si tu te rappelles de la solution envisagée 😅

**Comment by sfinx13** [comment]
Prendre en compte cette erreur https://sentry.incubateur.net/share/issue/800952c2da5044578ad4e352aac4774e/

**Comment by sfinx13** [comment]
@mathildepoulpux Est ce que les partenaires peuvent communiquer sur les signalements des 2 agglomérations

**Comment by mathildepoulpux** [comment]
Alors oui, c'est possible que des partenaires soient affectés sur des signalements dans les 2 agglo

**Comment by sfinx13** [comment]
Création des comptes partenaire, liste envoyé par Chouaib
