### ISSUE TITLE
[BO - Partenaires] Réactiver un compte utilisateur archivé

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#843]
Aujourd'hui, les comptes supprimés sont archivés et conservés en base pendant 12 mois (RGPD).
Or, il est fréquent qu'un responsable de territoire ou super admin veuille re-créé un compte archivé dans un partenaire.
Problème : il a un message d'erreur "Adresse email non valide" puisque celle-ci est déjà enregistrée en base.

Pour donner plus de liberté aux super admin, la réactivation d'un compte archivé devrait être dispo depuis le BO.

### Tâches : 
- [x] Créer la fonctionnalité
- [ ] Ajouter l'item dans le menu BO (cf. specs ci-dessous)
- [x] Créer le listing des comptes archivés (cf. specs ci-dessous)
- [x] Afficher une page d'erreur sur page partenaire actif -> actuellement, si on a l'URL, on peut accéder aux détails d'un partenaire archivé donc y créer des users etc. Il faudrait bloquer cet affichage et mettre une page d'erreur à la page
_Solution retenue_ : renvoi vers la liste des partenaires
- [ ] Créer un email de réactivation

**Comment by mathildepoulpux** [comment]
### Listing des users archivés

**URL** : cf. [le tableau](https://docs.google.com/spreadsheets/d/1Z2rzfxRd_jI8gTm43b-VZQ56fdtgXBDQ-JFYGmfIYfI/edit#gid=0)
**Titre de la page** : Comptes archivés

**Filtres :** 
| Champ | Type de champ | Valeurs | Valeur par défaut 
| :--- | :---- | :---- | :----
| Utilisateur | Saisie libre | Recherche sur le nom, prénom & email du user | Vide (affiche tout)
| Territoire | Dropdown | Liste des territoires classés par num de département | Tous les territoires
| Partenaire |  Dropdown | Liste des partenaires par ordre alphabétique | Tous les partenaires 

**Résultats :** 
- Affichés sous forme de tableau
- Tri par défaut : de la date d'archivage la plus récente à la plus ancienne
- 20 lignes puis pagination

Nombre de résultats affichés au dessus du tableau : _{nombre} comptes utilisateurs trouvés_

Le tableau :
| Nom de la colonne | Contenu affiché | Tri 
| :--- | :---- | :---- 
| Date | Date d'archivage au format DD/MM/YYYY | Oui par ordre antichronologique
| Territoire | numéro du département | Oui par ordre de grandeur
| Partenaire | nom du partenaire | Oui ordre alphabétique 
| Statut partenaire | Label (actif / archivé) | Non
| Email | adresse mail du compte | non
| Nom | nom du user | non
| Prénom | prénom du user | non
| Action | Bouton réactivation | non

**Comment by mathildepoulpux** [comment]
@hmeneuvrier @emilschn @sfinx13 est-ce qu'il vous faut une maquette / un croquis pour : 
- La page de réactivation
- Le listing des comptes archivés 
?

**Comment by mathildepoulpux** [comment]
Les maquettes ci-dessous
Et le [prototype interactif est ici 🔗](https://xd.adobe.com/view/42a8bcc5-42c6-4835-b5dd-7e8859512560-17fb/) 

Le listing des comptes archivés : 
![BO - Comptes archivés](https://user-images.githubusercontent.com/97226289/215086199-98129a05-ce9b-465e-8366-736e269b1529.png)

La page de réactivation : 
![BO - Comptes archivés – réactivation](https://user-images.githubusercontent.com/97226289/215086239-21d09dc5-91f3-4696-97d9-23a69e909155.png)

**Comment by hmeneuvrier** [comment]
@mathildepoulpux : on n'a pas de date d'archivage, et quand on archive un compte, on ne met même pas à jour le champ updatedAt. Je supprime cette colonne ?

**Comment by hmeneuvrier** [comment]
@mathildepoulpux : autre question, on a maintenant des utilisateurs correspondant aux déclarants/occupants.
Eux n'ont ni territoire, ni partenaire. Pour rl'instant, j'affiche 'aucun' dans les colonnes Partenaire et Statut part. Mais peut-être qu'"usager" sera plus parlant (ou déclarant/occupant) (j'aime autant ne pas avoir à spécifier si c'est déclarant ou occupant, car ça ajoute des requêtes en base, et je ne pense pas que ça vaille le coup pour une partie admin)
j'enlève aussi les dropdowns territoire et partenaire dans la réactivation pour ces cas-là.

Même si, on est bien d'accord, ces cas ne doivent pas se présenter car on n'a pas d'endroit où on archive ces usagers... Je préfère le prévoir au cas où pour éviter des plantages

**Comment by hmeneuvrier** [comment]
@mathildepoulpux encore une question, pour l'instant j'envoie le mail TYPE_ACCOUNT_ACTIVATION, mais il n'est pas totalement cohérent avec ce qui se passe : 
        <p>Vous n'avez toujours pas activé votre compte depuis sa création, si vous le souhaitez, cliquez sur le bouton
            ci-dessous pour vous connecter et activer
            votre compte</p>
            
Faudra qu'on voie si on laisse celui-ci ou si on en fait un autre

**Comment by sfinx13** [comment]
> @mathildepoulpux : autre question, on a maintenant des utilisateurs correspondant aux déclarants/occupants. Eux n'ont ni territoire, ni partenaire. Pour rl'instant, j'affiche 'aucun' dans les colonnes Partenaire et Statut part. Mais peut-être qu'"usager" sera plus parlant (ou déclarant/occupant) (j'aime autant ne pas avoir à spécifier si c'est déclarant ou occupant, car ça ajoute des requêtes en base, et je ne pense pas que ça vaille le coup pour une partie admin) j'enlève aussi les dropdowns territoire et partenaire dans la réactivation pour ces cas-là.
> 
> Même si, on est bien d'accord, ces cas ne doivent pas se présenter car on n'a pas d'endroit où on archive ces usagers... Je préfère le prévoir au cas où pour éviter des plantages

@hmeneuvrier Les usagers sont rentre pas dans ce cas d'usage, il ne faut pas les afficher.

**Comment by hmeneuvrier** [comment]
@mathildepoulpux en cas d'accès à un partenaire archivé avec l'url d'édition de partenaire, je redirige vers la liste des partenaires de ce territoire. Ok pour toi ?

**Comment by mathildepoulpux** [comment]
> @mathildepoulpux : on n'a pas de date d'archivage, et quand on archive un compte, on ne met même pas à jour le champ updatedAt. Je supprime cette colonne ?

Oui !

**Comment by mathildepoulpux** [comment]
> @mathildepoulpux encore une question, pour l'instant j'envoie le mail TYPE_ACCOUNT_ACTIVATION, mais il n'est pas totalement cohérent avec ce qui se passe :
> 
> Vous n'avez toujours pas activé votre compte depuis sa création, si vous le souhaitez, cliquez sur le bouton ci-dessous pour vous connecter et activer votre compte
> 
> Faudra qu'on voie si on laisse celui-ci ou si on en fait un autre

Si on utilise celui-ci ça me paraît pas mal : https://github.com/MTES-MCT/histologe/blob/main/templates/emails/login_link_email.html.twig

**Comment by mathildepoulpux** [comment]
> @mathildepoulpux encore une question, pour l'instant j'envoie le mail TYPE_ACCOUNT_ACTIVATION, mais il n'est pas totalement cohérent avec ce qui se passe :
> 
> Vous n'avez toujours pas activé votre compte depuis sa création, si vous le souhaitez, cliquez sur le bouton ci-dessous pour vous connecter et activer votre compte
> 
> Faudra qu'on voie si on laisse celui-ci ou si on en fait un autre

Effectivement, y a aucun template qui colle, il en faudrait un nouveau ! 
C'est long ou ça va ?

**Comment by hmeneuvrier** [comment]
ça va, si tu me donnes le texte :)

**Comment by mathildepoulpux** [comment]
@hmeneuvrier Contenu de l'email de réactivation : 

_Objet_ : Votre compte Histologe est activé !

_Corps_ :
Bonjour,

Votre compte a bien été activé sur la plateforme Histologe - {territoire}.
Vous pouvez désormais traiter et assurer le suivi des signalements du partenaire {nom du partenaire}.
Cliquez ci-dessous pour vous connecter à votre compte.

_Btn_: [Accéder à mon compte]
Si le bouton ne fonctionne pas, [cliquez ici].

**Comment by sfinx13** [comment]
je n'ai pas fermé ce ticket, je laisse @mathildepoulpux le faire
