### ISSUE TITLE
[BO - Statistiques] Partenaires

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#845]
En tant qu'agent d'un partenaire (Rôle Utilisateur) lorsque je me rends dans l'onglet Statistiques de mon Tableau de Bord je visualise les **données relatives à la Totalité des signalements du Territoire** 

Cette vue ne devrait être accessible qu'au Responsable Territoire

Pour les Partenaires de Type Partenaire ou Commune, et les rôles Utilisateurs je ne devrais avoir sur la page Statistiques que les **données relatives à mon Partenaire** 

Cas Bouches du Rhone
Partenaire LOGIREM vit sur la page statistiques la totalité des infos du territoire - par contre la carto est ok

**Comment by hmeneuvrier** [comment]
Revoir BackStatistiquesController, GlobalBackAnalyticsProvider, FilteredBackAnalyticsProvider, les autres providers de src/Service/Statistics et plusieurs méthodes de signalementRepository pour passer le Partner et faire une jointure sur les affectations

**Comment by arnaudchouk** [comment]
je me connecte sur le 34 - 
partenaire caf compte utilisateur
le listing et la carto indiquent 98 signalements 
la page stat m en donne 127 + 2 refusés...

partenaire Montpellier - compte utilisateur
le listing et la carto indiquent 10 signalements
la page stat m en donne 127+2 refuses

je me connecte en tant que SA - le total signalement du 34 est de 127+2 refuses
la page stat reprend toujours le total territoire

**Comment by hmeneuvrier** [comment]
ok après un redéploiement

**Comment by arnaudchouk** [comment]
c est buen
