### ISSUE TITLE
[BO - Partenaires] [NDE  - Lot 2] Améliorer la partie Partenaires

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#852]
Refonte partie partenaires prenant en comptes les différents retours et dans la continuité de l'expé Non décence énergétique : 
- [specs](https://github.com/MTES-MCT/histologe/wiki/Partenaires)
- [maquette](https://xd.adobe.com/view/6078cc0b-9cbe-4039-b94d-ba77d50c97f8-352b/)

Faire avec le #905 

Fournir la liste des partenaires actifs de tous les territoires avec : 
- numéro département
- nom territoire
- nom du partenaire
- Type actuel (partenaire ou commune)
- Codes INSEE
- Nb de users actifs
- Nb de users inactifs

**Comment by mathildepoulpux** [comment]
[BO - Partenaires] Télécharger la liste des partenaires
- Retour 04 : Souhaiterait pouvoir télécharger en 1 clic la liste des communes, ou des partenaires ou les comptes inactifs
- Retour interne : pouvoir télécharger la liste. Le but étant de pouvoir facilement acceder aux emails des agents des partenaires pour des communications ciblés

**Comment by hmeneuvrier** [comment]
On peut aussi rendre les colonnes triables

**Comment by mathildepoulpux** [comment]
> On peut aussi rendre les colonnes triables

Oui pour commencer ce serait bien !

**Comment by mathildepoulpux** [comment]
Specs -> https://github.com/MTES-MCT/histologe/wiki/Partenaires

**Comment by hmeneuvrier** [comment]
Penser à améliorer la validation des adresses emails : 
- ajouter l'adresse email invalide dans le message d'erreur
- ne pas prendre en compte les utilisateurs archivés dans la validation
cf https://mattermost.incubateur.net/betagouv/pl/hg6h64dy6i8qzpfyrma81g1hba

**Comment by hmeneuvrier** [comment]
@mathildepoulpux Le bouton "gérer les utilisateurs" directement depuis la liste partenaire n'est pas spécifié. J'ai tenté de faire un raccourci "ajouter un utilisateur à ce partenaire" mais techniquement c'est un peu pénible à faire, et finalement en en parlant avec Emilien, on ne voit pas bien l'intérêt de ce bouton. Du coup je l'ai supprimé. Ok pour toi ?

**Comment by mathildepoulpux** [comment]
Oui, effectivement on peut l'enlever vu que ce bouton va renvoyer à la fiche partenaire !

**Comment by mathildepoulpux** [comment]
Le tableau avec les types de partenaires [est dispo ici](https://docs.google.com/spreadsheets/d/1j5AjRJ0Oa4ib4VjjbOB10R_aDyvuLILnECFVx-Kp9w0/edit#gid=1157214031)
