### ISSUE TITLE
[BO - Notifications] Permettre la sélection de notification pour suppression

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#853]
Refonte des principes de notifications
Chaque action d'un agent génère une notification : ajout d'un document, ajout d'une date de visite, ajout d'un suivi et ce même si toutes ces actions sont faites lors de la même "session"
Trouver la meilleure façon d'alléger le volume de notifications

Ne plus envoyer des mails de notifs quand les partenaires acceptent les signalements. Les notif et les email.

Et les notifs de nouveaux signalements

**Comment by mathildepoulpux** [comment]
Notifications Email - Titre
ADIL + RT Correze
Donner le Nom dans le titre du  mail 
Ex: 
afin de simplifier le travail des agents 
message actuel : "un nouveau suivi est disponible pour le signalement #2022-65 sur votre plateforme Histologe par FRANCH Frédéric "
message souhaité : "un nouveau suivi est disponible pour le signalement #2022-65 / TROGNON sur votre plateforme Histologe par FRANCH Frédéric
ajouter commune et code postal dans l'objet du mail

**Comment by mathildepoulpux** [comment]
Dans les notifications on devrait pouvoir cocher pour sélectionner les signalements (comme sur gmail) pour pouvoir les supprimer rapidement

**Comment by mathildepoulpux** [comment]
Dans l'onglet notifications, les notifications “nouveaux signalements" et "signalements validés" sont inutiles et devrait être supprimé.

**Comment by sfinx13** [comment]
Lié à #972

**Comment by sfinx13** [comment]
> Dans l'onglet notifications, les notifications “nouveaux signalements" et "signalements validés" sont inutiles et devrait être supprimé.
Ceci a été traité dans #972

**Comment by mathildepoulpux** [comment]
La partie _Revoir l'objet et contenu du mail dans le mail de suivi_ c'est pas la peine de le faire ! 
En fait j'ai mis les retours des territoires dans des commentaires pour tout avoir dans le même ticket mais j'avais pas revu ce qu'on acceptait ou non. Pour l'objet de l'email y a que la Corrèze qui a fait ce retour et honnêtement je pense que ça va être confus pour pas mal de monde. 
On peut laisser cette tâche de côté et juste faire le 2ème point _Permettre de sélectionner les notifications afin de les marquer comme lues ou supprimées_

**Comment by sfinx13** [comment]
Comme `La partie Revoir l'objet et contenu du mail dans le mail de suivi` n'est plus à faire. Je sépare la refacto des emails et le fait des selectionner des notifs pour suppression dans deux PR différentes @emilschn @hmeneuvrier
