### ISSUE TITLE
[Environnement démo] Création d'une plateforme démo

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#856]
mettre à jour pour que l'ordre des questions du formulaire de démo pour qu'il corresponde à l'ordre du formulaire de la plateforme unique 
aujourd'hui le site de démo est un site qui se balade dans la nature. Il faudrait automatiser le déploiement sur le serveur qui l'héberge afin que le site de démo bénéficie des mises à jour de la plateforme unique

**Comment by sfinx13** [comment]
Je reprend ce ticket en changeant l’intitulé
