### ISSUE TITLE
[BO - Liste des signalements] Permettre aux agents de filtrer par arrondissement dans le filtre commune

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#858]
-> cf. #578 

Commentaire @arnaudchouk : 
Par contre - je ne sais pas pourquoi mais ils n'ont accès qu'à la ville de Marseille en totalité, alors que nous avons la possibilité de proposer les arrondissements - idealement il faudrait debloquer cette possibilité
vue schs (agent)
![image](https://user-images.githubusercontent.com/93710194/194267543-c7402174-3762-4d33-97e8-43a4f57c1727.png)
vue perso (super admin)
![image](https://user-images.githubusercontent.com/93710194/194267671-1c6aa3d9-2fa1-43fa-9747-ba465240acf1.png)

-----

_➡️ Comportement attendu : ajouter la liste des arrondissements dans le filtre commune pour les communes concernées, pour tous les rôles (agent / partenaire admin / responsable territoire / super admin)_

**Comment by arnaudchouk** [comment]
il se trouve que les arrondissements ne concerne que les signalements importés qui étaient renseignés avec l'arrondissement dans le nom de la commune - donc on voit le filtre arrondissement parce qu on a accès à l'historique

**Comment by mathildepoulpux** [comment]
AH ! Donc la règle pour l'afficher ce serait quoi ?

**Comment by arnaudchouk** [comment]
Si on souhaite proposer le filtre Arrondissement - il faudrait faire un filtre sur les CP ?

**Comment by mathildepoulpux** [comment]
Avant de définir comment on le fait, faut que je connaisse le besoin : 
- Pour quel rôle on affiche les arrondissements ?
- Dans quels cas ? Tout le temps ? Seulement si y a de la reprise de données ?

**Comment by mathildepoulpux** [comment]
OK, donc on est bon sur le comportement attendu dans la description du ticket 😊 
Faut juste lui mettre une prio dans le backlog !

**Comment by sfinx13** [comment]
Filtre code postal implémenté dans  ce ticket https://github.com/MTES-MCT/histologe/issues/2117 dans le cadre de la refonte de la liste et filtre signalement
