### ISSUE TITLE
[Redirections - Url territoires]

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#866]
les anciennes url ne sont plus actives - ancien hébergement
il faudrait réactiver la totalité de ces url  au moins pour le semestre afin de permettre aux territoires de corriger leurs communications

**Comment by sfinx13** [comment]
- 04 : [Alpes-de-Haute-Provence](https://guichetunique04.lhi.histologe.fr/)
- 06 : [Alpes-Maritimes](https://habitat-indigne06.histologe.fr/)
- 08 : [Ardennes](https://ardennes.histologe.fr/)
- 13 : [Bouches-du-Rhône](https://habitatindigne13.histologe.fr/)
- 19 : [Corrèze](https://habitatindigne19.histologe.fr/)
- 29 : [Finistère](https://habitatindigne29.histologe.fr/)
- 31 : [Haute-Garonne](https://haute-garonne.histologe.fr/)
- 47 : [Lot-et-Garonne](https://signaltoit.histologe.fr/)
- 59 : [Métropole de Lille](https://amelio.histologe.fr/)
- 63 : [Puy-de-Dôme](https://signalement-logement63.histologe.fr/)
- 64 : [Pyrénées-Atlantiques](https://agglo-pau.histologe.fr/)
- 71 : [Saône-et-Loire](https://habitatindigne71.histologe.fr/)
- 81 : [Tarn](https://habitatindigne81.histologe.fr/)
- 2A : [Corse-du-Sud](https://signalicasa.histologe.fr/)
- 69 : [Rhône](https://rhone69.histologe.fr/)
