### ISSUE TITLE
[BO - Filtre signalement]  Listing des signalements filtré sur les signalements ayant été fermé par au moins 1 partenaire

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#869]
#785 
 Ce filtre n'existe pas 
## Tableau de bord Super Admin
> Clôtures partenaires :
Accès : listing des signalements filtré sur les signalements ayant été fermé par au moins 1 partenaire

**Comment by hmeneuvrier** [comment]
@mathildepoulpux Pour ce filtre avancé, je propose (textes à revoir)

Affectation 
- Ouvert chez tous les partenaires
- Fermé chez au moins un partenaire
- Fermé pour tous les partenaires

Il me semble que ce filtre aurait plus de valeur ajoutée. A noter que s'il n'y a qu'un partenaire, les deux dernières options sont équivalentes. Qu'en penses-tu ?

**Comment by hmeneuvrier** [comment]
(pour moi : https://github.com/MTES-MCT/histologe/pull/863#discussion_r1097665147)

**Comment by hmeneuvrier** [comment]
@mathildepoulpux ça me pose plusieurs questions.
Déjà pour qui est visible ce nouveau filtre ? (à mon avis, pour les admins et responsables territoires)
et les affectations peuvent avoir ces 4 statuts : 

    public const STATUS_WAIT = 0;
    public const STATUS_ACCEPTED = 1;
    public const STATUS_REFUSED = 2;
    public const STATUS_CLOSED = 3;
    
 Du coup mes intitulés ne me semblent pas pertinents.
 
Fermé chez aucun partenaire : aucune affectation à closed (ou refused ?)
Fermé pour au moins un partenaire : une affectation à closed ? (ou refused aussi est pris en compte)
Fermé pour tous les partenaires : toutes les affectations refused ou closed ?

**Comment by mathildepoulpux** [comment]
Alors oui ce sera dispo pour les responsables de territoires et admin !
Je propose qu'on prenne en compte uniquement les closed (pas les refused, ce qui nous intéresse c'est ce qui acceptent et font des actions avant de fermer pour eux).
Du coup, les intitulés que tu proposais me paraissent pertinents :  
- Ouvert chez tous les partenaires =  aucune affectation à closed
- Fermé chez au moins un partenaire = 1 affectation à closed ou + (en gros 1 minimum, mais moins que toutes)
- Fermé pour tous les partenaires = toutes les affectations closed / le statut du signalement est closed

**Comment by hmeneuvrier** [comment]
@mathildepoulpux finalement on ne laisse que l'option "fermé par au moins 1 partenaire" car on a besoin de le faire vite pour sortir le dashboard. Et pour laisser les 2 autres options (qui ont été faites mais commentées) il faut revoir l'UI car on ne peut pas cumuler les options. 

J'ai créé une carte ici : https://github.com/MTES-MCT/histologe/issues/944
