### ISSUE TITLE
[BO - Suivis] - Suppression -

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#877]
Alpes de Haute Provence -  besoin de supprimer certains suivis : 
Priorité haute car le 2021-51 rompt la confidentialité des infos - la vacataire a copié les infos de plusieurs dossiers dans ce suivi
Fiche 2021-51 : supprimer message déposé le 03/02/23 par C Garcin 

- Fiche 2022-96 supprimer message déposé le 14/10/22 par C Garcin
- Fiche 2020-141supprimer message déposé le 14/10/22 par C Garcin
- Fiche 2022-10 supprimer message déposé le 14/10/22 par C Garcin

- fiche 2022-157 supprimer message déposé le 7/12/2022 par C Garcin / suivi "public"

**Comment by emilschn** [comment]
Vu avec Arnaud : le contenu entier est modifié par "Contenu supprimé"

**Comment by sfinx13** [comment]
ok @emilschn je ferme donc le ticket
