### ISSUE TITLE
[Emails] Revoir contenu des emails usagers

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#884]
Afin d'encourager les usagers à utiliser leur page de suivi et à ne pas répondre directement aux emails de la plateforme, il faudrait revoir le contenu des emails.

Modifier les emails destinés aux usagers : 
- [Accusé de réception](https://github.com/MTES-MCT/histologe/blob/main/templates/emails/accuse_reception_email.html.twig)
- [Nouveau suivi](https://github.com/MTES-MCT/histologe/blob/main/templates/emails/nouveau_suivi_signalement_email.html.twig)
- [Clôture globale](https://github.com/MTES-MCT/histologe/blob/main/templates/emails/closed_to_usager_signalement_email.html.twig)

A faire : 
- [x] Dans les 3 mails, ajouter la mention "Cet email est généré automatiquement. Merci de ne pas y répondre."
- [x] Dans le mail accusé de réception : ajouter, au-dessus du bouton, la mention _Pour suivre votre signalement ou nous envoyer un message, cliquez sur le bouton ci-dessous._
- [x] Dans le mail nouveau suivi : remplacer la mention _~~Vous pouvez consulter la mise à jour en cliquant sur le bouton ci-dessous :~~_ par _Vous pouvez consulter la mise à jour ou nous envoyer un message en cliquant sur le bouton ci-dessous :_ 
- [x] Dans les 3 mails, remplacer le texte du bouton par : _Accéder à mon signalement_

Voir [ce template](https://my.sendinblue.com/camp/template/61/message-setup?editor=v6) pour savoir où placer les différentes mentions : 
![image](https://user-images.githubusercontent.com/97226289/216990292-f5821c94-0623-43f9-8ac8-92c64b057f01.png)

**Comment by hmeneuvrier** [comment]
@mathildepoulpux Tous les mails héritent d'un template de base 'emails/base_email.html.twig' dans lequel est la zone où doit se trouver la mention "Cet email est généré automatiquement. Merci de ne pas y répondre."
Est-ce ok pour toi si tous les mails ont cette mention ? Sinon, on la fait apparaitre dans le cadre blanc, sous le logo ?

Et pour le template https://github.com/MTES-MCT/histologe/blob/main/templates/emails/accuse_reception_email.html.twig, il n'avait pas de bouton, donc j'en ai rajouté un pour pouvoir l'appeler "Accéder à mon signalement"

**Comment by mathildepoulpux** [comment]
Oui on peut mettre la mention sur tous les mails, c'est mieux même !

**Comment by hmeneuvrier** [comment]
@mathildepoulpux ok top ! Il ne me manque plus que le css de cette mention, je n'ai pas accès à SiB pour la récupérer, si tu as moyen de me la donner ? (sinon on attend que Saidi ait dépetré cette histoire de redirection de domaine pour les mails)
