### ISSUE TITLE
[BO - Signalement] Evolution Algo criticité

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#896]
Avant la mise en place d'un nouveau formulaire, la 1ere etape consiste à améliorer le calcul de criticité.

Principe : 
categoriser les desordres par "Type" : Logement / Immeuble
calculer une criticite Logement + criticité Immeuble
faire la moyenne des 2 criticités pour définir la criticité globale

Criticité Logement : Total score /(Score Logement Maximum)
Criticité Immeuble : Total score /(Score Immeuble Maximum)

Score Logement Max = 107 (total ponderation x score max)
Score Immeuble Max = 75 (total ponderation x max)
(revérifier en sommant dans la base les desordres batiment / logement, poids max de chaque question x ponderation en faisant attention au conditionnement évoqué au point 3)

2/ Critère Danger :
Quand sélectionné, afficher le Tag Danger Occupant mais ne pas impacter le Score criticité totale

3/ Conditionner la prise en compte de certains scores à la non sélection de certains critères (voir fichier) 

4/ Modifier Label 
Label 13 - L'installation du réseau électrique **de l'immeuble** a un problème
Label52 - Fils électriques dénudés -**Bâtiment/Parties communes** 
[Base Ponderation Algo V2.xlsx](https://github.com/MTES-MCT/histologe/files/10684866/Base.Ponderation.Algo.V2.xlsx)

**Comment by mathildepoulpux** [comment]
Il faudrait aussi afficher le chiffre à côté du curseur sur la liste des signalements : 
![image](https://user-images.githubusercontent.com/97226289/217516251-bb4d1824-35f5-430e-9525-68aafdd5e13c.png)

**Comment by arnaudchouk** [comment]
Suite aux retous voici le fichier  (formats CSV et XLS), pour contourner le point 3/ initialement prévu

[Base Ponderation Algo V2_1.csv](https://github.com/MTES-MCT/histologe/files/10688397/Base.Ponderation.Algo.V2_1.csv)
[Base Ponderation Algo V2_1.xlsx](https://github.com/MTES-MCT/histologe/files/10688402/Base.Ponderation.Algo.V2_1.xlsx)

les scores max sont (à revérifier automatiquement)
Score Logement Max = 109 (total ponderation x score max)
Score Immeuble Max = 75 (total ponderation x max)

**Comment by hmeneuvrier** [comment]
[Base.Ponderation.Algo.V2_3_modifHelene.xlsx](https://github.com/MTES-MCT/histologe/files/10724626/Base.Ponderation.Algo.V2_3_modifHelene.xlsx)

Les modifications que j'ai faites sont en rose, le produit score*coef reste le même

**Comment by arnaudchouk** [comment]
je ne sais pas s il y a un blocage temporaire, mais j ai vu 2 criticités evoluer, depuis je reste à 0

test signalement 2022-1959
,nouvelle criticite indique 0 - les desordres mentionnés impliques un total score de 4 (algo logement) - on devrait avoir un criticité 2 de 1,58%
test signalement 2022-135 
,nouvelle criticite indique 0 - les desordres mentionnés impliques un total score de 2x 1 (algo logement et batiment) - on devrait avoir un criticité 2 de 0,76%
test 2023-1
nouvelle criticité à 0 et 4 désordres selectionnés qui ont des scores et ponderations non nulles
Test - 2023-4 
criticité 0; un desordre avec un poids et score non nul + presence d enfants ne devrait pas etre à 0

**Comment by hmeneuvrier** [comment]
@arnaudchouk est-ce que le fichier xlsx 2 commentaires ci-dessus ne te permet pas de voir ces ajustements (en rose) ?

**Comment by arnaudchouk** [comment]
j avais pas vu desole - 
pas simple ceci... dit vu mes premiers test est ce que tu pourrais ajuster le score des criticites suivantes :
L37 du fichier : escaliers instables /risque effondrement : score 3 au lieu de 1.5
L43 du fichier : fissure importante à l exterieur : 6 au lieu de 4
L 107 : mon logement est en sous sol sans lumiere naturelle : 3 au lieu de 2

**Comment by hmeneuvrier** [comment]
[Base.Ponderation.Algo.V2_4.xlsx](https://github.com/MTES-MCT/histologe/files/10814294/Base.Ponderation.Algo.V2_4.xlsx)

Ok, j'ai fait les modifs, c'est en PR, je remet le fichier à jour

**Comment by hmeneuvrier** [comment]
@arnaudchouk c'est déployé sur la staging

**Comment by arnaudchouk** [comment]
les quelques tests ont l air cohérents - peu de risque à passer en prod tant que reservé au super admin :)
