### ISSUE TITLE
[Punaises - BO] Créer une entreprise

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#9]
### Objectif
Créer une entreprise dans le BO.
Une entreprise = création d'un compte dans le BO.
[Voir maquette 🔗](https://xd.adobe.com/view/2b4d3ce7-960a-41ba-b226-bbcd83297f51-7e1e/screen/c1f8b06d-a5c6-43bf-b165-bb52399c70ee/)
[Voir la microcopie 💬 ](https://docs.google.com/spreadsheets/d/1JeIJb1PKFHyAH6LIBxsH0HvYsGFw8KjN/edit#gid=344031466)
[Modèle email activation compte](https://my.sendinblue.com/camp/template/24/message-setup)

### Prérequis
Avoir un compte admin actif sur la plateforme

### User flow
1. Je clique sur le bouton "créer une entreprise" sur le dashboard 
  a. J'accède à la page entreprise
4. Je clique sur le bouton "créer une entreprise"
5. Je remplis les champs demandés dans la side modale 
**NB : les champs sont obligatoires sauf mention contraire**
  a. Nom / raison sociale
  b. Numéro SIRET
  c. Téléphone
  d. Numéro de label
  e. Email
  f. Territoires d'intervention
6. Clic sur "valider"

![image](https://user-images.githubusercontent.com/97226289/173329997-d676d6ad-98cc-4056-9018-5771274f0157.png)

#### Conséquences
- Success message
- Création de l'entreprise (visible dans le listing entreprise)
- Envoi d'un email d'activation au compte entreprise

**Comment by emilschn** [comment]
Manque la création de l'utilisateur simultanée et l'e-mail de confirmation.
