### ISSUE TITLE
Personnaliser la page d'erreur Scalingo "Application Timeout"

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#906]
Il est possible de créer des pages pour personnaliser les pages d'erreur de Scalingo actuelles.

Il y a 4 templates différents :
    SCALINGO_NO_FRONT_ERROR_URL: if the application has no web container running but other types of containers are.
    SCALINGO_STOPPED_PAGE_URL: if the application has no running container.
    SCALINGO_APP_ERROR_URL: if the application returns a 502 HTTP response, crashed or cut the connection unexpectedly.
    SCALINGO_TIMEOUT_ERROR_URL: if the application returns a 504 HTTP response or timed out.

Documentation :
https://doc.scalingo.com/platform/app/custom-error-page#custom-error-pages

**Comment by mathildepoulpux** [comment]
Pour les 4 je ferais la même chose : 
Le logo histologe
Titre : Service indisponible
Message : Le service Histologe n'est pas disponible pour le moment. Veuillez réessayer dans quelques minutes.

**Comment by hmeneuvrier** [comment]
@mathildepoulpux quelque-chose comme ça ?

![image](https://github.com/MTES-MCT/histologe/assets/33071753/f608c8c9-b182-4433-b5f6-edff510c7d58)

**Comment by mathildepoulpux** [comment]
Oui ! Est-ce qu'on peut mettre le fond de couleur sur toute la page et centrer le texte + le logo ?

**Comment by hmeneuvrier** [comment]
@mathildepoulpux je viens de voir que le dsfr a fait des exemples de pages d'erreurs... https://www.systeme-de-design.gouv.fr/elements-d-interface/modeles/page-d-erreurs

**Comment by hmeneuvrier** [comment]
> Il faudrait vous hébergiez les pages d'erreur ailleurs que dans l'application, car ces pages ont pour vocation de s'afficher si l'application ne fonctionne pas.
> 
> Cela devrait vous aider à résoudre votre problème.
> 
> N'hésitez pas à revenir vers nous,
> Anouchka MAURER
> UFS @ Scalingo

Garder les pages d'erreurs statiques (mettre un commentaire pour expliquer), virer (ou changer le lien) vers la page d'accueil, puis les mettre sur alwaysdata

Changer les variables d'environnement, tester avec les controllers, puis virer les controllers de tests

**Comment by hmeneuvrier** [comment]
Je viens d'héberger la page d'erreur sur alwaysdata : https://maintenance.histologe.fr/error.html,
J'ai changé les variables d'environnement sur la reviewapp, et cela ne marche toujours pas : 
https://histologe-staging-pr1326.osc-fr1.scalingo.io/error-504
https://histologe-staging-pr1326.osc-fr1.scalingo.io/error-502

j'ai renvoyé un message à scalingo
