### ISSUE TITLE
[FO - Form étape 4] Supprimer la question sur le handicap

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#917]
Supprimer cette question du formulaire sur le FO
C'est souvent un élément bloquant pour les partenaires étant donné qu'il s'agit d'une info sur l'état de santé des occupants
cf. [ce thread](https://mattermost.incubateur.net/betagouv/pl/fyptiibm37fqjx6r63kwh5coto) sur Mattermost
![image](https://user-images.githubusercontent.com/97226289/218687427-0a5c330b-85ec-4a15-b321-2749fcfb12bd.png)

**Comment by sfinx13** [comment]
@mathildepoulpux  Doit on aussi supprimer la colonne en base de données également ?

**Comment by mathildepoulpux** [comment]
Oui je pense que c'est plus safe de pas avoir l'info du tout de notre côté :)
