### ISSUE TITLE
[ESABORA - Lyon]

### ISSUE THREAD

**Issue by arnaudchouk** [MTES-MCT/histologe#919]
Permettre connexion pour test - voir mail transfere si necessaire

**Comment by sfinx13** [comment]
@arnaudchouk j'ai supprimé les identifiants du ticket :-)

**Comment by sfinx13** [comment]
Quel est le nom du partenaire pour la mairie de Lyon ?
J'en ai deux avec l'intitulé Mairie de Lyon

**Comment by arnaudchouk** [comment]
la direction santé a priori - partenaire 194

**Comment by emilschn** [comment]
L'URL de recette et le token ont été enregistrés sur notre plateforme de staging sur le partenaire 194.
@arnaudchouk peux-tu prendre en main les tests pour avoir des tests utilisateurs "réalistes" et discuter en direct avec eux ?

**Comment by arnaudchouk** [comment]
concretement, une fois que c est ok chez eux cela signifie
creer signalement
affecter au partenaire 194
Voir si c est bien remonté chez eux
Voir si on récupère bien les statuts 
c est bien ça ?

**Comment by emilschn** [comment]
Oui c'est ça dans l'esprit, mais sur les plateformes de test dans l'immédiat :)

**Comment by arnaudchouk** [comment]
oui - je vais creer les signalements sur staging dès que c est confirimé de leur cote

**Comment by arnaudchouk** [comment]
test limité compte tenu de leur environnement de recette, mais  ce stade ca fonctionne
