### ISSUE TITLE
[BO - ESABORA] Permettre à un super admin d'activer ou désactiver la synchronisation via la page partenaire

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#920]
Aujourd'hui pour arrêter la synchronisation esabora avec un partenaire, il faut supprimer ses identifiants. 
Il faudrait donc permettre à un super admin la possibilité d'activer ou désactiver la synchronisation via une case à cocher.

**Comment by sfinx13** [comment]
@hmeneuvrier j'avais déjà crée le ticket désolé, il faut donc supprimer  un des deux tickets cf #1128

**Comment by hmeneuvrier** [comment]
ok, je supprime celui-ci
