### ISSUE TITLE
Créer un champ/tag Conclusion visite

### ISSUE THREAD

**Issue by emilschn** [MTES-MCT/histologe#924]
https://www.notion.so/Creer-un-champ-tag-Conclusion-visite-9c8482a9b6e6497ea906b7c4924376d1?pvs=4

**Comment by mathildepoulpux** [comment]
![image](https://user-images.githubusercontent.com/97226289/224397735-1f2e1511-0e72-47a6-b303-4357217343ff.png)

![image](https://user-images.githubusercontent.com/97226289/224398063-5b7bf6da-6d5c-4d43-a1a5-7e5239ffba66.png)

![image](https://user-images.githubusercontent.com/97226289/224398226-e3fc63a0-66fd-48d4-a3c6-664a5e496b16.png)
