### ISSUE TITLE
[BO - Documentation] Implémenter un chatbot

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#926]
Faire un chatbot qui propose des liens vers la doc avant de laisser poser la question. Etudier ce qu'on peut interfacer avec gitbook

https://chatbot.fabnum.fr/
https://fabrique-a-chatbots.gitbook.io/fabrique-a-chatbots/

**Comment by hmeneuvrier** [comment]
@arnaudchouk @mathildepoulpux j'avais créé cette carte pour le chatbot

**Comment by arnaudchouk** [comment]
merci - je les ai contactés car il n est pas certain que ce soit ouvert à toutes les SE

**Comment by arnaudchouk** [comment]
bon c est en accès restreint pour le moment...
à toutes fins utiles ils m ont précisé que le code est open source 
https://fabrique-a-chatbots.gitbook.io/doc-installation/
mais je ne suis pas sur que l'on puisse gérer ça en plus, vous me direz

**Comment by mathildepoulpux** [comment]
Je déplace vers notion tant que c'est pas validé / spécifié
