### ISSUE TITLE
[BO - Filtre signalement] Listing des signalements filtré sur les signalements ayant été fermé par aucun partenaire ou par tous les partenaires

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#944]
Suite du ticket #869 

> Alors oui ce sera dispo pour les responsables de territoires et admin !
Je propose qu'on prenne en compte uniquement les closed (pas les refused, ce qui nous intéresse c'est ce qui acceptent et font des actions avant de fermer pour eux).
Du coup, les intitulés que tu proposais me paraissent pertinents :

-     Ouvert chez tous les partenaires = aucune affectation à closed
-     Fermé chez au moins un partenaire = 1 affectation à closed ou + (en gros 1 minimum, mais moins que toutes)
-     Fermé pour tous les partenaires = toutes les affectations closed / le statut du signalement est closed

Le code a été fait en back, et commenté dans le twig, car il faut revoir l'UI pour ne pas pouvoir sélectionner plus d'une option, la façon dont elles sont construires les rend excluantes et non-cumulables

PR ici  : https://github.com/MTES-MCT/histologe/pull/929

Code dans src/Service/SearchFilterService.php et templates/_partials/_search_filter_form.html.twig

**Comment by sfinx13** [comment]
Je ferme c'est fait
