### ISSUE TITLE
[BO - Affectation] Différencier visuellement les refus / clôture par partenaire

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#949]
### Besoin
Rôle : responsable territoire et supérieur
Besoin : dans le BO, sur la liste des signalements j'aimerais différencier les partenaires ayant refusés une affectation de ceux ayant clôturés le signalement pour leur partenaire. Actuellement, ils sont présentés de la même manière : 

![image](https://user-images.githubusercontent.com/97226289/223193366-931bb8f3-bc7d-49c5-8bff-fcd095deb494.png)

### Proposition
Pour les signalements clôturés pour le partenaire : 
- ajouter l'icône close-circle-fill
- fond : #E5E5E5
- texte : #3A3A3A 

Pour les affectations refusées : 
- remplacer l'icône actuelle par indeterminate-circle-fill

**Comment by hmeneuvrier** [comment]
@mathildepoulpux l'icône indeterminate-circle-fill n'est pas dans notre version du dsfr (ni même dans celle en cours du dsfr il me semble, je ne l'ai pas trouvée https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/icone )

Pour l'instant, j'ai fait ça (image jointe), mais je remettrais bien l'icone de base pour les affectations refusées (la croix), et une autre icone pour les affectations cloturées ?
Voici les icônes qu'on a actuellement : 
fr-fi-account-fill
fr-fi-account-line
fr-fi-add-circle-fill
fr-fi-add-circle-line
fr-fi-add-line
fr-fi-alert-fill
fr-fi-alert-line
fr-fi-arrow-down-line
fr-fi-arrow-down-s-line
fr-fi-arrow-left-line
fr-fi-arrow-left-s-first-line
fr-fi-arrow-left-s-line-double
fr-fi-arrow-left-s-line
fr-fi-arrow-right-line
fr-fi-arrow-right-s-last-line
fr-fi-arrow-right-s-line-double
fr-fi-arrow-right-s-line
fr-fi-arrow-right-up-line
fr-fi-arrow-up-line
fr-fi-arrow-up-s-line
fr-fi-attachment-fill
fr-fi-attachment-line
fr-fi-calendar-fill
fr-fi-calendar-line
fr-fi-chat-quote-fill
fr-fi-chat-quote-line
fr-fi-check-line
fr-fi-checkbox-circle-fill
fr-fi-checkbox-circle-line
fr-fi-close-circle-fill
fr-fi-close-circle-line
fr-fi-close-line
fr-fi-dailymotion-fill
fr-fi-dailymotion-line
fr-fi-delete-fill
fr-fi-delete-line
fr-fi-download-line
fr-fi-edit-fill
fr-fi-edit-line
fr-fi-equalizer-fill
fr-fi-equalizer-line
fr-fi-error-warning-fill
fr-fi-error-warning-line
fr-fi-external-link-line
fr-fi-eye-fill
fr-fi-eye-line
fr-fi-eye-off-fill
fr-fi-eye-off-line
fr-fi-facebook-circle-fill
fr-fi-facebook-circle-line
fr-fi-file-download-fill
fr-fi-file-download-line
fr-fi-file-fill
fr-fi-file-line
fr-fi-file-pdf-fill
fr-fi-file-pdf-line
fr-fi-filter-fill
fr-fi-filter-line
fr-fi-github-fill
fr-fi-github-line
fr-fi-information-fill
fr-fi-information-line
fr-fi-instagram-fill
fr-fi-instagram-line
fr-fi-linkedin-box-fill
fr-fi-linkedin-box-line
fr-fi-links-fill
fr-fi-lock-fill
fr-fi-lock-line
fr-fi-logout-box-r-fill
fr-fi-logout-box-r-line
fr-fi-mail-fill.fr-fi-mail-line
fr-fi-menu-2-fill
fr-fi-menu-fill
fr-fi-npmjs-fill
fr-fi-npmjs-line
fr-fi-pause-circle-fill
fr-fi-pause-circle-line
fr-fi-play-fill
fr-fi-play-line
fr-fi-printer-fill
fr-fi-printer-line
fr-fi-question-fill
fr-fi-question-line
fr-fi-refresh-fill
fr-fi-refresh-line
fr-fi-remixicon-fill
fr-fi-remixicon-line
fr-fi-save-fill
fr-fi-save-line
fr-fi-search-fill
fr-fi-search-line
fr-fi-slack-fill
fr-fi-slack-line
fr-fi-snapchat-fill
fr-fi-snapchat-line
fr-fi-subtract-line
fr-fi-telegram-fill
fr-fi-telegram-line
fr-fi-theme-fill
fr-fi-tiktok-fill
fr-fi-tiktok-line
fr-fi-twitch-fill
fr-fi-twitch-line
fr-fi-twitter-fill
fr-fi-twitter-line
fr-fi-upload-2-fill
fr-fi-upload-2-line
fr-fi-user-fill
fr-fi-user-line
fr-fi-vimeo-fill
fr-fi-vimeo-line
fr-fi-volume-down-fill
fr-fi-volume-down-line
fr-fi-volume-mute-fill
fr-fi-volume-mute-line
fr-fi-volume-up-fill
fr-fi-volume-up-line
fr-fi-youtube-fill
fr-fi-youtube-line
fr-icon-error-fill

![image](https://user-images.githubusercontent.com/33071753/224674839-283712c9-7cb8-4c29-b7dd-aaf578b94add.png)

**Comment by mathildepoulpux** [comment]
C'est pas possible de la prendre dans Remix Icon comme c'est indiqué là : https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/icone ?
![image](https://user-images.githubusercontent.com/97226289/224677017-f67c74fb-2bb9-4d5b-95be-6e465d08cbb0.png)

**Comment by hmeneuvrier** [comment]
Je le comprends comme "participer à améliorer le dsfr"
