### ISSUE TITLE
[Performance] Stocker les images sur le cloud pendant le parcours usager

### ISSUE THREAD

**Issue by sfinx13** [MTES-MCT/histologe#979]
## Solution

Dés le parcours stocker les images sur le bucket S3 (dans un dossier temporaire)

## Problème
Pendant le parcours usager, l'image est stocker temporairement dans un dossier /tmp avant de l'envoyer dans un bucket S3
![image](https://user-images.githubusercontent.com/5757116/222126559-b49e6411-d5e4-4efd-9ba6-8df6c4398da9.png)
Ce qui pose problème lorsque on active l'auto-scaling car nous allons donc avoir un /tmp par container. Le contenu de ce 
dossier n'est pas répliqué sur les autres container. Il faut donc stocker l'image temporairement dans une brique commune afin d'éviter cet effet de bord lors de l'auto-scaling

**Comment by emilschn** [comment]
Je propose de mettre les fichiers dans un dossier automatique tmp-YYYYMM pour nous simplifier la suppression ensuite. Ce serait ok ?
