### ISSUE TITLE
Investiguer sur les utilisateurs sans territoire ni partenaire

### ISSUE THREAD

**Issue by hmeneuvrier** [MTES-MCT/histologe#993]
Deux filtres dans Metbase : 

https://histologe-metabase.osc-fr1.scalingo.io/question/104-user-non-usager-sans-partner

https://histologe-metabase.osc-fr1.scalingo.io/question/103-user-non-usager-sans-territoire

une des erreurs induites : https://sentry.incubateur.net/share/issue/72d446be164d42539816475165320240/

**Comment by sfinx13** [comment]
Afin de temporiser l'investigation, une évolution de sur la page compte archivé a été faite sur le ticket #1090

**Comment by hmeneuvrier** [comment]
Avec la sortie de la nouvelle page partenaire #852 on va remettre le territoire du partenaire à tous les utilisateurs sans territoires.
Et on verra après si cela se reproduit encore ou si ça venait de l'étrange gestion partenaire/utilisateur d'avant

**Comment by hmeneuvrier** [comment]
La migration `migrations/Version20230407115407.php` qui remet le territoire du partenaire aux utilisateurs sans territoire est en ligne depuis la 1.7.5, soit le 17 avril, et pourtant quand je vais dans Metabase, il y a toujours 309 utilisateurs sans territoire...

**Comment by hmeneuvrier** [comment]
Bilan sur les utilisateurs sans territoire.

**Avant de rejouer la migration :** 
2 utilisateurs sans partenaire,
410 utilisateurs sans territoires
732 comptes archivés ou sans territoires et/ou partenaires trouvés

**Après avoir rejoué la migration :** 
2 utilisateurs sans partenaire
1 utilisateur sans territoire (qui n'a pas de partenaire non plus)
332 comptes archivés ou sans territoires et/ou partenaires trouvés

Je me mets un TODO pour revérifier dans 1 semaine
