### ISSUE TITLE
[BO - Criticité] Passer du score à une liste de qualifications

### ISSUE THREAD

**Issue by mathildepoulpux** [MTES-MCT/histologe#995]
Revoir l'affichage du listing pour afficher les tags suivants, les tags pouvant s'additionner :
(1)suspicion non décence/rsd
(2)suspicion insalubrité
(3)danger occupant

(1) tous les signalements avec un score inférieur à 10
(1) et (2) tous les signalements avec un score supérieur à 10 et inférieur à 30
(2) tous les signalements avec score supérieur à 30 OU ceux qui ont les critères suivant sélectionnés :
mon logement est situé en sous-sol sans éclairage naturel. 
Pièce unique du logement de moins de 9m2 
 il n'y a aucune ventilation dans mon logement. 
(3) tous les signalements ou un désordre est associé à Danger occupant

Conserver le score sur la page du signalement en plus des tags

**Comment by emilschn** [comment]
Vu en direct avec Arnaud 
- On affiche les tags pour tout le monde
- On supprime l'ancienne notation
- On affiche la nouvelle notation pour tout le monde
  - On l'affiche au format numérique (et plus la jauge)
  - A déterminer : est-ce qu'on l'affiche juste sur la page signalement, ou sur la liste aussi ?

**Comment by emilschn** [comment]
Vu en direct avec Arnaud pour les classifications (pour info @hmeneuvrier @sfinx13 @arnaudchouk @mathildepoulpux )
C'est un premier essai de tags, donc pour l'instant ça pourra évoluer relativement vite pour affiner.
Rappel : les tags sont cumulatifs.

- Tous les signalements
  - Tags `RSD à vérifier` et `Non décence à vérifier`
  - Tech : Qualification `RSD` ou `NON_DECENCE` ; Status `à vérifier`
- Entre 10 et 30
  - Tag `Manquement à l'insalubrité à vérifier`
  - Tech : Qualification `INSALUBRITE` ; Status `manquement à vérifier`
- Supérieur à 30
  - Tag `Insalubrité à vérifier`
  - Tech : Qualification `INSALUBRITE` ; Status `à vérifier`
- Désordres spécifiques sélectionnés (voir tâche du haut)
  - Tag `Insalubrité à vérifier`
  - Tech : Qualification `INSALUBRITE` ; Status `à vérifier`
- Désordres de type Danger sélectionnés
  - Tag `Danger pour l'occupant`
  - Tech : Ne pas utiliser de qualification, parcourir les criticités et vérifier `isDanger`

**Comment by sfinx13** [comment]
> A déterminer : est-ce qu'on l'affiche juste sur la page signalement, ou sur la liste aussi ?

@emilschn 
L'affichage des tags va nécessiter l'ajout d'une jointure supplémentaire sur la requête par défaut et impacter les performances. Je propose de limiter l'affichage des tags à la page de signalement pour maintenir de bonnes performances.

Néanmoins, les utilisateurs pourront continuer à filtrer les signalements par tags.

**Comment by emilschn** [comment]
> > A déterminer : est-ce qu'on l'affiche juste sur la page signalement, ou sur la liste aussi ?
> 
> @emilschn L'affichage des tags va nécessiter l'ajout d'une jointure supplémentaire sur la requête par défaut et impacter les performances. Je propose de limiter l'affichage des tags à la page de signalement pour maintenir de bonnes performances.
> 
> Néanmoins, les utilisateurs pourront continuer à filtrer les signalements par tags.

@sfinx13 
Il y a déjà une jointure sur SignalementQualifications pour la NDE, ça devrait aller.
Les tags sont la fonctionnalité de base, ça semble difficile de s'en passer. C'est la présence du score qui pose question, par contre.

**Comment by sfinx13** [comment]
> Il y a déjà une jointure sur SignalementQualifications pour la NDE, ça devrait aller.
Les tags sont la fonctionnalité de base, ça semble difficile de s'en passer. C'est la présence du score qui pose question, par contre.

@emilschn je parlais des tags, avec les tables tag et tag_signalement

**Comment by emilschn** [comment]
Suite à mésentente avec @sfinx13 , j'ai renommé l'ensemble de mes messages qui parlaient de `tags` (équivalent des étiquettes pour les devs) en `qualification`.

**Comment by hmeneuvrier** [comment]
@mathildepoulpux @emilschn C'est fonctionnel et ce n'était pas dans les specs, mais je le pose là : 
Dans les filtres, on a un filtre sur la qualification NDE (en fonction des statuts), on n'en a pas pour les autres qualifications. S'il n'existe pas de carte pour ça, il faut penser à en faire une (et peut-être au passage voir si on change ou on vire le filtre sur le score)

**Comment by emilschn** [comment]
Questions pour @mathildepoulpux :
- faut-il ajouter des filtres pour les nouvelles qualifications de Signalement ?
  - éventuellement pour un ticket suivant, en attendant de voir l'usage ?
- dans la page d'un signalement, on affiche les nouvelles qualifications (RSD, ...) dès que c'est qualifié comme tel lors de l'ajout / l'édition d'un signalement ; on laisse comme ça ? Pour l'instant, le fonctionnement est le même que pour la NDE.
  - dans l'immédiat, ça va surtout être "à vérifier" et ils n'auront pas de possibilité de l'éditer, en dehors de la modification des critères
- dans les stats back, on a répartition des criticités par score (par tranches de 25%) ; est-ce que ça a encore du sens, maintenant qu'on supprime l'ancien score ?

Si besoin, on en parle jeudi :)
Merci !

**Comment by mathildepoulpux** [comment]
Pour les questions : 
- Filtres : pas pour le moment. Je bosse sur une story pour revoir les filtres, j'ai prévu de l'intégrer à ce moment là !
- Oui on peut laisser comme ça pour le moment et en évolution prévoir la possibilité d'éditer la qualification (sachant que ce sera fait avec la visite déjà) -> il y a déjà  un ticket dessus
- Stats : pour le graph donut, on peut modifier pour avoir : 
    - 0 à 10
    - > 10 à 30
    - > 30
Aussi @arnaudchouk va préciser les besoins pour l'ajout d'un graphique avec la distribution par procédure !

Concernant l'UI, après discussion avec Arnaud, il faudrait :
- Faire un tag unique "RSD / Non décence" (plutôt qu'en avoir 2 distincts)
- Mettre les tags de la même taille que les labels affectations partenaires
- Modifier les couleurs des tags : 
    - RSD / Non décence : bleu info (couleur actuelle)
    - Manquement à l'insalubrité ET Insalubrité : orange warning
    - Danger : rouge error

**Comment by emilschn** [comment]
Infos complémentaires :
- la qualification "RSD / Non décence" est juste dans l'affichage (on garde les deux séparés en donnée) et on renomme `Suspicion Non décence/RSD`
- `Suspicion Insalubrité` et `Suspicion Manquement à l'insalubrité`
- `Danger occupant`

**Comment by emilschn** [comment]
Les modifications ont été faites @mathildepoulpux @arnaudchouk 
Est-ce qu'il faut attendre la nouvelle stat pour tests et mise en ligne ? Ou est-ce que ça fera partie d'un ticket complémentaire ?

**Comment by mathildepoulpux** [comment]
Ca sera un ticket complémentaire je pense !

**Comment by arnaudchouk** [comment]
j aimerais bien si possible avoir effectivement une vue de la distribution des criticités
spontanément je pense à la loi normale
a priori c est pas inclus dans la librairie de base chart.js mais semble t il faisable avec ce code
https://codepen.io/Sire404/pen/dyvYPBM

a vous de me dire si c est ok

**Comment by emilschn** [comment]
Question naïve : Quelle est la différence avec un histogramme vertical ? :)

**Comment by arnaudchouk** [comment]
la repartition dans ton histogramme
visuellement plus simple à appréhender pour moi, mais c est une deformation "pro" liée à mon historique

**Comment by emilschn** [comment]
Du coup, j'ajoute une carte "à trier" pour une stat complémentaire.
@arnaudchouk @mathildepoulpux est-ce que vous voulez refaire des tests sur la review app, ou est-ce que vous voulez qu'on mette tout ça sur la staging pour des tests plus "réalistes" ?
